### ISSUE TITLE
when enabling verifier inspec I get a berkshelf error

### ISSUE THREAD

**Issue by username-is-already-taken2** [test-kitchen/test-kitchen#1019]
## Description

I'm unable to use the verifier inspec, within test-kitchen, if I enable the verifier within my .kitchen.yml
```
verifier:
  name: inspec
```
I get an error running any kitchen create or list.
I get an error saying that berkshelf isn't installed, using the default Busser I can complete a full test.

```
!!!!!! The `berkshelf' gem is missing and must be installed or cannot be properly activated. Run `gem install berkshelf` or add the following to your Gemfile if you are using Bundler: `gem 'berkshelf'`.
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::UserError
>>>>>> Message: Could not load or activate Berkshelf (cannot load such file -- berkshelf)
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```
berkshelf is installed (berkshelf-4.3.2)

## Kitchen Version

PS C:\chef-repo\cookbooks\niu_app_view> kitchen --version
Test Kitchen version 1.7.3

## ChefDK Version

```
PS C:\chef-repo\cookbooks\niu_app_view> chef --version
Chef Development Kit Version: 0.13.21
chef-client version: 12.9.41
berks version: 4.3.2
kitchen version: 1.7.3
```

## Platform Version

OS = Windows 10 x64

## Kitchen Diagnose

```
PS C:\chef-repo\cookbooks\niu_app_view> kitchen diagnose --loader
!!!!!! The `berkshelf' gem is missing and must be installed or cannot be properly activated. Run `gem install berkshelf` or add the following to your Gemfile if you are using Bundler: `gem 'berkshelf'`.
---
timestamp: 2016-04-29 10:20:46 UTC
kitchen_version: 1.7.3
loader:
  process_erb: true
  process_local: true
  process_global: true
  global_config:
  project_config:
    filename: C:/chef-repo/cookbooks/niu_app_view/.kitchen.yml
    raw_data:
      driver:
        name: vagrant
        network:
        - - forwarded_port
          - guest: 3389
            host: 33389
      provisioner:
        name: chef_zero
      verifier:
        name: inspec
      platforms:
      - name: windows-2012r2
      suites:
      - name: default
        run_list:
        - recipe[niu_app_view::default]
        attributes:
  local_config:
  combined_config:
    filename:
    raw_data:
      driver:
        name: vagrant
        network:
        - - forwarded_port
          - guest: 3389
            host: 33389
      provisioner:
        name: chef_zero
      verifier:
        name: inspec
      platforms:
      - name: windows-2012r2
      suites:
      - name: default
        run_list:
        - recipe[niu_app_view::default]
        attributes:
instances:
  error:
    exception: "#<Kitchen::UserError: Could not load or activate Berkshelf (cannot
      load such file -- berkshelf)>"
    message: Could not load or activate Berkshelf (cannot load such file -- berkshelf)
    backtrace:
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.7.3/lib/kitchen/provisioner/chef/berkshelf.rb:108:in
      `rescue in load_berkshelf!'
```

## NOTE:

This repository is for core issues with the Test-Kitchen framework, so if the issue is with a plugin you may be referred to file the issue with the appropriate plugin.

**Comment by username-is-already-taken2** [comment]
Hi there

I've found a bit more that I thought I would pass on.

I generated a 2 new cookbooks 

using `knife cookbook create knife_cookbook` & `chef generate cookbook chef_cookbook`

the chef command generated 

```
C:.
│   .kitchen.yml
│   Berksfile
│   chefignore
│   metadata.rb
│   README.md
│
├───recipes
│       default.rb
│
├───spec
│   │   spec_helper.rb
│   │
│   └───unit
│       └───recipes
│               default_spec.rb
│
└───test
    └───integration
        ├───default
        │   └───serverspec
        │           default_spec.rb
        │
        └───helpers
            └───serverspec
                    spec_helper.rb
```
if I use the same .kitchen.yml in both cookbooks the one created with knife command works but the one created with the chef command fails with the same as above.

further testing, the chef command generated a 'Berksfile' where the knife command didn't

```
PS C:\chef-repo\cookbooks\chef_cookbook> type .\Berksfile
source 'https://supermarket.chef.io'

metadata
```
if I delete that file then I don't get the kitchen error anymore and I can use inspec as a verifier.

I appreciate this might not be a test-kitchen issue? let me know either way.

Thanks

**Comment by cheeseplus** [comment]
This should have been addressed in recent ChefDK updates. Is the issue still present? Test-kitchen uses a Berksfile by default if it's present but this seems to be a specific issue as berks should be available if you are using the chefdk.

**Comment by bigbam505** [comment]
I am also seeing this issue now on version 0.15.9 of chefdk on a centos host. We downgraded to chefdk 0.14.25 and it seemed to work as expected.  I did test on 0.15.9 that removing the following block in the .kitchen.yml did let that step pass:

```
verifier:
  name: inspec
```

Version Information

```
os: centos 6
chefdk version: 0.15.9
```

Error Log:

```
I, [2016-06-15T21:29:11.710951 #7494]  INFO -- Kitchen: -----> Starting Kitchen (v1.9.2)
E, [2016-06-15T21:29:13.014123 #7494] ERROR -- Kitchen: ------Exception-------
E, [2016-06-15T21:29:13.014174 #7494] ERROR -- Kitchen: Class: Kitchen::UserError
E, [2016-06-15T21:29:13.014206 #7494] ERROR -- Kitchen: Message: Could not load or activate Berkshelf (cannot load such file -- berkshelf)
E, [2016-06-15T21:29:13.014236 #7494] ERROR -- Kitchen: ----------------------
E, [2016-06-15T21:29:13.014327 #7494] ERROR -- Kitchen: ------Backtrace-------
E, [2016-06-15T21:29:13.014363 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/provisioner/chef/berkshelf.rb:108:in `rescue in load_berkshelf!'
E, [2016-06-15T21:29:13.014393 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/provisioner/chef/berkshelf.rb:95:in `load_berkshelf!'
E, [2016-06-15T21:29:13.014423 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/provisioner/chef/berkshelf.rb:54:in `load!'
E, [2016-06-15T21:29:13.014452 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/provisioner/chef_base.rb:285:in `load_needed_dependencies!'
E, [2016-06-15T21:29:13.014481 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/configurable.rb:56:in `finalize_config!'
E, [2016-06-15T21:29:13.014510 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/instance.rb:321:in `setup_provisioner'
E, [2016-06-15T21:29:13.014539 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/instance.rb:107:in `initialize'
E, [2016-06-15T21:29:13.014567 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/config.rb:247:in `new'
E, [2016-06-15T21:29:13.014597 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/config.rb:247:in `new_instance'
E, [2016-06-15T21:29:13.014625 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/config.rb:144:in `block in build_instances'
E, [2016-06-15T21:29:13.014654 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/config.rb:143:in `map'
E, [2016-06-15T21:29:13.014732 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/config.rb:143:in `with_index'
E, [2016-06-15T21:29:13.014768 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/config.rb:143:in `build_instances'
E, [2016-06-15T21:29:13.014798 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/config.rb:119:in `instances'
E, [2016-06-15T21:29:13.014827 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/command.rb:97:in `all_instances'
E, [2016-06-15T21:29:13.014856 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/command.rb:145:in `parse_subcommand'
E, [2016-06-15T21:29:13.014884 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/command/test.rb:43:in `block in call'
E, [2016-06-15T21:29:13.014913 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
E, [2016-06-15T21:29:13.014942 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/command/test.rb:41:in `call'
E, [2016-06-15T21:29:13.014971 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/cli.rb:56:in `perform'
E, [2016-06-15T21:29:13.014999 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/cli.rb:231:in `test'
E, [2016-06-15T21:29:13.015028 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
E, [2016-06-15T21:29:13.015064 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
E, [2016-06-15T21:29:13.015095 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/cli.rb:325:in `invoke_task'
E, [2016-06-15T21:29:13.015125 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
E, [2016-06-15T21:29:13.015154 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
E, [2016-06-15T21:29:13.015182 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/bin/kitchen:13:in `block in <top (required)>'
E, [2016-06-15T21:29:13.015242 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/errors.rb:174:in `with_friendly_errors'
E, [2016-06-15T21:29:13.015289 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/bin/kitchen:13:in `<top (required)>'
E, [2016-06-15T21:29:13.015320 #7494] ERROR -- Kitchen: /usr/bin/kitchen:17:in `load'
E, [2016-06-15T21:29:13.015348 #7494] ERROR -- Kitchen: /usr/bin/kitchen:17:in `<main>'
E, [2016-06-15T21:29:13.015376 #7494] ERROR -- Kitchen: ----End Backtrace-----
E, [2016-06-15T21:29:13.015405 #7494] ERROR -- Kitchen: ---Nested Exception---
E, [2016-06-15T21:29:13.015432 #7494] ERROR -- Kitchen: Class: LoadError
E, [2016-06-15T21:29:13.015460 #7494] ERROR -- Kitchen: Message: cannot load such file -- berkshelf
E, [2016-06-15T21:29:13.015488 #7494] ERROR -- Kitchen: ----------------------
E, [2016-06-15T21:29:13.015516 #7494] ERROR -- Kitchen: ------Backtrace-------
E, [2016-06-15T21:29:13.015544 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/provisioner/chef/berkshelf.rb:108:in `rescue in load_berkshelf!'
E, [2016-06-15T21:29:13.015573 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/provisioner/chef/berkshelf.rb:95:in `load_berkshelf!'
E, [2016-06-15T21:29:13.015601 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/provisioner/chef/berkshelf.rb:54:in `load!'
E, [2016-06-15T21:29:13.015630 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/provisioner/chef_base.rb:285:in `load_needed_dependencies!'
E, [2016-06-15T21:29:13.015659 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/configurable.rb:56:in `finalize_config!'
E, [2016-06-15T21:29:13.015691 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/instance.rb:321:in `setup_provisioner'
E, [2016-06-15T21:29:13.015753 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/instance.rb:107:in `initialize'
E, [2016-06-15T21:29:13.015859 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/config.rb:247:in `new'
E, [2016-06-15T21:29:13.015893 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/config.rb:247:in `new_instance'
E, [2016-06-15T21:29:13.015922 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/config.rb:144:in `block in build_instances'
E, [2016-06-15T21:29:13.015951 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/config.rb:143:in `map'
E, [2016-06-15T21:29:13.015980 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/config.rb:143:in `with_index'
E, [2016-06-15T21:29:13.016009 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/config.rb:143:in `build_instances'
E, [2016-06-15T21:29:13.016049 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/config.rb:119:in `instances'
E, [2016-06-15T21:29:13.016080 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/command.rb:97:in `all_instances'
E, [2016-06-15T21:29:13.016110 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/command.rb:145:in `parse_subcommand'
E, [2016-06-15T21:29:13.016139 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/command/test.rb:43:in `block in call'
E, [2016-06-15T21:29:13.016168 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
E, [2016-06-15T21:29:13.016197 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/command/test.rb:41:in `call'
E, [2016-06-15T21:29:13.016226 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/cli.rb:56:in `perform'
E, [2016-06-15T21:29:13.016267 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/cli.rb:231:in `test'
E, [2016-06-15T21:29:13.016307 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
E, [2016-06-15T21:29:13.016338 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
E, [2016-06-15T21:29:13.016397 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/cli.rb:325:in `invoke_task'
E, [2016-06-15T21:29:13.016428 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
E, [2016-06-15T21:29:13.016457 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
E, [2016-06-15T21:29:13.016486 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/bin/kitchen:13:in `block in <top (required)>'
E, [2016-06-15T21:29:13.016514 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/lib/kitchen/errors.rb:174:in `with_friendly_errors'
E, [2016-06-15T21:29:13.016543 #7494] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.9.2/bin/kitchen:13:in `<top (required)>'
E, [2016-06-15T21:29:13.016571 #7494] ERROR -- Kitchen: /usr/bin/kitchen:17:in `load'
E, [2016-06-15T21:29:13.016599 #7494] ERROR -- Kitchen: /usr/bin/kitchen:17:in `<main>'
E, [2016-06-15T21:29:13.016627 #7494] ERROR -- Kitchen: ----End Backtrace-----
```

**Comment by cheeseplus** [comment]
We actually pulled 0.15.9 for other reasons but I've reported this so it should be addressed in the next build.

**Comment by mwrock** [comment]
oh wow. glad we caught this. looks like berkshelf and some other gems that test-kitchen dynamically loads are not added to the `$LOAD_PATH`

**Comment by tyler-ball** [comment]
If you delete your `~/.chefdk` or `~/appdata/local/chefdk` does this issue go away?

**Comment by mwrock** [comment]
that made the error go away for me. A bit unsettling but i'm betting it will block you.

**Comment by davidcpell** [comment]
I'm also having this problem with ChefDK v0.16.28 / Kitchen v1.10.2:

`Message: Could not load the 'inspec' verifier from the load path. Please ensure that your transport is installed as a gem or included in your Gemfile if using Bundler.`

I do not have `~/.chefdk` or `~/appdata/local/chefdk`

**Comment by srjayep** [comment]
My issue : 

#kitchen verify
-----> Starting Kitchen (v1.11.1)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'inspec' verifier from the load path. Please ensure that your transport is installed as a gem or included in your Gemfile if using Bundler.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

and Resolution : 
gem 'kitchen-inspec' in Gemfile

Hope this helps.

**Comment by username-is-already-taken2** [comment]
Hi there

I'm now using chefdk 0.17.17 still on windows :)

```
Chef Development Kit Version: 0.17.17
chef-client version: 12.13.37
delivery version: master (f68e5c5804cd7d8a76c69b926fbb261e1070751b)
berks version: 4.3.5
kitchen version: 1.11.1
```

I see that the chef generate cookbook command is now creating cookbooks with a default .kitchen.yml that has inspec as the verifier

```
verifier:
  name: inspec
```

That's cool but I'm still getting the gem berkshelf missing error when having inspec as my verifier 

```
>kitchen list
!!!!!! The `berkshelf' gem is missing and must be installed or cannot be properly activated. Run `gem install berkshelf` or add the following to your Gemfile if you are using Bundler: `gem 'berkshelf'`.
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::UserError
>>>>>> Message: Could not load or activate Berkshelf (cannot load such file -- berkshelf)
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

```
>chef gem list --local | grep berks
berkshelf (4.3.5, 4.3.2)
berkshelf-api-client (2.0.2)
```

There was a suggestion that I should edit my gemfile? should that have been created as part of the chef generate command? as I don't have a file called that within my cookbook directory.

Appreciate your help

Best Regards

Gary

**Comment by davidcpell** [comment]
@username-is-already-taken2 can you try also prefacing `kitchen list` with `chef`, i.e.:

`$ chef kitchen list`

**Comment by username-is-already-taken2** [comment]
Hi there @davidcpell 

I tired `chef exec kitchen list` but I got exactly same error :(

**Comment by chris-rock** [comment]
Do you use test-kitchen and a gemfile?

**Comment by username-is-already-taken2** [comment]
Hi 

Just test-kitchen.  I don't have a gemfile in my cookbook, I only have what was generated with the chef generate cookbook command.

**Comment by chris-rock** [comment]
@username-is-already-taken2 is that publicly available, so that we are able to reproduce

**Comment by username-is-already-taken2** [comment]
I'm pleased to report this issue is now resolved, unfortunately I can't tell you exactly what the fix was.

It was either going to `chefdk-0.18.30-1` or the fact that I uninstalled the chefdk, rebooted and then install 18.30 but I've had this issue through multiple vesions of the dk, so maybe it was the uninstalled?

Either way thanks for your help

**Comment by HighwayofLife** [comment]
Adding `gem 'berkshelf'` to your `Gemfile` would be one way to resolve the issue.
