### ISSUE TITLE
No live threads left. Deadlock? (fatal) error

### ISSUE THREAD

**Issue by nellshamrell** [test-kitchen/test-kitchen#1041]
## Description

I am seeing this error when attempting to spin up a new kitchen:
```ruby
      Resolving cookbook dependencies with Berkshelf 4.3.2...
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.7.3/lib/kitchen/command.rb:181:in `join': No live threads left. Deadlock? (fatal)
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.7.3/lib/kitchen/command.rb:181:in `map'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.7.3/lib/kitchen/command.rb:181:in `run_action'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.7.3/lib/kitchen/command/action.rb:39:in `block in call'
        from /opt/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.7.3/lib/kitchen/command/action.rb:37:in `call'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.7.3/lib/kitchen/cli.rb:56:in `perform'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.7.3/lib/kitchen/cli.rb:180:in `block (2 levels) in <class:CLI>'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.7.3/lib/kitchen/cli.rb:321:in `invoke_task'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.7.3/bin/kitchen:13:in `block in <top (required)>'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.7.3/lib/kitchen/errors.rb:154:in `with_friendly_errors'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.7.3/bin/kitchen:13:in `<top (required)>'
        from /opt/chefdk/bin/kitchen:17:in `load'
        from /opt/chefdk/bin/kitchen:17:in `<main>'
```

I have attempted 
```
$ rm ~/.chefdk
```
And I am still seeing the error when attempting to run kitchen converge

## Kitchen Version

```ruby
Test Kitchen version 1.7.3
```

## ChefDK Version

```ruby
Chef Development Kit Version: 0.13.21
```

## Ruby Version

```ruby
I am using ChefDK
```

## Platform Version

OS X Yosemite Version 10.10.5

## Replication Case

1) Use the above ChefDK and kitchen versions
2) Attempt to run $ kitchen converge for an ubuntu-1004 and ubuntu-1204 instance (I have not tested this with Ubuntu 1404 or 1604)
3) You should see the same error

## Kitchen Output

```ruby
-----> Converging <default-ubuntu-1004>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 4.3.2...
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.7.3/lib/kitchen/command.rb:181:in `join': No live threads left. Deadlock? (fatal)
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.7.3/lib/kitchen/command.rb:181:in `map'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.7.3/lib/kitchen/command.rb:181:in `run_action'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.7.3/lib/kitchen/command/action.rb:39:in `block in call'
        from /opt/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.7.3/lib/kitchen/command/action.rb:37:in `call'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.7.3/lib/kitchen/cli.rb:56:in `perform'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.7.3/lib/kitchen/cli.rb:180:in `block (2 levels) in <class:CLI>'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.7.3/lib/kitchen/cli.rb:321:in `invoke_task'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.7.3/bin/kitchen:13:in `block in <top (required)>'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.7.3/lib/kitchen/errors.rb:154:in `with_friendly_errors'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.7.3/bin/kitchen:13:in `<top (required)>'
        from /opt/chefdk/bin/kitchen:17:in `load'
        from /opt/chefdk/bin/kitchen:17:in `<main>'
```

## Kitchen Diagnose

https://gist.github.com/nellshamrell/cd0f57f95311dcfe2fd8d2b713140cc3

## NOTE:

This repository is for core issues with the Test-Kitchen framework, so if the issue is with a plugin you may be referred to file the issue with the appropriate plugin.

**Comment by nellshamrell** [comment]
This is the same issue reported in #978

**Comment by nellshamrell** [comment]
Upgraded my ChefDK and Test Kitchen versions to:

Chef Development Kit Version: 0.14.25
chef-client version: 12.10.24
berks version: 4.3.3
kitchen version: 1.8.0

Still seeing the same error :(

**Comment by nellshamrell** [comment]
Results of running $ kitchen converge default-ubuntu-1204 -l debug

https://gist.github.com/nellshamrell/b6f99c8ed04b515a2723e8deb910ab0a

**Comment by nellshamrell** [comment]
Still seeing the same error after downgrading to Chef DK 0.12.0
```
11:10:47-nshamrell~/Projects/supermarket/omnibus (add-option-to-configure-s3-url-type)$ chef -v
Chef Development Kit Version: 0.12.0
chef-client version: 12.8.1
berks version: 4.3.0
kitchen version: 1.6.0
```

**Comment by xeron** [comment]
Remove `~/.chefdk`, remove chefdk itself from `/opt` completely and reinstall it.

See https://gist.github.com/otukutun/0106977649dd765eb9b7

**Comment by nellshamrell** [comment]
Ty, that process of 1) Removing ~/.chefdk, removing chefdk itself complete from /opt, and 3) reinstalling chef dk worked.  I much appreciate it!
