### ISSUE TITLE
Converge fails if encrypted_data_bag_secret_path is specified

### ISSUE THREAD

**Issue by remkade** [test-kitchen/test-kitchen#1052]
## Description

Once I upgraded to kitchen 1.9.1 all of my converges fail with no such file or directory when kitchen attempts to scp over the encrypted data bag. I even went so far as to remove all symlinks that it could possibly stumble on. Converge gets passed the error if I remove the `encrypted_data_bag_secret_path` line from the kitchen.yml, but then chef fails.

## Kitchen Version
1.9.1

## Ruby Version
`ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]`

## Platform Version

OS X 10.11.5

## Replication Case

Include a line similar to this in your .kitchen.yml:
`encrypted_data_bag_secret_key_path: ../avvo_chef/encrypted_data_bag_secret`

## Kitchen Output
(Truncated to relevant lines)
```
       Thank you for installing Chef!
D      [SSH] vagrant@127.0.0.1<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>"2222", :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :keys_only=>true, :keys=>["/Users/kyle_leaders/Documents/Cookbooks/switchboard/.kitchen/kitchen-vagrant/kitchen-switchboard-default-ubuntu-1404/.vagrant/machines/default/virtualbox/private_key"], :auth_methods=>["publickey"], :user=>"vagrant"}> (sh -c '
sudo_rm="sudo -E rm"
dirs="/tmp/kitchen/clients /tmp/kitchen/cookbooks /tmp/kitchen/data /tmp/kitchen/data_bags /tmp/kitchen/encrypted_data_bag_secret /tmp/kitchen/environments /tmp/kitchen/roles"
root_path="/tmp/kitchen"

$sudo_rm -rf $dirs
mkdir -p $root_path
')
       Transferring files to <default-ubuntu-1404>
D      TIMING: scp async upload (Kitchen::Transport::Ssh)
D      Cleaning up local sandbox in /var/folders/x_/0734n0sn4f3cq1jd4xm2_nlh0000gn/T/default-ubuntu-1404-sandbox-20160609-93297-7rt5ee
D      [SSH] shutting previous connection vagrant@127.0.0.1<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>"2222", :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :keys_only=>true, :keys=>["/Users/kyle_leaders/Documents/Cookbooks/switchboard/.kitchen/kitchen-vagrant/kitchen-switchboard-default-ubuntu-1404/.vagrant/machines/default/virtualbox/private_key"], :auth_methods=>["publickey"], :user=>"vagrant"}>
D      [SSH] closing connection to vagrant@127.0.0.1<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>"2222", :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :keys_only=>true, :keys=>["/Users/kyle_leaders/Documents/Cookbooks/switchboard/.kitchen/kitchen-vagrant/kitchen-switchboard-default-ubuntu-1404/.vagrant/machines/default/virtualbox/private_key"], :auth_methods=>["publickey"], :user=>"vagrant"}>
/usr/local/lib/ruby/gems/2.3.0/gems/net-scp-1.2.1/lib/net/scp/upload.rb:117:in `stat': No such file or directory @ rb_file_s_stat - /var/folders/x_/0734n0sn4f3cq1jd4xm2_nlh0000gn/T/default-ubuntu-1404-sandbox-20160609-93297-7rt5ee/roles (Errno::ENOENT)
	from /usr/local/lib/ruby/gems/2.3.0/gems/net-scp-1.2.1/lib/net/scp/upload.rb:117:in `set_current'
	from /usr/local/lib/ruby/gems/2.3.0/gems/net-scp-1.2.1/lib/net/scp/upload.rb:24:in `upload_start_state'
	from /usr/local/lib/ruby/gems/2.3.0/gems/net-scp-1.2.1/lib/net/scp.rb:365:in `block (3 levels) in start_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/net-ssh-3.1.1/lib/net/ssh/connection/channel.rb:607:in `do_close'
	from /usr/local/lib/ruby/gems/2.3.0/gems/net-ssh-3.1.1/lib/net/ssh/connection/session.rb:598:in `channel_close'
	from /usr/local/lib/ruby/gems/2.3.0/gems/net-ssh-3.1.1/lib/net/ssh/connection/session.rb:476:in `dispatch_incoming_packets'
	from /usr/local/lib/ruby/gems/2.3.0/gems/net-ssh-3.1.1/lib/net/ssh/connection/session.rb:222:in `preprocess'
	from /usr/local/lib/ruby/gems/2.3.0/gems/net-ssh-3.1.1/lib/net/ssh/connection/session.rb:206:in `process'
	from /usr/local/lib/ruby/gems/2.3.0/gems/net-ssh-3.1.1/lib/net/ssh/connection/session.rb:170:in `block in loop'
	from /usr/local/lib/ruby/gems/2.3.0/gems/net-ssh-3.1.1/lib/net/ssh/connection/session.rb:170:in `loop'
	from /usr/local/lib/ruby/gems/2.3.0/gems/net-ssh-3.1.1/lib/net/ssh/connection/session.rb:170:in `loop'
	from /usr/local/lib/ruby/gems/2.3.0/gems/net-ssh-3.1.1/lib/net/ssh/connection/session.rb:119:in `close'
	from /usr/local/lib/ruby/gems/2.3.0/gems/test-kitchen-1.9.1/lib/kitchen/transport/ssh.rb:113:in `close'
	from /usr/local/lib/ruby/gems/2.3.0/gems/test-kitchen-1.9.1/lib/kitchen/transport/ssh.rb:95:in `cleanup!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/test-kitchen-1.9.1/lib/kitchen/instance.rb:274:in `cleanup!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/test-kitchen-1.9.1/lib/kitchen/command.rb:200:in `ensure in run_action_in_thread'
	from /usr/local/lib/ruby/gems/2.3.0/gems/test-kitchen-1.9.1/lib/kitchen/command.rb:200:in `run_action_in_thread'
	from /usr/local/lib/ruby/gems/2.3.0/gems/test-kitchen-1.9.1/lib/kitchen/command.rb:173:in `block (2 levels) in run_action'
```

**Comment by mwrock** [comment]
1.9.2 has JUST been released with some important fixes to SCP addressing this exact issue. Can you give that a try?

**Comment by remkade** [comment]
That fixes it! Thanks!
