### ISSUE TITLE
"incompatible character encodings: UTF-8 and ASCII-8BIT" when using cyrillic letters in cookbook

### ISSUE THREAD

**Issue by jugatsu** [test-kitchen/test-kitchen#1170]
## Description

test-kitchen failes on converge state when cookbook contains cyrillic letters. Error:

> "incompatible character encodings: UTF-8 and ASCII-8BIT"

## Kitchen Version

Test Kitchen version 1.14.2

## ChefDK Version

Chef Development Kit Version: 1.1.16
chef-client version: 12.17.44
delivery version: master (83358fb62c0f711c70ad5a81030a6cae4017f103)
berks version: 5.2.0
kitchen version: 1.14.2

## Platform Version

Ubuntu 14.04.5 LTS.

## Replication Case

Please see example cookbook below

```ruby
windows_ad_ou 'Ай-ти отдел' do
  domain_name 'contoso.com'
  action :create
end
```

depends on https://github.com/TAMUArch/cookbook.windows_ad

BTW, it doesn't matter which resource to use. It could be windows_package or dsc_resource

```ruby
windows_package 'Ай-ти отдел' do # name changed for demonstration purpose
  source 'https://notepad-plus-plus.org/repository/7.x/7.0/npp.7.Installer.exe'
  checksum '0155c4ab117d63ba5142fc1090debc07dc7953264f7202ef8d25014e2cf8668d'
  action :install
end
```
or

```ruby
dsc_resource 'Add OU' do
   resource :xADOrganizationalUnit
   property :Name, 'Ай-ти отдел'
   property :Path, 'dc=contoso,dc=com'
   property :Ensure, 'Present'
 end
```

## Kitchen Output

https://gist.github.com/jugatsu/4e2b36e74177910aa3da401c1757a1fa

## Kitchen Diagnose

https://gist.github.com/jugatsu/b1290d85667c41cbcc4f5f4696d54b03

**Comment by jugatsu** [comment]
I think it may be https://github.com/WinRb/WinRM issue.

**Comment by jugatsu** [comment]
However, test-kitchen **doesn't fail** when using
```ruby
package = 'Ай-ти отдел'.encode('windows-1251')
windows_package package do
  source 'https://notepad-plus-plus.org/repository/7.x/7.0/npp.7.Installer.exe'
  checksum '0155c4ab117d63ba5142fc1090debc07dc7953264f7202ef8d25014e2cf8668d'
  action :install
end
```

```ruby
Converging 4 resources
       Recipe: gf_adds::default
         * windows_package[Àé-òè îòäåë] action install
         Recipe: <Dynamically Defined Resource>
           * remote_file[C:\Users\vagrant\AppData\Local\Temp\kitchen\cache\package\npp.7.Installer.exe] action create (up to date)
           - install version latest of package Àé-òè îòäåë
       Recipe: ms_dotnet::ms_dotnet2
         * ms_dotnet_framework[2.0.SP2] action install (up to date)
       Recipe: powershell::windows_reboot
         * reboot[powershell] action nothing (skipped due to action :nothing)
       Recipe: powershell::powershell5
         * windows_package[Windows Management Framework Core 5.0] action install (skipped due to not_if)
       
       Running handlers:
       Running handlers complete
       Chef Client finished, 1/5 resources updated in 08 seconds
       Finished converging <default-windows2008r2> (0m49.53s).

```

but windows_ad_ou resource still failes

```ruby
Converging 5 resources
       Recipe: gf_adds::default
         * windows_ad_ou[Àé-òè îòäåë] action create (up to date)
         * windows_ad_ou_2008[Àé-òè îòäåë] action create
       
           ================================================================================
           Error executing action `create` on resource 'windows_ad_ou_2008[Àé-òè îòäåë]'
           ================================================================================
       
           RuntimeError
           ------------
           Failed to execute command.
           STDOUT: 
           STDERR: dsadd failed:ou=??-?? ?????,DC=contoso,DC=com:An attempt was made to add an object to the directory with a name that is already in use.
       
           type dsadd /? for help.
       
           Resource Declaration:
           ---------------------
           # In C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/windows_ad/providers/ou.rb
       
            32:     windows_ad_ou_2008 new_resource.name do
            33:       action :create
            34:       ou new_resource.ou unless new_resource.ou.nil?
            35:       domain_name new_resource.domain_name
            36:     end
            37:   elsif node['os_version'] >= '6.2'
            38:     windows_ad_ou_2012 new_resource.name do
            39:       action :create
            40:       path new_resource.ou unless new_resource.ou.nil?
            41:       domain_name new_resource.domain_name
            42:     end
            43:   else
            44:     Chef::Log.error('This version of Windows is not supported')
            45:   end
            46: end
            47: 
       
           Compiled Resource:
           ------------------
           # Declared in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/windows_ad/providers/ou.rb:32:in `block in class_from_file'
       
           windows_ad_ou_2008("Àé-òè îòäåë") do
             action [:create]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :windows_ad_ou_2008
             cookbook_name "gf_adds"
             domain_name "contoso.com"
           end
       
           Platform:
           ---------
           x64-mingw32
       
       
       Running handlers:
       [2016-12-18T02:04:40-08:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-12-18T02:04:40-08:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 06 seconds
       [2016-12-18T02:04:40-08:00] FATAL: Stacktrace dumped to C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/chef-stacktrace.out
       [2016-12-18T02:04:40-08:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2016-12-18T02:04:40-08:00] FATAL: RuntimeError: windows_ad_ou_2008[Àé-òè îòäåë] (C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/windows_ad/providers/ou.rb line 32) had an error: RuntimeError: Failed to execute command.
       STDOUT: 
       STDERR: dsadd failed:ou=??-?? ?????,DC=contoso,DC=com:An attempt was made to add an object to the directory with a name that is already in use.
       
       type dsadd /? for help.

```

I think it isn't resource issue but encoding.

**Comment by jugatsu** [comment]
Continue debugging. I'm trying to connect with this simple script

```ruby
require 'winrm'
opts = {
  endpoint: 'http://192.168.50.10:5985/wsman',
  user: 'vagrant',
  password: 'vagrant'
}
conn = WinRM::Connection.new(opts)
conn.shell(:powershell) do |shell|
  output = shell.run('echo "Ай-ти отдел"') do |stdout, stderr|
    STDOUT.print stdout
    STDERR.print stderr
  end
  puts "The script exited with exit code #{output.exitcode}"
end
``` 

The output:

> Ай-ти отдел
The script exited with exit code 0

As far as I know, test-kitchen is using PSRP protocol by default. So I think the root of this issue is from encoding powershell output by https://github.com/WinRb/WinRM/blob/master/lib/winrm/psrp/powershell_output_decoder.rb#L133

**Comment by jugatsu** [comment]
I can reproduce this issue with knife winrm command
knife winrm -m 192.168.50.10 "chef-client" -x vagrant --winrm-shell powershell -VV
```ruby
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.1.0/lib/winrm/psrp/message_data/pipeline_output.rb:35:in `gsub': incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.1.0/lib/winrm/psrp/message_data/pipeline_output.rb:35:in `block in extract_out_string'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.1.0/lib/winrm/psrp/message_data/pipeline_output.rb:32:in `map'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.1.0/lib/winrm/psrp/message_data/pipeline_output.rb:32:in `extract_out_string'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.1.0/lib/winrm/psrp/message_data/pipeline_output.rb:25:in `output'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.1.0/lib/winrm/psrp/powershell_output_decoder.rb:51:in `decode_pipeline_output'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.1.0/lib/winrm/psrp/powershell_output_decoder.rb:33:in `decode'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.1.0/lib/winrm/psrp/receive_response_reader.rb:63:in `block (2 levels) in read_output'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.1.0/lib/winrm/psrp/receive_response_reader.rb:45:in `block in read_message'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.1.0/lib/winrm/wsmv/receive_response_reader.rb:66:in `block in read_response'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.1.0/lib/winrm/wsmv/receive_response_reader.rb:121:in `block in read_streams'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.1.0/lib/winrm/wsmv/receive_response_reader.rb:119:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.1.0/lib/winrm/wsmv/receive_response_reader.rb:119:in `read_streams'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.1.0/lib/winrm/wsmv/receive_response_reader.rb:65:in `read_response'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.1.0/lib/winrm/psrp/receive_response_reader.rb:41:in `read_message'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.1.0/lib/winrm/psrp/receive_response_reader.rb:60:in `block in read_output'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.1.0/lib/winrm/wsmv/receive_response_reader.rb:75:in `with_output'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.1.0/lib/winrm/psrp/receive_response_reader.rb:59:in `read_output'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.1.0/lib/winrm/shells/base.rb:81:in `block in run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.1.0/lib/winrm/shells/base.rb:127:in `with_command_shell'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.1.0/lib/winrm/shells/base.rb:80:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/knife-windows-1.7.1/lib/chef/knife/winrm_session.rb:69:in `block in relay_command'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.1.0/lib/winrm/connection.rb:43:in `shell'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/knife-windows-1.7.1/lib/chef/knife/winrm_session.rb:67:in `relay_command'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/knife-windows-1.7.1/lib/chef/knife/winrm_knife_base.rb:130:in `block in relay_winrm_command'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/knife-windows-1.7.1/lib/chef/knife/winrm_knife_base.rb:128:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/knife-windows-1.7.1/lib/chef/knife/winrm_knife_base.rb:128:in `relay_winrm_command'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/knife-windows-1.7.1/lib/chef/knife/winrm_knife_base.rb:114:in `run_command'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/knife-windows-1.7.1/lib/chef/knife/winrm.rb:60:in `execute_remote_command'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/knife-windows-1.7.1/lib/chef/knife/winrm.rb:52:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/knife.rb:443:in `block in run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/local_mode.rb:44:in `with_server_connectivity'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/knife.rb:442:in `run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/knife.rb:219:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application/knife.rb:156:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/bin/knife:58:in `load'
	from /opt/chefdk/bin/knife:58:in `<main>'
```

**Comment by cheeseplus** [comment]
This looks like chef-client is failing, not kitchen

**Comment by mwrock** [comment]
I've confirmed this is definitely a winrm bug. Hoping to have a fix out this weekend.

**Comment by jugatsu** [comment]
Thanks for reply Matt.

**Comment by jugatsu** [comment]
Further debbuging.
chef-client doesn't fail. I don't see any chef-stacktrace in cache dir. I also checked with this hack

```ruby
dsc_resource 'Add OU-1' do
  resource :xADOrganizationalUnit
  property :Name, 'Бухгалтерия'
  property :Path, 'dc=corp,dc=contoso,dc=com'
  property :Ensure, 'Present'
end

file 'C:\\test.txt' do
  content 'Русский язык'
  action :create
end
```

File resource is successfully created. And so OU.

**Comment by mwrock** [comment]
Fix pending in the elevated shell here: https://github.com/WinRb/winrm-elevated/pull/18 but the fact that you hit this via knife winrm using the plain powershell shell indicates there may be another "hole to plug" so investigating that.

**Comment by jugatsu** [comment]
Awesome. Matter thanks for quick fix.
Btw, how can i test it this?

**Comment by jugatsu** [comment]
OK. I wil try to wget updated elevated_shell.ps1 to /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/winrm-elevated-1.1.0/lib/winrm-elevated/scripts/

I will report results.

**Comment by mwrock** [comment]
That *should* fix the TK run where you used the elevated shell. It seems the vanilla powershell shell has no issues with with utf-8 directly but something in knife windows is probably not handing over the command text or printing the response correctly so I'm gonna fix tat and makesure its all working and then I'll release the winrm fixes and report back.

**Comment by jugatsu** [comment]
It definitely works! But got the same error if i change elavated to false. Comments in this PR
https://github.com/WinRb/winrm-elevated/pull/18

**Comment by mwrock** [comment]
Just released winrm 2.1.1 which fixes this. Please reopen if you are still broken. I need to figure out why the winrm elevated tests are failing before releasing that but that is more of an aesthetic fix while the winrm core fix stops the breakage for both elevated and non elevated.

**Comment by jugatsu** [comment]
**It works.**
Appreciate for great support.

But how to get russian letters in output rather that `РђР Рњ РѕРїРµСЂР°С‚РѕСЂР° РђР—РЎ`

```ruby
Chef Omnibus installation detected (install only if missing)
       Transferring files to <default-windows-posready7>
       Starting Chef Client, version 12.15.19
       resolving cookbooks for run list: ["gf_itoil_gas::default"]
       Synchronizing Cookbooks:
         - gf_itoil_gas (0.6.1)
         - seven_zip (2.0.2)
         - gf_iconv (0.1.1)
         - windows (2.1.1)
         - ohai (4.2.2)
         - compat_resource (12.16.2)
       Installing Cookbook Gems:
       Compiling Cookbooks...
       Converging 1 resources
       Recipe: gf_itoil_gas::install
         * windows_package[РђР Рњ РѕРїРµСЂР°С‚РѕСЂР° РђР—РЎ] action install
         Recipe: <Dynamically Defined Resource>
           * remote_file[C:\Users\vagrant\AppData\Local\Temp\kitchen\cache\package\ItOilStation24606.exe] action create (up to date)
            (up to date)
       
       Running handlers:
       Running handlers complete
       Chef Client finished, 0/2 resources updated in 07 seconds
       Finished converging <default-windows-posready7> (0m18.15s).
```

But resource is idempotent because HKLM uninstall registry of DisplayName is perfectly good.

Testing on:
Windows Embedded POSReady 7 SP1
Windows Server 2008 R2 SP1

**Comment by mwrock** [comment]
Yeah the rendering of the UTF-8 is very sub par and I explain further in the winrm PR. Basically a limitation of powershell remoting is you cant change the console encoding of a remote shell. However, you see the same thing you would see if you ran chef in a native windows powershell remoting session.

Once I wrap up the winrm-elevated PR, at least if you are using an elevated shell, the rendering will show the true UTF-8 characters.

Thanks for testing and verifying the fix!

**Comment by jugatsu** [comment]
Confirmed.
wget https://raw.githubusercontent.com/WinRb/winrm-elevated/eadacf30b71a6f81dffe5bb34863a7f2d6619233/lib/winrm-elevated/scripts/elevated_shell.ps1 to /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/winrm-elevated-1.1.0/lib/winrm-elevated/scripts

Using elevated: true

```ruby
Recipe: gf_itoil_gas::install
         * windows_package[АРМ оператора АЗС] action install
         Recipe: <Dynamically Defined Resource>
           * remote_file[C:\Users\vagrant\AppData\Local\Temp\kitchen\cache\package\ItOilStation24606.exe] action create
            (up to date)
       
       Running handlers:
       Running handlers complete
       Chef Client finished, 0/2 resources updated in 07 seconds
       Finished converging <default-windows-posready7> (0m42.13s).
```

For template resource workaround I will be using diff_disabled config option
```yaml
client_rb:
    exit_status: :enabled
    client_fork: false
    diff_disabled: true
```
