### ISSUE TITLE
Compat issues with net-ssh 4.x

### ISSUE THREAD

**Issue by coderanger** [test-kitchen/test-kitchen#1184]
With Chef finally moving over to net-ssh 4.x, I think this has exposed a compat issue:

The error trace is:

```
IOError: closed stream
  /Users/coderanger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/net-ssh-4.0.1/lib/net/ssh/buffered_io.rb:102:in `send'
  /Users/coderanger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/net-ssh-4.0.1/lib/net/ssh/buffered_io.rb:102:in `send_pending'
  /Users/coderanger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/net-ssh-4.0.1/lib/net/ssh/connection/session.rb:271:in `block in ev_do_handle_events'
  /Users/coderanger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/net-ssh-4.0.1/lib/net/ssh/connection/session.rb:270:in `each'
  /Users/coderanger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/net-ssh-4.0.1/lib/net/ssh/connection/session.rb:270:in `ev_do_handle_events'
  /Users/coderanger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/net-ssh-4.0.1/lib/net/ssh/connection/event_loop.rb:110:in `ev_select_and_postprocess'
  /Users/coderanger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/net-ssh-4.0.1/lib/net/ssh/connection/event_loop.rb:29:in `process'
  /Users/coderanger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/net-ssh-4.0.1/lib/net/ssh/connection/session.rb:216:in `process'
  /Users/coderanger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/net-ssh-4.0.1/lib/net/ssh/connection/session.rb:178:in `block in loop'
  /Users/coderanger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/net-ssh-4.0.1/lib/net/ssh/connection/session.rb:178:in `loop'
  /Users/coderanger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/net-ssh-4.0.1/lib/net/ssh/connection/session.rb:178:in `loop'
  /Users/coderanger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:802:in `loop'
  /Users/coderanger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:730:in `close_channel'
  /Users/coderanger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kitchen-sync-2.1.1/lib/kitchen/transport/sftp.rb:54:in `close'
  /Users/coderanger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/test-kitchen-2ce46e6e369e/lib/kitchen/transport/ssh.rb:98:in `cleanup!'
  /Users/coderanger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/test-kitchen-2ce46e6e369e/lib/kitchen/instance.rb:285:in `cleanup!'
  /Users/coderanger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/test-kitchen-2ce46e6e369e/lib/kitchen/command.rb:205:in `run_action_in_thread'
  /Users/coderanger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/test-kitchen-2ce46e6e369e/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
  /Users/coderanger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:450:in `block in create_with_logging_context'
```

Seems to be triggered on the initial connection to second instance of a multi-instance `kitchen test` but only if there is a lot of time or output (not sure which yet). More details to follow as I figure them out.

Prior discussion over on https://github.com/chef/chef/issues/5740

**Comment by lamont-granquist** [comment]
what happens if you remove kitchen-sync/net-sftp?

**Comment by coderanger** [comment]
That does fix it. Sigh, might be something in my code then :(

**Comment by lamont-granquist** [comment]
might be net-sftp incompatibility with net-ssh 4.x

**Comment by coderanger** [comment]
Maybe but I'm not sure how yet. Tempted to just add a `rescue IOError` and give no shits but I should probably stare at the networking code for at least a few minutes.

**Comment by coderanger** [comment]
As best I can tell from looking over all the 4.x changes, everything in kitchen itself is still correct and this is some weird interplay between net-ssh and net-sftp because of how I'm doing connection shutdown. If this comes up from kitchen's own shutdown code I'll care more :)

**Comment by coderanger** [comment]
Created https://github.com/net-ssh/net-ssh/pull/493 in case this comes up for someone else.
