### ISSUE TITLE
[windows] No live threads left. Deadlock?

### ISSUE THREAD

**Issue by username-is-already-taken2** [test-kitchen/test-kitchen#1224]
Hi there

## Description

I'm struggling to get test-kitchen to converge.  When I run a `chef exec kitchen converge` I get the following error.  

```
-----> Converging <default-rhel-7>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 5.6.4...
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:173:in `join': No live threads left. Deadlock? (fatal)
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:173:in `map'
```

I'm using windows 10, Vagrant (1.9.3) and VMware workstation (12.5.5) The annoying thing is that `kitchen create` works my test vm is create and configured `chef exec kitchen login` works fine I just can't converge my vm.

## Kitchen Version

```
Chef Development Kit Version: 1.3.43
chef-client version: 12.19.36
delivery version: master (dd319aa632c2f550c92a2172b9d1226478fea997)
berks version: 5.6.4
kitchen version: 1.16.0
```
## ChefDK Version

If you are running test-kitchen via ChefDK, `chef --version` will provide additional relevent version details.

```ruby
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:173:in `join': No live threads left. Deadlock? (fata
l)                                                                                                                                                 
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:173:in `map'                           
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:173:in `run_action'                    
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command/action.rb:36:in `block in call'           
        from C:/opscode/chefdk/embedded/lib/ruby/2.3.0/benchmark.rb:293:in `measure'                                                               
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command/action.rb:34:in `call'                    
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:53:in `perform'                            
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:187:in `block (2 levels) in <class:CLI>'   
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'                                       
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'                        
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:334:in `invoke_task'                       
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'                                         
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'                                       
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/bin/kitchen:13:in `block in <top (required)>'                 
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/errors.rb:171:in `with_friendly_errors'           
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/bin/kitchen:13:in `<top (required)>'                          
        from C:/opscode/chefdk/bin/kitchen:24:in `load'                                                                                            
        from C:/opscode/chefdk/bin/kitchen:24:in `<main>'                                                                                          
```

## Platform Version

windows 10, Vagrant (1.9.3) and VMware workstation (12.5.5)

## Possible Fix? 
Some other threads have suggested deleting the .chefdk folder.  I don't know where that is on windows so I have tried uninstalling and reinstalled the chefdk.

**Comment by username-is-already-taken2** [comment]
Sorry, clearly I did my usual `man look` for that folder on double checking I found it tucked away in my profile

```C:\Users\Cant_See_For_Looking\AppData\Local\chefdk```

renamed that folder and it converged first time, sorry
