### ISSUE TITLE
Kitchen create command failing for SUSE 

### ISSUE THREAD

**Issue by ksravs** [test-kitchen/test-kitchen#1239]
## Description

Briefly describe the issue
I want to use kitchen tests on SUSE 12 Sp1  with docker as driver.
## Kitchen Version
Test Kitchen version 1.16.0
Tell us which version of test-kitchen you are using (`kitchen --version`).  

```ruby ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux-gnu]

# Copy-paste your results here

My .kitchen.yml file 
----------------------------------------
driver:
  name: docker
provisioner:
  name: chef_solo
platforms:
  - name: ubuntu-12.04
  - name: centos-7.2
  - name: sles-12.1
---------------------------------------------------
Error while using the following command: ``` kitchen create server-sles-121
-----> Starting Kitchen (v1.16.0)
-----> Creating <server-sles-121>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Create failed on instance <server-sles-121>.  Please see .kitchen/logs/server-sles-121.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

Error in the log is below :
I, [2017-05-24T14:53:38.844121 #24347]  INFO -- server-sles-121: -----> Creating <server-sles-121>...
E, [2017-05-24T14:53:38.844422 #24347] ERROR -- server-sles-121: Create failed on instance <server-sles-121>.
E, [2017-05-24T14:53:38.844523 #24347] ERROR -- server-sles-121: ------Exception-------
E, [2017-05-24T14:53:38.844548 #24347] ERROR -- server-sles-121: Class: Kitchen::ActionFailed
E, [2017-05-24T14:53:38.844563 #24347] ERROR -- server-sles-121: Message: Unknown platform 'sles'
E, [2017-05-24T14:53:38.844576 #24347] ERROR -- server-sles-121: ----------------------
E, [2017-05-24T14:53:38.844589 #24347] ERROR -- server-sles-121: ------Backtrace-------
E, [2017-05-24T14:53:38.844601 #24347] ERROR -- server-sles-121: /usr/lib64/ruby/gems/2.1.0/gems/kitchen-docker-2.6.0/lib/kitchen/driver/docker.rb:249:in `build_dockerfile'
E, [2017-05-24T14:53:38.844614 #24347] ERROR -- server-sles-121: /usr/lib64/ruby/gems/2.1.0/gems/kitchen-docker-2.6.0/lib/kitchen/driver/docker.rb:285:in `dockerfile'
E, [2017-05-24T14:53:38.844627 #24347] ERROR -- server-sles-121: /usr/lib64/ruby/gems/2.1.0/gems/kitchen-docker-2.6.0/lib/kitchen/driver/docker.rb:304:in `build_image'
E, [2017-05-24T14:53:38.844643 #24347] ERROR -- server-sles-121: /usr/lib64/ruby/gems/2.1.0/gems/kitchen-docker-2.6.0/lib/kitchen/driver/docker.rb:122:in `create'
E, [2017-05-24T14:53:38.844656 #24347] ERROR -- server-sles-121: /usr/lib64/ruby/gems/2.1.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:460:in `public_send'
E, [2017-05-24T14:53:38.844669 #24347] ERROR -- server-sles-121: /usr/lib64/ruby/gems/2.1.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:460:in `block in perform_action'
E, [2017-05-24T14:53:38.844681 #24347] ERROR -- server-sles-121: /usr/lib64/ruby/gems/2.1.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
E, [2017-05-24T14:53:38.844694 #24347] ERROR -- server-sles-121: /usr/lib64/ruby/gems/2.1.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:489:in `block in action'
E, [2017-05-24T14:53:38.844706 #24347] ERROR -- server-sles-121: /usr/lib64/ruby/2.1.0/benchmark.rb:279:in `measure'
E, [2017-05-24T14:53:38.844719 #24347] ERROR -- server-sles-121: /usr/lib64/ruby/gems/2.1.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:488:in `action'
E, [2017-05-24T14:53:38.844731 #24347] ERROR -- server-sles-121: /usr/lib64/ruby/gems/2.1.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:460:in `perform_action'
E, [2017-05-24T14:53:38.844746 #24347] ERROR -- server-sles-121: /usr/lib64/ruby/gems/2.1.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:370:in `create_action'
E, [2017-05-24T14:53:38.844759 #24347] ERROR -- server-sles-121: /usr/lib64/ruby/gems/2.1.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:359:in `block in transition_to'
E, [2017-05-24T14:53:38.844771 #24347] ERROR -- server-sles-121: /usr/lib64/ruby/gems/2.1.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `each'
E, [2017-05-24T14:53:38.844784 #24347] ERROR -- server-sles-121: /usr/lib64/ruby/gems/2.1.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `transition_to'
E, [2017-05-24T14:53:38.844796 #24347] ERROR -- server-sles-121: /usr/lib64/ruby/gems/2.1.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:124:in `create'
E, [2017-05-24T14:53:38.844809 #24347] ERROR -- server-sles-121: /usr/lib64/ruby/gems/2.1.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `public_send'
E, [2017-05-24T14:53:38.844821 #24347] ERROR -- server-sles-121: /usr/lib64/ruby/gems/2.1.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2017-05-24T14:53:38.844834 #24347] ERROR -- server-sles-121: /usr/lib64/ruby/gems/2.1.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2017-05-24T14:53:38.844864 #24347] ERROR -- server-sles-121: ----End Backtrace-----


## ChefDK Version

If you are running test-kitchen via ChefDK, `chef --version` will provide additional relevent version details.

```ruby
# Copy-paste your results here
```

## Ruby Version

If you are not using test-kitchen via ChefDK, please provide the output of ruby --version.

```ruby
# Copy-paste your results here
```

## Platform Version

Tell us which Operating System distribution and version test-kitchen is running on.

## Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

## Kitchen Output

The relevant output of the test-kitchen run or a link to a gist of the entire run, if there is one.

The debug output (kitchen -l debug) may be useful, but please link to a gist, or truncate it.

Please do not paste the full run out put here.  If the full output would be useful, link to it in a gist.

```ruby
# Copy-paste your results here
```

## Kitchen Diagnose

Please include the output of `kitchen diagnose --all` or `kitchen diagnose --loader` (if the first failed).  This can be helpful in troubleshooting, so please include it in a gist.

## NOTE:

This repository is for core issues with the Test-Kitchen framework, so if the issue is with a plugin you may be referred to file the issue with the appropriate plugin.

**Comment by coderanger** [comment]
SLES support for kitchen-docker was merged maybe 5 minutes ago, give me a few :)

**Comment by ksravs** [comment]
sure. thanks. when would this be available for use ?
