### ISSUE TITLE
test pass with `kitchen verify` but not with `kitchen test`

### ISSUE THREAD

**Issue by wickedviking** [test-kitchen/test-kitchen#1244]
## Description

`kitchen test` - fails all tests
`kitchen verify` - passes all test

## Kitchen Version
```ruby
Test Kitchen version 1.16.0
```

## ChefDK Version
```ruby
Chef Development Kit Version: 1.4.3
chef-client version: 12.19.36
delivery version: master (41b94ffb5efd33723cf72a89bf4d273c8151c9dc)
berks version: 5.6.4
kitchen version: 1.16.0
inspec version: 1.25.1
```

## Ruby Version

I am using test-kitchen as part of ChefDK, but also have ruby...
```ruby
ruby 2.3.3p222 (2016-11-21 revision 56859) [x64-mingw32]
```

## Platform Version

Windows 10 (Creators) fully update, building on Hyper-V using Vagrant driver.

## Replication Case
My .kitchen.yml, git.rb recipe, and git_test.rb inspec test along with screen output

https://gist.github.com/wickedviking/4fdbd928484b24e88418394202e82494

run ```kitchen test``` everything builds but the tests fail
immediately run ```kitchen verify``` and tests all pass

## Kitchen Output

.kitchen/logs/default-domain-controller.log
full: https://gist.github.com/wickedviking/e6b833c73ea867c60fec2c09a9da184d
snips
```
I, [2017-07-07T13:35:37.417805 #13836]  INFO -- default-domain-controller: -----> Verifying <default-domain-controller>...
I, [2017-07-07T13:35:37.529240 #13836]  INFO -- default-domain-controller: Loaded tests from test/smoke/default 
E, [2017-07-07T13:35:42.062842 #13836] ERROR -- default-domain-controller: Verify failed on instance <default-domain-controller>.
E, [2017-07-07T13:35:42.062842 #13836] ERROR -- default-domain-controller: ------Exception-------
E, [2017-07-07T13:35:42.062842 #13836] ERROR -- default-domain-controller: Class: Kitchen::ActionFailed
E, [2017-07-07T13:35:42.062842 #13836] ERROR -- default-domain-controller: Message: Inspec Runner returns 1
E, [2017-07-07T13:35:42.062842 #13836] ERROR -- default-domain-controller: ----------------------
E, [2017-07-07T13:35:42.062842 #13836] ERROR -- default-domain-controller: ------Backtrace-------
E, [2017-07-07T13:35:42.062842 #13836] ERROR -- default-domain-controller: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/kitchen-inspec-0.17.0/lib/kitchen/verifier/inspec.rb:96:in `call'
E, [2017-07-07T13:35:42.062842 #13836] ERROR -- default-domain-controller: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:434:in `block in verify_action'
E, [2017-07-07T13:35:42.062842 #13836] ERROR -- default-domain-controller: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
E, [2017-07-07T13:35:42.062842 #13836] ERROR -- default-domain-controller: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:489:in `block in action'
E, [2017-07-07T13:35:42.062842 #13836] ERROR -- default-domain-controller: C:/opscode/chefdk/embedded/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2017-07-07T13:35:42.062842 #13836] ERROR -- default-domain-controller: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:488:in `action'
E, [2017-07-07T13:35:42.062842 #13836] ERROR -- default-domain-controller: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:426:in `verify_action'
E, [2017-07-07T13:35:42.062842 #13836] ERROR -- default-domain-controller: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:359:in `block in transition_to'
E, [2017-07-07T13:35:42.062842 #13836] ERROR -- default-domain-controller: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `each'
E, [2017-07-07T13:35:42.062842 #13836] ERROR -- default-domain-controller: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `transition_to'
E, [2017-07-07T13:35:42.062842 #13836] ERROR -- default-domain-controller: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:157:in `verify'
E, [2017-07-07T13:35:42.062842 #13836] ERROR -- default-domain-controller: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:186:in `block in test'
E, [2017-07-07T13:35:42.062842 #13836] ERROR -- default-domain-controller: C:/opscode/chefdk/embedded/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2017-07-07T13:35:42.062842 #13836] ERROR -- default-domain-controller: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:182:in `test'
E, [2017-07-07T13:35:42.062842 #13836] ERROR -- default-domain-controller: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `public_send'
E, [2017-07-07T13:35:42.062842 #13836] ERROR -- default-domain-controller: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2017-07-07T13:35:42.062842 #13836] ERROR -- default-domain-controller: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2017-07-07T13:35:42.062842 #13836] ERROR -- default-domain-controller: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/logging-2.2.0/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
E, [2017-07-07T13:35:42.062842 #13836] ERROR -- default-domain-controller: ----End Backtrace-----
```
.kitchen/logs/kitchen.log
full: https://gist.github.com/wickedviking/f64b69b753800bcf262d4c49d7c10912
snips
```
I, [2017-07-07T13:28:46.783065 #13836]  INFO -- Kitchen: -----> Converging <default-domain-controller>...
I, [2017-07-07T13:35:37.402178 #13836]  INFO -- Kitchen: -----> Setting up <default-domain-controller>...
I, [2017-07-07T13:35:37.417805 #13836]  INFO -- Kitchen: -----> Verifying <default-domain-controller>...
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: ------Exception-------
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: Message: 1 actions failed.
>>>>>>     Verify failed on instance <default-domain-controller>.  Please see .kitchen/logs/default-domain-controller.log for more details
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: ----------------------
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: ------Backtrace-------
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:183:in `report_errors'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:174:in `run_action'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command/test.rb:42:in `block in call'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command/test.rb:38:in `call'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:53:in `perform'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:234:in `test'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:334:in `invoke_task'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/bin/kitchen:13:in `block in <top (required)>'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/errors.rb:171:in `with_friendly_errors'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/bin/kitchen:13:in `<top (required)>'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/bin/kitchen:24:in `load'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/bin/kitchen:24:in `<main>'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: ----End Backtrace-----
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: -Composite Exception--
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: Class: Kitchen::InstanceFailure
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: Message: Verify failed on instance <default-domain-controller>.  Please see .kitchen/logs/default-domain-controller.log for more details
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: ----------------------
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: ------Backtrace-------
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/kitchen-inspec-0.17.0/lib/kitchen/verifier/inspec.rb:96:in `call'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:434:in `block in verify_action'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:489:in `block in action'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:488:in `action'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:426:in `verify_action'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:359:in `block in transition_to'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `each'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `transition_to'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:157:in `verify'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:186:in `block in test'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:182:in `test'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `public_send'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/logging-2.2.0/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: ----End Backtrace-----
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: ---Nested Exception---
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: Message: Inspec Runner returns 1
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: ----------------------
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: ------Backtrace-------
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/kitchen-inspec-0.17.0/lib/kitchen/verifier/inspec.rb:96:in `call'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:434:in `block in verify_action'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:489:in `block in action'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:488:in `action'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:426:in `verify_action'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:359:in `block in transition_to'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `each'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `transition_to'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:157:in `verify'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:186:in `block in test'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:182:in `test'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `public_send'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/logging-2.2.0/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
E, [2017-07-07T13:35:42.078464 #13836] ERROR -- Kitchen: ----End Backtrace-----
```

.kitchen/default-domain-controller.yml
```
---
hostname: 10.101.142.37
port: '5985'
username: vagrant
password: vagrant
rdp_port: '3389'
last_action: setup
last_error: Kitchen::ActionFailed
```

## Kitchen Diagnose
kitchen diagnose --all
https://gist.github.com/wickedviking/43fb9471585484daf8615f21a198bf05

**Comment by stormerider** [comment]
My suggestion would be to try running `kitchen converge;kitchen verify` and see if it also fails. But as Adam Leff mentioned in Slack, it sounds like some form of race condition like a service being slow to start up.

**Comment by wickedviking** [comment]
so i did try dropping sleeps is various locations in the recipe and test, but seemed to have no impact

**Comment by wickedviking** [comment]
```kitchen create; kitchen converge; kitchen verify``` passes just fine. Is it possible that ```kitchen test``` is having an issue firing off the inspec tests for some reason?

**Comment by cheeseplus** [comment]
`kitchen test` is literally just an aggregate command and as such is going to hit the same codepath as verify so far as I can tell so that wouldn't explain it - I'm still thinking like above it's a timing issue.

**Comment by wickedviking** [comment]
I agree, my setup has evolved and this problem has disappeared. I wouldn't say it got solved, but I haven't experienced since I refactored my base box build. I'm comfortable with this getting closed. If it happens again I'll open a new issue and mention this one.
