### ISSUE TITLE
kitchen verify fails

### ISSUE THREAD

**Issue by pratri07** [test-kitchen/test-kitchen#1245]
## Description

kitchen verify fails

```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Verify failed on instance <default-centos-73>.  Please see .kitchen/logs/default-centos-73.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```
## Kitchen Version

Tell us which version of test-kitchen you are using (`kitchen --version`).  

```
chef -v
Chef Development Kit Version: 2.0.26
chef-client version: 13.2.20
delivery version: master (17c1b0fed9be4c70f69091a6d21a4cbf0df60a23)
berks version: 6.2.0
kitchen version: 1.16.0
inspec version: 1.30.0

 kitchen --version
Test Kitchen version 1.16.0
```

## Ruby Version

If you are not using test-kitchen via ChefDK, please provide the output of ruby --version.

```
ruby --version
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin14]
```

## Platform Version

Tell us which Operating System distribution and version test-kitchen is running on.

10.12.5 - macOS sierra 

```
       Running handlers:
       Running handlers complete
       Chef Client finished, 3/3 resources updated in 15 seconds
       Finished converging <default-centos-73> (0m29.34s).
-----> Setting up <default-centos-73>...
       Finished setting up <default-centos-73> (0m0.00s).
-----> Verifying <default-centos-73>...
       Loaded tests from test/smoke/default 

Profile: tests from test/smoke/default
Version: (not specified)
Target:  ssh://vagrant@127.0.0.1:2222


  Port 80
     ∅  should not be listening
     expected `Port 80.listening?` to return false, got true

Test Summary: 0 successful, 1 failures, 0 skipped
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Verify failed on instance <default-centos-73>.  Please see .kitchen/logs/default-centos-73.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

cat kitchen.log 
I, [2017-07-09T20:06:09.233360 #38106]  INFO -- Kitchen: -----> Starting Kitchen (v1.16.0)
I, [2017-07-09T20:06:10.730267 #38106]  INFO -- Kitchen: -----> Cleaning up any prior instances of <default-centos-73>
I, [2017-07-09T20:06:10.730429 #38106]  INFO -- Kitchen: -----> Destroying <default-centos-73>...
I, [2017-07-09T20:06:10.733165 #38106]  INFO -- Kitchen: -----> Testing <default-centos-73>
I, [2017-07-09T20:06:10.733318 #38106]  INFO -- Kitchen: -----> Creating <default-centos-73>...
I, [2017-07-09T20:06:48.290903 #38106]  INFO -- Kitchen: -----> Converging <default-centos-73>...
I, [2017-07-09T20:07:17.630623 #38106]  INFO -- Kitchen: -----> Setting up <default-centos-73>...
I, [2017-07-09T20:07:17.632842 #38106]  INFO -- Kitchen: -----> Verifying <default-centos-73>...
E, [2017-07-09T20:07:18.034826 #38106] ERROR -- Kitchen: ------Exception-------
E, [2017-07-09T20:07:18.034895 #38106] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2017-07-09T20:07:18.034942 #38106] ERROR -- Kitchen: Message: 1 actions failed.
>>>>>>     Verify failed on instance <default-centos-73>.  Please see .kitchen/logs/default-centos-73.log for more details
E, [2017-07-09T20:07:18.034986 #38106] ERROR -- Kitchen: ----------------------
E, [2017-07-09T20:07:18.035007 #38106] ERROR -- Kitchen: ------Backtrace-------
E, [2017-07-09T20:07:18.035021 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:183:in `report_errors'
E, [2017-07-09T20:07:18.035037 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:174:in `run_action'
E, [2017-07-09T20:07:18.035051 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command/test.rb:42:in `block in call'
E, [2017-07-09T20:07:18.035064 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
E, [2017-07-09T20:07:18.035078 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command/test.rb:38:in `call'
E, [2017-07-09T20:07:18.035091 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:53:in `perform'
E, [2017-07-09T20:07:18.035105 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:234:in `test'
E, [2017-07-09T20:07:18.035118 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
E, [2017-07-09T20:07:18.035131 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
E, [2017-07-09T20:07:18.035145 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:334:in `invoke_task'
E, [2017-07-09T20:07:18.035158 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
E, [2017-07-09T20:07:18.035172 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
E, [2017-07-09T20:07:18.035185 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/bin/kitchen:13:in `block in <top (required)>'
E, [2017-07-09T20:07:18.035198 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/errors.rb:171:in `with_friendly_errors'
E, [2017-07-09T20:07:18.035211 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/bin/kitchen:13:in `<top (required)>'
E, [2017-07-09T20:07:18.035223 #38106] ERROR -- Kitchen: /opt/chefdk/bin/kitchen:264:in `load'
E, [2017-07-09T20:07:18.035235 #38106] ERROR -- Kitchen: /opt/chefdk/bin/kitchen:264:in `<main>'
E, [2017-07-09T20:07:18.035247 #38106] ERROR -- Kitchen: ----End Backtrace-----
E, [2017-07-09T20:07:18.035260 #38106] ERROR -- Kitchen: -Composite Exception--
E, [2017-07-09T20:07:18.035272 #38106] ERROR -- Kitchen: Class: Kitchen::InstanceFailure
E, [2017-07-09T20:07:18.035301 #38106] ERROR -- Kitchen: Message: Verify failed on instance <default-centos-73>.  Please see .kitchen/logs/default-centos-73.log for more details
E, [2017-07-09T20:07:18.035317 #38106] ERROR -- Kitchen: ----------------------
E, [2017-07-09T20:07:18.035329 #38106] ERROR -- Kitchen: ------Backtrace-------
E, [2017-07-09T20:07:18.035341 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/kitchen-inspec-0.19.0/lib/kitchen/verifier/inspec.rb:96:in `call'
E, [2017-07-09T20:07:18.035354 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:434:in `block in verify_action'
E, [2017-07-09T20:07:18.035368 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
E, [2017-07-09T20:07:18.035382 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:489:in `block in action'
E, [2017-07-09T20:07:18.035395 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
E, [2017-07-09T20:07:18.035407 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:488:in `action'
E, [2017-07-09T20:07:18.035419 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:426:in `verify_action'
E, [2017-07-09T20:07:18.035432 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:359:in `block in transition_to'
E, [2017-07-09T20:07:18.035446 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `each'
E, [2017-07-09T20:07:18.035458 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `transition_to'
E, [2017-07-09T20:07:18.035471 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:157:in `verify'
E, [2017-07-09T20:07:18.035484 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:186:in `block in test'
E, [2017-07-09T20:07:18.035497 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
E, [2017-07-09T20:07:18.035509 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:182:in `test'
E, [2017-07-09T20:07:18.035522 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `public_send'
E, [2017-07-09T20:07:18.035581 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2017-07-09T20:07:18.035596 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2017-07-09T20:07:18.035609 #38106] ERROR -- Kitchen: ----End Backtrace-----
E, [2017-07-09T20:07:18.035621 #38106] ERROR -- Kitchen: ---Nested Exception---
E, [2017-07-09T20:07:18.035633 #38106] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2017-07-09T20:07:18.035646 #38106] ERROR -- Kitchen: Message: Inspec Runner returns 1
E, [2017-07-09T20:07:18.035658 #38106] ERROR -- Kitchen: ----------------------
E, [2017-07-09T20:07:18.035670 #38106] ERROR -- Kitchen: ------Backtrace-------
E, [2017-07-09T20:07:18.035683 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/kitchen-inspec-0.19.0/lib/kitchen/verifier/inspec.rb:96:in `call'
E, [2017-07-09T20:07:18.035696 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:434:in `block in verify_action'
E, [2017-07-09T20:07:18.035709 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
E, [2017-07-09T20:07:18.035729 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:489:in `block in action'
E, [2017-07-09T20:07:18.035745 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
E, [2017-07-09T20:07:18.035759 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:488:in `action'
E, [2017-07-09T20:07:18.035773 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:426:in `verify_action'
E, [2017-07-09T20:07:18.035789 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:359:in `block in transition_to'
E, [2017-07-09T20:07:18.035802 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `each'
E, [2017-07-09T20:07:18.035815 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `transition_to'
E, [2017-07-09T20:07:18.035827 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:157:in `verify'
E, [2017-07-09T20:07:18.035841 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:186:in `block in test'
E, [2017-07-09T20:07:18.035854 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
E, [2017-07-09T20:07:18.035866 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:182:in `test'
E, [2017-07-09T20:07:18.035879 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `public_send'
E, [2017-07-09T20:07:18.035891 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2017-07-09T20:07:18.035904 #38106] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2017-07-09T20:07:18.035916 #38106] ERROR -- Kitchen: ----End Backtrace-----
```

## Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

## Kitchen Output

The relevant output of the test-kitchen run or a link to a gist of the entire run, if there is one.

The debug output (kitchen -l debug) may be useful, but please link to a gist, or truncate it.

Please do not paste the full run out put here.  If the full output would be useful, link to it in a gist.

## Kitchen Diagnose

Please include the output of `kitchen diagnose --all` or `kitchen diagnose --loader` (if the first failed).  This can be helpful in troubleshooting, so please include it in a gist.

```
kitchen verify -l debug
-----> Starting Kitchen (v1.16.0)
D      [Vagrant command] BEGIN (vagrant --version)
D      [Vagrant command] END (0m0.06s)
D      Berksfile found at /Users/Pratri/learningchef/oracle/Berksfile, loading Berkshelf
D      Berkshelf 6.2.0 library loaded
-----> Setting up <default-centos-69>...
       Finished setting up <default-centos-69> (0m0.00s).
-----> Verifying <default-centos-69>...
D      Initialize InSpec
[2017-07-09T20:39:22-04:00] DEBUG: Resolve test/smoke/default into cache /Users/Pratri/.inspec/cache
[2017-07-09T20:39:22-04:00] DEBUG: Dependency does not exist in the cache test/smoke/default
       Loaded tests from test/smoke/default 
[2017-07-09T20:39:22-04:00] DEBUG: Starting run with targets: ["Inspec::Profile<tests from test/smoke/default>"]
[2017-07-09T20:39:22-04:00] DEBUG: Loading test/smoke/default/default_test.rb into #<Inspec::ProfileContext:0x007ff73f554d10>
[2017-07-09T20:39:22-04:00] DEBUG: Registering rule (generated from default_test.rb:8 94987ef42ef70eabc0feece73c39a91f)
[2017-07-09T20:39:22-04:00] DEBUG: Registering rule (generated from default_test.rb:12 0fbca5462a07a60b8956b7922e21a458)
[2017-07-09T20:39:22-04:00] DEBUG: Registering rule (generated from default_test.rb:18 1f5a74cef17a90705e04a63cff0da14a)
[2017-07-09T20:39:22-04:00] DEBUG: Registering rule (generated from default_test.rb:32 187be14ae8f8a1e3656445417e7392b6)
[2017-07-09T20:39:22-04:00] DEBUG: Registering rule (generated from default_test.rb:36 b15542989230608a9d7bfa1341fb8cd2)
[2017-07-09T20:39:22-04:00] DEBUG: Registering rule (generated from default_test.rb:40 094022da8b65bd2e75241ab1b064ae6d)

Profile: tests from test/smoke/default
Version: (not specified)
Target:  ssh://vagrant@127.0.0.1:2200


  Port 1521
     ✔  should not be listening
  User oracle
     ✔  should exist
     ✔  uid should eq 201
     ✔  shell should eq "/bin/ksh"
  File /u01/orainv
     ✔  should be directory
     ✔  should be owned by "oracle"
  Kernel Parameter
     ✔  kernel.shmmax value should eq 4294967295
  Grub Config
     ∅  kernel should include "transparent_hugepage=never"
     expected ["/vmlinuz-2.6.32-696.el6.x86_64", "ro", "root=/dev/mapper/VolGroup-lv_root", "rd_NO_LUKS", "LANG=en_...=auto", "rd_LVM_LV=VolGroup/lv_root", "KEYBOARDTYPE=pc", "KEYTABLE=us", "rd_NO_DM", "rhgb", "quiet"] to include "transparent_hugepage=never"
  File /etc/grub_conf
     ∅  content should match /transparent_hugepage=never/
     expected nil to match /transparent_hugepage=never/

Test Summary: 7 successful, 2 failures, 0 skipped
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Verify failed on instance <default-centos-69>.  Please see .kitchen/logs/default-centos-69.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: 1 actions failed.
>>>>>>     Verify failed on instance <default-centos-69>.  Please see .kitchen/logs/default-centos-69.log for more details
D      ----------------------
D      ------Backtrace-------
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:183:in `report_errors'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:174:in `run_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command/action.rb:36:in `block in call'
D      /opt/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command/action.rb:34:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:53:in `perform'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:187:in `block (2 levels) in <class:CLI>'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:334:in `invoke_task'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/bin/kitchen:13:in `block in <top (required)>'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/errors.rb:171:in `with_friendly_errors'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/bin/kitchen:13:in `<top (required)>'
D      /opt/chefdk/bin/kitchen:264:in `load'
D      /opt/chefdk/bin/kitchen:264:in `<main>'
D      ----End Backtrace-----
D      -Composite Exception--
D      Class: Kitchen::InstanceFailure
D      Message: Verify failed on instance <default-centos-69>.  Please see .kitchen/logs/default-centos-69.log for more details
D      ----------------------
D      ------Backtrace-------
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/kitchen-inspec-0.19.0/lib/kitchen/verifier/inspec.rb:96:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:434:in `block in verify_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:489:in `block in action'
D      /opt/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:488:in `action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:426:in `verify_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:359:in `block in transition_to'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `each'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `transition_to'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:157:in `verify'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `public_send'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      ----End Backtrace-----
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: Inspec Runner returns 1
D      ----------------------
D      ------Backtrace-------
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/kitchen-inspec-0.19.0/lib/kitchen/verifier/inspec.rb:96:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:434:in `block in verify_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:489:in `block in action'
D      /opt/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:488:in `action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:426:in `verify_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:359:in `block in transition_to'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `each'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `transition_to'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:157:in `verify'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `public_send'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      ----End Backtrace-----
```

## NOTE:

This repository is for core issues with the Test-Kitchen framework, so if the issue is with a plugin you may be referred to file the issue with the appropriate plugin.

**Comment by coderanger** [comment]
Yes, your test failed. Not sure what you expected.

**Comment by pratri07** [comment]
thanks for reply, i would like to know why it gives exception here after running test?

**Comment by coderanger** [comment]
Because your test failed, hence it raises an `ActionFailed` exception.

**Comment by pratri07** [comment]
thanks a lot, i checked removing those failed test and verify finished without exception.

Can you please help me resolving below issue?

I want to verify Oracle database by running some query, but it's not working..

How can we run Inspec test with specific user like "oracle" ?

sql = oracledb_session( user: 'system', pass: 'XXXXX', host: 'chefd.local.com', sid: 'chkdb', sqlplus_bin: '/u01/db12201/bin/sqlplus' )
describe sql.query('SELECT NAME FROM v$database;').row(0).column('name') do
  its('value') { should cmp 'CHKDB' }
end

it errors like below,

 SQL Column
     ∅  undefined method `[]' for nil:NilClass

I've also tried below,

inspec exec default/oratest.rb -t ssh://oracle@192.168.33.8 --password 'XXXXX'
[DEPRECATED] use `password` option to supply password instead of `pass`
Could not execute the sql query 
Error 6 initializing SQL*Plus
SP2-0667: Message file sp1<lang>.msb not found
SP2-0750: You may need to set ORACLE_HOME to your Oracle software directory

Profile: tests from default/oratest.rb
Version: (not specified)
Target:  ssh://oracle@192.168.33.8:22

  SQL Column
     ∅  undefined method `[]' for nil:NilClass

Test Summary: 0 successful, 1 failures, 0 skipped
