### ISSUE TITLE
Failed to complete #converge action: [key{hostname} not found] on default-windows-2012r2

### ISSUE THREAD

**Issue by giacDaddy** [test-kitchen/test-kitchen#1246]
## Description

Everytime I run `kitchen converge` it prints out `ActionFailed` and that it `failed to complete converge action: [key{hostname} not found] on default-windows-2012r2`. Does anyone know what/where the `[key{hostname} not found]` is coming from? I can't figure it out for the life of me. See below.

## Kitchen Version
`Test Kitchen version 1.16.0`

## ChefDK Version
`Chef Development Kit Version: 1.3.43`

## Ruby Version
`ruby 2.0.0p648 (2015-12-16) [x86_64-linux]`

## Platform Version
`Oracle Linux Server release 7.3`
`NAME="Oracle Linux Server"`
`VERSION="7.3"`
`ID="ol"`
`VERSION_ID="7.3"`
`PRETTY_NAME="Oracle Linux Server 7.3"`
`ANSI_COLOR="0;31"`
`CPE_NAME="cpe:/o:oracle:linux:7:3:server"`
`HOME_URL="https://linux.oracle.com/"`
`BUG_REPORT_URL="https://bugzilla.oracle.com/"`

`ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"`
`ORACLE_BUGZILLA_PRODUCT_VERSION=7.3`
`ORACLE_SUPPORT_PRODUCT="Oracle Linux"`
`ORACLE_SUPPORT_PRODUCT_VERSION=7.3`
`Red Hat Enterprise Linux Server release 7.3 (Maipo)`
`Oracle Linux Server release 7.3`

## Replication Case

I just created a recipe within a cookbook that I wanted to try out with test kitchen for the first time and ran the create and converge commands.

## Kitchen Output
```ruby
-----> Starting Kitchen (v1.16.0)
D      winrm requested, loading winrm gem (["~> 2.0"])
D      winrm is loaded.
D      winrm-fs requested, loading winrm-fs gem (["~> 1.0"])
D      winrm-fs is loaded.
D      winrm-elevated requested, loading winrm-elevated gem (["~> 1.0"])
D      winrm-elevated is loaded.
-----> Converging <default-windows-2012r2>...
       Preparing files for transfer
D      Creating local sandbox in /tmp/default-windows-2012r2-sandbox-20170712-21788-lhls1k
       Preparing dna.json
D      Creating dna.json from {:run_list=>["recipe[opc::windows_base]"]}
       Preparing cookbooks from project directory
D      Using cookbooks from /home/user@domain.com/chef-repo/cookbooks
       Removing non-cookbook files before transfer
       Preparing data_bags
D      Using data_bags from /home/user@domain.com/chef-repo/data_bags
       Preparing environments
D      Using environments from /home/user@domain.com/chef-repo/environments
       Preparing nodes
D      Using nodes from /home/user@domain.com/chef-repo/nodes
       Preparing roles
D      Using roles from /home/user@domain.com/chef-repo/roles
       Preparing solo.rb
D      Creating solo.rb from {:node_name=>"default-windows-2012r2", :checksum_path=>"\#{ENV['TEMP']}\\kitchen\\checksums", :file_cache_path=>"\#{ENV['TEMP']}\\kitchen\\cache", :file_backup_path=>"\#{ENV['TEMP']}\\kitchen\\backup", :cookbook_path=>["\#{ENV['TEMP']}\\kitchen\\cookbooks", "\#{ENV['TEMP']}\\kitchen\\site-cookbooks"], :data_bag_path=>"\#{ENV['TEMP']}\\kitchen\\data_bags", :environment_path=>"\#{ENV['TEMP']}\\kitchen\\environments", :node_path=>"\#{ENV['TEMP']}\\kitchen\\nodes", :role_path=>"\#{ENV['TEMP']}\\kitchen\\roles", :client_path=>"\#{ENV['TEMP']}\\kitchen\\clients", :user_path=>"\#{ENV['TEMP']}\\kitchen\\users", :validation_key=>"\#{ENV['TEMP']}\\kitchen\\validation.pem", :client_key=>"\#{ENV['TEMP']}\\kitchen\\client.pem", :chef_server_url=>"http://127.0.0.1:8889", :encrypted_data_bag_secret=>"\#{ENV['TEMP']}\\kitchen\\encrypted_data_bag_secret", :treat_deprecation_warnings_as_errors=>false}
D      Cleaning up local sandbox in /tmp/default-windows-2012r2-sandbox-20170712-21788-lhls1k
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #converge action: [key{hostname} not found] on default-windows-2012r2
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: 1 actions failed.
>>>>>>     Failed to complete #converge action: [key{hostname} not found] on default-windows-2012r2
D      ----------------------
D      ------Backtrace-------
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:183:in `report_errors'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:174:in `run_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command/action.rb:36:in `block in call'
D      /opt/chefdk/embedded/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command/action.rb:34:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:53:in `perform'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:187:in `block (2 levels) in <class:CLI>'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:334:in `invoke_task'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/bin/kitchen:13:in `block in <top (required)>'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/errors.rb:171:in `with_friendly_errors'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/bin/kitchen:13:in `<top (required)>'
D      /bin/kitchen:21:in `load'
D      /bin/kitchen:21:in `<main>'
D      ----End Backtrace-----
D      -Composite Exception--
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #converge action: [key{hostname} not found] on default-windows-2012r2
D      ----------------------
D      ------Backtrace-------
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/transport/winrm.rb:375:in `%'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/transport/winrm.rb:375:in `connection_options'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/transport/winrm.rb:69:in `connection'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/provisioner/base.rb:68:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:384:in `block in converge_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:489:in `block in action'
D      /opt/chefdk/embedded/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:488:in `action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:380:in `converge_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:359:in `block in transition_to'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `each'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `transition_to'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:135:in `converge'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `public_send'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/logging-2.2.0/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
D      ----End Backtrace-----
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #converge action: [key{hostname} not found]
D      ----------------------
D      ------Backtrace-------
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/transport/winrm.rb:375:in `%'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/transport/winrm.rb:375:in `connection_options'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/transport/winrm.rb:69:in `connection'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/provisioner/base.rb:68:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:384:in `block in converge_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:489:in `block in action'
D      /opt/chefdk/embedded/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:488:in `action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:380:in `converge_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:359:in `block in transition_to'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `each'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `transition_to'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:135:in `converge'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `public_send'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/logging-2.2.0/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
D      ----End Backtrace-----

```

## Kitchen Diagnose
```ruby
---
timestamp: 2017-07-12 21:56:47 UTC
kitchen_version: 1.16.0
plugins:
  driver:
    Dummy:
      class: Kitchen::Driver::Dummy
      version: 1.16.0
      api_version: 2
  provisioner:
    ChefSolo:
      class: Kitchen::Provisioner::ChefSolo
      version: 1.16.0
      api_version: 2
  transport:
    Winrm:
      class: Kitchen::Transport::Winrm
      version: 1.16.0
      api_version: 1
  verifier:
    Busser:
      class: Kitchen::Verifier::Busser
      version: 1.16.0
      api_version: 1
loader:
  process_erb: true
  process_local: true
  process_global: true
  global_config:
  project_config:
    filename: "/home/user@domain.com/chef-repo/.kitchen.yml"
    raw_data:
      driver:
      name: chef_zero
      provisioner:
      deprecations_as_errors: true
      platforms:
      - name: windows-2012r2
        os_type: windows
        transport:
          name: winrm
          elevated: true
        driver:
          box: windows-2012r2
      suites:
      - name: default
        run_list:
        - recipe[opc::windows_base]
  local_config:
  combined_config:
    filename:
    raw_data:
      driver: {}
      name: chef_zero
      provisioner: {}
      deprecations_as_errors: true
      platforms:
      - name: windows-2012r2
        os_type: windows
        transport:
          name: winrm
          elevated: true
        driver:
          box: windows-2012r2
      suites:
      - name: default
        run_list:
        - recipe[opc::windows_base]
instances:
  default-windows-2012r2:
    platform:
      os_type: windows
      shell_type: powershell
    state_file:
      last_action: create
      last_error: KeyError
      my_id: default-windows-2012r2-1499886141
    driver:
      box: windows-2012r2
      kitchen_root: "/home/user@domain.com/chef-repo"
      log_level: :info
      name: dummy
      random_failure: false
      sleep: 0
      test_base_path: "/home/user@domain.com/chef-repo/test/integration"
    provisioner:
      always_update_cookbooks: false
      attributes: {}
      chef_omnibus_install_options:
      chef_omnibus_url: https://omnitruck.chef.io/install.sh
      chef_solo_path: "\\bin\\chef-solo.bat"
      clients_path:
      command_prefix:
      config_path:
      cookbook_files_glob: README.*,metadata.{json,rb},attributes/**/*,definitions/**/*,files/**/*,libraries/**/*,providers/**/*,recipes/**/*,resources/**/*,templates/**/*
      data_bags_path: "/home/user@domain.com/chef-repo/data_bags"
      data_path:
      deprecations_as_errors: false
      encrypted_data_bag_secret_key_path:
      enforce_idempotency: false
      environments_path: "/home/user@domain.com/chef-repo/environments"
      ftp_proxy:
      http_proxy:
      https_proxy:
      kitchen_root: "/home/user@domain.com/chef-repo"
      log_file:
      log_level: auto
      max_retries: 1
      multiple_converge: 1
      name: chef_solo
      nodes_path: "/home/user@domain.com/chef-repo/nodes"
      policyfile:
      policyfile_path:
      profile_ruby: false
      require_chef_omnibus: true
      retry_on_exit_code: []
      roles_path: "/home/user@domain.com/chef-repo/roles"
      root_path: "$env:TEMP\\kitchen"
      run_list:
      - recipe[opc::windows_base]
      solo_rb: {}
      sudo:
      sudo_command:
      test_base_path: "/home/user@domain.com/chef-repo/test/integration"
      wait_for_retry: 30
    transport:
      connection_retries: 5
      connection_retry_sleep: 1
      elevated: true
      endpoint_template: http://%{hostname}:%{port}/wsman
      kitchen_root: "/home/user@domain.com/chef-repo"
      log_level: :info
      max_wait_until_ready: 600
      name: winrm
      password:
      port: 5985
      rdp_port: 3389
      test_base_path: "/home/user@domain.com/chef-repo/test/integration"
      username: administrator
      winrm_transport: :negotiate
    verifier:
      busser_bin: "$env:TEMP\\verifier\\bin\\busser.bat"
      chef_omnibus_root: "/opt/chef"
      command_prefix:
      ftp_proxy:
      http_proxy:
      https_proxy:
      kitchen_root: "/home/user@domain.com/chef-repo"
      log_level: :info
      name: busser
      root_path: "$env:TEMP\\verifier"
      ruby_bindir: "$env:systemdrive\\opscode\\chef\\embedded\\bin"
      sudo:
      sudo_command:
      suite_name: default
      test_base_path: "/home/user@domain.com/chef-repo/test/integration"
      version: busser
```

**Comment by cheeseplus** [comment]
I feel like it's probably coming from `endpoint_template: http://%{hostname}:%{port}/wsman` but I'm not sure exactly why you'd be getting that one.

**Comment by cheeseplus** [comment]
Closing this as the bug itself was upstream with winrm/winrmfs and is comlplicated by the use of the `dummy` driver which we are planning on refactoring as part of upcoming work.

**Comment by mikhail-anfimau** [comment]
I got precisely the same error as described above because of mistyping the name of the platform. Instead of windows-2012R2 (upper case R) I typed windows-2012r2 (lower-case r). kitchen create gave no error, and kitchen converge failed with "key{hostname} not found" error.
