### ISSUE TITLE
Kitchen create is not able to create a VM with the below error

### ISSUE THREAD

**Issue by seshikanthguduri** [test-kitchen/test-kitchen#1292]
## Description

Kitchen create is not able to create a VM

## Kitchen Version
Test Kitchen version 1.18.0 

## ChefDK Version
$ chef --version
Chef Development Kit Version: 2.3.4
chef-client version: 13.4.19
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.17.0
inspec version: 1.36.1

## Ruby Version

If you are not using test-kitchen via ChefDK, please provide the output of ruby --version.

$ ruby --version
ruby 2.3.2p217 (2016-11-15 revision 56796) [x86_64-darwin16]

## Platform Version

Tell us which Operating System distribution and version test-kitchen is running on.
Running on MacOS Sierra
version : 10.12.6(16G29)

## Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

## Kitchen Output

```
kitchen test -l debug
-----> Starting Kitchen (v1.18.0)
D      Berksfile found at /Users/user_name/usf/on_prem/chef-repo/cookbooks/usf_mw_jira/Berksfile, loading Berkshelf
D      Berkshelf 6.3.1 library loaded
-----> Cleaning up any prior instances of <default-redhat-68>
-----> Destroying <default-redhat-68>...
       Finished destroying <default-redhat-68> (0m0.00s).
-----> Testing <default-redhat-68>
-----> Creating <default-redhat-68>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [undefined method `[]=' for nil:NilClass] on default-redhat-68
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [undefined method `[]=' for nil:NilClass] on default-redhat-68
D      ----------------------
D      ------Backtrace-------
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/lib/kitchen/command.rb:183:in `report_errors'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/lib/kitchen/command.rb:174:in `run_action'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/lib/kitchen/command/test.rb:42:in `block in call'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/lib/kitchen/command/test.rb:38:in `call'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/lib/kitchen/cli.rb:53:in `perform'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/lib/kitchen/cli.rb:234:in `test'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/lib/kitchen/cli.rb:334:in `invoke_task'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/bin/kitchen:13:in `block in <top (required)>'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/lib/kitchen/errors.rb:171:in `with_friendly_errors'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/bin/kitchen:13:in `<top (required)>'
D      /Users/user_name/.rbenv/versions/2.3.2/bin/kitchen:22:in `load'
D      /Users/user_name/.rbenv/versions/2.3.2/bin/kitchen:22:in `<main>'
D      ----End Backtrace-----
D      -Composite Exception--
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #create action: [undefined method `[]=' for nil:NilClass] on default-redhat-68
D      ----------------------
D      ------Backtrace-------
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/kitchen-vsphere-0.2.0/lib/kitchen/driver/vsphere.rb:76:in `compute'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/kitchen-vsphere-0.2.0/lib/kitchen/driver/vsphere.rb:95:in `create_server'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/kitchen-vsphere-0.2.0/lib/kitchen/driver/vsphere.rb:54:in `create'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:460:in `public_send'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:460:in `block in perform_action'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:489:in `block in action'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:488:in `action'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:460:in `perform_action'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:370:in `create_action'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:359:in `block in transition_to'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:358:in `each'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:358:in `transition_to'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:157:in `verify'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:186:in `block in test'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:182:in `test'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/lib/kitchen/command.rb:197:in `public_send'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      ----End Backtrace-----
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #create action: [undefined method `[]=' for nil:NilClass]
D      ----------------------
D      ------Backtrace-------
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/kitchen-vsphere-0.2.0/lib/kitchen/driver/vsphere.rb:76:in `compute'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/kitchen-vsphere-0.2.0/lib/kitchen/driver/vsphere.rb:95:in `create_server'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/kitchen-vsphere-0.2.0/lib/kitchen/driver/vsphere.rb:54:in `create'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:460:in `public_send'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:460:in `block in perform_action'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:489:in `block in action'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:488:in `action'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:460:in `perform_action'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:370:in `create_action'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:359:in `block in transition_to'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:358:in `each'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:358:in `transition_to'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:157:in `verify'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:186:in `block in test'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:182:in `test'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/lib/kitchen/command.rb:197:in `public_send'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
D      /Users/user_name/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/test-kitchen-1.18.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      ----End Backtrace-----
```

## Kitchen Diagnose

```
$ kitchen diagnose --all
---
timestamp: 2017-10-04 23:16:18 UTC
kitchen_version: 1.18.0
plugins:
  driver:
    Vsphere:
      class: Kitchen::Driver::Vsphere
      version:
      api_version:
  provisioner:
    ChefZero:
      class: Kitchen::Provisioner::ChefZero
      version: 1.18.0
      api_version: 2
  transport:
    Ssh:
      class: Kitchen::Transport::Ssh
      version: 1.18.0
      api_version: 1
  verifier:
    Inspec:
      class: Kitchen::Verifier::Inspec
      version: 0.19.0
      api_version: 1
loader:
  process_erb: true
  process_local: true
  process_global: true
  global_config:
  project_config:
    filename: "/Users/user_name/on_prem/chef-repo/cookbooks/cookbook_name/.kitchen.yml"
    raw_data:
      driver:
        name: vsphere
        driver_options:
          host: hostname.company.com
          insecure: true
          password: ********
          user: domain\user_name
        machine_options:
          bootstrap_options:
            customization_spec:
              domain: main.company.com
              ipsettings:
                dnsServerList:
                - 10.10.12.111
                - 10.10.13.111
            datacenter: data_center_name
            memory_mb: 4096
            network_name:
            - 1p-vsmqa1/lin_v123
            num_cpus: 2
            resource_pool: pool_name
            ssh:
              paranoid: false
              password: ********
              port: 22
              user: root
            template_folder: Linux/chef_templates
            template_name: kitchen-image
            use_linked_clone: true
            vm_folder: Linux/chef
          create_timeout: 600
          ready_timeout: 90
          start_timeout: 600
      platforms:
      - name: redhat-6.8
      provisioner:
        chef_omnibus_url: http://host2_name.company.com:8000/binaries/chef/install.sh
        client_rb:
          environment: jira_dev
        data_bags_path: "../../data_bags"
        environments_path: "../../environments"
        name: chef_zero
        nodes_path: "../../nodes"
        roles_path: "../../roles"
      suites:
      - name: default
        run_list:
        - recipe[cookbook_name::default]
        verifier:
          inspec_tests:
          - test/smoke/default
      verifier:
        name: inspec
  local_config:
  combined_config:
    filename:
    raw_data:
      driver:
        name: vsphere
        driver_options:
          host: hostname.company.com
          insecure: true
          password: ******
          user: domain\user_name
        machine_options:
          bootstrap_options:
            customization_spec:
              domain: main.company.com
              ipsettings:
                dnsServerList:
                - 10.10.12.111
                - 10.10.13.111
            datacenter: data_center_name
            memory_mb: 4096
            network_name:
            - network_name
            num_cpus: 2
            resource_pool: pool_name
            ssh:
              paranoid: false
              password: *******
              port: 22
              user: root
            template_folder: Linux/chef_templates
            template_name: kitchen-image
            use_linked_clone: true
            vm_folder: Linux/chef
          create_timeout: 600
          ready_timeout: 90
          start_timeout: 600
      platforms:
      - name: redhat-6.8
      provisioner:
        chef_omnibus_url: http://host2_name.company.com:8000/binaries/chef/install.sh
        client_rb:
          environment: jira_dev
        data_bags_path: "../../data_bags"
        environments_path: "../../environments"
        name: chef_zero
        nodes_path: "../../nodes"
        roles_path: "../../roles"
      suites:
      - name: default
        run_list:
        - recipe[cookbook_name::default]
        verifier:
          inspec_tests:
          - test/smoke/default
      verifier:
        name: inspec
instances:
  default-redhat-68:
    platform:
      os_type: unix
      shell_type: bourne
    state_file:
      last_error: NoMethodError
    driver:
      driver_options:
        host: hostname.company.com
        insecure: true
        password: ******
        user: domain\user_name
      kitchen_root: "/Users/user_name/on_prem/chef-repo/cookbooks/cookbook_name"
      log_level: :info
      machine_options:
        bootstrap_options:
          customization_spec:
            domain: main.company.com
            ipsettings:
              dnsServerList:
              - 10.34.115.200
              - 10.34.108.148
          datacenter: data_center_name
          memory_mb: 4096
          network_name:
          - network_name
          num_cpus: 2
          resource_pool: pool_name
          ssh:
            paranoid: false
            password: *******
            port: 22
            user: root
          template_folder: Linux/chef_templates
          template_name: kitchen-image
          use_linked_clone: true
          vm_folder: Linux/chef
        create_timeout: 600
        ready_timeout: 90
        start_timeout: 600
      max_ssh_sessions: 9
      name: vsphere
      port: '22'
      public_key_path: "/Users/user_name/.ssh/id_rsa.pub"
      sudo: true
      test_base_path: "/Users/user_name/on_prem/chef-repo/cookbooks/cookbook_name/test/integration"
      upload_public_ssh_key: true
      use_ipv6: false
      username: root
    provisioner:
      always_update_cookbooks: false
      architecture:
      attributes: {}
      channel: :stable
      checksum:
      chef_client_path: "/bin/chef-client"
      chef_omnibus_install_options:
      chef_omnibus_url: http://host2_name.company.com:8000/binaries/chef/install.sh
      chef_zero_host:
      chef_zero_port: 8889
      client_rb:
        environment: jira_dev
      clients_path:
      command_prefix:
      config_path:
      cookbook_files_glob: README.*,metadata.{json,rb},attributes/**/*,definitions/**/*,files/**/*,libraries/**/*,providers/**/*,recipes/**/*,resources/**/*,templates/**/*
      data_bags_path: "/Users/user_name/on_prem/chef-repo/data_bags"
      data_path:
      deprecations_as_errors: false
      download_url:
      encrypted_data_bag_secret_key_path:
      enforce_idempotency: false
      environments_path: "/Users/user_name/on_prem/chef-repo/environments"
      ftp_proxy:
      http_proxy:
      https_proxy:
      install_strategy: once
      json_attributes: true
      kitchen_root: "/Users/user_name/on_prem/chef-repo/cookbooks/cookbook_name"
      log_file:
      log_level: auto
      max_retries: 1
      multiple_converge: 1
      name: chef_zero
      named_run_list: {}
      nodes_path: "/Users/user_name/on_prem/chef-repo/nodes"
      platform:
      platform_version:
      policyfile:
      policyfile_path:
      product_name:
      product_version: :latest
      profile_ruby: false
      require_chef_omnibus: true
      retry_on_exit_code: []
      roles_path: "/Users/user_name/on_prem/chef-repo/roles"
      root_path: "/tmp/kitchen"
      ruby_bindir: "/embedded/bin"
      run_list:
      - recipe[cookbook_name::default]
      sudo: true
      sudo_command: sudo -E
      test_base_path: "/Users/user_name/on_prem/chef-repo/cookbooks/cookbook_name/test/integration"
      wait_for_retry: 30
    transport:
      compression: false
      compression_level: 0
      connection_retries: 5
      connection_retry_sleep: 1
      connection_timeout: 15
      keepalive: true
      keepalive_interval: 60
      kitchen_root: "/Users/user_name/on_prem/chef-repo/cookbooks/cookbook_name"
      log_level: :info
      max_ssh_sessions: 9
      max_wait_until_ready: 600
      name: ssh
      port: 22
      ssh_gateway:
      ssh_gateway_username:
      ssh_key:
      test_base_path: "/Users/user_name/on_prem/chef-repo/cookbooks/cookbook_name/test/integration"
      username: root
    verifier:
      chef_omnibus_root: "/opt/chef"
      command_prefix:
      ftp_proxy:
      http_proxy:
      https_proxy:
      inspec_tests:
      - test/smoke/default
      kitchen_root: "/Users/user_name/on_prem/chef-repo/cookbooks/cookbook_name"
      log_level: :info
      name: inspec
      root_path: "/tmp/verifier"
      sudo: true
      sudo_command: sudo -E
      suite_name: default
      test_base_path: "/Users/user_name/on_prem/chef-repo/cookbooks/cookbook_name/test/integration"
```

## NOTE:

This repository is for core issues with the Test-Kitchen framework, so if the issue is with a plugin you may be referred to file the issue with the appropriate plugin.

**Comment by cheeseplus** [comment]
This is likely a missing configuration item for the vsphere driver. Also it seems like you've got rbenv in the mix so you're either not using the ChefDK ruby/gems or mixing the two - either way you won't have a good time.

I don't see this being an issue with core kitchen but perhaps a better error message from the underlying kitchen-vsphere driver. I'd open an issue there if you're still stuck.

**Comment by cheeseplus** [comment]
Closing due to lack of response.
