### ISSUE TITLE
Errors when passing encrypted_data_bag_secret_key_path

### ISSUE THREAD

**Issue by bashls** [test-kitchen/test-kitchen#1297]
## Description

When my kitchen file specifies 'encrypted_data_bag_secret_key_path' I am returned a connection error.  I think the connection error is misleading though, as soon as I remove encrypted_data_bag_secret_key_path from my kitchen yml file, converge runs fine.

## Kitchen Version

```ruby
kitchen version: 1.17.0
```

## ChefDK Version

If you are running test-kitchen via ChefDK, `chef --version` will provide additional relevent version details.

```ruby
Chef Development Kit Version: 2.3.4
chef-client version: 13.4.19
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.17.0
inspec version: 1.36.1
```

## Ruby Version

If you are not using test-kitchen via ChefDK, please provide the output of ruby --version.

```ruby
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin14]
```

## Platform Version

CentOS 7.3

## Replication Case

I can reproduce by uncommenting the following line in my kitchen yml:

  encrypted_data_bag_secret_key_path: /Users/chefuser/chef-repo/

I've tried passing the full path to the key as well:

  encrypted_data_bag_secret_key_path: /Users/chefuser/chef-repo/encrypted_data_bag_secret

And tried both with filenames encrypted_data_bag_secret and encrypted_data_bag_secret_key

## Kitchen Output

The relevant output of the test-kitchen run or a link to a gist of the entire run, if there is one.

The debug output (kitchen -l debug) may be useful, but please link to a gist, or truncate it.

Please do not paste the full run out put here.  If the full output would be useful, link to it in a gist.

```ruby
...
I, [2017-10-10T14:31:07.707947 #64642]  INFO -- default-centos-73: Preparing client.rb
I, [2017-10-10T14:31:08.129005 #64642]  INFO -- default-centos-73: -----> Chef Omnibus installation detected (install only if missing)
I, [2017-10-10T14:31:08.155862 #64642]  INFO -- default-centos-73: Transferring files to <default-centos-73>
E, [2017-10-10T14:31:08.363842 #64642] ERROR -- default-centos-73: Converge failed on instance <default-centos-73>.
E, [2017-10-10T14:31:08.363943 #64642] ERROR -- default-centos-73: ------Exception-------
E, [2017-10-10T14:31:08.363962 #64642] ERROR -- default-centos-73: Class: Kitchen::ActionFailed
E, [2017-10-10T14:31:08.363974 #64642] ERROR -- default-centos-73: Message: SCP upload failed (open failed (1))
E, [2017-10-10T14:31:08.363985 #64642] ERROR -- default-centos-73: ----------------------
E, [2017-10-10T14:31:08.363996 #64642] ERROR -- default-centos-73: ------Backtrace-------
E, [2017-10-10T14:31:08.364006 #64642] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/li
b/kitchen/provisioner/base.rb:83:in `rescue in call'
E, [2017-10-10T14:31:08.364016 #64642] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/li
b/kitchen/provisioner/base.rb:86:in `call'
E, [2017-10-10T14:31:08.364027 #64642] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/li
b/kitchen/instance.rb:384:in `block in converge_action'
E, [2017-10-10T14:31:08.364037 #64642] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/li
b/kitchen/instance.rb:527:in `synchronize_or_call'
E, [2017-10-10T14:31:08.364047 #64642] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/li
b/kitchen/instance.rb:489:in `block in action'
E, [2017-10-10T14:31:08.364058 #64642] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
E, [2017-10-10T14:31:08.364068 #64642] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/li
b/kitchen/instance.rb:488:in `action'
E, [2017-10-10T14:31:08.364078 #64642] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/li
b/kitchen/instance.rb:380:in `converge_action'
E, [2017-10-10T14:31:08.364088 #64642] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/li
b/kitchen/instance.rb:359:in `block in transition_to'
E, [2017-10-10T14:31:08.364098 #64642] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/li
b/kitchen/instance.rb:358:in `each'
E, [2017-10-10T14:31:08.364108 #64642] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/li
b/kitchen/instance.rb:358:in `transition_to'
E, [2017-10-10T14:31:08.364137 #64642] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/li
b/kitchen/instance.rb:135:in `converge'
E, [2017-10-10T14:31:08.364156 #64642] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/li
b/kitchen/command.rb:197:in `public_send'
E, [2017-10-10T14:31:08.364170 #64642] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/li
b/kitchen/command.rb:197:in `run_action_in_thread'
E, [2017-10-10T14:31:08.364181 #64642] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/li
b/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2017-10-10T14:31:08.364191 #64642] ERROR -- default-centos-73: ----End Backtrace-----
E, [2017-10-10T14:31:08.364201 #64642] ERROR -- default-centos-73: ---Nested Exception---
E, [2017-10-10T14:31:08.364210 #64642] ERROR -- default-centos-73: Class: Kitchen::Transport::SshFailed
E, [2017-10-10T14:31:08.364219 #64642] ERROR -- default-centos-73: Message: SCP upload failed (open failed (1))
E, [2017-10-10T14:31:08.364229 #64642] ERROR -- default-centos-73: ----------------------
E, [2017-10-10T14:31:08.364238 #64642] ERROR -- default-centos-73: ------Backtrace-------
E, [2017-10-10T14:31:08.364248 #64642] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/provisioner/base.rb:83:in `rescue in call'
E, [2017-10-10T14:31:08.364257 #64642] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/provisioner/base.rb:86:in `call'
E, [2017-10-10T14:31:08.364267 #64642] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:384:in `block in converge_action'
E, [2017-10-10T14:31:08.364277 #64642] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
E, [2017-10-10T14:31:08.364286 #64642] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:489:in `block in action'
E, [2017-10-10T14:31:08.364296 #64642] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
E, [2017-10-10T14:31:08.364306 #64642] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:488:in `action'
E, [2017-10-10T14:31:08.364315 #64642] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:380:in `converge_action'
E, [2017-10-10T14:31:08.364325 #64642] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:359:in `block in transition_to'
E, [2017-10-10T14:31:08.364334 #64642] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:358:in `each'
E, [2017-10-10T14:31:08.364344 #64642] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:358:in `transition_to'
E, [2017-10-10T14:31:08.364356 #64642] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:135:in `converge'
E, [2017-10-10T14:31:08.364367 #64642] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/command.rb:197:in `public_send'
E, [2017-10-10T14:31:08.364377 #64642] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2017-10-10T14:31:08.364387 #64642] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2017-10-10T14:31:08.364396 #64642] ERROR -- default-centos-73: ----End Backtrace-----
```

## Kitchen Diagnose

```
$ kitchen diagnose --all
-----> Using policyfile mode for chef-client
---
timestamp: 2017-10-10 18:36:25 UTC
kitchen_version: 1.17.0
plugins:
  driver:
    Vagrant:
      class: Kitchen::Driver::Vagrant
      version: 1.2.1
      api_version: 2
  provisioner:
    PolicyfileZero:
      class: Kitchen::Provisioner::PolicyfileZero
      version:
      api_version:
  transport:
    Ssh:
      class: Kitchen::Transport::Ssh
      version: 1.17.0
      api_version: 1
  verifier:
    Inspec:
      class: Kitchen::Verifier::Inspec
      version: 0.19.0
      api_version: 1
loader:
  process_erb: true
  process_local: true
  process_global: true
  global_config:
  project_config:
    filename: "/Users/chefuser/chef-repo/cookbooks/data_bag_test/.kitchen.yml"
    raw_data:
      driver:
        name: docker
        driver_config:
          require_chef_omnibus: true
        use_sudo: false
        run_command: "/sbin/init"
        privileged: true
      provisioner:
        name: policyfile_zero
      verifier:
        name: inspec
      platforms:
      - name: centos-7.3
      suites:
      - name: default
        verifier:
          inspec_tests:
          - test/smoke/default
        attributes:
  local_config:
    filename: "/Users/chefuser/chef-repo/cookbooks/data_bag_test/.kitchen.local.yml"
    raw_data:
      driver:
        name: vagrant
      provisioner:
        name: policyfile_zero
        data_bags_path: "/Users/chefuser/chef-repo/data_bags"
        encrypted_data_bag_secret_key_path: "/Users/chefuser/chef-repo/"
      verifier:
        name: inspec
      platforms:
      - name: centos-7.3
      suites:
      - name: default
        verifier:
          inspec_tests:
          - test/smoke/default
        attributes:
  combined_config:
    filename:
    raw_data:
      driver:
        name: vagrant
        driver_config:
          require_chef_omnibus: true
        use_sudo: false
        run_command: "/sbin/init"
        privileged: true
      provisioner:
        name: policyfile_zero
        data_bags_path: "/Users/chefuser/chef-repo/data_bags"
        encrypted_data_bag_secret_key_path: "/Users/chefuser/chef-repo/"
      verifier:
        name: inspec
      platforms:
      - name: centos-7.3
      suites:
      - name: default
        verifier:
          inspec_tests:
          - test/smoke/default
        attributes:
instances:
  default-centos-73:
    platform:
      os_type: unix
      shell_type: bourne
    state_file:
      hostname: 127.0.0.1
      last_action: converge
      last_error: Kitchen::ActionFailed
      port: '2222'
      ssh_key: "/Users/chefuser/chef-repo/cookbooks/data_bag_test/.kitchen/kitchen-vagrant/default-centos-73/.vagrant/machines/default/virtualbox/private_key"
      username: vagrant
    driver:
      boot_timeout:
      box: bento/centos-7.3
      box_check_update:
      box_download_ca_cert:
      box_download_insecure:
      box_url:
      box_version:
      cache_directory: "/tmp/omnibus/cache"
      cachier:
      customize: {}
      driver_config:
        require_chef_omnibus: true
      gui:
      kitchen_cache_directory: "/Users/chefuser/.kitchen/cache"
      kitchen_root: "/Users/chefuser/chef-repo/cookbooks/data_bag_test"
      linked_clone:
      log_level: :info
      name: vagrant
      network: []
      pre_create_command:
      privileged: true
      provider: virtualbox
      provision: false
      run_command: "/sbin/init"
      ssh: {}
      synced_folders:
      - - "/Users/chefuser/.kitchen/cache"
        - "/tmp/omnibus/cache"
        - 'create: true'
      test_base_path: "/Users/chefuser/chef-repo/cookbooks/data_bag_test/test/integration"
      use_sudo: false
      vagrant_binary: vagrant
      vagrantfile_erb: "/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/kitchen-vagrant-1.2.1/templates/Vagrantfile.erb"
      vagrantfiles: []
      vm_hostname: default-centos-73.vagrantup.com
    provisioner:
      always_update_cookbooks: false
      attributes: {}
      chef_client_path: "/bin/chef-client"
      chef_omnibus_install_options:
      chef_omnibus_url: https://omnitruck.chef.io/install.sh
      chef_zero_host:
      chef_zero_port: 8889
      client_rb: {}
      clients_path:
      command_prefix:
      config_path:
      cookbook_files_glob: README.*,metadata.{json,rb},attributes/**/*,definitions/**/*,files/**/*,libraries/**/*,providers/**/*,recipes/**/*,resources/**/*,templates/**/*
      data_bags_path: "/Users/chefuser/chef-repo/data_bags"
      data_path:
      deprecations_as_errors: false
      encrypted_data_bag_secret_key_path: "/Users/chefuser/chef-repo"
      enforce_idempotency: false
      environments_path:
      ftp_proxy:
      http_proxy:
      https_proxy:
      json_attributes: true
      kitchen_root: "/Users/chefuser/chef-repo/cookbooks/data_bag_test"
      log_file:
      log_level: auto
      max_retries: 1
      multiple_converge: 1
      name: policyfile_zero
      named_run_list:
      nodes_path:
      policyfile: Policyfile.rb
      policyfile_path:
      profile_ruby: false
      require_chef_omnibus: true
      retry_on_exit_code: []
      roles_path:
      root_path: "/tmp/kitchen"
      ruby_bindir: "/embedded/bin"
      run_list: []
      sudo: true
      sudo_command: sudo -E
      test_base_path: "/Users/chefuser/chef-repo/cookbooks/data_bag_test/test/integration"
      wait_for_retry: 30
    transport:
      compression: false
      compression_level: 0
      connection_retries: 5
      connection_retry_sleep: 1
      connection_timeout: 15
      keepalive: true
      keepalive_interval: 60
      kitchen_root: "/Users/chefuser/chef-repo/cookbooks/data_bag_test"
      log_level: :info
      max_ssh_sessions: 9
      max_wait_until_ready: 600
      name: ssh
      port: 22
      ssh_gateway:
      ssh_gateway_username:
      ssh_key:
      test_base_path: "/Users/chefuser/chef-repo/cookbooks/data_bag_test/test/integration"
      username: root
    verifier:
      chef_omnibus_root: "/opt/chef"
      command_prefix:
      ftp_proxy:
      http_proxy:
      https_proxy:
      inspec_tests:
      - test/smoke/default
      kitchen_root: "/Users/chefuser/chef-repo/cookbooks/data_bag_test"
      log_level: :info
      name: inspec
      root_path: "/tmp/verifier"
      sudo: true
      sudo_command: sudo -E
      suite_name: default
      test_base_path: "/Users/chefuser/chef-repo/cookbooks/data_bag_test/test/integration"
```

**Comment by bashls** [comment]
Following the steps outlined in another issue (https://github.com/test-kitchen/test-kitchen/issues/248) and not specifying encrypted_data_bag_secret_key_path but simply having encrypted_data_bag_secret_key in the same directory I am running kitchen from yields the same failure.  It seems anytime kitchen has to prepare secret, it consequently hits this error for me.  If I rename the file and converge again, it passes with no issues.

**Comment by bashls** [comment]
Just as a follow up, I'm seeing the same behaviour when I use docker driver instead of vagrant as well as I've reproduced the problem using test-kitchen 1.18.0.  Something is failing from the upload method in `lib/kitchen/transport/ssh.rb`

**Comment by bashls** [comment]
I don't want to jump the gun, but I found an upgrade to net-ssh gem and after upgrading the issue is no longer reproducible.  Please go ahead and close.  Happy to remove the updated gem and gather more logs or data if there's interest as it's somehow consistently failing only when I have `encrypted_data_bag_secret_key_path` set.

The net-ssh gem upgrade for me was 4.1.0 to 4.2.0.

**Comment by cheeseplus** [comment]
Updating test-kitchen or net-ssh out of band in the ChefDK install most definitely won't work how you expect it to. The ChefDK appbundles and creates it's own binstubs this technique of updating gems that are already included adhoc in ChefDK 2.x+ will not work.

Additionally, at least by the gist above you were only providing a folder when `encrypted_data_bag_secret_key_path` expects the full path to the secret file. This is understandably confusing given most of the other `*_path` keys take directories.

**Comment by bashls** [comment]
Thanks for the feedback.  I get the same results when passing a key file instead of just the path.  I can confirm upgrading net-ssh resolves it, the issue has not recurred the entire day.  I uninstalled the updated net-ssh and the issue recurred on the next converge attempt.
