### ISSUE TITLE
upload of sandbox directory fails with symlink in repo

### ISSUE THREAD

**Issue by atheiman** [test-kitchen/test-kitchen#1319]
## Description

If there is a symlink in a cookbook repo that points to another directory within the repo, the upload of the sandbox directory fails at the beginning of a converge. There might be some issue with net-scp trying to recursively upload a directory that contains a symlink to another directory (which seems like something it would be able to handle)?

## Kitchen Version

1.19.1

## Ruby Version

2.4.1

## Platform Version

Mac OS 10.12.6

## Replication Case

Create a cookbook repo with a symlink in it - for me this was symlnking a fixture data bag to be shared between test-kitchen and chefspec tests:

```
test-cookbook $ tree test/fixtures/
test/fixtures/
└── data_bags
    └── some_bag
        └── some_item.json
test-cookbook $ ls -l spec/support/
total 8
lrwxr-xr-x  1 austinheiman  staff  29 Nov 20 20:17 data_bags -> ../../test/fixtures/data_bags
```

## Kitchen Output

A full debug failure can be shown in [a travis build](https://travis-ci.org/atheiman/test-cookbook/jobs/305064879) for [this pr](https://github.com/atheiman/test-cookbook/pull/5). There is also a commit that shows a regular file works fine. Here is a shortened output:

```ruby
test-cookbook $ bundle exec kitchen converge default-ubuntu-14
-----> Starting Kitchen (v1.19.1)
-----> Creating <default-ubuntu-1404>...
       ...
       Finished creating <default-ubuntu-1404> (0m33.96s).
-----> Converging <default-ubuntu-1404>...
       ...
-----> Installing Chef Omnibus (install only if missing)
       ...
       Thank you for installing Chef!
       Transferring files to <default-ubuntu-1404>
bundler: failed to load command: kitchen (/Users/austinheiman/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bin/kitchen)
Net::SCP::Error: SCP did not finish successfully ():
  /Users/austinheiman/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/net-scp-1.2.1/lib/net/scp.rb:365:in `block (3 levels) in start_command'
  /Users/austinheiman/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/channel.rb:607:in `do_close'
  /Users/austinheiman/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:573:in `channel_closed'
  /Users/austinheiman/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:684:in `channel_close'
  /Users/austinheiman/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:549:in `dispatch_incoming_packets'
  /Users/austinheiman/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:246:in `ev_preprocess'
  /Users/austinheiman/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/event_loop.rb:99:in `each'
  /Users/austinheiman/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/event_loop.rb:99:in `ev_preprocess'
  /Users/austinheiman/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/event_loop.rb:27:in `process'
  /Users/austinheiman/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:225:in `process'
  /Users/austinheiman/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:178:in `block in loop'
  /Users/austinheiman/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:178:in `loop'
  /Users/austinheiman/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:178:in `loop'
  /Users/austinheiman/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:124:in `close'
  /Users/austinheiman/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.1/lib/kitchen/transport/ssh.rb:121:in `close'
  /Users/austinheiman/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.1/lib/kitchen/transport/ssh.rb:98:in `cleanup!'
  /Users/austinheiman/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.1/lib/kitchen/instance.rb:294:in `cleanup!'
  /Users/austinheiman/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.1/lib/kitchen/command.rb:205:in `run_action_in_thread'
  /Users/austinheiman/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.1/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
```

It looks like others have run into this before but I could not find an issue on this repo for it https://github.com/neillturner/kitchen-ansible/issues/173#issuecomment-223328243

**Comment by coderanger** [comment]
I'm not sure there is a lot we can do about this since we just pass the top-level folders in to the SCP code :-/ Will probably have to be fixed at that level.

**Comment by atheiman** [comment]
Yea i kinda realized this halfway through typing this issue up.

Ill try to log an issue to net-scp and poke around with this.

**Comment by cheeseplus** [comment]
Closing this one as it's mostly an upstream issue and if anyone searches they'll still happen upon this one.
