### ISSUE TITLE
Test-kitchen converge fails with closed stream (IOError)

### ISSUE THREAD

**Issue by bladerunner512** [test-kitchen/test-kitchen#1320]
## Description

Test-kitchen converge fails with closed stream (IOError)

## Kitchen Version

1.17.0

# Copy-paste your results here
```
$ kitchen converge
-----> Starting Kitchen (v1.17.0)
-----> Creating <ol6-8-x86-64-prod-1-3>...
       Bringing machine 'default' up with 'virtualbox' provider...
       ==> default: Clearing any previously set forwarded ports...
       ==> default: Clearing any previously set network interfaces...
       ==> default: Preparing network interfaces based on configuration...
           default: Adapter 1: nat
       ==> default: Forwarding ports...
           default: 22 (guest) => 2222 (host) (adapter 1)
       ==> default: Booting VM...
       ==> default: Waiting for machine to boot. This may take a few minutes...
           default: SSH address: 127.0.0.1:2222
           default: SSH username: vagrant
           default: SSH auth method: private key
           default: 
           default: Vagrant insecure key detected. Vagrant will automatically replace
           default: this with a newly generated keypair for better security.
           default: 
           default: Inserting generated public key within guest...
           default: Removing insecure key from the guest if it's present...
           default: Key inserted! Disconnecting and reconnecting using new SSH key...
       ==> default: Machine booted and ready!
       ==> default: Checking for guest additions in VM...
       ==> default: Setting hostname...
       ==> default: Machine not provisioned because `--no-provision` is specified.
       [SSH] Established
       Vagrant instance <ol6-8-x86-64-prod-1-3> created.
       Finished creating <ol6-8-x86-64-prod-1-3> (0m54.36s).
-----> Converging <ol6-8-x86-64-prod-1-3>...
       Preparing files for transfer
       Preparing dna.json
       Preparing cookbooks from project directory
       Removing non-cookbook files before transfer
       Preparing data_bags
       Preparing environments
       Preparing roles
       Preparing validation.pem
       Preparing client.rb
-----> Chef Omnibus installation detected (install only if missing)
       Transferring files to <ol6-8-x86-64-prod-1-3>
       Starting Chef Client, version 12.14.89
       Creating a new client identity for ol6-8-x86-64-prod-1-3 using the validator key.
       resolving cookbooks for run list: ["validate_env::default", "validate_compute_node::default"]
       Synchronizing Cookbooks:
         - validate_compute_node (0.1.2)
         - validate_env (0.1.2)
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.1.0/lib/net/ssh/ruby_compat.rb:20:in `select': closed stream (IOError)
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.1.0/lib/net/ssh/ruby_compat.rb:20:in `io_select'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.1.0/lib/net/ssh/transport/packet_stream.rb:75:in `available_for_read?'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.1.0/lib/net/ssh/transport/packet_stream.rb:90:in `next_packet'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.1.0/lib/net/ssh/transport/session.rb:193:in `block in poll_message'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.1.0/lib/net/ssh/transport/session.rb:188:in `loop'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.1.0/lib/net/ssh/transport/session.rb:188:in `poll_message'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:535:in `dispatch_incoming_packets'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:237:in `ev_preprocess'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/event_loop.rb:99:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/event_loop.rb:99:in `ev_preprocess'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/event_loop.rb:27:in `process'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:216:in `process'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:178:in `block in loop'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:178:in `loop'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:178:in `loop'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:124:in `close'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/transport/ssh.rb:121:in `close'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/transport/ssh.rb:98:in `cleanup!'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:285:in `cleanup!'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/command.rb:205:in `run_action_in_thread'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
```

## ChefDK Version

$ chef -v
Chef Development Kit Version: 2.3.4
chef-client version: 13.4.19
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.17.0
inspec version: 1.36.1

$ vboxmanage --version
5.0.40_Ubuntur115130

$ vagrant -v
Vagrant 1.8.1

## Platform Version

Ubuntu 16.04 64bit

## Replication Case

Install ChefDK
Install VirtualBox 
Install Vagrant
execute 'kitchen converge'

## Kitchen Diagnose
```
$ kitchen diagnose --all
---
timestamp: 2017-11-21 22:24:59 UTC
kitchen_version: 1.17.0
plugins:
  driver:
    Vagrant:
      class: Kitchen::Driver::Vagrant
      version: 1.2.1
      api_version: 2
  provisioner:
    ChefZero:
      class: Kitchen::Provisioner::ChefZero
      version: 1.17.0
      api_version: 2
  transport:
    Ssh:
      class: Kitchen::Transport::Ssh
      version: 1.17.0
      api_version: 1
  verifier:
    Inspec:
      class: Kitchen::Verifier::Inspec
      version: 0.19.0
      api_version: 1
loader:
  process_erb: true
  process_local: true
  process_global: true
  global_config: 
  project_config:
    filename: "/home/user101/git/chef/chef-repo/.kitchen.yml"
    raw_data:
      driver:
        name: vagrant
      provisioner:
        name: chef_zero
        data_bags_path: data_bags
        roles_path: roles
        environments_path: environments
        client_rb:
          environment: vagrant_kitchen_env
        cookbooks_path:
        - cookbooks
      verifier:
        name: inspec
      platforms:
      - name: ol6-8-x86-64-prod-1-3
        driver:
          box: prod_vm/ol6-8-x86-64-prod-1-3
      suites:
      - name: prod_deploy
        run_list:
        - recipe[validate_env::default]
        - recipe[validate_compute_node::default]
        verifier:
          inspec_tests:
          - test/recipes
        attributes: 
  local_config: 
  combined_config:
    filename: 
    raw_data:
      driver:
        name: vagrant
      provisioner:
        name: chef_zero
        data_bags_path: data_bags
        roles_path: roles
        environments_path: environments
        client_rb:
          environment: vagrant_kitchen_env
        cookbooks_path:
        - cookbooks
      verifier:
        name: inspec
      platforms:
      - name: ol6-8-x86-64-prod-1-3
        driver:
          box: prod_vm/ol6-8-x86-64-prod-1-3
      suites:
      - name: prod_deploy
        run_list:
        - recipe[validate_env::default]
        - recipe[validate_compute_node::default]
        verifier:
          inspec_tests:
          - test/recipes
        attributes: 
instances:
  ol6-8-x86-64-prod-1-3:
    platform:
      os_type: unix
      shell_type: bourne
    state_file:
      last_error: Kitchen::ShellOut::ShellCommandFailed
    driver:
      boot_timeout: 
      box: prod_vm/ol6-8-x86-64-prod-1-3
      box_check_update: 
      box_download_ca_cert: 
      box_download_insecure: 
      box_url: 
      box_version: 
      cache_directory: "/tmp/omnibus/cache"
      cachier: 
      customize: {}
      gui: 
      kitchen_cache_directory: "/home/user101/.kitchen/cache"
      kitchen_root: "/home/user101/git/chef/chef-repo"
      linked_clone: 
      log_level: :info
      name: vagrant
      network: []
      pre_create_command: 
      provider: virtualbox
      provision: false
      ssh: {}
      synced_folders: []
      test_base_path: "/home/user101/git/chef/chef-repo/test/integration"
      vagrant_binary: vagrant
      vagrantfile_erb: "/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/kitchen-vagrant-1.2.1/templates/Vagrantfile.erb"
      vagrantfiles: []
      vm_hostname: ol6-8-x86-64-prod-1-3.vagrantup.com
    provisioner:
      always_update_cookbooks: false
      attributes: {}
      chef_client_path: "/bin/chef-client"
      chef_omnibus_install_options: 
      chef_omnibus_url: https://omnitruck.chef.io/install.sh
      chef_zero_host: 
      chef_zero_port: 8889
      client_rb:
        environment: vagrant_kitchen_env
      clients_path: 
      command_prefix: 
      config_path: 
      cookbook_files_glob: README.*,metadata.{json,rb},attributes/**/*,definitions/**/*,files/**/*,libraries/**/*,providers/**/*,recipes/**/*,resources/**/*,templates/**/*
      cookbooks_path:
      - cookbooks
      data_bags_path: "/home/user101/git/chef/chef-repo/data_bags"
      data_path: 
      deprecations_as_errors: false
      encrypted_data_bag_secret_key_path: 
      enforce_idempotency: false
      environments_path: "/home/user101/git/chef/chef-repo/environments"
      ftp_proxy: 
      http_proxy: 
      https_proxy: 
      json_attributes: true
      kitchen_root: "/home/user101/git/chef/chef-repo"
      log_file: 
      log_level: auto
      max_retries: 1
      multiple_converge: 1
      name: chef_zero
      named_run_list: {}
      nodes_path: 
      policyfile: 
      policyfile_path: 
      profile_ruby: false
      require_chef_omnibus: true
      retry_on_exit_code: []
      roles_path: "/home/user101/git/chef/chef-repo/roles"
      root_path: "/tmp/kitchen"
      ruby_bindir: "/embedded/bin"
      run_list:
      - recipe[validate_env::default]
      - recipe[validate_compute_node::default]
      sudo: true
      sudo_command: sudo -E
      test_base_path: "/home/user101/git/chef/chef-repo/test/integration"
      wait_for_retry: 30
    transport:
      compression: false
      compression_level: 0
      connection_retries: 5
      connection_retry_sleep: 1
      connection_timeout: 15
      keepalive: true
      keepalive_interval: 60
      kitchen_root: "/home/user101/git/chef/chef-repo"
      log_level: :info
      max_ssh_sessions: 9
      max_wait_until_ready: 600
      name: ssh
      port: 22
      ssh_gateway: 
      ssh_gateway_username: 
      ssh_key: 
      test_base_path: "/home/user101/git/chef/chef-repo/test/integration"
      username: root
    verifier:
      chef_omnibus_root: "/opt/chef"
      command_prefix: 
      ftp_proxy: 
      http_proxy: 
      https_proxy: 
      inspec_tests:
      - test/recipes
      kitchen_root: "/home/user101/git/chef/chef-repo"
      log_level: :info
      name: inspec
      root_path: "/tmp/verifier"
      sudo: true
      sudo_command: sudo -E
      suite_name: prod_deploy
      test_base_path: "/home/user101/git/chef/chef-repo/test/integration"
```

**Comment by cheeseplus** [comment]
The problem here is:

```
$ vboxmanage --version
5.0.40_Ubuntur115130

$ vagrant -v
Vagrant 1.8.1
```

Those version are so old as to be unusable/unpredictable against current boxes. This isn't an issue with test-kitchen, nor kitchen-vagrant (which is the driver being used) but one of Vagrant and VirtualBox being extremely out of date.

**Comment by bladerunner512** [comment]
Vagrant and VirtualBox both work fine with no issues? Updated and got exact same result with VirtualBox 5.1/5.2 and Vagrant 2.0.1, but error message slightly different:
-----> Chef Omnibus installation detected (install only if missing)
       Transferring files to <ol6-8-x86-64-prod-1-3>
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/keepalive.rb:50:in `send_as_needed': Timeout, server 127.0.0.1 not responding. (Net::SSH::Timeout)
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:278:in `ev_do_postprocess'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/event_loop.rb:111:in `ev_select_and_postprocess'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/event_loop.rb:29:in `process'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:216:in `process'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:178:in `block in loop'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:178:in `loop'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:178:in `loop'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:124:in `close'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/transport/ssh.rb:121:in `close'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/transport/ssh.rb:98:in `cleanup!'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:285:in `cleanup!'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/command.rb:205:in `run_action_in_thread'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'

Also updated gems to test-kitchen 1.19.0 and net-ssh-4.2.0 with same result, so really starting to look like issue with test-kitchen.
