### ISSUE TITLE
Class: Kitchen::Transport::SshFailed on kitchen converge every few runs 

### ISSUE THREAD

**Issue by ebenezar-mccoy** [test-kitchen/test-kitchen#1321]
## Description
I am using test-kitchen with kitchen-ansible and kitchen-docker.
Every few runs i am unable to run kitchen converge, with error that exit run `Class:Kitchen::Transport::SshFailed`.
Re-running kitchen converge again solves problem.

## Kitchen Version

```
Test Kitchen version 1.19.1
```

## Ruby Version

```
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin17]
```

## Platform Version

`OSX 10.13.1`
`Darwin ebenezar.local 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64`

## Kitchen Output

```
D      TIMING: scp async upload (Kitchen::Transport::Ssh)
D      Cleaning up local sandbox in /var/folders/dj/334yscx916xdjrjr796blswh0000gp/T/default-ubuntu-sandbox-20171125-15655-spf7s2
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-ubuntu>.  Please see .kitchen/logs/default-ubuntu.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-ubuntu>.  Please see .kitchen/logs/default-ubuntu.log for more details
D      ----------------------
D      ------Backtrace-------
D      /Users/mariuszmakowski/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/command.rb:183:in `report_errors'
D      /Users/mariuszmakowski/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/command.rb:174:in `run_action'
D      /Users/mariuszmakowski/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/command/action.rb:36:in `block in call'
D      /opt/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
D      /Users/mariuszmakowski/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/command/action.rb:34:in `call'
D      /Users/mariuszmakowski/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/cli.rb:53:in `perform'
D      /Users/mariuszmakowski/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/cli.rb:187:in `block (2 levels) in <class:CLI>'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
D      /Users/mariuszmakowski/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/cli.rb:334:in `invoke_task'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
D      /Users/mariuszmakowski/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.17.0/bin/kitchen:13:in `block in <top (required)>'
D      /Users/mariuszmakowski/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/errors.rb:171:in `with_friendly_errors'
D      /Users/mariuszmakowski/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.17.0/bin/kitchen:13:in `<top (required)>'
D      /opt/chefdk/bin/kitchen:263:in `load'
D      /opt/chefdk/bin/kitchen:263:in `<main>'
D      ----End Backtrace-----
D      -Composite Exception--
D      Class: Kitchen::InstanceFailure
D      Message: Converge failed on instance <default-ubuntu>.  Please see .kitchen/logs/default-ubuntu.log for more details
D      ----------------------
D      ------Backtrace-------
D      /Users/mariuszmakowski/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/provisioner/base.rb:83:in `rescue in call'
D      /Users/mariuszmakowski/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/provisioner/base.rb:86:in `call'
D      /Users/mariuszmakowski/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:384:in `block in converge_action'
D      /Users/mariuszmakowski/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
D      /Users/mariuszmakowski/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:489:in `block in action'
D      /opt/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
D      /Users/mariuszmakowski/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:488:in `action'
D      /Users/mariuszmakowski/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:380:in `converge_action'
D      /Users/mariuszmakowski/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:359:in `block in transition_to'
D      /Users/mariuszmakowski/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:358:in `each'
D      /Users/mariuszmakowski/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:358:in `transition_to'
D      /Users/mariuszmakowski/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:135:in `converge'
D      /Users/mariuszmakowski/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/command.rb:197:in `public_send'
D      /Users/mariuszmakowski/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
D      /Users/mariuszmakowski/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      ----End Backtrace-----
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: SCP upload failed (open failed (1))
D      ----------------------
D      ------Backtrace-------
D      /Users/mariuszmakowski/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/provisioner/base.rb:83:in `rescue in call'
D      /Users/mariuszmakowski/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/provisioner/base.rb:86:in `call'
D      /Users/mariuszmakowski/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:384:in `block in converge_action'
D      /Users/mariuszmakowski/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
D      /Users/mariuszmakowski/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:489:in `block in action'
D      /opt/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
D      /Users/mariuszmakowski/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:488:in `action'
D      /Users/mariuszmakowski/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:380:in `converge_action'
D      /Users/mariuszmakowski/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:359:in `block in transition_to'
D      /Users/mariuszmakowski/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:358:in `each'
D      /Users/mariuszmakowski/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:358:in `transition_to'
D      /Users/mariuszmakowski/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:135:in `converge'
D      /Users/mariuszmakowski/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/command.rb:197:in `public_send'
D      /Users/mariuszmakowski/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
D      /Users/mariuszmakowski/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      ----End Backtrace-----
```

## Kitchen yml

```
---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: ansible_playbook
  require_chef_for_busser: false
  playbook: site.yml
  ansible_diff: true
  hosts: all

platforms:
  - name: ubuntu
    driver_config:
      image: ubuntu:16.04
      privileged: true
      run_command: /sbin/init

suites:
  - name: default

transport:
  username: kitchen
```

**Comment by cheeseplus** [comment]
I'd be curious what version of `net-ssh` you have - also it definitely looks like you're on `kitchen 1.17.0` according to those logs. If you're using ChefDK you can't install a newer version of test-kitchen than what is in there, it'll look like it works but it won't actually do anything.

**Comment by cheeseplus** [comment]
Given no response to versions and that the version reported is aging rapidly - closing this one. Typically these are related to intermittent network issues, ssh config on the instance side, or upstream issues in net-ssh/scp. If still encountering on 1.19.2+ please do report anew/re-open and we can try to narrow it down more.
