### ISSUE TITLE
Parsing kitchen.yml in linux seems to fail

### ISSUE THREAD

**Issue by avillalain** [test-kitchen/test-kitchen#1352]
Hi everyone, 

I'm experience an strange situation here, it seems the test-kitchen library is failing to parse the kitchen yml, but the interesting thing is that only fails on linux, I have the same exact file in mac and there it works.

This is the output
```
-----> Starting Kitchen (v1.20.0)
/home/avilla/.rvm/gems/ruby-2.4.1/gems/test-kitchen-1.20.0/lib/kitchen/data_munger.rb:366:in `convert_legacy_driver_format_at!': undefined method `key?' for [:name, "aws"]:Array (NoMethodError)
	from /home/avilla/.rvm/gems/ruby-2.4.1/gems/test-kitchen-1.20.0/lib/kitchen/data_munger.rb:348:in `block in convert_legacy_driver_format!'
	from /home/avilla/.rvm/gems/ruby-2.4.1/gems/test-kitchen-1.20.0/lib/kitchen/data_munger.rb:347:in `each'
	from /home/avilla/.rvm/gems/ruby-2.4.1/gems/test-kitchen-1.20.0/lib/kitchen/data_munger.rb:347:in `convert_legacy_driver_format!'
	from /home/avilla/.rvm/gems/ruby-2.4.1/gems/test-kitchen-1.20.0/lib/kitchen/data_munger.rb:42:in `initialize'
	from /home/avilla/.rvm/gems/ruby-2.4.1/gems/test-kitchen-1.20.0/lib/kitchen/config.rb:152:in `new'
	from /home/avilla/.rvm/gems/ruby-2.4.1/gems/test-kitchen-1.20.0/lib/kitchen/config.rb:152:in `data'
	from /home/avilla/.rvm/gems/ruby-2.4.1/gems/test-kitchen-1.20.0/lib/kitchen/config.rb:131:in `suites'
	from /home/avilla/.rvm/gems/ruby-2.4.1/gems/test-kitchen-1.20.0/lib/kitchen/config.rb:182:in `filter_instances'
	from /home/avilla/.rvm/gems/ruby-2.4.1/gems/test-kitchen-1.20.0/lib/kitchen/config.rb:141:in `build_instances'
	from /home/avilla/.rvm/gems/ruby-2.4.1/gems/test-kitchen-1.20.0/lib/kitchen/config.rb:117:in `instances'
	from /home/avilla/.rvm/gems/ruby-2.4.1/gems/test-kitchen-1.20.0/lib/kitchen/command.rb:112:in `filtered_instances'
	from /home/avilla/.rvm/gems/ruby-2.4.1/gems/test-kitchen-1.20.0/lib/kitchen/command.rb:142:in `parse_subcommand'
	from /home/avilla/.rvm/gems/ruby-2.4.1/gems/test-kitchen-1.20.0/lib/kitchen/command/test.rb:40:in `block in call'
	from /home/avilla/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
	from /home/avilla/.rvm/gems/ruby-2.4.1/gems/test-kitchen-1.20.0/lib/kitchen/command/test.rb:38:in `call'
	from /home/avilla/.rvm/gems/ruby-2.4.1/gems/test-kitchen-1.20.0/lib/kitchen/cli.rb:52:in `perform'
	from /home/avilla/.rvm/gems/ruby-2.4.1/gems/test-kitchen-1.20.0/lib/kitchen/cli.rb:245:in `test'
	from /home/avilla/.rvm/gems/ruby-2.4.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/avilla/.rvm/gems/ruby-2.4.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/avilla/.rvm/gems/ruby-2.4.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /home/avilla/.rvm/gems/ruby-2.4.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/avilla/.rvm/gems/ruby-2.4.1/gems/test-kitchen-1.20.0/bin/kitchen:13:in `block in <top (required)>'
	from /home/avilla/.rvm/gems/ruby-2.4.1/gems/test-kitchen-1.20.0/lib/kitchen/errors.rb:171:in `with_friendly_errors'
	from /home/avilla/.rvm/gems/ruby-2.4.1/gems/test-kitchen-1.20.0/bin/kitchen:13:in `<top (required)>'
	from /home/avilla/.rvm/gems/ruby-2.4.1/bin/kitchen:23:in `load'
	from /home/avilla/.rvm/gems/ruby-2.4.1/bin/kitchen:23:in `<main>'
	from /home/avilla/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /home/avilla/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

And this is the kitchen.yml that I am using

```
driver:
  name: terraform

provisioner:
  name: terraform

platforms:
  name: aws

verifier:
  name: awspec

suites:
  name: default
  verifier:
   patterns:
   - spec/*_spec.rb

```

**Comment by cheeseplus** [comment]
The sections `platforms` and `suites` both expect an array, not a hash. Ff it was a YAML parsing issue it'd look a bit different but this is kitchen barfing on bad data. See the below example for how this should look normally.

```
driver:
  name: vagrant

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: amazonlinux

suites:
- name: default
  run_list:
    - recipe[test::default]
```
