### ISSUE TITLE
Net::SCP::Error

### ISSUE THREAD

**Issue by willis7** [test-kitchen/test-kitchen#1408]
## Description

When running `kitchen converge` I intermittently get the error below. I haven't been able to pinpoint the scenario which causes this behavior.

## Kitchen Version

Tell us which version of test-kitchen you are using (`kitchen --version`).  

```ruby
Test Kitchen version 1.21.1
```

## ChefDK Version

If you are running test-kitchen via ChefDK, `chef --version` will provide additional relevent version details.

```ruby
Chef Development Kit Version: 2.4.17
chef-client version: 13.6.4
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.19.2
inspec version: 1.45.13
```

## Ruby Version

If you are not using test-kitchen via ChefDK, please provide the output of ruby --version.

```ruby
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]
```

## Platform Version

Tell us which Operating System distribution and version test-kitchen is running on.

## Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

``` yaml
---
driver:
  name: vagrant

verifier:
  name: inspec

provisioner:
  name: ansible_playbook
  require_ansible_repo: true
  hosts: test-kitchen
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbose: true
  sudo: true

platforms:
  - name: centos-7.4

suites:
- name: defaul
```

## Kitchen Output

The relevant output of the test-kitchen run or a link to a gist of the entire run, if there is one.

The debug output (kitchen -l debug) may be useful, but please link to a gist, or truncate it.

Please do not paste the full run out put here.  If the full output would be useful, link to it in a gist.

```ruby
       Transferring files to <default-centos-74>
#<Thread:0x00007f92908130d8@/usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.1/lib/kitchen/command.rb:167 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	20: from /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.1/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
	19: from /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.1/lib/kitchen/command.rb:205:in `run_action_in_thread'
	18: from /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.1/lib/kitchen/instance.rb:294:in `cleanup!'
	17: from /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.1/lib/kitchen/transport/ssh.rb:105:in `cleanup!'
	16: from /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.1/lib/kitchen/transport/ssh.rb:128:in `close'
	15: from /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:124:in `close'
	14: from /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:178:in `loop'
	13: from /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:178:in `loop'
	12: from /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:178:in `block in loop'
	11: from /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:225:in `process'
	10: from /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/event_loop.rb:27:in `process'
	 9: from /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/event_loop.rb:99:in `ev_preprocess'
	 8: from /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/event_loop.rb:99:in `each'
	 7: from /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:247:in `ev_preprocess'
	 6: from /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:538:in `each_channel'
	 5: from /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:538:in `each'
	 4: from /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:247:in `block in ev_preprocess'
	 3: from /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/channel.rb:320:in `process'
	 2: from /usr/local/lib/ruby/gems/2.5.0/gems/net-scp-1.2.1/lib/net/scp.rb:369:in `block (3 levels) in start_command'
	 1: from /usr/local/lib/ruby/gems/2.5.0/gems/net-scp-1.2.1/lib/net/scp.rb:400:in `await_response_state'
/usr/local/lib/ruby/gems/2.5.0/gems/net-scp-1.2.1/lib/net/scp/upload.rb:40:in `upload_current_state': not a directory or a regular file: "/var/folders/jj/2t6vwbpn4lzgpjc7n5t_50xm0000gn/T/default-centos-74-sandbox-20180424-9555-1oz51xv/filter_plugins" (Net::SCP::Error)
Traceback (most recent call last):
	20: from /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.1/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
	19: from /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.1/lib/kitchen/command.rb:205:in `run_action_in_thread'
	18: from /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.1/lib/kitchen/instance.rb:294:in `cleanup!'
	17: from /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.1/lib/kitchen/transport/ssh.rb:105:in `cleanup!'
	16: from /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.1/lib/kitchen/transport/ssh.rb:128:in `close'
	15: from /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:124:in `close'
	14: from /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:178:in `loop'
	13: from /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:178:in `loop'
	12: from /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:178:in `block in loop'
	11: from /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:225:in `process'
	10: from /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/event_loop.rb:27:in `process'
	 9: from /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/event_loop.rb:99:in `ev_preprocess'
	 8: from /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/event_loop.rb:99:in `each'
	 7: from /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:247:in `ev_preprocess'
	 6: from /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:538:in `each_channel'
	 5: from /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:538:in `each'
	 4: from /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:247:in `block in ev_preprocess'
	 3: from /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/channel.rb:320:in `process'
	 2: from /usr/local/lib/ruby/gems/2.5.0/gems/net-scp-1.2.1/lib/net/scp.rb:369:in `block (3 levels) in start_command'
	 1: from /usr/local/lib/ruby/gems/2.5.0/gems/net-scp-1.2.1/lib/net/scp.rb:400:in `await_response_state'
/usr/local/lib/ruby/gems/2.5.0/gems/net-scp-1.2.1/lib/net/scp/upload.rb:40:in `upload_current_state': not a directory or a regular file: "/var/folders/jj/2t6vwbpn4lzgpjc7n5t_50xm0000gn/T/default-centos-74-sandbox-20180424-9555-1oz51xv/filter_plugins" (Net::SCP::Error)
```

## Kitchen Diagnose

Please include the output of `kitchen diagnose --all` or `kitchen diagnose --loader` (if the first failed).  This can be helpful in troubleshooting, so please include it in a gist.

## NOTE:

This repository is for core issues with the Test-Kitchen framework, so if the issue is with a plugin you may be referred to file the issue with the appropriate plugin.

**Comment by willis7** [comment]
Looks to be linked to #1035 and #1023

**Comment by willis7** [comment]
I found the workaround in #1035 

```
transport:
  max_ssh_sessions: 6
```
