### ISSUE TITLE
Internal error when running kitchen EC2

### ISSUE THREAD

**Issue by diegofduarte** [test-kitchen/test-kitchen#1433]
# Version:

root@8ff5b304596e:~# chef gem list knife-ec2
*** LOCAL GEMS ***
knife-ec2 (0.18.0)

# Environment: [Details about the environment such as the Operating System, cookbook details, etc...]

Ubuntu 14.04
CircleCI 2.13

`Note: I even tried to return the old kitchen.yml file to the last working build in our pipeline, but it suddenly stopped to work and never woke up again.`
`I'm able to reproduce this problem locally with a different ChefDK version.`

root@8ff5b304596e:~# chef -v
Chef Development Kit Version: 3.0.36
chef-client version: 14.1.12
delivery version: master (7206afaf4cf29a17d2144bb39c55b7212cfafcc7)
berks version: 7.0.2
kitchen version: 1.21.2
inspec version: 2.1.72

# Scenario:

We're trying to run a kitchen CI test inside our CircleCI to generate a new AMI with Packer afterwards. But when we reach the kitchen deployment stage, we get a error:

```
#!/bin/bash -eo pipefail
chef exec kitchen test --destroy=always ec2 -l debug
-----> Starting Kitchen (v1.21.2)
D      [local command] BEGIN (docker >> /dev/null 2>&1)
D      [local command] END (0m0.06s)
$$$$$$ Deprecated configuration detected:
require_chef_omnibus
Run 'kitchen doctor' for details.

D      Berksfile found at /tmp/ubuntu_base_ami/Berksfile, loading Berkshelf
D      Berkshelf 7.0.2 library loaded
D      Berksfile found at /tmp/ubuntu_base_ami/Berksfile, loading Berkshelf
D      Berkshelf 7.0.2 previously loaded
D      Berksfile found at /tmp/ubuntu_base_ami/Berksfile, loading Berkshelf
D      Berkshelf 7.0.2 previously loaded
-----> Cleaning up any prior instances of <default-ec2>
-----> Destroying <default-ec2>...
       Finished destroying <default-ec2> (0m0.00s).
-----> Testing <default-ec2>
-----> Creating <default-ec2>...
D      Searching for images matching {:name=>"xxxx-foundation-ubuntu*", :"tag:Branch"=>"master"} ...
D      Search returned 4 images:
D      - xxxx-foundation-ubuntu14 1516829451: Detected ubuntu 1516829451 x86_64.  Architecture: x86_64, Virtualization: hvm, Storage: ebs gp2, Created: 2018-01-24T21:30:25.000Z
D      - xxxx-foundation-ubuntu14 1516666045: Detected ubuntu 1516666045 x86_64.  Architecture: x86_64, Virtualization: hvm, Storage: ebs gp2, Created: 2018-01-23T00:07:06.000Z
D      - xxxx-foundation-ubuntu14 1516666027: Detected ubuntu 1516666027 x86_64.  Architecture: x86_64, Virtualization: hvm, Storage: ebs gp2, Created: 2018-01-23T00:07:14.000Z
D      - xxxx-foundation-ubuntu14 1515709081: Detected ubuntu 1515709081 x86_64.  Architecture: x86_64, Virtualization: hvm, Storage: ebs gp2, Created: 2018-01-11T22:18:32.000Z
D      Image for default-ec2: xxxx-foundation-ubuntu14 1516829451.  Architecture: x86_64, Virtualization: hvm, Storage: ebs gp2, Created: 2018-01-24T21:30:25.000Z
       Detected platform: ubuntu version 1516829451 on x86_64. Instance Type: t2.medium. Default username: ubuntu (default).
       If you are not using an account that qualifies under the AWS
free-tier, you may be charged to run these suites. The charge
should be minimal, but neither Test Kitchen nor its maintainers
are responsible for your incurred costs.

D      Creating EC2 instance in region us-east-1 with properties:
D      - instance_type = "t2.medium"
D      - ebs_optimized = false
D      - image_id = "ami-2cd0e056"
D      - key_name = "test-kitchen"
D      - private_ip_address = nil
D      - placement = {:availability_zone=>"us-east-1b", :tenancy=>"default"}
D      - block_device_mappings = [{:device_name=>"/dev/sda1", :ebs=>{:volume_type=>"gp2", :volume_size=>8, :delete_on_termination=>true}}]
D      - network_interfaces = [{:device_index=>0, :associate_public_ip_address=>false, :delete_on_termination=>true, :subnet_id=>"subnet-616eff4a", :groups=>["sg-e7c18b9d"]}]
-----> Destroying <default-ec2>...
       Finished destroying <default-ec2> (0m0.00s).
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [An internal error has occurred] on default-ec2
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [An internal error has occurred] on default-ec2
D      ----------------------
D      ------Backtrace-------
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/command.rb:183:in `report_errors'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/command.rb:174:in `run_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/command/test.rb:42:in `block in call'
D      /opt/chefdk/embedded/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/command/test.rb:38:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/cli.rb:52:in `perform'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/cli.rb:245:in `test'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/bin/kitchen:13:in `block in <top (required)>'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/errors.rb:171:in `with_friendly_errors'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/bin/kitchen:13:in `<top (required)>'
D      /opt/chefdk/bin/kitchen:270:in `load'
D      /opt/chefdk/bin/kitchen:270:in `<main>'
D      ----End Backtrace-----
D      -Composite Exception--
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #create action: [An internal error has occurred] on default-ec2
D      ----------------------
D      ------Backtrace-------
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-core-2.11.50/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-core-2.11.50/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-core-2.11.50/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-core-2.11.50/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-core-2.11.50/lib/seahorse/client/plugins/response_target.rb:21:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-core-2.11.50/lib/seahorse/client/request.rb:70:in `send_request'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-core-2.11.50/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-resources-2.11.50/lib/aws-sdk-resources/request.rb:24:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-resources-2.11.50/lib/aws-sdk-resources/operations.rb:41:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-resources-2.11.50/lib/aws-sdk-resources/operations.rb:87:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-resources-2.11.50/lib/aws-sdk-resources/operation_methods.rb:19:in `block in add_operation'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/kitchen-ec2-2.2.1/lib/kitchen/driver/aws/client.rb:53:in `create_instance'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/kitchen-ec2-2.2.1/lib/kitchen/driver/ec2.rb:415:in `submit_server'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/kitchen-ec2-2.2.1/lib/kitchen/driver/ec2.rb:230:in `create'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/instance.rb:469:in `public_send'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/instance.rb:469:in `block in perform_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/instance.rb:536:in `synchronize_or_call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/instance.rb:498:in `block in action'
D      /opt/chefdk/embedded/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/instance.rb:497:in `action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/instance.rb:469:in `perform_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/instance.rb:379:in `create_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/instance.rb:368:in `block in transition_to'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/instance.rb:367:in `each'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/instance.rb:367:in `transition_to'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/instance.rb:157:in `verify'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/instance.rb:186:in `block in test'
D      /opt/chefdk/embedded/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/instance.rb:182:in `test'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/command.rb:197:in `public_send'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/command.rb:197:in `run_action_in_thread'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      ----End Backtrace-----
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #create action: [An internal error has occurred]
D      ----------------------
D      ------Backtrace-------
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-core-2.11.50/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-core-2.11.50/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-core-2.11.50/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-core-2.11.50/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-core-2.11.50/lib/seahorse/client/plugins/response_target.rb:21:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-core-2.11.50/lib/seahorse/client/request.rb:70:in `send_request'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-core-2.11.50/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-resources-2.11.50/lib/aws-sdk-resources/request.rb:24:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-resources-2.11.50/lib/aws-sdk-resources/operations.rb:41:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-resources-2.11.50/lib/aws-sdk-resources/operations.rb:87:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-resources-2.11.50/lib/aws-sdk-resources/operation_methods.rb:19:in `block in add_operation'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/kitchen-ec2-2.2.1/lib/kitchen/driver/aws/client.rb:53:in `create_instance'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/kitchen-ec2-2.2.1/lib/kitchen/driver/ec2.rb:415:in `submit_server'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/kitchen-ec2-2.2.1/lib/kitchen/driver/ec2.rb:230:in `create'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/instance.rb:469:in `public_send'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/instance.rb:469:in `block in perform_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/instance.rb:536:in `synchronize_or_call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/instance.rb:498:in `block in action'
D      /opt/chefdk/embedded/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/instance.rb:497:in `action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/instance.rb:469:in `perform_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/instance.rb:379:in `create_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/instance.rb:368:in `block in transition_to'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/instance.rb:367:in `each'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/instance.rb:367:in `transition_to'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/instance.rb:157:in `verify'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/instance.rb:186:in `block in test'
D      /opt/chefdk/embedded/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/instance.rb:182:in `test'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/command.rb:197:in `public_send'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/command.rb:197:in `run_action_in_thread'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      ----End Backtrace-----
Exited with code 20
```

# Steps to Reproduce:

* Install Chef14
* Run chef exec kitchen test ec2
Wait for the error

# Expected Result:

A correct convergence

# Actual Result:

The above error

**Comment by cheeseplus** [comment]
This probably belongs on https://github.com/test-kitchen/kitchen-ec2 based on the stacktrace - that appears to be an error coming from the AWS SDK/API

**Comment by diegofduarte** [comment]
Hey @cheeseplus

Here is (and sorry about the many xxxxx. I had to pull out some sensitive info regarding the company:

```
---
<%
  #--------------------------------------------------------------------------
  # the driver_plugin can be overridden with an environment variable:
  #   $ KITCHEN_DRIVER=ec2 kitchen test
  # if not specified, defaults are used...
  #   - kitchen_driver_ci if environment variable CI=true is present
  #   - kitchen_driver_local is used otherwise (which defaults to vagrant)
  #--------------------------------------------------------------------------

  kitchen_driver_ci = 'ec2'
  kitchen_driver_local = 'vagrant'
  kitchen_driver_default = kitchen_driver_local

  if ENV['KITCHEN_DRIVER']
    kitchen_driver = ENV['KITCHEN_DRIVER']
  elsif ENV['CI']=="true"
    kitchen_driver = kitchen_driver_ci
  else
    kitchen_driver = kitchen_driver_default
  end
  puts "-----> driver_plugin: #{kitchen_driver.to_s}"
%>

driver_plugin: <%= kitchen_driver %>
driver_config:
  require_chef_omnibus: 13
  <% if kitchen_driver == 'ec2' %>
  aws_access_key_id:      <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key:  <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id:         <%= ENV['AWS_SSH_KEY_ID']         || "test-ami-foundation" %>
  region:                 <%= ENV['AWS_REGION']             || "us-east-1" %>
  availability_zone:      <%= ENV['AWS_AVAILABILITY_ZONE']  || "us-east-1b" %>
  instance_type: "t2.medium"
  security_group_ids: ["sg-xxxxxxxx"]
  subnet_id: "subnet-xxxxxx"
  vpc_id: "vpc-xxxxxxxx"
  associate_public_ip: false
  <% end %>
  <% if kitchen_driver == 'vagrant' %>
  customize:
    memory: 2048
  <% end %>

<% if kitchen_driver == 'ec2' %>
transport:
  ssh_key: /home/ubuntu/.ssh/id_004f2fc5b525090140a32d025ba58d39
  username: ubuntu
<% end %>

provisioner:
  name: chef_zero
  http_proxy: http://proxy-dev.xxxx.tech:3128
  https_proxy: https://proxy-dev.xxxx.tech:3128
  no_proxy: .xxxx.tech,.xxxxx.com,.xxxxxx.corp,.xxxx.p10,s3.amazonaws.com

platforms:
- name: ubuntu-1404
  <% if kitchen_driver == 'ec2' %>
  driver_config:
    image_id: <%= ENV['AMI_ID'] %>
    tags: { "Name": "Test-Kitchen xxxxxxxxxx", "Department": "Infrastructure", "Team": "xxxxxx Engineering", "TeamEmail": "xxxxxxxxx@xxxxxxx.com", "Compliance": "None", "ApplicationGroup": "cloud", "Application": "cloud-ami-builder", "IncidentEmail": "xxxxxxx-engineering@xxxxxxxx.pagerduty.com"}
  <% end %>

suites:
- name: default
  run_list:
    - recipe[xxxxxxxx_ubuntu_base_ami::default]
  attributes:
    qualys_ssh_password: "<%= ENV['QUALYS_PASS'] %>"
    newrelic:
      license: <%= ENV['NEWRELIC_LICENSE'] %>

```

**Comment by diegofduarte** [comment]
@cheeseplus Turned out it was a weird problem at AWS side. We're talking with our support analyst at there to solve this. We've built a new Foundation AMI and now everything is fine, we're seeing this just with some random AMIs.

Also, isn't there a way to turn these Kitchen messages a little more verbose? I just figured out after running this on Packer, which returned the error 500 and gave me a clue for the AWS side.

**Comment by cheeseplus** [comment]
In this case the stacktrace combined with the message is exactly what helped us find the underlying error - that is to say wrapping the exception comes with a cost and additional abstraction is something we try to avoid, as a rule, in the kitchen ecosystem.

We have several other issues around improving the message but this would isn't really germane to this repo (core kitchen) specifically so I'm closing it out.
