### ISSUE TITLE
syntax error kitchen-ssh-1.0.1/lib/kitchen/driver/ssh.rb line 13

### ISSUE THREAD

**Issue by SuvarinA** [test-kitchen/test-kitchen#1438]
## Description

I got syntax error on kitchen-ssh-1.0.1/lib/kitchen/driver/ssh.rb line 13 when I run the following command:
[vagrant@rhel7 ]$ KITCHEN_YAML=.kitchen.javamon.yml kitchen converge test-ACS1

Result:
```
-----> Starting Kitchen (v1.23.0)
Traceback (most recent call last):
        28: from /home/vagrant/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
        27: from /home/vagrant/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
        26: from /home/vagrant/.rvm/gems/ruby-2.5.1/bin/kitchen:23:in `<main>'
        25: from /home/vagrant/.rvm/gems/ruby-2.5.1/bin/kitchen:23:in `load'
        24: from /home/vagrant/.rvm/gems/ruby-2.5.1/gems/test-kitchen-1.23.0/bin/kitchen:13:in `<top (required)>'
        23: from /home/vagrant/.rvm/gems/ruby-2.5.1/gems/test-kitchen-1.23.0/lib/kitchen/errors.rb:171:in `with_friendly_errors'
        22: from /home/vagrant/.rvm/gems/ruby-2.5.1/gems/test-kitchen-1.23.0/bin/kitchen:13:in `block in <top (required)>'
        21: from /home/vagrant/.rvm/gems/ruby-2.5.1/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        20: from /home/vagrant/.rvm/gems/ruby-2.5.1/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        19: from /home/vagrant/.rvm/gems/ruby-2.5.1/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        18: from /home/vagrant/.rvm/gems/ruby-2.5.1/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        17: from /home/vagrant/.rvm/gems/ruby-2.5.1/gems/test-kitchen-1.23.0/lib/kitchen/cli.rb:193:in `block (2 levels) in <class:CLI>'
        16: from /home/vagrant/.rvm/gems/ruby-2.5.1/gems/test-kitchen-1.23.0/lib/kitchen/cli.rb:52:in `perform'
        15: from /home/vagrant/.rvm/gems/ruby-2.5.1/gems/test-kitchen-1.23.0/lib/kitchen/command/action.rb:34:in `call'
        14: from /home/vagrant/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
        13: from /home/vagrant/.rvm/gems/ruby-2.5.1/gems/test-kitchen-1.23.0/lib/kitchen/command/action.rb:35:in `block in call'
        12: from /home/vagrant/.rvm/gems/ruby-2.5.1/gems/test-kitchen-1.23.0/lib/kitchen/command.rb:142:in `parse_subcommand'
        11: from /home/vagrant/.rvm/gems/ruby-2.5.1/gems/test-kitchen-1.23.0/lib/kitchen/command.rb:112:in `filtered_instances'
        10: from /home/vagrant/.rvm/gems/ruby-2.5.1/gems/test-kitchen-1.23.0/lib/kitchen/config.rb:117:in `instances'
         9: from /home/vagrant/.rvm/gems/ruby-2.5.1/gems/test-kitchen-1.23.0/lib/kitchen/config.rb:141:in `build_instances'
         8: from /home/vagrant/.rvm/gems/ruby-2.5.1/gems/test-kitchen-1.23.0/lib/kitchen/config.rb:141:in `with_index'
         7: from /home/vagrant/.rvm/gems/ruby-2.5.1/gems/test-kitchen-1.23.0/lib/kitchen/config.rb:141:in `map'
         6: from /home/vagrant/.rvm/gems/ruby-2.5.1/gems/test-kitchen-1.23.0/lib/kitchen/config.rb:142:in `block in build_instances'
         5: from /home/vagrant/.rvm/gems/ruby-2.5.1/gems/test-kitchen-1.23.0/lib/kitchen/config.rb:247:in `new_instance'
         4: from /home/vagrant/.rvm/gems/ruby-2.5.1/gems/test-kitchen-1.23.0/lib/kitchen/config.rb:234:in `new_driver'
         3: from /home/vagrant/.rvm/gems/ruby-2.5.1/gems/test-kitchen-1.23.0/lib/kitchen/driver.rb:38:in `for_plugin'
         2: from /home/vagrant/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
         1: from /home/vagrant/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
/home/vagrant/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require': /home/vagrant/.rvm/gems/ruby-2.5.1/gems/kitchen-ssh-1.0.1/lib/kitchen/driver/ssh.rb:13: syntax error, unexpected tIDENTIFIER, expecting ':' (SyntaxError)
         state[:hostname] = config[:hostnam...
         ^~~~~
/home/vagrant/.rvm/gems/ruby-2.5.1/gems/kitchen-ssh-1.0.1/lib/kitchen/driver/ssh.rb:15: syntax error, unexpected tSTRING_BEG, expecting keyword_do or '{' or '('
         print "Kitchen-ssh does not start yo...
               ^
```

## Kitchen Version

```
[vagrant@rhel7 ]$ kitchen --version
Test Kitchen version 1.23.0
```

## ChefDK Version

```
[vagrant@rhel7 ]$ chef --version
Chef Development Kit Version: 2.4.17
chef-client version: 13.6.4
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.23.0
inspec version: 1.45.13
```

## Ruby Version

```
[vagrant@rhel7 ]$ ruby --version
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
```

## Platform Version

```
[vagrant@rhel7 ]$ uname -a
Linux rhel7.vagrant.box 3.10.0-327.55.3.el7.x86_64 #1 SMP Tue Jul 4 12:38:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by cheeseplus** [comment]
Unless I am missing something, that would be an issue with https://github.com/neillturner/kitchen-ssh and not core test-kitchen.

**Comment by cheeseplus** [comment]
Running RuboCop (a Ruby linter) against the repo reveals the underlying issue:

```
lib/kitchen/driver/ssh.rb:13:10: E: Lint/Syntax: unexpected token tIDENTIFIER
(Using Ruby 2.1 parser; configure using TargetRubyVersion parameter, under AllCops)
         state[:hostname] = config[:hostname]
         ^^^^^
lib/kitchen/driver/ssh.rb:15:16: E: Lint/Syntax: unexpected token tSTRING_BEG
(Using Ruby 2.1 parser; configure using TargetRubyVersion parameter, under AllCops)
         print "Kitchen-ssh does not start your server '#{state[:hostname]}' but will look for an ssh connection with user '#{state[:username]}'"
               ^
```

The code in kitchen-ssh is itself broken and an issue should be opened here https://github.com/neillturner/kitchen-ssh/issues. Closing this as it's not something we can solve or address in this repo.
