### ISSUE TITLE
Chef::Config.from_file in local workstation configuration breaks Kitchen

### ISSUE THREAD

**Issue by bdausses** [test-kitchen/test-kitchen#1483]
## Description

I have a knife_override file set up on my local workstation's knife.rb file, and I'm calling it with this line at the end of my knife.rb:
```
# Allow overriding values in this knife.rb
Chef::Config.from_file(knife_override) if File.exist?(knife_override)
```

This is similar to what I find in @fnichol 's repo here:
https://github.com/fnichol/chef-bootstrap-repo/blob/master/.chef/knife.rb

And for the record, the code in his repo breaks this same way too.

## Kitchen Version

Tell us which version of test-kitchen you are using (`kitchen --version`).  

```ruby
Test Kitchen version 1.23.2
```

## ChefDK Version

If you are running test-kitchen via ChefDK, `chef --version` will provide additional relevent version details.

```ruby
Chef Development Kit Version: 3.2.8
chef-client version: 14.3.37
delivery version: master (6862f27aba89109a9630f0b6c6798efec56b4efe)
berks version: 7.0.6
kitchen version: 1.23.2
inspec version: 2.2.55
```

## Ruby Version

If you are not using test-kitchen via ChefDK, please provide the output of ruby --version.

```ruby
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
```

## Platform Version

MacOS 10.13.6

## Replication Case

Have a working kitchen setup and add these lines to the bottom of your knife.rb file:
```
# Allow overriding values in this knife.rb
Chef::Config.from_file(knife_override) if File.exist?(knife_override)
```

## Kitchen Output

The relevant output of the test-kitchen run or a link to a gist of the entire run, if there is one.

The debug output (kitchen -l debug) may be useful, but please link to a gist, or truncate it.

Please do not paste the full run out put here.  If the full output would be useful, link to it in a gist.

```ruby
Traceback (most recent call last):
	26: from /usr/local/bin/kitchen:288:in `<main>'
	25: from /usr/local/bin/kitchen:288:in `load'
	24: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/bin/kitchen:13:in `<top (required)>'
	23: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/errors.rb:171:in `with_friendly_errors'
	22: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/bin/kitchen:13:in `block in <top (required)>'
	21: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	20: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	19: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	18: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	17: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/cli.rb:120:in `list'
	16: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/cli.rb:52:in `perform'
	15: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/command/list.rb:30:in `call'
	14: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:142:in `parse_subcommand'
	13: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:112:in `filtered_instances'
	12: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/config.rb:117:in `instances'
	11: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/config.rb:141:in `build_instances'
	10: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/config.rb:141:in `with_index'
	 9: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/config.rb:141:in `map'
	 8: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/config.rb:142:in `block in build_instances'
	 7: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/config.rb:252:in `new_instance'
	 6: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/config.rb:302:in `new_provisioner'
	 5: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/provisioner.rb:42:in `for_plugin'
	 4: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/provisioner.rb:42:in `new'
	 3: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/provisioner/chef_base.rb:234:in `initialize'
	 2: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-config-14.3.37/lib/chef-config/workstation_config_loader.rb:82:in `load'
	 1: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-config-14.3.37/lib/chef-config/workstation_config_loader.rb:190:in `apply_config'
/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-config-14.3.37/lib/chef-config/workstation_config_loader.rb:212:in `rescue in apply_config': You have an error in your config file /Users/brad/.chef/knife.rb (ChefConfig::ConfigurationError)

NameError: uninitialized constant #<Class:0x00007fb91604de28>::Chef
  /Users/brad/.chef/knife.rb:42:in `from_string'
Relevant file content:
 41: # Allow overriding values in this knife.rb
 42: Chef::Config.from_file(knife_override) if File.exist?(knife_override)
```

## Kitchen Diagnose

https://gist.github.com/bdausses/e7a6e6f50a093bc4ed9b52ad45409cb1

## NOTE:

This repository is for core issues with the Test-Kitchen framework, so if the issue is with a plugin you may be referred to file the issue with the appropriate plugin.

**Comment by bdausses** [comment]
@cheeseplus, yep totally understood.  I am almost positive this used to work, but the closest thing to a version I can give you is "roughly Jan of 2017."   Its not that big of a deal, and honestly something I should stop doing anyway, so if the right thing to do here is not waste time on it and close this ticket, please feel free to do so.

**Comment by coderanger** [comment]
You need actually `require 'chef/config'` if you're going to use it.

**Comment by bdausses** [comment]
Thanks, @coderanger, that works perfectly!
