### ISSUE TITLE
Gems in metadata.rb not installing

### ISSUE THREAD

**Issue by joshphp** [test-kitchen/test-kitchen#1484]
## Description

When adding gems to a cookbooks `metadata.rb`, and then running `kitchen converge`, the gems listed are not installed therefore the cookbook will not run. 

## Kitchen Version

Tell us which version of test-kitchen you are using (`kitchen --version`).  

```ruby
Test Kitchen version 1.23.2
```

## ChefDK Version

If you are running test-kitchen via ChefDK, `chef --version` will provide additional relevent version details.

```ruby
Chef Development Kit Version: 3.3.23
chef-client version: 14.5.33
delivery version: master (6862f27aba89109a9630f0b6c6798efec56b4efe)
berks version: 7.0.6
kitchen version: 1.23.2
inspec version: 2.2.112
```

## Ruby Version

If you are not using test-kitchen via ChefDK, please provide the output of ruby --version.

```ruby
# Copy-paste your results here
```

## Platform Version

Max OSX Mojave

## Replication Case

Add a gem dependency to a `metadata.rb` file such as below, then run that recipe in test-kitchen. The run will not install any gems, even though they are defined in the cookbooks metadata.rb.

```
gem 'elasticsearch'
```

## Kitchen Output

The relevant output of the test-kitchen run or a link to a gist of the entire run, if there is one.

The debug output (kitchen -l debug) may be useful, but please link to a gist, or truncate it.

Please do not paste the full run out put here.  If the full output would be useful, link to it in a gist.

```ruby
-----> Starting Kitchen (v1.23.2)
-----> Converging <default-ubuntu-1604>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 7.0.6...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Chef Omnibus installation detected (install only if missing)
       Transferring files to <default-ubuntu-1604>
       Starting Chef Client, version 14.5.33
       resolving cookbooks for run list: ["elasticsearch_6::upgrade"]
       Synchronizing Cookbooks:
         - elasticsearch_6 (0.3.0)
         - elasticsearch (4.0.3)
         - haproxy (6.2.5)
         - chef-sugar (4.1.0)
         - rsyslog (6.0.7)
         - yum (5.1.0)
         - logrotate (2.2.0)
         - build-essential (8.2.1)
         - homebrew (5.0.8)
         - apt (7.1.1)
         - ark (4.0.0)
         - windows (5.1.3)
         - seven_zip (3.0.0)
         - java (1.50.0)
         - poise (2.8.2)
         - poise-service (1.5.2)
         - mingw (2.1.0)
       Installing Cookbook Gems:
       Compiling Cookbooks...

       ================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/elasticsearch_6/recipes/upgrade.rb
       ================================================================================

       NameError
       ---------
       undefined local variable or method `es' for cookbook: elasticsearch_6, recipe: upgrade :Chef::Recipe

       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/elasticsearch_6/recipes/upgrade.rb:11:in `get_version'
         /tmp/kitchen/cache/cookbooks/elasticsearch_6/recipes/upgrade.rb:23:in `from_file'
```

## Kitchen Diagnose

https://gist.github.com/joshphp/00a1171f045c1b217e9a0c6f046e6050

**Comment by joshphp** [comment]
I confirmed the gems are listed in the `metadata.json` on the node 

```
{
  "name": "elasticsearch_6",
  "description": "Installs/Configures elasticsearch_6",
  "long_description": "Installs/Configures elasticsearch_6",
  "platforms": {

  },
  "dependencies": {
    "elasticsearch": "~> 4.0.0",
    "java": "~> 1.50.0",
    "haproxy": "~> 6.2.0",
    "logrotate": "~> 2.2.0",
    "rsyslog": "~> 6.0.4"
  },
  "providing": {

  },
  "attributes": {

  },
  "recipes": {

  },
  "version": "0.3.0",
  "privacy": false,
  "chef_versions": [
    [
      ">= 12.1"
    ]
  ],
  "ohai_versions": [

  ],
  "gems": [
    [
      "aws-sdk"
    ],
    [
      "elasticsearch"
    ]
  ]
}
```

**Comment by cheeseplus** [comment]
Could we get a gist of the debug output?

**Comment by joshphp** [comment]
Turns out my issue was scope related. Creating a class, putting my methods in the class, then calling them worked. The issue was not with gems after all, although I wish the output of `test-kitchen` showed the gems being installed, as it would have been more clear that was not the issue.
