### ISSUE TITLE
Kitchen Login Fails on Windows

### ISSUE THREAD

**Issue by darkn3rd** [test-kitchen/test-kitchen#1485]
## Description

Kitchen cannot log into guest systems on Windows with `kitchen login`, and will stack traces as feedback to the user.  With pure vagrant, `vagrant ssh` works fine.

## Kitchen Version

Tell us which version of test-kitchen you are using (`kitchen --version`).  

```ruby
Test Kitchen version 1.23.2
```

## ChefDK Version

```ruby
Chef Development Kit Version: 3.2.30
```

## Platform Version

```
Microsoft Windows
Version 1802 (OS Build 17134.285)
```

## Replication Case

1. Install Vagrant 2.2.0 and ChefDK 3.2.30
2. `kitchen create`
3. `kitchen login`

```yaml
---
driver:
  name: vagrant
  provider: hyperv

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[ez_apache::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
```

## Expected Result

Expected this to work, as `vagrant ssh` works just fine, and it is similar functionality with vagrant + kitchen on macOS or Linux.  Also, expected to be an error message, not a traceback for user feedback.  I would expect traceback with logging set to debug.

```PowerShell
cd .kitchen\kitchen-vagrant\default-ubuntu-1604
vagrant ssh
```

## Actual Result

The result is a stack trace, below is with the `-l debug`.

```
D      [Vagrant command] BEGIN (vagrant --version)
D      [Vagrant command] END (0m0.00s)
D      Preparing to run:
D                  Get-DefaultVMSwitch  | ConvertTo-Json

D      Loading functions from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/kitchen-vagrant-1.3.3/lib/kitchen/driver/../../../support/hyperv.ps1
D      Wrapped script: . C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/kitchen-vagrant-1.3.3/lib/kitchen/driver/../../../support/hyperv.ps1;
          Get-DefaultVMSwitch  | ConvertTo-Json

D      #Local Command BEGIN (c:\windows\system32\windowspowershell\v1.0\powershell.exe -noprofile -executionpolicy bypass -encodedcommand LgAgAEMAOgAvAG8AcABzAGMAbwBkAGUALwBjAGgAZQBmAGQAawAvAGUAbQBiAGUAZABkAGUAZAAvAGwAaQBiAC8AcgB1AGIAeQAvAGcAZQBtAHMALwAyAC4ANQAuADAALwBnAGUAbQBzAC8AawBpAHQAYwBoAGUAbgAtAHYAYQBnAHIAYQBuAHQALQAxAC4AMwAuADMALwBsAGkAYgAvAGsAaQB0AGMAaABlAG4ALwBkAHIAaQB2AGUAcgAvAC4ALgAvAC4ALgAvAC4ALgAvAHMAdQBwAHAAbwByAHQALwBoAHkAcABlAHIAdgAuAHAAcwAxADsACgAgACAAIAAgACAAIAAgACAAIAAgAEcAZQB0AC0ARABlAGYAYQB1AGwAdABWAE0AUwB3AGkAdABjAGgAIAAgAHwAIABDAG8AbgB2AGUAcgB0AFQAbwAtAEoAcwBvAG4ACgA= -outputformat Text)
D      Local Command END (0m0.00s)
D      Berksfile found at C:/Users/joaquin/msyshome/projarea/wordpress-exp/desired_stat/chef/cookbooks/ez_apache/Berksfile, loading Berkshelf
D      Berkshelf 7.0.6 library loaded
D      Login command: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o LogLevel=VERBOSE -i C:/Users/joaquin/msyshome/projarea/wordpress-exp/desired_state/chef/cookbooks/ez_apache/.kitchen/kitchen-vagrant/default-ubuntu-1604/.vagrant/machines/default/hyperv/private_key -p 22 vagrant@172.29.17.70 (Options: {})
Traceback (most recent call last):
        13: from C:/opscode/chefdk/bin/kitchen:306:in `<main>'
        12: from C:/opscode/chefdk/bin/kitchen:306:in `load'
        11: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/bin/kitchen:13:in `<top (required)>'
        10: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/errors.rb:171:in `with_friendly_errors'
         9: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/bin/kitchen:13:in `block in <top (required)>'
         8: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
         7: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
         6: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
         5: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
         4: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/cli.rb:252:in `login'
         3: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/cli.rb:52:in `perform'
         2: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/command/login.rb:36:in `call'
         1: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:222:in `login'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:222:in `exec': No such file or directory - ssh (Errno::ENOENT)
```

## NOTES

Hashicorp has an embedded ssh that it uses to log in: `C:\HashiCorp\Vagrant\embedded\usr\bin/ssh.EXE`.  Expect that with vagrant scenario on Windows, this would be used if no ssh client is available.

The Microsoft Windows-10-only solution is an non-option currently, and in fact breaks things.  For those that don't know about this, Microsoft is slipping their own OpenSSH version with recent versions Windows 10,  `C:\WINDOWS\System32\OpenSSH\ssh.EXE`, but this fails as it tries to parse `$home/.ssh/config` and reads Linux/Unix permissions from Windows NTFS filesystem, which fails.

**Comment by coderanger** [comment]
I think this can be closed as out of scope for Test Kitchen. We support many drivers other than Vagrant so using that as a default value in a core command is more likely to cause problems than solve them. The TK project doesn't maintain installers so including an SSH client at that level would be up to the packagers.
