### ISSUE TITLE
lifecycle: pre_destroy remote hook on unexisting instance

### ISSUE THREAD

**Issue by guskovd** [test-kitchen/test-kitchen#1511]
If the instance does not exist, I get exception:

```bash
$ kitchen destroy linux-node-centos
-----> Starting Kitchen (v1.24.0)
#<Thread:0x0000000002b14098@/home/guskov/.hab-shell/ruby/bundle/2.5.1/gems/test-kitchen-1.24.0/lib/kitchen/command.rb:167 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        11: from /home/guskov/.hab-shell/ruby/bundle/2.5.1/gems/test-kitchen-1.24.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
        10: from /home/guskov/.hab-shell/ruby/bundle/2.5.1/gems/test-kitchen-1.24.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
         9: from /home/guskov/.hab-shell/ruby/bundle/2.5.1/gems/test-kitchen-1.24.0/lib/kitchen/command.rb:197:in `public_send'
         8: from /home/guskov/.hab-shell/ruby/bundle/2.5.1/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:173:in `destroy'
         7: from /home/guskov/.hab-shell/ruby/bundle/2.5.1/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:380:in `transition_to'
         6: from /home/guskov/.hab-shell/ruby/bundle/2.5.1/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:380:in `each'
         5: from /home/guskov/.hab-shell/ruby/bundle/2.5.1/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:381:in `block in transition_to'
         4: from /home/guskov/.hab-shell/ruby/bundle/2.5.1/gems/test-kitchen-1.24.0/lib/kitchen/lifecycle_hooks.rb:44:in `run_with_hooks'
         3: from /home/guskov/.hab-shell/ruby/bundle/2.5.1/gems/test-kitchen-1.24.0/lib/kitchen/lifecycle_hooks.rb:64:in `run'
         2: from /home/guskov/.hab-shell/ruby/bundle/2.5.1/gems/test-kitchen-1.24.0/lib/kitchen/lifecycle_hooks.rb:64:in `each'
         1: from /home/guskov/.hab-shell/ruby/bundle/2.5.1/gems/test-kitchen-1.24.0/lib/kitchen/lifecycle_hooks.rb:73:in `block in run'
/home/guskov/.hab-shell/ruby/bundle/2.5.1/gems/test-kitchen-1.24.0/lib/kitchen/lifecycle_hooks.rb:127:in `run_remote_hook': Cannot use remote lifecycle hooks during phases when the instance is not available (Kitchen::UserError)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::UserError
>>>>>> Message: Cannot use remote lifecycle hooks during phases when the instance is not available
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by guskovd** [comment]
I would like it to work more idempotently.

**Comment by marcparadise** [comment]
@guskovd could you let us know what driver you were using for this node?

**Comment by guskovd** [comment]
> @guskovd could you let us know what driver you were using for this node?

Hello from 2021! I do not remember. Thank you very much for your promptness))
