### ISSUE TITLE
[regression] inspec "not found in load path" when used as verifier

### ISSUE THREAD

**Issue by chrisLeeTW** [test-kitchen/test-kitchen#1512]
## Description

It's seems this regression error (#1090) is back after v1.23.3, but v1.23.2 is ok.

## Kitchen Version
```ruby
Test Kitchen version 1.23.3
```

## ChefDK Version
```ruby
not installed.
```

## Ruby Version
```ruby
ruby 2.5.2p104 (2018-10-18 revision 65133) [x86_64-linux-musl]
```

## Platform Version

Alpine Linux v3.8 (with docker)

## Replication Case
```
$ docker run --rm -it alpine:3.8 sh
$ cd /tmp
$ apk add --no-cache ruby ruby-dev build-base ruby-bundler

$ cat << EOF > ./Gemfile
# encoding: utf-8
source 'https://rubygems.org'

gem 'test-kitchen', '1.23.3'
gem 'inspec', '~> 2.2'
gem 'rake', '~> 12.3'
gem 'kitchen-docker_cli'
gem 'kitchen-inspec'
EOF

$ bundle install --clean --no-cache -j5

$ cat << EOF > .kitchen.yml
---
driver:
  name: docker_cli
  skip_preparation: true

transport:
  name: docker_cli

provisioner:
  name: shell
  data_path: ./src/playbooks
  script: ./bootstrap.sh

verifier:
  name: inspec
  sudo: true

platforms:
  - name: ubuntu-1604
    driver:
      image: "anue/ansible-container:ubuntu-16.04"
      platform: ubuntu

suites:
  - name: users-data-bastion-host
    provisioner:
      arguments:
        - users
        - data
        - bastion-host
    verifier:
      inspec_tests:
        - path: test/integration/users
      attributes:
        user_groups: "admin,dataGoalKeeper"
EOF

$ kitchen diagnose all
```

## Kitchen Output
```ruby
---
timestamp: 2019-01-19 08:31:19 UTC
kitchen_version: 1.23.3
instances:
  error:
    exception: "#<Kitchen::ClientError: Could not load the 'inspec' verifier from
      the load path. Please ensure that your transport is installed as a gem or included
      in your Gemfile if using Bundler.>"
    message: Could not load the 'inspec' verifier from the load path. Please ensure
      that your transport is installed as a gem or included in your Gemfile if using
      Bundler.
    backtrace:
    - "/usr/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.3/lib/kitchen/verifier.rb:47:in
      `rescue in for_plugin'"
    - "/usr/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.3/lib/kitchen/verifier.rb:38:in
      `for_plugin'"
    - "/usr/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.3/lib/kitchen/config.rb:337:in
      `new_verifier'"
    - "/usr/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.3/lib/kitchen/config.rb:254:in
      `new_instance'"
    - "/usr/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.3/lib/kitchen/config.rb:142:in
      `block in build_instances'"
    - "/usr/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.3/lib/kitchen/config.rb:141:in
      `map'"
    - "/usr/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.3/lib/kitchen/config.rb:141:in
      `with_index'"
    - "/usr/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.3/lib/kitchen/config.rb:141:in
      `build_instances'"
    - "/usr/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.3/lib/kitchen/config.rb:117:in
      `instances'"
    - "/usr/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.3/lib/kitchen/command.rb:94:in
      `all_instances'"
    - "/usr/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.3/lib/kitchen/command.rb:142:in
      `parse_subcommand'"
    - "/usr/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.3/lib/kitchen/command/diagnose.rb:53:in
      `load_instances'"
    - "/usr/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.3/lib/kitchen/command/diagnose.rb:32:in
      `block in call'"
    - "/usr/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.3/lib/kitchen/command/diagnose.rb:73:in
      `record_failure'"
    - "/usr/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.3/lib/kitchen/command/diagnose.rb:32:in
      `call'"
    - "/usr/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.3/lib/kitchen/cli.rb:52:in
      `perform'"
    - "/usr/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.3/lib/kitchen/cli.rb:142:in
      `diagnose'"
    - "/usr/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'"
    - "/usr/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'"
    - "/usr/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'"
    - "/usr/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'"
    - "/usr/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.3/bin/kitchen:13:in `block
      in <top (required)>'"
    - "/usr/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.3/lib/kitchen/errors.rb:171:in
      `with_friendly_errors'"
    - "/usr/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.3/bin/kitchen:13:in `<top (required)>'"
    - "/usr/bin/kitchen:23:in `load'"
    - "/usr/bin/kitchen:23:in `<main>'"
```

## Kitchen Diagnose
```
same as Kitchen Output
```

**Comment by damacus** [comment]
Hey @chrisLeeTW,

Thanks for the excellent reproducer steps. I've tried this with kitchen `1.24.0`. With the image you're using I needed to install the `bigdecimal` gem, but this no longer looks like a problem 👍
