### ISSUE TITLE
Test failures on fresh checkout

### ISSUE THREAD

**Issue by zenspider** [test-kitchen/test-kitchen#1549]
+ Done via rake or `minitest spec` (via minitest-sprint gem)
+ Seed is not important

```
add simplecov to Gemfile.local or GEMFILE_MOD to generate code coverage
Run options: --seed 37540

# Running:

..........................................................................................................................................................................................................................................................................................................F...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................F...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

Finished in 8.305072s, 274.7719 runs/s, 425.6435 assertions/s.

  1) Failure:
Kitchen::Driver::SSHBase::#verify#test_0020_uploads sandbox files [/Users/ryan/Work/git/test-kitchen/test-kitchen/spec/kitchen/driver/ssh_base_spec.rb:668]:
not all expectations were satisfied
unsatisfied expectations:
- expected exactly once, not yet invoked: #<Mock:0x7f7f453e09b0>.upload([], "/tmp/verifier")
satisfied expectations:
- allowed any number of times, invoked once: #<Mock:transport>.connection(any_parameters)
- allowed any number of times, invoked once: #<Mock:0x7f7f453e09b0>.upload(any_parameters)
- allowed any number of times, invoked 3 times: #<Mock:0x7f7f453e09b0>.execute(any_parameters)
- allowed any number of times, invoked once: #<Mock:busser>.[](:root_path)
- allowed any number of times, invoked once: #<Mock:busser>.sandbox_path(any_parameters)
- allowed any number of times, invoked once: #<Mock:busser>.cleanup_sandbox(any_parameters)
- allowed any number of times, invoked once: #<Mock:busser>.create_sandbox(any_parameters)
- allowed any number of times, invoked once: #<Mock:busser>.run_command(any_parameters)
- allowed any number of times, invoked once: #<Mock:busser>.prepare_command(any_parameters)
- allowed any number of times, invoked once: #<Mock:busser>.init_command(any_parameters)
- allowed any number of times, not yet invoked: #<Mock:busser>.install_command(any_parameters)
- allowed any number of times, not yet invoked: #<Mock:0x7f7f46d5ffa8>.sandbox_path(any_parameters)
- allowed any number of times, not yet invoked: #<Mock:0x7f7f46d5ffa8>.cleanup_sandbox(any_parameters)
- allowed any number of times, not yet invoked: #<Mock:0x7f7f46d5ffa8>.create_sandbox(any_parameters)
- allowed any number of times, not yet invoked: #<Mock:0x7f7f46d5ffa8>.run_command(any_parameters)
- allowed any number of times, not yet invoked: #<Mock:0x7f7f46d5ffa8>.prepare_command(any_parameters)
- allowed any number of times, not yet invoked: #<Mock:0x7f7f46d5ffa8>.init_command(any_parameters)
- allowed any number of times, not yet invoked: #<Mock:0x7f7f46d5ffa8>.install_command(any_parameters)
- allowed any number of times, invoked once: #<Mock:0x7f7f46d66880>.to_str(any_parameters)
- allowed any number of times, invoked once: #<Mock:0x7f7f46d66880>.transport(any_parameters)
- allowed any number of times, not yet invoked: #<Mock:0x7f7f46d66880>.provisioner(any_parameters)
- allowed any number of times, invoked twice: #<Mock:0x7f7f46d66880>.verifier(any_parameters)
- allowed any number of times, invoked twice: #<Mock:0x7f7f46d66880>.logger(any_parameters)
- allowed any number of times, not yet invoked: #<Mock:0x7f7f46d66880>.name(any_parameters)


  2) Failure:
Kitchen::Provisioner::ChefBase::#check_license::when the license is required::when there is an error accepting the license#test_0001_raises the error [/Users/ryan/Work/git/test-kitchen/test-kitchen/spec/kitchen/provisioner/chef_base_spec.rb:855]:
[LicenseAcceptance::LicenseNotAcceptedError] exception expected, not
Class: <ArgumentError>
Message: <"wrong number of arguments (given 1, expected 2)">
---Backtrace---
/Users/ryan/.gem/repos/test-kitchen/gems/license-acceptance-1.0.5/lib/license_acceptance/acceptor.rb:164:in `initialize'
/Users/ryan/Work/git/test-kitchen/test-kitchen/spec/kitchen/provisioner/chef_base_spec.rb:853:in `new'
/Users/ryan/Work/git/test-kitchen/test-kitchen/spec/kitchen/provisioner/chef_base_spec.rb:853:in `block (6 levels) in <top (required)>'
/Users/ryan/.gem/repos/test-kitchen/gems/mocha-1.8.0/lib/mocha/parameters_matcher.rb:13:in `match?'
/Users/ryan/.gem/repos/test-kitchen/gems/mocha-1.8.0/lib/mocha/expectation.rb:546:in `match?'
/Users/ryan/.gem/repos/test-kitchen/gems/mocha-1.8.0/lib/mocha/expectation_list.rb:55:in `block in matching_expectations'
/Users/ryan/.gem/repos/test-kitchen/gems/mocha-1.8.0/lib/mocha/expectation_list.rb:55:in `select'
/Users/ryan/.gem/repos/test-kitchen/gems/mocha-1.8.0/lib/mocha/expectation_list.rb:55:in `matching_expectations'
/Users/ryan/.gem/repos/test-kitchen/gems/mocha-1.8.0/lib/mocha/expectation_list.rb:25:in `match_allowing_invocation'
/Users/ryan/.gem/repos/test-kitchen/gems/mocha-1.8.0/lib/mocha/mock.rb:298:in `method_missing'
/Users/ryan/Work/git/test-kitchen/test-kitchen/lib/kitchen/provisioner/chef_base.rb:276:in `check_license'
/Users/ryan/Work/git/test-kitchen/test-kitchen/spec/kitchen/provisioner/chef_base_spec.rb:855:in `block (6 levels) in <top (required)>'
---------------

2282 runs, 3535 assertions, 2 failures, 0 errors, 0 skips
```

**Comment by tyler-ball** [comment]
Hey @zenspider - Thanks for this report! The second error is definitely valid and based on https://github.com/chef/license-acceptance/pull/43. I don't see the first error locally though. What does your `gem env` look like? Are you running these tests with `bundle exec`?
