### ISSUE TITLE
kitchen destroy stopped working on kitchen-vcenter

### ISSUE THREAD

**Issue by nimDevOps** [test-kitchen/test-kitchen#1580]
## Description
kitchen destroy command stopped working few months ago via kitchen-vcenter driver on vmware vcenter.

## Kitchen Version

```ruby
$ kitchen --version
Test Kitchen version 1.25.0
```

## ChefDK Version

```ruby
$ chef --version
Chef Development Kit Version: 3.11.3
chef-client version: 14.13.11
delivery version: master (9d07501a3b347cc687c902319d23dc32dd5fa621)
berks version: 7.0.8
kitchen version: 1.25.0
inspec version: 3.9.3
```

## Ruby Version

```ruby
ruby 2.5.5p157 (2019-03-15 revision 67260) [x64-mingw32]
```

## Platform Version

Windows 10 and Windows Server 2016

## Gems

```ruby
$ chef gem list
activesupport (5.2.3)
addressable (2.5.2)
akami (1.3.1)
app_conf (0.4.2)
appbundler (0.12.5)
artifactory (3.0.0)
ast (2.4.0)
aws-eventstream (1.0.3)
aws-sdk (2.11.285)
aws-sdk-core (2.11.285)
aws-sdk-resources (2.11.285)
aws-sigv4 (1.1.0)
axiom-types (0.1.1)
azure_graph_rbac (0.17.1)
azure_mgmt_key_vault (0.17.4)
azure_mgmt_network (0.18.8)
azure_mgmt_resources (0.17.5)
backports (3.15.0)
berkshelf (7.0.8)
bigdecimal (default: 1.3.4)
binding_of_caller (0.8.0)
builder (3.2.3)
bundler (default: 1.16.6)
byebug (11.0.1)
chef (14.13.11 universal-mingw32)
chef-api (0.9.0)
chef-apply (0.2.13)
chef-config (14.13.11)
chef-dk (3.11.3)
chef-provisioning (2.7.6)
chef-provisioning-aws (3.0.7)
chef-provisioning-fog (0.26.3)
chef-sugar (5.0.1)
chef-telemetry (0.1.8)
chef-vault (3.4.3)
chef-zero (14.0.12)
cheffish (14.0.4)
chefspec (7.3.4)
chefstyle (0.11.2)
citrus (3.0.2)
cleanroom (1.0.0)
cmath (default: 1.0.0)
coderay (1.1.2)
coercible (1.0.0)
concurrent-ruby (1.1.5)
cookbook-omnifetch (0.8.1)
cookstyle (3.0.2)
csv (default: 1.0.0)
cucumber (3.1.2)
cucumber-core (3.2.1)
cucumber-expressions (6.0.1)
cucumber-tag_expressions (1.1.1)
cucumber-wire (0.0.1)
date (default: 1.0.0)
dco (1.0.1)
debug_inspector (0.0.3)
declarative (0.0.10)
declarative-option (0.1.0)
dep-selector-libgecode (1.3.1)
dep_selector (1.0.6)
descendants_tracker (0.0.4)
did_you_mean (1.2.0)
diff-lcs (1.3)
diffy (3.3.0)
docker-api (1.34.2)
domain_name (0.5.20180417)
droplet_kit (2.9.0)
equalizer (0.0.11)
equatable (0.5.0)
erubis (2.7.0)
etc (default: 1.0.0)
excon (0.64.0)
faraday (0.15.4)
faraday-cookie_jar (0.0.6)
faraday_middleware (0.12.2)
fauxhai (6.11.0)
fcntl (default: 1.0.0)
ffi (1.11.1 x64-mingw32)
ffi-libarchive (0.4.6)
ffi-rzmq (2.0.7)
ffi-rzmq-core (1.0.7)
ffi-win32-extensions (1.0.3)
ffi-yajl (2.3.1)
fiddle (default: 1.0.0)
filesize (0.1.1)
fileutils (default: 1.0.2)
fog-aws (2.0.1)
fog-core (1.45.0)
fog-digitalocean (0.4.0)
fog-joyent (0.0.1)
fog-json (1.2.0)
fog-openstack (0.3.10)
fog-rackspace (0.1.6)
fog-scaleway (0.5.0)
fog-softlayer (1.1.4)
fog-xenserver (1.0.0)
fog-xml (0.1.3)
foodcritic (15.1.0)
formatador (0.2.5)
fuzzyurl (0.9.0)
gcewinpass (1.1.0)
gherkin (5.1.0)
git (1.5.0)
google-api-client (0.23.9)
google-protobuf (3.5.2)
googleauth (0.6.7)
gssapi (1.3.0)
guard (2.15.0)
gyoku (1.3.1)
hashie (3.6.0)
highline (1.7.10)
htmlentities (4.3.4)
http (2.2.2)
http-cookie (1.0.3)
http-form_data (1.0.3)
http_parser.rb (0.6.0)
httpclient (2.8.3)
httpi (2.4.4)
i18n (1.6.0)
ice_nine (0.11.2)
inifile (3.0.0)
iniparse (1.4.4)
inspec (3.9.3)
io-console (default: 0.4.6)
ipaddr (default: 1.2.0)
ipaddress (0.8.3)
iso8601 (0.12.1)
jmespath (1.4.0)
json (2.2.0, default: 2.1.0)
jwt (2.2.1)
kartograph (0.2.7)
kitchen-azurerm (0.14.8)
kitchen-digitalocean (0.10.3)
kitchen-dokken (2.7.0)
kitchen-ec2 (2.5.0)
kitchen-google (2.0.1)
kitchen-hyperv (0.5.3)
kitchen-inspec (1.1.0)
kitchen-vagrant (1.5.2)
kitchen-vcenter (1.4.2)
knife-acl (1.0.3)
knife-cloud (1.2.3)
knife-ec2 (0.19.16)
knife-google (3.3.7)
knife-opc (0.4.1)
knife-push (1.1.2)
knife-spork (1.7.2)
knife-tidy (2.0.1)
knife-vsphere (2.1.3)
knife-windows (1.9.6)
libyajl2 (1.2.0)
license-acceptance (1.0.12)
listen (3.1.5)
little-plugger (1.1.4)
lockfile (2.1.3)
logging (2.2.2)
logify (0.2.0)
lumberjack (1.0.13)
memoist (0.16.0)
method_source (0.9.2)
mime-types (3.2.2)
mime-types-data (3.2019.0331)
mini_portile2 (2.4.0)
minitar (0.8)
minitest (5.10.3)
mixlib-archive (1.0.1 universal-mingw32)
mixlib-authentication (2.1.1)
mixlib-cli (2.0.6)
mixlib-config (3.0.1)
mixlib-install (3.11.18)
mixlib-log (3.0.1)
mixlib-shellout (2.4.4 universal-mingw32)
mixlib-versioning (1.2.7)
molinillo (0.6.6)
ms_rest (0.7.4)
ms_rest_azure (0.11.1)
multi_json (1.13.1)
multi_test (0.1.2)
multipart-post (2.1.1)
necromancer (0.4.0)
nenv (0.3.0)
net-scp (1.2.1)
net-sftp (2.1.2)
net-ssh (4.2.0)
net-ssh-gateway (2.0.0)
net-ssh-multi (1.2.1)
net-telnet (0.1.1)
netaddr (1.5.1)
nokogiri (1.10.3 x64-mingw32)
nori (2.6.0)
notiffany (0.1.1)
octokit (4.14.0)
ohai (14.8.12)
openssl (default: 2.1.2)
opscode-pushy-client (2.99.0)
os (1.0.1)
paint (1.0.1)
parallel (1.17.0)
parser (2.6.3.0)
parslet (1.8.2)
pastel (0.7.2)
plist (3.5.0)
polyglot (0.3.5)
power_assert (1.1.1)
powerpack (0.1.2)
proxifier (1.0.3)
pry (0.12.2)
pry-byebug (3.7.0)
pry-remote (0.1.8)
pry-stack_explorer (0.4.9.3)
psych (default: 3.0.2)
public_suffix (3.1.0)
r18n-core (3.2.0)
r18n-desktop (3.2.0)
rack (2.0.7)
rainbow (3.0.0)
rake (12.3.0)
rb-fsevent (0.10.3)
rb-inotify (0.10.0)
rb-readline (0.5.5)
rbvmomi (1.13.0)
rdoc (default: 6.0.1)
rdp-ruby-wmi (0.3.1)
representable (3.0.4)
resource_kit (0.1.7)
retriable (3.1.2)
retryable (2.0.4)
rspec (3.8.0)
rspec-core (3.8.0)
rspec-expectations (3.8.3)
rspec-its (1.3.0)
rspec-mocks (3.8.0)
rspec-support (3.8.0)
rspec_junit_formatter (0.2.3)
rubocop (0.55.0)
ruby-prof (0.18.0 x64-mingw32)
ruby-progressbar (1.10.1)
ruby_dep (1.5.0)
rubygems-update (2.7.9)
rubyntlm (0.6.2)
rubyzip (1.2.3)
rufus-lru (1.1.0)
savon (2.12.0)
sawyer (0.8.2)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
semverse (3.0.0)
serverspec (2.41.4)
sfl (2.3)
shellany (0.0.1)
signet (0.11.0)
slop (3.6.0)
socksify (1.7.1)
solve (4.0.2)
specinfra (2.77.3)
sshkey (1.9.0)
sslshake (1.3.0)
stove (7.1.0)
stringio (default: 0.0.1)
strings (0.1.5)
strings-ansi (0.1.0)
strscan (default: 1.0.0)
structured_warnings (0.3.0)
syslog-logger (1.6.8)
systemu (2.6.5)
term-ansicolor (1.7.1)
test-kitchen (1.25.0)
test-unit (3.2.7)
thor (0.20.3)
thread_safe (0.3.6)
timeliness (0.3.10)
timers (4.3.0)
tins (1.20.2)
toml-rb (1.1.2)
tomlrb (1.2.8)
train (1.7.6)
train-habitat (0.1.1)
treetop (1.6.10)
trollop (2.9.9)
tty-box (0.3.0)
tty-color (0.4.3)
tty-cursor (0.6.1)
tty-prompt (0.18.1)
tty-reader (0.5.0)
tty-screen (0.6.5)
tty-spinner (0.9.0)
tty-table (0.10.0)
tzinfo (1.2.5)
uber (0.1.0)
ubuntu_ami (0.4.2)
unf (0.1.4)
unf_ext (0.0.7.2 x64-mingw32)
unicode-display_width (1.6.0)
unicode_utils (1.4.0)
uuidtools (2.1.5)
virtus (1.0.5)
vsphere-automation-sdk (6.6.1)
wasabi (3.5.0)
webrick (default: 1.4.2)
win32-api (1.5.3 universal-mingw32)
win32-certstore (0.3.0)
win32-dir (0.5.1)
win32-event (0.6.3)
win32-eventlog (0.6.3)
win32-ipc (0.7.0)
win32-mmap (0.4.2)
win32-mutex (0.4.3)
win32-process (0.8.3)
win32-service (2.1.4)
win32-taskscheduler (2.0.4)
windows-api (0.4.4)
windows-pr (1.2.6)
winrm (2.3.2)
winrm-elevated (1.1.1)
winrm-fs (1.3.2)
wisper (2.0.0)
wmi-lite (1.0.2)
xmlrpc (0.3.0)
yard (0.9.19)
zlib (default: 1.0.0)

```

## Replication Case

1. install ChefDK 3.11.3 on Windows 64bit (Win10,WS2012/WS2016)
2. chef gem install --no-user-install ~/vsphere-automation-sdk-6.6.1.gem
(installed from locally compiled gem  )
3. chef gem install --no-user-install kitchen-vcenter -v 1.4.2
4. in git-bash terminal create and source environment file with following values(get VCENTER USER,PASSWORD, HOST and DATACENTER from vmware where your templates are hosted, under root level only; guest_elevated username/password are vm credentials, not used for create/destroy commands )
export KITCHEN_DRIVER=vcenter
export VCENTER_USER=kitchenuser@domain
export VCENTER_PASSWORD=Some!P@ssw0rd1$
export VCENTER_HOST=vcenterhost@domain
export VCENTER_DATACENTER=DATACENTER
export VCENTER_GuestElevatedUserName=vagrant
export VCENTER_PhotonGuestElevatedPassword=Welc0me@1234
export VCENTER_Photon2_Template=Photon2-s888.10

5. Place any bootable vm configured with dhcp on root folder of vcenter, name should match with env variable above, for example  Photon2-s888.10
6. Create a project/folder with .kitchen.yml file:

driver:
  name: vcenter
  vcenter_username: <%= ENV['VCENTER_USER'] || 'administrator@vsphere.local' %>
  vcenter_password: <%= ENV['VCENTER_PASSWORD'] || 'Some!P@ssw0rd1$' %>
  vcenter_host: <%= ENV['VCENTER_HOST'] || 'localhost' %>
  vcenter_disable_ssl_verify: true

transport:
  name: ssh
  elevated: true
  username: <%= ENV['VCENTER_GuestElevatedUserName'] || 'unknown' %>
  password: <%= ENV['VCENTER_PhotonGuestElevatedPassword'] || 'unknown' %>

platforms:
  - name: Photon2
    os_type: linux
    driver_config:
      datacenter: <%= ENV['VCENTER_DATACENTER'] || 'unknown' %>
      template: <%= ENV['VCENTER_Photon2_Template'] || 'unknown' %>

suites:
  - name: Docker
    provisioner:
      name: shell

## Kitchen Output
```ruby
$ kitchen list
Instance        Driver   Provisioner  Verifier  Transport  Last Action    Last Error
Docker-Photon2  Vcenter  Shell        Busser    Ssh        <Not Created>  <None>

$ kitchen create Docker-Photon2
-----> Starting Kitchen (v1.25.0)
-----> Creating <Docker-Photon2>...
Cloning 'Photon2-s888.10' to create the VM...
Waiting for network interfaces to become available...
       Finished creating <Docker-Photon2> (1m14.74s).
-----> Kitchen is finished. (1m15.90s)
```

Verify that instance has been created

```ruby
$ cat .kitchen/Docker-Photon2.yml
---
hostname: 10.132.24.22
vm_name: Docker-Photon2-f899f066
last_action: create
last_error:
```

Run command to destroy the instance:

```ruby
$ kitchen destroy -l debug Docker-Photon2
-----> Starting Kitchen (v1.25.0)
-----> Destroying <Docker-Photon2>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #destroy action: [] on Docker-Photon2
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: 1 actions failed.
>>>>>>     Failed to complete #destroy action: [] on Docker-Photon2
D      ----------------------
D      ------Backtrace-------
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/command.rb:184:in `report_errors'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/command.rb:175:in `run_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/command/action.rb:36:in `block in call'
D      C:/opscode/chefdk/embedded/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/command/action.rb:34:in `call'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/cli.rb:52:in `perform'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/cli.rb:198:in `block (2 levels) in <class:CLI>'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/bin/kitchen:13:in `block in <top (required)>'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/errors.rb:171:in `with_friendly_errors'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/bin/kitchen:13:in `<top (required)>'
D      C:/opscode/chefdk/embedded/bin/kitchen:23:in `load'
D      C:/opscode/chefdk/embedded/bin/kitchen:23:in `<main>'
D      ----End Backtrace-----
D      -Composite Exception--
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #destroy action: [] on Docker-Photon2
D      ----------------------
D      ------Backtrace-------
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/rbvmomi-1.13.0/lib/rbvmomi/vim.rb:32:in `connect'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/kitchen-vcenter-1.4.2/lib/kitchen/driver/vcenter.rb:263:in `lookup_service_host'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/kitchen-vcenter-1.4.2/lib/kitchen/driver/vcenter.rb:287:in `connect'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/kitchen-vcenter-1.4.2/lib/kitchen/driver/vcenter.rb:133:in `destroy'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:485:in `public_send'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:485:in `block in perform_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:552:in `synchronize_or_call'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:514:in `block in action'
D      C:/opscode/chefdk/embedded/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:513:in `action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:485:in `perform_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:472:in `destroy_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:381:in `block in transition_to'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:380:in `each'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:380:in `transition_to'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:173:in `destroy'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/command.rb:198:in `public_send'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/command.rb:198:in `run_action_in_thread'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      ----End Backtrace-----
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #destroy action: []
D      ----------------------
D      ------Backtrace-------
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/rbvmomi-1.13.0/lib/rbvmomi/vim.rb:32:in `connect'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/kitchen-vcenter-1.4.2/lib/kitchen/driver/vcenter.rb:263:in `lookup_service_host'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/kitchen-vcenter-1.4.2/lib/kitchen/driver/vcenter.rb:287:in `connect'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/kitchen-vcenter-1.4.2/lib/kitchen/driver/vcenter.rb:133:in `destroy'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:485:in `public_send'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:485:in `block in perform_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:552:in `synchronize_or_call'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:514:in `block in action'
D      C:/opscode/chefdk/embedded/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:513:in `action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:485:in `perform_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:472:in `destroy_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:381:in `block in transition_to'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:380:in `each'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:380:in `transition_to'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:173:in `destroy'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/command.rb:198:in `public_send'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/command.rb:198:in `run_action_in_thread'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      ----End Backtrace-----
```

## Kitchen Diagnose

```ruby
timestamp: 2019-08-02 16:14:54 UTC
kitchen_version: 1.25.0
plugins:
  driver:
    Vcenter:
      class: Kitchen::Driver::Vcenter
      version:
      api_version:
  provisioner:
    Shell:
      class: Kitchen::Provisioner::Shell
      version: 1.25.0
      api_version: 2
  transport:
    Ssh:
      class: Kitchen::Transport::Ssh
      version: 1.25.0
      api_version: 1
  verifier:
    Busser:
      class: Kitchen::Verifier::Busser
      version: 1.25.0
      api_version: 1
loader:
  process_erb: true
  process_local: true
  process_global: true
  global_config:
  project_config:
    filename: D:/dev/chef/DestroyFailExample/.kitchen.yml
    raw_data:
      driver:
        name: vcenter
        vcenter_username: kitchenuser@domain
        vcenter_password: Some!P@ssw0rd1$
        vcenter_host: vcenterhost@domain
        vcenter_disable_ssl_verify: true
      transport:
        name: ssh
        elevated: true
        username: vagrant
        password: Welc0me@1234
      platforms:
      - name: Photon2
        os_type: linux
        driver_config:
          datacenter:  DATACENTER
          template: Photon2-s888.10
      suites:
      - name: Docker
        provisioner:
          name: shell
  local_config:
  combined_config:
    filename:
    raw_data:
      driver:
        name: vcenter
        vcenter_username: kitchenuser@domain
        vcenter_password: Some!P@ssw0rd1$
        vcenter_host: vcenterhost@domain
        vcenter_disable_ssl_verify: true
      transport:
        name: ssh
        elevated: true
        username: vagrant
        password: Welc0me@1234
      platforms:
      - name: Photon2
        os_type: linux
        driver_config:
          datacenter:  DATACENTER
          template: Photon2-s888.10
      suites:
      - name: Docker
        provisioner:
          name: shell
instances:
  Docker-Photon2:
    platform:
      os_type: linux
      shell_type: bourne
    state_file:
      hostname: 10.132.24.22
      last_action: create
      last_error: RuntimeError
      vm_name: Docker-Photon2-f899f066
    driver:
      clone_type: :full
      cluster:
      datacenter:  DATACENTER
      folder:
      kitchen_root: D:/dev/chef/DestroyFailExample
      log_level: :info
      lookup_service_host:
      name: vcenter
      poweron: true
      pre_create_command:
      resource_pool:
      targethost:
      template: Photon2-s888.10
      test_base_path: D:/dev/chef/DestroyFailExample/test/integration
      vcenter_disable_ssl_verify: true
      vcenter_host: vcenterhost@domain
      vcenter_password: Some!P@ssw0rd1$
      vcenter_username: kitchenuser@domain
      vm_name:
    provisioner:
      arguments: []
      command:
      command_prefix:
      data_path:
      debug:
      downloads: {}
      ftp_proxy:
      http_proxy:
      https_proxy:
      kitchen_root: D:/dev/chef/DestroyFailExample
      max_retries: 1
      name: shell
      retry_on_exit_code: []
      root_path: "/tmp/kitchen"
      script:
      sudo: true
      sudo_command: sudo -E
      test_base_path: D:/dev/chef/DestroyFailExample/test/integration
      wait_for_retry: 30
    transport:
      compression: false
      compression_level: 0
      connection_retries: 5
      connection_retry_sleep: 1
      connection_timeout: 15
      elevated: true
      keepalive: true
      keepalive_interval: 60
      kitchen_root: D:/dev/chef/DestroyFailExample
      log_level: :info
      max_ssh_sessions: 9
      max_wait_until_ready: 600
      name: ssh
      password: Welc0me@1234
      port: 22
      ssh_gateway:
      ssh_gateway_port: 22
      ssh_gateway_username:
      ssh_http_proxy:
      ssh_http_proxy_password:
      ssh_http_proxy_port:
      ssh_http_proxy_user:
      ssh_key:
      test_base_path: D:/dev/chef/DestroyFailExample/test/integration
      username: vagrant
    verifier:
      busser_bin: "/tmp/verifier/bin/busser"
      chef_omnibus_root: "/opt/chef"
      command_prefix:
      debug:
      ftp_proxy:
      http_proxy:
      https_proxy:
      kitchen_root: D:/dev/chef/DestroyFailExample
      log_level: :info
      name: busser
      root_path: "/tmp/verifier"
      ruby_bindir: "/opt/chef/embedded/bin"
      sudo: true
      sudo_command: sudo -E
      suite_name: Docker
      test_base_path: D:/dev/chef/DestroyFailExample/test/integration
      version: busser

```

**Comment by nimDevOps** [comment]
Linked issues on rbvmomi :  https://github.com/vmware/rbvmomi/issues/170

**Comment by tas50** [comment]
I'm going to close this one out since it looks like the upstream changes in the vmware API have resolved the problem.
