### ISSUE TITLE
Update all test dependencies to avoid deprecation warnings

### ISSUE THREAD

**Issue by xorima** [test-kitchen/test-kitchen#1624]
```
/usr/local/rvm/rubies/ruby-2.6.0/bin/ruby -S bundle exec cucumber features -x --format progress --no-color --tags ~@ignore
Deprecated: Found tags option '~@ignore'. Support for '~@tag' will be removed from the next release of Cucumber. Please use 'not @tag' instead.
The use of "Aruba::InProcess" is deprecated. Use "Aruba::Processes::InProcess" instead.. Called by /home/jfield/dev/test-kitchen/test-kitchen/features/support/env.rb:5:in `require'
The use of "Aruba::SpawnProcess" is deprecated. Use "Aruba::Processes::SpawnProcess" instead.. Called by /home/jfield/dev/test-kitchen/test-kitchen/features/support/env.rb:6:in `require'
```

**Comment by tas50** [comment]
Our test suite needs to be fully modernized.
