### ISSUE TITLE
WinRM user: value not being set when defined via transport

### ISSUE THREAD

**Issue by danielcbright** [test-kitchen/test-kitchen#1699]
## :ghost: Brief Description

When using the WinRM transport, Test Kitchen fails on the `converge` action with the error message:

```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #converge action: [user is a required option] on default-windows
>>>>>> ----------------------
```
## Version

`2.8.0`

## Environment

Windows 10 Machine, using the `kitchen-docker` driver, and the `winrm` transport.

## Scenario

Trying to spin up a Docker container with Test Kitchen, then use `winrm` to connect to it.

## Steps to Reproduce

1. Setup a `kitchen.yml` with the `docker` driver, and the following `transport:` options

    ```
      transport:
        name: winrm
        user: Administrator
        password: blah
     ```
2. Run `kitchen converge` and get the error message:
    ```
    >>>>>> ------Exception-------
    >>>>>> Class: Kitchen::ActionFailed
    >>>>>> Message: 1 actions failed.
    >>>>>>     Failed to complete #converge action: [user is a required option] on default-windows
    >>>>>> ----------------------
    ```
3. When run with debug options `-D -l debug`, this is the output:
    ```
    D      Cleaning up local sandbox in C:/Users/admin/AppData/Local/Temp/default-windows-sandbox-20201215-9432-ry0ybi
    D      ------Exception-------
    D      Class: Kitchen::ActionFailed
    D      Message: 1 actions failed.
    >>>>>>     Failed to complete #converge action: [user is a required option] on default-windows
    D      ----------------------
    ------Backtrace-------
    D      C:/Users/admin/AppData/Local/chefdk/gem/ruby/2.7.0/gems/winrm-2.3.5/lib/winrm/connection_opts.rb:71:in `validate_required_fields'
    D      C:/Users/admin/AppData/Local/chefdk/gem/ruby/2.7.0/gems/winrm-2.3.5/lib/winrm/connection_opts.rb:59:in `validate'
    D      C:/Users/admin/AppData/Local/chefdk/gem/ruby/2.7.0/gems/winrm-2.3.5/lib/winrm/connection_opts.rb:31:in `create_with_defaults'
    D      C:/Users/admin/AppData/Local/chefdk/gem/ruby/2.7.0/gems/winrm-2.3.5/lib/winrm/connection.rb:64:in `configure_connection_opts'
    D      C:/Users/admin/AppData/Local/chefdk/gem/ruby/2.7.0/gems/winrm-2.3.5/lib/winrm/connection.rb:27:in `initialize'
    D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/transport/winrm.rb:384:in `new'
    D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/transport/winrm.rb:384:in `connection'
    D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/transport/winrm.rb:365:in `elevated_session'
    D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/transport/winrm.rb:250:in `execute_with_exit_code'
    D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/transport/winrm.rb:108:in `execute'
    D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/provisioner/base.rb:75:in `block in call'
    D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/transport/base.rb:100:in `initialize'
    D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/transport/winrm.rb:87:in `initialize'
    D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/transport/winrm.rb:475:in `new'
    D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/transport/winrm.rb:475:in `create_new_connection'
    D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/transport/winrm.rb:74:in `connection'
    D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/provisioner/base.rb:74:in `call'
    D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:419:in `block in converge_action'
    D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:563:in `synchronize_or_call'
    D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:524:in `block in action'
    D      C:/opscode/chef-workstation/embedded/lib/ruby/2.7.0/benchmark.rb:293:in `measure'
    D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:523:in `action'
    D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:414:in `converge_action'
    D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:392:in `block (2 levels) in transition_to'
    D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/lifecycle_hooks.rb:44:in `run_with_hooks'
    D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:391:in `block in transition_to'
    D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:390:in `each'
    D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:390:in `transition_to'
    D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:139:in `converge'
    D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/command.rb:195:in `public_send'
    D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/command.rb:195:in `run_action_in_thread'
    D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/command.rb:166:in `block (2 levels) in run_action'
    D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
    D      ----End Backtrace-----
    ```
## Expected Result

I expect the converge to happen successfully.

## Actual Result

Error described above.

## :heavy_plus_sign: Additional context

I can workaround this issue by editing the following file `C:/Users/admin/AppData/Local/chefdk/gem/ruby/2.7.0/gems/winrm-2.3.5/lib/winrm/connection_opts.rb` and edit the `module WinRM` to match this:

```
module WinRM
  # WinRM connection options, provides defaults and validation.
  class ConnectionOpts < Hash
    DEFAULT_OPERATION_TIMEOUT = 60
    DEFAULT_RECEIVE_TIMEOUT = DEFAULT_OPERATION_TIMEOUT + 10
    DEFAULT_MAX_ENV_SIZE = 153600
    DEFAULT_LOCALE = 'en-US'.freeze
    DEFAULT_RETRY_DELAY = 10
    DEFAULT_RETRY_LIMIT = 3
    DEFAULT_USER = 'administrator'
    class << self
      def create_with_defaults(overrides)
        config = default.merge(overrides)
        config = ensure_receive_timeout_is_greater_than_operation_timeout(config)
        config[:user] = DEFAULT_USER
        config.validate
        config
      end
```
Note, I added `DEFAULT_USER = 'administrator'`
and `config[:user] = DEFAULT_USER`, you can change that to what you want however.

**Comment by danielcbright** [comment]
Update, it seems that the issue lies with the `winrm.rb` in the transport lib, it doesn't like `:username`, so I changed all occurances of `:username` to `:winrm_username` in https://github.com/test-kitchen/test-kitchen/blob/3dcb8dc5a75a4d909c8f7d36c28cb4369af17846/lib/kitchen/transport/winrm.rb#L427 and the username setting works if I change my `kitchen.yml` to use `:winrm_username`

I'm not great at troubleshooting this code but I'm willing to do any testing, just let me know!

**Comment by marcparadise** [comment]
Thanks for reporting @danielcbright, and for the details.

**Comment by marcparadise** [comment]
Looking at the linked code and the (transport settings)[https://docs.chef.io/workstation/config_yml_kitchen/#transport-settings], should this be set in the yml as `username` and not `user`?

**Comment by danielcbright** [comment]
hi @marcparadise it's been a while since I looked at this, but IIRC, setting it to `username` had no affect on `config[:user]`, for whatever reason it isn't passing that variable through to the function, and I didn't have time to really dig through the code path and figure it out

**Comment by thumperward** [comment]
https://github.com/test-kitchen/kitchen-docker/blob/b45c4858bef19f22a32096e44777bff097f35dd8/lib/kitchen/driver/docker.rb#L107 explicitly unsets `:username` on Windows.
