### ISSUE TITLE
Cannot enable Ohai Optional Plugins in Test Kitchen

### ISSUE THREAD

**Issue by trinitronx** [test-kitchen/test-kitchen#1836]
## :ghost: Brief Description

I am trying to update a legacy cookbook that works fine on Chef `13.x`, but was broken by the [Ohai `:Passwd` plugin change in Chef `14`][2].

It appears that [other Chef customers are having the same issue][4], yet with no confirmed working solution.

[Chef documentation for Ohai `optional_plugins`][1] gives the example `client.rb` syntax:

```
ohai.optional_plugins = [
  :Sessions,
  :Lspci,
]
```

This [StackOverflow answer][3] suggests the same syntax for `client.rb`.

## Version

Chef Infra Client, version 18.0.6

## Environments

- Bug Reproduction Cookbook: [trinitronx/sprout-base](https://github.com/trinitronx/sprout-base/tree/forked-repo)
- Hosts tested:

| Operating System           | CPU                                                   | Driver                     | Test Kitchen Version | Chef Version         |
| :--------------------------| :-----------------------------------------------------| :--------------------------| :--------------------| :------------------- |
| macOS Monterey `12.1`      | Apple M1 Pro (`arm64` / `aarch64`)                    | Dokken + Docker `20.10.11` | v3.2.2               | 18.0.6               |
| macOS Catalina `10.15.7`   | 3.1 GHz Dual-Core Intel Core i7 (`x86_64`)            | Dokken + Docker `20.10.12` | v3.2.2               | 18.0.6               |
| Ubuntu Focal Fossa `20.04` | Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (`x86_64`)   | Dokken + Docker `20.10.12` | v1.17.0              | 18.0.6               |

```
# Host #1
$ sw_vers
ProductName:	macOS
ProductVersion:	12.1
BuildVersion:	21C52

# Host #2
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H1615

# Host #3
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
```

## Scenario

Scenario: Enable `:Passwd` Ohai Optional Plugin via Test Kitchen
Given a `.kitchen.yml` including:

```
provisioner:
  name: chef_zero
  client_rb:
    'ohai.optional_plugins = ':
        - :Passwd
```

When I run `KITCHEN_LOCAL_YAML=.kitchen.dokken.yml  kitchen test`
Then the Ohai `:Passwd` plugin should run during the Chef run
And `node['etc']['passwd']` data should be set in node attributes

This is basically the opposite scenario as described in issue #415

## Steps to Reproduce

1. Ensure Docker is running, accessible in current shell session, and Test Kitchen installed
2. Clone the following cookbook, checkout `ohai-bug-reproduction` branch, and run Test Kitchen
```
git clone https://github.com/trinitronx/sprout-base.git
cd sprout-base
git checkout ohai-bug-reproduction
KITCHEN_LOCAL_YAML=.kitchen.dokken.yml  kitchen test
```

## Expected Result

The node attributes for `node['etc']['passwd']` should be set.

## Actual Result

The node attributes under `node['etc']` are not set, and I get a `NoMethodError`: 

```
$ KITCHEN_LOCAL_YAML=.kitchen.dokken.yml  kitchen test
-----> Starting Kitchen (v1.17.0)
-----> Cleaning up any prior instances of <default-ubuntu-2004>
-----> Destroying <default-ubuntu-2004>...
       Deleting kitchen sandbox at /home/trinitronx/.dokken/kitchen_sandbox/c3734815b5-default-ubuntu-2004
       Deleting verifier sandbox at /home/trinitronx/.dokken/verifier_sandbox/c3734815b5-default-ubuntu-2004
       Finished destroying <default-ubuntu-2004> (0m0.10s).
-----> Testing <default-ubuntu-2004>
-----> Creating <default-ubuntu-2004>...
       Creating container chef-current
       Creating kitchen sandbox at /home/trinitronx/.dokken/kitchen_sandbox/c3734815b5-default-ubuntu-2004
       Creating verifier sandbox at /home/trinitronx/.dokken/verifier_sandbox/c3734815b5-default-ubuntu-2004
       Building work image..
       Creating container c3734815b5-default-ubuntu-2004
       Finished creating <default-ubuntu-2004> (0m49.40s).
-----> Converging <default-ubuntu-2004>...
       Creating kitchen sandbox in /home/trinitronx/.dokken/kitchen_sandbox/c3734815b5-default-ubuntu-2004
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 6.3.1...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
+---------------------------------------------+
✔ 2 product licenses accepted.
+---------------------------------------------+
Chef Infra Client, version 18.0.6
Patents: https://www.chef.io/patents
Infra Phase starting
Creating a new client identity for default-ubuntu-2004 using the validator key.
Resolving cookbooks for run list: ["sprout-base::default"]
Synchronizing cookbooks:
  - sprout-base (0.7.0)
  - homebrew (5.3.0)
Installing cookbook gem dependencies:
Compiling cookbooks...
Loading Chef InSpec profile files:
Loading Chef InSpec input files:
Loading Chef InSpec waiver files:

================================================================================
Recipe Compile Error in /opt/kitchen/cache/cookbooks/sprout-base/attributes/bash_it.rb
================================================================================

NoMethodError
-------------
undefined method `[]' for nil:NilClass

Cookbook Trace: (most recent call first)
----------------------------------------
  /opt/kitchen/cache/cookbooks/sprout-base/attributes/home.rb:19:in `from_file'
  /opt/kitchen/cache/cookbooks/sprout-base/attributes/bash_it.rb:3:in `from_file'

Relevant File Content:
----------------------
/opt/kitchen/cache/cookbooks/sprout-base/attributes/home.rb:

 12:    Chef::Log.warn('            https://docs.chef.io/ohai/#optional-plugins')
 13:    Chef::Log.warn('            https://github.com/chef/chef/issues/8888')
 14:    Chef::Log.warn('            https://stackoverflow.com/a/57953198/645491')
 15:  # else
 16:  end
 17:
 18:  begin
 19>>   node.default['sprout']['home'] = node['etc']['passwd'][node['sprout']['user']]['dir']
 20:  rescue => e
 21:    Chef::Log.fatal("node['etc']['passwd'] Ohai attributes are nil!") if node['etc'].nil? || node['etc']['passwd'].nil?
 22:    raise e
 23:  end
 24:

System Info:
------------
chef_version=18.0.6
platform=ubuntu
platform_version=20.04
ruby=ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]
program_name=/opt/chef/embedded/bin/chef-client
executable=/opt/chef/embedded/bin/chef-client


Running handlers:
[2022-01-16T05:47:46+00:00] ERROR: Running exception handlers
Running handlers complete
[2022-01-16T05:47:46+00:00] ERROR: Exception handlers complete
Infra Phase failed. 0 resources updated in 03 seconds
[2022-01-16T05:47:46+00:00] FATAL: Stacktrace dumped to /opt/kitchen/cache/chef-stacktrace.out
[2022-01-16T05:47:46+00:00] FATAL: ---------------------------------------------------------------------------------------
[2022-01-16T05:47:46+00:00] FATAL: PLEASE PROVIDE THE CONTENTS OF THE stacktrace.out FILE (above) IF YOU FILE A BUG REPORT
[2022-01-16T05:47:46+00:00] FATAL: ---------------------------------------------------------------------------------------
[2022-01-16T05:47:46+00:00] FATAL: NoMethodError: undefined method `[]' for nil:NilClass
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-ubuntu-2004>.  Please see .kitchen/logs/default-ubuntu-2004.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

## :heavy_plus_sign: Additional context

The opposite scenario was described in issue #415 for disabling the same `:Passwd` plugin.  Various syntax options were described and one appeared to work as the solution, according to the original poster.  

This was in 2016, with Chef & Test Kitchen versions that were available at that time.

The current [Chef documentation for Ohai `optional_plugins`][1] gives the example `client.rb` syntax:

```
ohai.optional_plugins = [
  :Sessions,
  :Lspci,
]
```

This [StackOverflow answer][3] suggests the same syntax for `client.rb`.

I have tried these various syntaxes in `.kitchen.yml` (see above `Scenario`), and verified that it results in the following `client.rb` inside the Docker `docker` container:

`/opt/kitchen/client.rb`:
```
node_name "default-ubuntu-2004"
checksum_path "/opt/kitchen/checksums"
file_cache_path "/opt/kitchen/cache"
file_backup_path "/opt/kitchen/backup"
cookbook_path ["/opt/kitchen/cookbooks", "/opt/kitchen/site-cookbooks"]
data_bag_path "/opt/kitchen/data_bags"
environment_path "/opt/kitchen/environments"
node_path "/opt/kitchen/nodes"
role_path "/opt/kitchen/roles"
client_path "/opt/kitchen/clients"
user_path "/opt/kitchen/users"
validation_key "/opt/kitchen/validation.pem"
client_key "/opt/kitchen/client.pem"
chef_server_url "http://127.0.0.1:8889"
encrypted_data_bag_secret "/opt/kitchen/encrypted_data_bag_secret"
treat_deprecation_warnings_as_errors true
chef_license "accept"
ohai.optional_plugins =  [:Passwd]
named_run_list {}
```

Notice `ohai.optional_plugins =  [:Passwd]` appears to be the correct `client.rb` syntax as described in the docs.

It appears that the current dokken image does include the Ohai gem, and `passwd.rb` plugin:

```
$ docker images
REPOSITORY                                  TAG       IMAGE ID       CREATED          SIZE
0de6e4bc7f-default-ubuntu-2004              latest    97a240230e5c   11 minutes ago   471MB
dokken/ubuntu-20.04                         latest    cf888fc1dfe8   6 hours ago      467MB
chef/chef                                   current   551d1b805bd1   34 hours ago     97.8MB

$ docker ps
CONTAINER ID   IMAGE                                   COMMAND          CREATED          STATUS          PORTS     NAMES
742bed3bbc67   0de6e4bc7f-default-ubuntu-2004:latest   "/bin/systemd"   12 minutes ago   Up 12 minutes             0de6e4bc7f-default-ubuntu-2004

$ docker exec -ti 0de6e4bc7f-default-ubuntu-2004 /bin/bash
root@dokken:/# ls -l /opt/chef/embedded/lib/ruby/gems/3.0.0/gems/ohai-18.0.1/lib/ohai/plugins/passwd.rb
-rw-r--r-- 1 root root 3300 Jan 14 03:11 /opt/chef/embedded/lib/ruby/gems/3.0.0/gems/ohai-18.0.1/lib/ohai/plugins/passwd.rb
```

[1]: https://docs.chef.io/ohai/#optional-plugins
[2]: https://github.com/chef/chef/issues/8888
[3]: https://stackoverflow.com/a/57953198/645491
[4]: https://stackoverflow.com/q/62261852/645491

**Comment by trinitronx** [comment]
As it turns out... the root cause was being masked by the error and some underlying assumptions about `intermediate_instructions` being set per-`platform` vs. `dokken.driver` level.  I had assumed that [`docker.driver.intermediate_instructions` would run commands][1] to create a user inside the container.  However, the entire hash key was overridden by the `platform.driver.intermediate_instructions` which needed to be specific to Ubuntu.

The fix was to [explicitly create a user][2] using `platform.driver.intermediate_instructions` instead.  This revealed that the Ohai plugin was actually running, and the `NoMethodError` was from another source: the user not being created (no hash key for the user rather than a missing `node['etc']['password']` hash key).

[1]: https://github.com/trinitronx/sprout-base/blob/ohai-bug-reproduction/.kitchen.dokken.yml#L9-L10
[2]: https://github.com/trinitronx/sprout-base/pull/1/commits/a803e62d3e598a764bb3b3c686bb4bad7e87999f#diff-630fcc94c990918ff1fc953d255aaf8b5ec6cb8c4f75602dfdda6b3a546c305f
