### ISSUE TITLE
Failed to complete #create action: [pkeys are immutable on OpenSSL 3.0]

### ISSUE THREAD

**Issue by nusenu** [test-kitchen/test-kitchen#1898]
## :ghost: Brief Description

`kitchen create ...` fails:
```
Failed to complete #create action: [pkeys are immutable on OpenSSL 3.0]
```

## Version

test-kitchen-3.2.2
kitchen-vagrant-1.11.0
Vagrant 2.2.19
VirtualBox-6.1-6.1.34_150636_fedora36-2
openssl gem version: 3.0.0
openssl-3.0.2-5.fc36

## Environment

Fedora 36

## Scenario

kitchen create 

## Steps to Reproduce

1. `git clone https://github.com/nusenu/ansible-relayor.git`
2. `cd ansible-relayor` 
3. `kitchen create t-guard-debian-11`
4. the VM is created and running but kitchen terminates with the exception ` Failed to complete #create action: [pkeys are immutable on OpenSSL 3.0] on t-guard-debian-11`

```
kitchen list
Instance                                                       Driver   Provisioner  Verifier  Transport  Last Action    Last Error
t-guard-debian-11                                              Vagrant  AnsiblePush  Busser    Ssh        <Not Created>  OpenSSL::PKey::PKeyError
```

## Expected Result

no exception is expected

## Actual Result

```
D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [pkeys are immutable on OpenSSL 3.0] on t-guard-debian-11
D      ----------------------
D      ------Backtrace-------
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/command.rb:181:in `report_errors'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/command.rb:172:in `run_action'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/command/action.rb:35:in `block in call'
D      .gem/ruby/gems/benchmark-0.2.0/lib/benchmark.rb:296:in `measure'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/command/action.rb:33:in `call'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/cli.rb:52:in `perform'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/cli.rb:198:in `block (2 levels) in <class:CLI>'
D      .gem/ruby/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
D      .gem/ruby/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
D      .gem/ruby/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
D      .gem/ruby/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
D      .gem/ruby/gems/test-kitchen-3.2.2/bin/kitchen:11:in `block in <top (required)>'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/errors.rb:183:in `with_friendly_errors'
D      .gem/ruby/gems/test-kitchen-3.2.2/bin/kitchen:11:in `<top (required)>'
D      bin/kitchen:23:in `load'
D      bin/kitchen:23:in `<main>'
D      ----End Backtrace-----
D      -Composite Exception--
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #create action: [pkeys are immutable on OpenSSL 3.0] on t-guard-debian-11
D      ----------------------
D      ------Backtrace-------
D      .gem/ruby/gems/net-ssh-6.1.0/lib/net/ssh/transport/kex/ecdh_sha2_nistp256.rb:21:in `generate_key!'
D      .gem/ruby/gems/net-ssh-6.1.0/lib/net/ssh/transport/kex/ecdh_sha2_nistp256.rb:21:in `generate_key'
D      .gem/ruby/gems/net-ssh-6.1.0/lib/net/ssh/transport/kex/abstract.rb:32:in `initialize'
D      .gem/ruby/gems/net-ssh-6.1.0/lib/net/ssh/transport/algorithms.rb:437:in `new'
D      .gem/ruby/gems/net-ssh-6.1.0/lib/net/ssh/transport/algorithms.rb:437:in `exchange_keys'
D      .gem/ruby/gems/net-ssh-6.1.0/lib/net/ssh/transport/algorithms.rb:245:in `proceed!'
D      .gem/ruby/gems/net-ssh-6.1.0/lib/net/ssh/transport/algorithms.rb:184:in `accept_kexinit'
D      .gem/ruby/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:210:in `block in poll_message'
D      .gem/ruby/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:190:in `loop'
D      .gem/ruby/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:190:in `poll_message'
D      .gem/ruby/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:225:in `block in wait'
D      .gem/ruby/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:223:in `loop'
D      .gem/ruby/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:223:in `wait'
D      .gem/ruby/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:90:in `initialize'
D      .gem/ruby/gems/net-ssh-6.1.0/lib/net/ssh.rb:251:in `new'
D      .gem/ruby/gems/net-ssh-6.1.0/lib/net/ssh.rb:251:in `start'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/transport/ssh.rb:337:in `block in establish_connection'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/transport/ssh.rb:356:in `retry_connection'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/transport/ssh.rb:336:in `establish_connection'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/transport/ssh.rb:435:in `session'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/transport/ssh.rb:219:in `wait_until_ready'
D      .gem/ruby/gems/kitchen-vagrant-1.11.0/lib/kitchen/driver/vagrant.rb:121:in `create'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:495:in `public_send'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:495:in `block in perform_action'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:560:in `block in synchronize_or_call'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:558:in `synchronize'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:558:in `synchronize_or_call'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:524:in `block in action'
D      .gem/ruby/gems/benchmark-0.2.0/lib/benchmark.rb:296:in `measure'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:523:in `action'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:495:in `perform_action'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:404:in `create_action'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:392:in `block (2 levels) in transition_to'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/lifecycle_hooks.rb:47:in `run_with_hooks'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:391:in `block in transition_to'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:390:in `each'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:390:in `transition_to'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:128:in `create'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/command.rb:195:in `public_send'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/command.rb:195:in `run_action_in_thread'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/command.rb:166:in `block (2 levels) in run_action'
D      ----End Backtrace-----
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #create action: [pkeys are immutable on OpenSSL 3.0]
D      ----------------------
D      ------Backtrace-------
D      .gem/ruby/gems/net-ssh-6.1.0/lib/net/ssh/transport/kex/ecdh_sha2_nistp256.rb:21:in `generate_key!'
D      .gem/ruby/gems/net-ssh-6.1.0/lib/net/ssh/transport/kex/ecdh_sha2_nistp256.rb:21:in `generate_key'
D      .gem/ruby/gems/net-ssh-6.1.0/lib/net/ssh/transport/kex/abstract.rb:32:in `initialize'
D      .gem/ruby/gems/net-ssh-6.1.0/lib/net/ssh/transport/algorithms.rb:437:in `new'
D      .gem/ruby/gems/net-ssh-6.1.0/lib/net/ssh/transport/algorithms.rb:437:in `exchange_keys'
D      .gem/ruby/gems/net-ssh-6.1.0/lib/net/ssh/transport/algorithms.rb:245:in `proceed!'
D      .gem/ruby/gems/net-ssh-6.1.0/lib/net/ssh/transport/algorithms.rb:184:in `accept_kexinit'
D      .gem/ruby/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:210:in `block in poll_message'
D      .gem/ruby/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:190:in `loop'
D      .gem/ruby/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:190:in `poll_message'
D      .gem/ruby/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:225:in `block in wait'
D      .gem/ruby/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:223:in `loop'
D      .gem/ruby/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:223:in `wait'
D      .gem/ruby/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:90:in `initialize'
D      .gem/ruby/gems/net-ssh-6.1.0/lib/net/ssh.rb:251:in `new'
D      .gem/ruby/gems/net-ssh-6.1.0/lib/net/ssh.rb:251:in `start'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/transport/ssh.rb:337:in `block in establish_connection'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/transport/ssh.rb:356:in `retry_connection'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/transport/ssh.rb:336:in `establish_connection'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/transport/ssh.rb:435:in `session'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/transport/ssh.rb:219:in `wait_until_ready'
D      .gem/ruby/gems/kitchen-vagrant-1.11.0/lib/kitchen/driver/vagrant.rb:121:in `create'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:495:in `public_send'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:495:in `block in perform_action'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:560:in `block in synchronize_or_call'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:558:in `synchronize'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:558:in `synchronize_or_call'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:524:in `block in action'
D      .gem/ruby/gems/benchmark-0.2.0/lib/benchmark.rb:296:in `measure'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:523:in `action'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:495:in `perform_action'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:404:in `create_action'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:392:in `block (2 levels) in transition_to'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/lifecycle_hooks.rb:47:in `run_with_hooks'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:391:in `block in transition_to'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:390:in `each'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:390:in `transition_to'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:128:in `create'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/command.rb:195:in `public_send'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/command.rb:195:in `run_action_in_thread'
D      .gem/ruby/gems/test-kitchen-3.2.2/lib/kitchen/command.rb:166:in `block (2 levels) in run_action'
D      ----End Backtrace-----

```

## :heavy_plus_sign: Additional context

* https://github.com/ruby/openssl/pull/399

**Comment by nusenu** [comment]
upgrading net-ssh from 6.1.0 to 7.0.0.beta1
solves this issue
https://github.com/net-ssh/net-ssh/issues/843
