### ISSUE TITLE
kitchen verify failed with busser dependencies error

### ISSUE THREAD

**Issue by luckeyca** [test-kitchen/test-kitchen#1911]
## :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

when running "kitchen test" command, it failed at "kitchen verify" stage with busser-controls installation dependencies error.

## Version

[Version of the project installed]

## Environment

ubuntu 20.04 with the following packages:

ruby 2.7 with Gemfile as below

source 'https://rubygems.org'
gem 'cookstyle', '7.32.1'
gem 'inspec', '4.56.20'
gem 'inspec-bin', '4.56.20'
gem 'inspec-core', '4.56.20'
gem 'kitchen-ansible', '0.56.0'
gem 'kitchen-ansiblepush', '0.10.1'
gem 'kitchen-azurerm', '1.10.5'
gem 'kitchen-docker', '2.13.0'
gem 'kitchen-docker_cli', '0.19.0'
gem 'kitchen-ec2', '3.13.0'
gem 'kitchen-google', '2.3.0'
gem 'kitchen-inspec', '2.6.1'
gem 'kitchen-oci', '1.12.1'
gem 'kitchen-terraform', '6.1.0'
gem 'kitchen-vagrant', '1.12.1'
gem 'test-kitchen', '3.3.2'
gem 'thor', '1.2.1'

## Scenario

To run kitchen-terraform tests.

## Steps to Reproduce

run kitchen test, it fails at "kitchen verify".  kitchen create/converge all ok.

## Expected Result

kitchen verify should run

## Actual Result

kitchen verify failed with the following errors:

root@c05eebcbbd48:/mnt# kitchen verify
-----> Starting Test Kitchen (v3.3.2)
/var/lib/gems/2.7.0/gems/dry-schema-1.10.2/lib/dry/schema/types_merger.rb:71: warning: Pattern matching is experimental, and the behavior may change in future versions of Ruby!
-----> Verifying <default-terraform>...
       Preparing files for transfer
-----> Installing Busser (busser)
       Fetching busser-0.8.0.gem
       Fetching thor-0.19.0.gem
       Successfully installed thor-0.19.0
       Successfully installed busser-0.8.0
       2 gems installed
-----> Installing Busser plugin: busser-controls
       Traceback (most recent call last):
        31: from /tmp/verifier/bin/busser:23:in `<main>'
        30: from /tmp/verifier/bin/busser:23:in `load'
        29: from /tmp/verifier/gems/gems/busser-0.8.0/bin/busser:8:in `<top (required)>'
        28: from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/base.rb:440:in `start'
        27: from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor.rb:359:in `dispatch'
        26: from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:126:in `invoke_command'
        25: from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/command.rb:27:in `run'
        24: from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor.rb:235:in `block in subcommand'
        23: from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:115:in `invoke'
        22: from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor.rb:359:in `dispatch'
        21: from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:126:in `invoke_command'
        20: from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/command.rb:27:in `run'
        19: from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor.rb:40:in `block in register'
        18: from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:115:in `invoke'
        17: from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/group.rb:232:in `dispatch'
        16: from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `invoke_all'
        15: from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `map'
        14: from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `each'
        13: from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `block in invoke_all'
        12: from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:126:in `invoke_command'
        11: from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/command.rb:27:in `run'
        10: from /tmp/verifier/gems/gems/busser-0.8.0/lib/busser/command/plugin_install.rb:50:in `install_all'
         9: from /tmp/verifier/gems/gems/busser-0.8.0/lib/busser/rubygems.rb:61:in `silence_gem_ui'
         8: from /tmp/verifier/gems/gems/busser-0.8.0/lib/busser/command/plugin_install.rb:51:in `block in install_all'
         7: from /tmp/verifier/gems/gems/busser-0.8.0/lib/busser/command/plugin_install.rb:51:in `each'
         6: from /tmp/verifier/gems/gems/busser-0.8.0/lib/busser/command/plugin_install.rb:51:in `block (2 levels) in install_all'
         5: from /tmp/verifier/gems/gems/busser-0.8.0/lib/busser/command/plugin_install.rb:61:in `install'
         4: from /tmp/verifier/gems/gems/busser-0.8.0/lib/busser/command/plugin_install.rb:74:in `install_plugin_gem'
         3: from /tmp/verifier/gems/gems/busser-0.8.0/lib/busser/rubygems.rb:40:in `install_gem'
         2: from /usr/lib/ruby/2.7.0/rubygems/dependency_installer.rb:301:in `install'
         1: from /usr/lib/ruby/2.7.0/rubygems/dependency_installer.rb:394:in `resolve_dependencies'
       /usr/lib/ruby/2.7.0/rubygems/resolver/installer_set.rb:72:in `add_always_install': Unable to resolve dependency: user requested 'busser-controls (>= 0)' (Gem::UnsatisfiableDependencyError)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Verify failed on instance <default-terraform>.  Please see .kitchen/logs/default-terraform.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

## :heavy_plus_sign: Additional context

Kitchen diagnose

root@c05eebcbbd48:/mnt# kitchen diagnose
/var/lib/gems/2.7.0/gems/dry-schema-1.10.2/lib/dry/schema/types_merger.rb:71: warning: Pattern matching is experimental, and the behavior may change in future versions of Ruby!
---
timestamp: 2022-09-07 01:18:30 UTC
kitchen_version: 3.3.2
instances:
  default-terraform:
    platform:
      os_type: unix
      shell_type: bourne
    state_file:
      kitchen_terraform_outputs:
        compartments:
          sensitive: false
          type:
          - object
          - access_level: string
            compartment_id: string
            compartment_id_in_subtree: bool
            compartments:
            - list
            - - object
              - compartment_id: string
                defined_tags:
                - map
                - string
                description: string
                enable_delete: bool
                freeform_tags:
                - map
                - string
                id: string
                inactive_state: string
                is_accessible: bool
                name: string
                state: string
                time_created: string
            filter:
            - set
            - - object
              - name: string
                regex: bool
                values:
                - list
                - string
            id: string
            name: string
            state: string
          value:
            access_level: ANY
            compartment_id: ocid1.tenancy.oc1..aaaaaaaawlq4uqsqhvqvtywcmwnzrgzon4iybbsm7isgzmcwqqxgmmvdystq
            compartment_id_in_subtree: true
            compartments:
            - compartment_id: ocid1.tenancy.oc1..aaaaaaaawlq4uqsqhvqvtywcmwnzrgzon4iybbsm7isgzmcwqqxgmmvdystq
              defined_tags:
                Oracle-Tags.CreatedBy: default/andrei.zagrean@ssc-spc.gc.ca
                Oracle-Tags.CreatedOn: '2022-05-20T00:09:14.018Z'
              description: Developer level compartment to isolate development activities
                from other tenant users.
              enable_delete: false
              freeform_tags: {}
              id: ocid1.compartment.oc1..aaaaaaaahoxwegjsy4suya6dordeulj3njjv2tx5bjvvoibkhm2p2h5cmp6a
              inactive_state: ''
              is_accessible: false
              name: oci163dev-cheng
              state: ACTIVE
              time_created: 2022-05-20 00:09:14.101 +0000 UTC
            filter:
            - name: name
              regex: false
              values:
              - oci163dev-cheng
            id: IdentityCompartmentsDataSource-3661684014
            name:
            state: ACTIVE
      kitchen_terraform_variables: {}
      last_action: setup
      last_error: Kitchen::ActionFailed
    driver:
      backend_configurations: {}
      client: terraform
      color: true
      command_timeout: 600
      kitchen_root: "/mnt"
      lock: true
      lock_timeout: 0
      log_level: :info
      name: terraform
      parallelism: 10
      plugin_directory:
      pre_create_command:
      root_module_directory: "/mnt/test/fixtures/deploy_test"
      test_base_path: "/mnt/test/integration"
      variable_files:
      - "/mnt/test/fixtures/deploy_test/test.tfvars"
      variables: {}
      verifier:
        name: terraform
        inspec_tests:
        - test/integration/default
        systems:
        - name: default
          backend: local
          reporter:
          - cli
          - junit2:test/reports/terraform-default-junit.xml
      verify_version: true
    provisioner:
      debug:
      kitchen_root: "/mnt"
      name: terraform
      require_chef_for_busser: false
      test_base_path: "/mnt/test/integration"
      uploads: {}
    transport:
      compression: false
      compression_level: 0
      connection_retries: 5
      connection_retry_sleep: 1
      connection_timeout: 15
      keepalive: true
      keepalive_interval: 60
      keepalive_maxcount: 3
      kitchen_root: "/mnt"
      log_level: :info
      max_ssh_sessions: 9
      max_wait_until_ready: 600
      name: ssh
      port: 22
      ssh_gateway:
      ssh_gateway_port: 22
      ssh_gateway_username:
      ssh_http_proxy:
      ssh_http_proxy_password:
      ssh_http_proxy_port:
      ssh_http_proxy_user:
      ssh_key:
      test_base_path: "/mnt/test/integration"
      username: root
    verifier:
      busser_bin: "/tmp/verifier/bin/busser"
      chef_omnibus_root: "/opt/chef"
      command_prefix:
      debug:
      ftp_proxy:
      http_proxy:
      https_proxy:
      kitchen_root: "/mnt"
      log_level: :info
      name: busser
      root_path: "/tmp/verifier"
      ruby_bindir: "/usr/bin"
      sudo: true
      sudo_command: sudo -E
      suite_name: default
      test_base_path: "/mnt/test/integration"
      version: busser
    lifecycle_hooks:
      debug:
      kitchen_root: "/mnt"
      log_level: :info
      test_base_path: "/mnt/test/integration"

================================
kitchen.yml

---
driver:
  name: terraform

provisioner:
  name: terraform
  require_chef_for_busser: false

busser:
  ruby_bindir: /usr/bin

platforms:
  - name: terraform

suites:
  - name: default
    driver:
      root_module_directory: test/fixtures/deploy_test
      variable_files:
        - test/fixtures/deploy_test/test.tfvars
      verifier:
        name: terraform
        inspec_tests:
          - test/integration/default # This is the default. test/integration/<suite_name>
        systems:
          - name: default
            backend: local
            reporter:
              - cli
              - junit2:test/reports/terraform-default-junit.xml

**Comment by luckeyca** [comment]
fixed. looks like my kitchen.yml config triggered something unexpected. once I moved the verify out of the suites section, everything is working. so kitchen terraform doesn't look like supporting verifier under suites section.
