### ISSUE TITLE
Converge on ubuntu 22.04 fails with `unsupported key type 'ssh-ed25519'`

### ISSUE THREAD

**Issue by jburns24** [test-kitchen/test-kitchen#1912]
## :ghost: Brief Description

Converge of a fresh bento/ubuntu-22.04 server with a modified `transport` to use `username: vagrant` and `password: vagrant` fails to connect to the vm with the error `unsupported key type 'ssh-ed25519'`

## Version

```
❯ test-ubu-22 git:(master)✘ chef --version
Chef Workstation version: 22.7.1006
Cookstyle version: 7.32.1
Chef Infra Client version: 17.10.0
Chef InSpec version: 4.56.20
Chef CLI version: 5.6.1
Chef Habitat version: 1.6.420
Test Kitchen version: 3.3.1
```

## Environment

Windows 10 
Powershell 5.1
Vagrant 2.3.1
VirtualBox 6.1.36

## Scenario
I cannot converge a new ubuntu 22.04 vm when I modify the `transport` settings to specify a username and password. This is my attempt to get around the RSA issue with ubuntu-22

## Steps

1) `chef generate cookbook test-ubu-22`
2) navigate to the new cookbook and modified kitchen.yml
```
platforms:
  - name: ubuntu-22.04
    transport:
      name: ssh
      username: vagrant
      password: vagrant

suites:
  - name: default
    includes:

      - ubuntu-22.04
    run_list:
     # This just has an `execute` resource that runs `whoami`
      - recipe[test-ubu-22::default] 
```
3) `kitchen converge`

## Expected Result

I would expect this to connect to vm using a username and password

## Actual Result

converge fails. Here is a full `debug` log 

```
❯ test-ubu-22 git:(master)✘ kitchen converge -l debug
-----> Starting Test Kitchen (v3.3.1)
D      [Vagrant command] BEGIN (vagrant --version)
D      [Vagrant command] END (0m0.00s)
D      Policyfile found at C:/git/test-ubu-22/Policyfile.rb, using Policyfile to resolve cookbook dependencies
-----> Creating <default-ubuntu-2204>...
D      <default-ubuntu-2204> is synchronizing on Kitchen::Driver::Vagrant#create
D      <default-ubuntu-2204> is messaging Kitchen::Driver::Vagrant#create
D      Creating Vagrantfile for <default-ubuntu-2204> (C:/git/test-ubu-22/.kitchen/kitchen-vagrant/default-ubuntu-2204/Vagrantfile)
D      ------------
D      Vagrant.configure("2") do |c|
D        c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
D        c.vm.box = "bento/ubuntu-22.04"
D        c.vm.hostname = "default-ubuntu-2204.vagrantup.com"
D        c.vm.synced_folder ".", "/vagrant", disabled: true
D        c.vm.synced_folder "C:/Users/jburns/.kitchen/cache", "/tmp/omnibus/cache", create: true
D        c.vm.provider :virtualbox do |p|
D          p.name = "kitchen-test-ubu-22-default-ubuntu-2204-9cc1f74d-d6c9-4faf-9f15-8c03200307fa"
D          p.customize ["modifyvm", :id, "--audio", "none"]
D        end
D      end
D      ------------
D      [Vagrant command] BEGIN (vagrant up --no-provision --provider virtualbox)
       Bringing machine 'default' up with 'virtualbox' provider...
       ==> default: Importing base box 'bento/ubuntu-22.04'...
==> default: Matching MAC address for NAT networking...
       ==> default: Checking if box 'bento/ubuntu-22.04' version '202206.13.0' is up to date...
       ==> default: Setting the name of the VM: kitchen-test-ubu-22-default-ubuntu-2204-9cc1f74d-d6c9-4faf-9f15-8c03200307fa
       ==> default: Clearing any previously set network interfaces...
       ==> default: Preparing network interfaces based on configuration...
           default: Adapter 1: nat
       ==> default: Forwarding ports...
           default: 22 (guest) => 2222 (host) (adapter 1)
       ==> default: Running 'pre-boot' VM customizations...
       ==> default: Booting VM...
       ==> default: Waiting for machine to boot. This may take a few minutes...
           default: SSH address: 127.0.0.1:2222
           default: SSH username: vagrant
           default: SSH auth method: private key
           default: Warning: Connection reset. Retrying...
           default: Warning: Connection aborted. Retrying...
           default:
           default: Vagrant insecure key detected. Vagrant will automatically replace
           default: this with a newly generated keypair for better security.
           default:
           default: Inserting generated public key within guest...
           default: Removing insecure key from the guest if it's present...
           default: Key inserted! Disconnecting and reconnecting using new SSH key...
       ==> default: Machine booted and ready!
       ==> default: Checking for guest additions in VM...
       ==> default: Setting hostname...
       ==> default: Mounting shared folders...
           default: /tmp/omnibus/cache => C:/Users/jburns/.kitchen/cache
       ==> default: Machine not provisioned because `--no-provision` is specified.
D      [Vagrant command] END (0m0.00s)
D      [Vagrant command] BEGIN (vagrant ssh-config)
D      [Vagrant command] END (0m0.00s)
D      [SSH] opening connection to vagrant@127.0.0.1<{:user_known_hosts_file=>"/dev/null", :port=>"2222", :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :keepalive_maxcount=>3, :timeout=>15, :password=>"******", :verify_host_key=>:never}>
D      [SSH] shutting previous connection vagrant@127.0.0.1<{:user_known_hosts_file=>"/dev/null", :port=>"2222", :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :keepalive_maxcount=>3, :timeout=>15, :password=>"******", :verify_host_key=>:never, :logger=>#<Logger:0x000001977bee3770 @level=4, @progname=nil, @default_formatter=#<Logger::Formatter:0x000001977bee2d70 @datetime_format=nil>, @formatter=nil, @logdev=#<Logger::LogDevice:0x000001977bee2708 @shift_period_suffix=nil, @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDERR>>, @binmode=false, @mon_data=#<Monitor:0x000001977bee2438>, @mon_data_owner_object_id=1080>>, :password_prompt=>#<Net::SSH::Prompt:0x000001977bee1ab0>, :user=>"vagrant"}>
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [unsupported key type `ssh-ed25519'
net-ssh requires the following gems for ed25519 support:
 * ed25519 (>= 1.2, < 2.0)
 * bcrypt_pbkdf (>= 1.0, < 2.0)
See https://github.com/net-ssh/net-ssh/issues/565 for more information
LoadError : "cannot load such file -- bcrypt_pbkdf_ext"
] on default-ubuntu-2204
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [unsupported key type `ssh-ed25519'
net-ssh requires the following gems for ed25519 support:
 * ed25519 (>= 1.2, < 2.0)
 * bcrypt_pbkdf (>= 1.0, < 2.0)
See https://github.com/net-ssh/net-ssh/issues/565 for more information
LoadError : "cannot load such file -- bcrypt_pbkdf_ext"
] on default-ubuntu-2204
D      ----------------------
D      ------Backtrace-------
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/command.rb:181:in `report_errors'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/command.rb:172:in `run_action'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/command/action.rb:35:in `block in call'
D      C:/opscode/chef-workstation/embedded/lib/ruby/3.0.0/benchmark.rb:293:in `measure'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/command/action.rb:33:in `call'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/cli.rb:52:in `perform'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/cli.rb:198:in `block (2 levels) in <class:CLI>'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/bin/kitchen:11:in `block in <top (required)>'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/errors.rb:183:in `with_friendly_errors'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/bin/kitchen:11:in `<top (required)>'
D      C:/opscode/chef-workstation/bin/kitchen:407:in `load'
D      C:/opscode/chef-workstation/bin/kitchen:407:in `<main>'
D      ----End Backtrace-----
D      -Composite Exception--
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #create action: [unsupported key type `ssh-ed25519'
net-ssh requires the following gems for ed25519 support:
 * ed25519 (>= 1.2, < 2.0)
 * bcrypt_pbkdf (>= 1.0, < 2.0)
See https://github.com/net-ssh/net-ssh/issues/565 for more information
LoadError : "cannot load such file -- bcrypt_pbkdf_ext"
] on default-ubuntu-2204
D      ----------------------
D      ------Backtrace-------
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/ed25519_loader.rb:21:in `raiseUnlessLoaded'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/net-ssh-6.1.0/lib/net/ssh/buffer.rb:322:in `read_keyblob'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/net-ssh-6.1.0/lib/net/ssh/buffer.rb:248:in `read_key'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/net-ssh-6.1.0/lib/net/ssh/key_factory.rb:103:in `load_data_public_key'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/net-ssh-6.1.0/lib/net/ssh/key_factory.rb:84:in `load_public_key'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/key_manager.rb:254:in `block in load_identities'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/key_manager.rb:250:in `map'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/key_manager.rb:250:in `load_identities'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/key_manager.rb:111:in `each_identity'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/methods/publickey.rb:19:in `authenticate'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/session.rb:86:in `block in authenticate'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/session.rb:72:in `each'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/session.rb:72:in `authenticate'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/net-ssh-6.1.0/lib/net/ssh.rb:255:in `start'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/transport/ssh.rb:344:in `block in establish_connection'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/transport/ssh.rb:365:in `retry_connection'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/transport/ssh.rb:343:in `establish_connection'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/transport/ssh.rb:444:in `session'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/transport/ssh.rb:226:in `wait_until_ready'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/kitchen-vagrant-1.12.0/lib/kitchen/driver/vagrant.rb:121:in `create'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/instance.rb:495:in `public_send'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/instance.rb:495:in `block in perform_action'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/instance.rb:560:in `block in synchronize_or_call'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/instance.rb:558:in `synchronize'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/instance.rb:558:in `synchronize_or_call'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/instance.rb:524:in `block in action'
D      C:/opscode/chef-workstation/embedded/lib/ruby/3.0.0/benchmark.rb:293:in `measure'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/instance.rb:523:in `action'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/instance.rb:495:in `perform_action'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/instance.rb:404:in `create_action'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/instance.rb:392:in `block (2 levels) in transition_to'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/lifecycle_hooks.rb:47:in `run_with_hooks'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/instance.rb:391:in `block in transition_to'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/instance.rb:390:in `each'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/instance.rb:390:in `transition_to'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/instance.rb:139:in `converge'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/command.rb:195:in `public_send'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/command.rb:195:in `run_action_in_thread'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/command.rb:166:in `block (2 levels) in run_action'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/logging-2.3.1/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
D      ----End Backtrace-----
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #create action: [unsupported key type `ssh-ed25519'
net-ssh requires the following gems for ed25519 support:
 * ed25519 (>= 1.2, < 2.0)
 * bcrypt_pbkdf (>= 1.0, < 2.0)
See https://github.com/net-ssh/net-ssh/issues/565 for more information
LoadError : "cannot load such file -- bcrypt_pbkdf_ext"
]
D      ----------------------
D      ------Backtrace-------
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/ed25519_loader.rb:21:in `raiseUnlessLoaded'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/net-ssh-6.1.0/lib/net/ssh/buffer.rb:322:in `read_keyblob'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/net-ssh-6.1.0/lib/net/ssh/buffer.rb:248:in `read_key'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/net-ssh-6.1.0/lib/net/ssh/key_factory.rb:103:in `load_data_public_key'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/net-ssh-6.1.0/lib/net/ssh/key_factory.rb:84:in `load_public_key'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/key_manager.rb:254:in `block in load_identities'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/key_manager.rb:250:in `map'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/key_manager.rb:250:in `load_identities'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/key_manager.rb:111:in `each_identity'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/methods/publickey.rb:19:in `authenticate'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/session.rb:86:in `block in authenticate'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/session.rb:72:in `each'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/session.rb:72:in `authenticate'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/net-ssh-6.1.0/lib/net/ssh.rb:255:in `start'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/transport/ssh.rb:344:in `block in establish_connection'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/transport/ssh.rb:365:in `retry_connection'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/transport/ssh.rb:343:in `establish_connection'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/transport/ssh.rb:444:in `session'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/transport/ssh.rb:226:in `wait_until_ready'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/kitchen-vagrant-1.12.0/lib/kitchen/driver/vagrant.rb:121:in `create'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/instance.rb:495:in `public_send'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/instance.rb:495:in `block in perform_action'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/instance.rb:560:in `block in synchronize_or_call'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/instance.rb:558:in `synchronize'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/instance.rb:558:in `synchronize_or_call'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/instance.rb:524:in `block in action'
D      C:/opscode/chef-workstation/embedded/lib/ruby/3.0.0/benchmark.rb:293:in `measure'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/instance.rb:523:in `action'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/instance.rb:495:in `perform_action'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/instance.rb:404:in `create_action'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/instance.rb:392:in `block (2 levels) in transition_to'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/lifecycle_hooks.rb:47:in `run_with_hooks'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/instance.rb:391:in `block in transition_to'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/instance.rb:390:in `each'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/instance.rb:390:in `transition_to'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/instance.rb:139:in `converge'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/command.rb:195:in `public_send'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/command.rb:195:in `run_action_in_thread'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.3.1/lib/kitchen/command.rb:166:in `block (2 levels) in run_action'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/logging-2.3.1/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
D      ----End Backtrace-----
```

## :heavy_plus_sign: Additional context

The error message suggests that net-ssh needs specific versions of other gems. From what I can tell chef ships with those dependant gems and they meet the version requirements.

```
❯ test-ubu-22 git:(master)✘ chef gem list | ag "ed25519|pbkdf"
bcrypt_pbkdf (1.1.0 x64-mingw32)
ed25519 (1.3.0)
```

**Comment by sidxz** [comment]
I believe this is linked to the below issue.
https://github.com/test-kitchen/test-kitchen/issues/1904

**Comment by jburns24** [comment]
Workaround for me was to downgrade chef workstation to 20.9.158 (this was an old version I used to run and never noticed issues). Downgrading to this version and I have been able to pass username and password in the transport section and converge an ubunt 22 vm
