### ISSUE TITLE
Shell Provisioner

### ISSUE THREAD

**Issue by tphummel** [test-kitchen/test-kitchen#331]
hello. running through a blog post: http://www.morethanseven.net/2014/01/12/shell-provisioner-for-test-kitchen/. trying to get the shell provisioner to work as described. my first issue was that my vagrant box didn't get the `ruby` and `gem` executables at `/opt/chef/embedded/` which test-kitchen appears to require. I tried a number of things to override the ruby bin path to use the vagrant provided `ruby` and `gem`. 

``` yaml

---
driver:
  name: vagrant
  ruby_bindir: /opt/vagrant_ruby/bin
  ruby_binpath: /opt/vagrant_ruby/bin

provisioner:
  name: shell
  ruby_bindir: /opt/vagrant_ruby/bin
  ruby_binpath: /opt/vagrant_ruby/bin

ruby_bindir: /opt/vagrant_ruby/bin
ruby_binpath: /opt/vagrant_ruby/bin
```

based on gh Issues i was reading, it sounds like these config options have been changing over the past few months. 

as far as I can tell, it doesn't look like these are being read/set anywhere. particularly in `lib/data_munger.rb` and `lib/busser.rb`. It doesn't look like the calls to busser.init ever pass ruby_bindir from anywhere I could find. 

i was able to get the desired result by manually overriding the defaults in a fork: 
https://github.com/tphummel/test-kitchen/commit/4df71d5605fe213eed77352a06fc45884e32ffba

which resulted in busser complaining that it needs ruby >= 1.9.1, while the `/opt/vagrant_ruby/bin` version is 1.8.7. 

what is the recommended way of using the shell provisioner? should i still bootstrap with chef in order to get access to `/opt/chef/embedded/bin` or maybe install those myself? 

i would appreciate any tips. 

osx mountain lion. ruby 1.9.3p429 (rvm), vagrant 1.4.3, ubunutu 12.04 x64 http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box

Gemfile:

```
source "https://rubygems.org"

gem "test-kitchen", :git => "https://github.com/test-kitchen/test-kitchen.git"
gem "kitchen-vagrant"
gem "vagrant-wrapper"
gem "serverspec"

```

Gemfile.lock:

```
GIT
  remote: git://github.com/tphummel/test-kitchen.git
  revision: 4df71d5605fe213eed77352a06fc45884e32ffba
  branch: shell-bindir
  specs:
    test-kitchen (1.1.2.dev)
      mixlib-shellout (~> 1.2)
      net-scp (~> 1.1)
      net-ssh (~> 2.7)
      safe_yaml (~> 1.0)
      thor (~> 0.18)

GEM
  remote: https://rubygems.org/
  specs:
    diff-lcs (1.2.5)
    highline (1.6.20)
    kitchen-vagrant (0.14.0)
      test-kitchen (~> 1.0)
    mixlib-shellout (1.3.0)
    net-scp (1.1.2)
      net-ssh (>= 2.6.5)
    net-ssh (2.7.0)
    rspec (2.14.1)
      rspec-core (~> 2.14.0)
      rspec-expectations (~> 2.14.0)
      rspec-mocks (~> 2.14.0)
    rspec-core (2.14.7)
    rspec-expectations (2.14.4)
      diff-lcs (>= 1.1.3, < 2.0)
    rspec-mocks (2.14.4)
    safe_yaml (1.0.1)
    serverspec (0.14.3)
      highline
      net-ssh
      rspec (>= 2.13.0)
      specinfra (>= 0.1.0)
    specinfra (0.4.1)
    thor (0.18.1)
    vagrant-wrapper (1.2.1.1)

PLATFORMS
  ruby

DEPENDENCIES
  kitchen-vagrant
  serverspec
  test-kitchen!
  vagrant-wrapper

```

TK output (using `test-kitchen/test-kitchen -b master`):

```

Dropbox/git/test-kitchen-demo% bundle exec kitchen test precise -l debug
-----> Starting Kitchen (v1.1.2.dev)
D      [kitchen::driver::vagrant command] BEGIN (vagrant --version)
D      [kitchen::driver::vagrant command] END (0m0.74s)
-----> Cleaning up any prior instances of <default-precise64>
-----> Destroying <default-precise64>...
D      <default-precise64> is synchronizing on Kitchen::Driver::Vagrant#destroy
D      <default-precise64> is messaging Kitchen::Driver::Vagrant#destroy
D      Creating Vagrantfile for <default-precise64> (/Users/tom/Dropbox/git/test-kitchen-demo/.kitchen/kitchen-vagrant/default-precise64/Vagrantfile)
D      ------------
D      Vagrant.configure("2") do |c|
D        c.vm.box = "precise64"
D        c.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box"
D        c.vm.hostname = "default-precise64.vagrantup.com"
D        c.vm.synced_folder ".", "/vagrant", disabled: true
D        c.vm.provider :virtualbox do |p|
D          p.customize ["modifyvm", :id, "--memory", "256"]
D        end
D      end
D      ------------
D      [kitchen::driver::vagrant command] BEGIN (vagrant destroy -f)
       [default] Forcing shutdown of VM...
       [default] Destroying VM and associated drives...
D      [kitchen::driver::vagrant command] END (0m4.00s)
       Vagrant instance <default-precise64> destroyed.
       Finished destroying <default-precise64> (0m4.41s).
-----> Testing <default-precise64>
-----> Creating <default-precise64>...
D      <default-precise64> is synchronizing on Kitchen::Driver::Vagrant#create
D      <default-precise64> is messaging Kitchen::Driver::Vagrant#create
D      Creating Vagrantfile for <default-precise64> (/Users/tom/Dropbox/git/test-kitchen-demo/.kitchen/kitchen-vagrant/default-precise64/Vagrantfile)
D      ------------
D      Vagrant.configure("2") do |c|
D        c.vm.box = "precise64"
D        c.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box"
D        c.vm.hostname = "default-precise64.vagrantup.com"
D        c.vm.synced_folder ".", "/vagrant", disabled: true
D        c.vm.provider :virtualbox do |p|
D          p.customize ["modifyvm", :id, "--memory", "256"]
D        end
D      end
D      ------------
D      [kitchen::driver::vagrant command] BEGIN (vagrant up --no-provision --provider=virtualbox)
       Bringing machine 'default' up with 'virtualbox' provider...
       [default] Importing base box 'precise64'...
       [default] Matching MAC address for NAT networking...
       [default] Setting the name of the VM...
       [default] Clearing any previously set forwarded ports...
       [default] Fixed port collision for 22 => 2222. Now on port 2200.
       [default] Clearing any previously set network interfaces...
       [default] Preparing network interfaces based on configuration...
       [default] Forwarding ports...
       [default] -- 22 => 2200 (adapter 1)
       [default] Running 'pre-boot' VM customizations...
       [default] Booting VM...
       [default] Waiting for machine to boot. This may take a few minutes...
       [default] Machine booted and ready!
       [default] Setting hostname...
D      [kitchen::driver::vagrant command] END (0m55.77s)
D      [kitchen::driver::vagrant command] BEGIN (vagrant ssh-config)
D      [kitchen::driver::vagrant command] END (0m1.62s)
       Vagrant instance <default-precise64> created.
       Finished creating <default-precise64> (1m2.64s).
-----> Converging <default-precise64>...
       Preparing files for transfer
D      Creating local sandbox in /var/folders/32/p61f71412ln4hy49qvtc803c0000gn/T/default-precise64-sandbox-20140119-14704-16an2j2
       Preparing data
D      Using data from /Users/tom/Dropbox/git/test-kitchen-demo/data
       Preparing script
D      Using script from /Users/tom/Dropbox/git/test-kitchen-demo/bootstrap.sh
D      [SSH] vagrant@127.0.0.1:2200<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :keys_only=>true, :port=>"2200", :keys=>["/Users/tom/.vagrant.d/insecure_private_key"]}> (sudo -E rm -rf /tmp/kitchen/data ; mkdir -p /tmp/kitchen)
D      [SSH] opening connection to vagrant@127.0.0.1:2200<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :keys_only=>true, :port=>"2200", :keys=>["/Users/tom/.vagrant.d/insecure_private_key"]}>
       Transfering files to <default-precise64>
D      Uploaded /var/folders/32/p61f71412ln4hy49qvtc803c0000gn/T/default-precise64-sandbox-20140119-14704-16an2j2/bootstrap.sh (35 bytes)
D      Uploaded /var/folders/32/p61f71412ln4hy49qvtc803c0000gn/T/default-precise64-sandbox-20140119-14704-16an2j2/data/tom2.data (0 bytes)
D      Transfer complete
D      [SSH] vagrant@127.0.0.1:2200<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :keys_only=>true, :port=>"2200", :keys=>["/Users/tom/.vagrant.d/insecure_private_key"], :user=>"vagrant"}> (sudo -E /tmp/kitchen/bootstrap.sh)
Reading package lists... Done
Building dependency tree       
Reading state information... 0%
Reading state information... Done
       ntp is already the newest version.
       0 upgraded, 0 newly installed, 0 to remove and 66 not upgraded.
D      [SSH] closing connection to vagrant@127.0.0.1:2200<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :keys_only=>true, :port=>"2200", :keys=>["/Users/tom/.vagrant.d/insecure_private_key"], :user=>"vagrant"}>
D      Cleaning up local sandbox in /var/folders/32/p61f71412ln4hy49qvtc803c0000gn/T/default-precise64-sandbox-20140119-14704-16an2j2
       Finished converging <default-precise64> (0m5.78s).
-----> Setting up <default-precise64>...
D      [SSH] vagrant@127.0.0.1:2200<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :keys_only=>true, :port=>"2200", :keys=>["/Users/tom/.vagrant.d/insecure_private_key"]}> (sh -c 'BUSSER_ROOT="/tmp/busser" GEM_HOME="/tmp/busser/gems" GEM_PATH="/tmp/busser/gems" GEM_CACHE="/tmp/busser/gems/cache" ; export BUSSER_ROOT GEM_HOME GEM_PATH GEM_CACHE; if ! sudo -E /opt/chef/embedded/bin/gem list busser -i >/dev/null; then sudo -E /opt/chef/embedded/bin/gem install busser --no-rdoc --no-ri; fi; gem_bindir=`/opt/chef/embedded/bin/ruby -rrubygems -e "puts Gem.bindir"`; sudo -E ${gem_bindir}/busser setup; sudo -E /tmp/busser/bin/busser plugin install busser-serverspec')
D      [SSH] opening connection to vagrant@127.0.0.1:2200<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :keys_only=>true, :port=>"2200", :keys=>["/Users/tom/.vagrant.d/insecure_private_key"]}>
       sudo: /opt/chef/embedded/bin/gem: command not found
       sudo: /opt/chef/embedded/bin/gem: command not found
       sh: 1: /opt/chef/embedded/bin/ruby: not found
       sudo: /busser: command not found
       sudo: /tmp/busser/bin/busser: command not found
>>>>>> Setup failed on instance <default-precise64>.
>>>>>> Please see .kitchen/logs/default-precise64.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sh -c 'BUSSER_ROOT="/tmp/busser" GEM_HOME="/tmp/busser/gems" GEM_PATH="/tmp/busser/gems" GEM_CACHE="/tmp/busser/gems/cache" ; export BUSSER_ROOT GEM_HOME GEM_PATH GEM_CACHE; if ! sudo -E /opt/chef/embedded/bin/gem list busser -i >/dev/null; then sudo -E /opt/chef/embedded/bin/gem install busser --no-rdoc --no-ri; fi; gem_bindir=`/opt/chef/embedded/bin/ruby -rrubygems -e "puts Gem.bindir"`; sudo -E ${gem_bindir}/busser setup; sudo -E /tmp/busser/bin/busser plugin install busser-serverspec']
>>>>>> ----------------------
D      Setup failed on instance <default-precise64>.
D      ------Exception-------
D      Class: Kitchen::InstanceFailure
D      Message: Setup failed on instance <default-precise64>.  Please see .kitchen/logs/default-precise64.log for more details
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: SSH exited (1) for command: [sh -c 'BUSSER_ROOT="/tmp/busser" GEM_HOME="/tmp/busser/gems" GEM_PATH="/tmp/busser/gems" GEM_CACHE="/tmp/busser/gems/cache" ; export BUSSER_ROOT GEM_HOME GEM_PATH GEM_CACHE; if ! sudo -E /opt/chef/embedded/bin/gem list busser -i >/dev/null; then sudo -E /opt/chef/embedded/bin/gem install busser --no-rdoc --no-ri; fi; gem_bindir=`/opt/chef/embedded/bin/ruby -rrubygems -e "puts Gem.bindir"`; sudo -E ${gem_bindir}/busser setup; sudo -E /tmp/busser/bin/busser plugin install busser-serverspec']
D      ------Backtrace-------
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-533dcb5ef16f/lib/kitchen/driver/ssh_base.rb:112:in `rescue in run_remote'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-533dcb5ef16f/lib/kitchen/driver/ssh_base.rb:108:in `run_remote'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-533dcb5ef16f/lib/kitchen/driver/ssh_base.rb:56:in `block in setup'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-533dcb5ef16f/lib/kitchen/ssh.rb:47:in `initialize'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-533dcb5ef16f/lib/kitchen/driver/ssh_base.rb:55:in `new'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-533dcb5ef16f/lib/kitchen/driver/ssh_base.rb:55:in `setup'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/gems/kitchen-vagrant-0.14.0/lib/kitchen/driver/vagrant.rb:80:in `setup'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-533dcb5ef16f/lib/kitchen/instance.rb:273:in `public_send'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-533dcb5ef16f/lib/kitchen/instance.rb:273:in `block in perform_action'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-533dcb5ef16f/lib/kitchen/instance.rb:308:in `call'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-533dcb5ef16f/lib/kitchen/instance.rb:308:in `synchronize_or_call'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-533dcb5ef16f/lib/kitchen/instance.rb:283:in `block in action'
D      /Users/tom/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/benchmark.rb:280:in `measure'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-533dcb5ef16f/lib/kitchen/instance.rb:282:in `action'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-533dcb5ef16f/lib/kitchen/instance.rb:273:in `perform_action'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-533dcb5ef16f/lib/kitchen/instance.rb:260:in `setup_action'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-533dcb5ef16f/lib/kitchen/instance.rb:246:in `block in transition_to'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-533dcb5ef16f/lib/kitchen/instance.rb:245:in `each'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-533dcb5ef16f/lib/kitchen/instance.rb:245:in `transition_to'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-533dcb5ef16f/lib/kitchen/instance.rb:141:in `verify'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-533dcb5ef16f/lib/kitchen/instance.rb:170:in `block in test'
D      /Users/tom/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/benchmark.rb:280:in `measure'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-533dcb5ef16f/lib/kitchen/instance.rb:166:in `test'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-533dcb5ef16f/lib/kitchen/command.rb:109:in `public_send'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-533dcb5ef16f/lib/kitchen/command.rb:109:in `block (2 levels) in run_action'
D      ----------------------
bundle exec kitchen test precise -l debug  12.97s user 5.52s system 24% cpu 1:15.24 total
```

TK output (using `tphummel/test-kitchen -b shell-bindir`):

```
Dropbox/git/test-kitchen-demo% bundle exec kitchen test precise -l debug
-----> Starting Kitchen (v1.1.2.dev)
D      [kitchen::driver::vagrant command] BEGIN (vagrant --version)
D      [kitchen::driver::vagrant command] END (0m0.77s)
-----> Cleaning up any prior instances of <default-precise64>
-----> Destroying <default-precise64>...
D      <default-precise64> is synchronizing on Kitchen::Driver::Vagrant#destroy
D      <default-precise64> is messaging Kitchen::Driver::Vagrant#destroy
D      Creating Vagrantfile for <default-precise64> (/Users/tom/Dropbox/git/test-kitchen-demo/.kitchen/kitchen-vagrant/default-precise64/Vagrantfile)
D      ------------
D      Vagrant.configure("2") do |c|
D        c.vm.box = "precise64"
D        c.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box"
D        c.vm.hostname = "default-precise64.vagrantup.com"
D        c.vm.synced_folder ".", "/vagrant", disabled: true
D        c.vm.provider :virtualbox do |p|
D          p.customize ["modifyvm", :id, "--memory", "256"]
D        end
D      end
D      ------------
D      [kitchen::driver::vagrant command] BEGIN (vagrant destroy -f)
       [default] Forcing shutdown of VM...
       [default] Destroying VM and associated drives...
D      [kitchen::driver::vagrant command] END (0m4.05s)
       Vagrant instance <default-precise64> destroyed.
       Finished destroying <default-precise64> (0m4.47s).
-----> Testing <default-precise64>
-----> Creating <default-precise64>...
D      <default-precise64> is synchronizing on Kitchen::Driver::Vagrant#create
D      <default-precise64> is messaging Kitchen::Driver::Vagrant#create
D      Creating Vagrantfile for <default-precise64> (/Users/tom/Dropbox/git/test-kitchen-demo/.kitchen/kitchen-vagrant/default-precise64/Vagrantfile)
D      ------------
D      Vagrant.configure("2") do |c|
D        c.vm.box = "precise64"
D        c.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box"
D        c.vm.hostname = "default-precise64.vagrantup.com"
D        c.vm.synced_folder ".", "/vagrant", disabled: true
D        c.vm.provider :virtualbox do |p|
D          p.customize ["modifyvm", :id, "--memory", "256"]
D        end
D      end
D      ------------
D      [kitchen::driver::vagrant command] BEGIN (vagrant up --no-provision --provider=virtualbox)
       Bringing machine 'default' up with 'virtualbox' provider...
       [default] Importing base box 'precise64'...
       [default] Matching MAC address for NAT networking...
       [default] Setting the name of the VM...
       [default] Clearing any previously set forwarded ports...
       [default] Fixed port collision for 22 => 2222. Now on port 2200.
       [default] Clearing any previously set network interfaces...
       [default] Preparing network interfaces based on configuration...
       [default] Forwarding ports...
       [default] -- 22 => 2200 (adapter 1)
       [default] Running 'pre-boot' VM customizations...
       [default] Booting VM...
       [default] Waiting for machine to boot. This may take a few minutes...
       [default] Machine booted and ready!
       [default] Setting hostname...
D      [kitchen::driver::vagrant command] END (0m58.79s)
D      [kitchen::driver::vagrant command] BEGIN (vagrant ssh-config)
D      [kitchen::driver::vagrant command] END (0m1.63s)
       Vagrant instance <default-precise64> created.
       Finished creating <default-precise64> (1m6.02s).
-----> Converging <default-precise64>...
       Preparing files for transfer
D      Creating local sandbox in /var/folders/32/p61f71412ln4hy49qvtc803c0000gn/T/default-precise64-sandbox-20140119-15984-16zeqop
       Preparing data
D      Using data from /Users/tom/Dropbox/git/test-kitchen-demo/data
       Preparing script
D      Using script from /Users/tom/Dropbox/git/test-kitchen-demo/bootstrap.sh
D      [SSH] vagrant@127.0.0.1:2200<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :keys_only=>true, :port=>"2200", :keys=>["/Users/tom/.vagrant.d/insecure_private_key"]}> (sudo -E rm -rf /tmp/kitchen/data ; mkdir -p /tmp/kitchen)
D      [SSH] opening connection to vagrant@127.0.0.1:2200<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :keys_only=>true, :port=>"2200", :keys=>["/Users/tom/.vagrant.d/insecure_private_key"]}>
       Transfering files to <default-precise64>
D      Uploaded /var/folders/32/p61f71412ln4hy49qvtc803c0000gn/T/default-precise64-sandbox-20140119-15984-16zeqop/bootstrap.sh (35 bytes)
D      Uploaded /var/folders/32/p61f71412ln4hy49qvtc803c0000gn/T/default-precise64-sandbox-20140119-15984-16zeqop/data/tom2.data (0 bytes)
D      Transfer complete
D      [SSH] vagrant@127.0.0.1:2200<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :keys_only=>true, :port=>"2200", :keys=>["/Users/tom/.vagrant.d/insecure_private_key"], :user=>"vagrant"}> (sudo -E /tmp/kitchen/bootstrap.sh)
Reading package lists... Done
Building dependency tree       
Reading state information... 0%
Reading state information... Done
       ntp is already the newest version.
       0 upgraded, 0 newly installed, 0 to remove and 66 not upgraded.
D      [SSH] closing connection to vagrant@127.0.0.1:2200<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :keys_only=>true, :port=>"2200", :keys=>["/Users/tom/.vagrant.d/insecure_private_key"], :user=>"vagrant"}>
D      Cleaning up local sandbox in /var/folders/32/p61f71412ln4hy49qvtc803c0000gn/T/default-precise64-sandbox-20140119-15984-16zeqop
       Finished converging <default-precise64> (0m5.16s).
-----> Setting up <default-precise64>...
D      [SSH] vagrant@127.0.0.1:2200<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :keys_only=>true, :port=>"2200", :keys=>["/Users/tom/.vagrant.d/insecure_private_key"]}> (sh -c 'BUSSER_ROOT="/tmp/busser" GEM_HOME="/tmp/busser/gems" GEM_PATH="/tmp/busser/gems" GEM_CACHE="/tmp/busser/gems/cache" ; export BUSSER_ROOT GEM_HOME GEM_PATH GEM_CACHE; if ! sudo -E /opt/vagrant_ruby/bin/gem list busser -i >/dev/null; then sudo -E /opt/vagrant_ruby/bin/gem install busser --no-rdoc --no-ri; fi; gem_bindir=`/opt/vagrant_ruby/bin/ruby -rrubygems -e "puts Gem.bindir"`; sudo -E ${gem_bindir}/busser setup; sudo -E /tmp/busser/bin/busser plugin install busser-serverspec')
D      [SSH] opening connection to vagrant@127.0.0.1:2200<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :keys_only=>true, :port=>"2200", :keys=>["/Users/tom/.vagrant.d/insecure_private_key"]}>
Fetching: thor-0.18.1.gem (100%) ( 88%)
Fetching: busser-0.6.0.gem (100%)
       ERROR:  Error installing busser:
        busser requires Ruby version >= 1.9.1.
       sudo: /tmp/busser/gems/bin/busser: command not found
       sudo: /tmp/busser/bin/busser: command not found
>>>>>> Setup failed on instance <default-precise64>.
>>>>>> Please see .kitchen/logs/default-precise64.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sh -c 'BUSSER_ROOT="/tmp/busser" GEM_HOME="/tmp/busser/gems" GEM_PATH="/tmp/busser/gems" GEM_CACHE="/tmp/busser/gems/cache" ; export BUSSER_ROOT GEM_HOME GEM_PATH GEM_CACHE; if ! sudo -E /opt/vagrant_ruby/bin/gem list busser -i >/dev/null; then sudo -E /opt/vagrant_ruby/bin/gem install busser --no-rdoc --no-ri; fi; gem_bindir=`/opt/vagrant_ruby/bin/ruby -rrubygems -e "puts Gem.bindir"`; sudo -E ${gem_bindir}/busser setup; sudo -E /tmp/busser/bin/busser plugin install busser-serverspec']
>>>>>> ----------------------
D      Setup failed on instance <default-precise64>.
D      ------Exception-------
D      Class: Kitchen::InstanceFailure
D      Message: Setup failed on instance <default-precise64>.  Please see .kitchen/logs/default-precise64.log for more details
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: SSH exited (1) for command: [sh -c 'BUSSER_ROOT="/tmp/busser" GEM_HOME="/tmp/busser/gems" GEM_PATH="/tmp/busser/gems" GEM_CACHE="/tmp/busser/gems/cache" ; export BUSSER_ROOT GEM_HOME GEM_PATH GEM_CACHE; if ! sudo -E /opt/vagrant_ruby/bin/gem list busser -i >/dev/null; then sudo -E /opt/vagrant_ruby/bin/gem install busser --no-rdoc --no-ri; fi; gem_bindir=`/opt/vagrant_ruby/bin/ruby -rrubygems -e "puts Gem.bindir"`; sudo -E ${gem_bindir}/busser setup; sudo -E /tmp/busser/bin/busser plugin install busser-serverspec']
D      ------Backtrace-------
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-4df71d5605fe/lib/kitchen/driver/ssh_base.rb:112:in `rescue in run_remote'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-4df71d5605fe/lib/kitchen/driver/ssh_base.rb:108:in `run_remote'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-4df71d5605fe/lib/kitchen/driver/ssh_base.rb:56:in `block in setup'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-4df71d5605fe/lib/kitchen/ssh.rb:47:in `initialize'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-4df71d5605fe/lib/kitchen/driver/ssh_base.rb:55:in `new'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-4df71d5605fe/lib/kitchen/driver/ssh_base.rb:55:in `setup'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/gems/kitchen-vagrant-0.14.0/lib/kitchen/driver/vagrant.rb:80:in `setup'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-4df71d5605fe/lib/kitchen/instance.rb:273:in `public_send'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-4df71d5605fe/lib/kitchen/instance.rb:273:in `block in perform_action'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-4df71d5605fe/lib/kitchen/instance.rb:308:in `call'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-4df71d5605fe/lib/kitchen/instance.rb:308:in `synchronize_or_call'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-4df71d5605fe/lib/kitchen/instance.rb:283:in `block in action'
D      /Users/tom/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/benchmark.rb:280:in `measure'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-4df71d5605fe/lib/kitchen/instance.rb:282:in `action'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-4df71d5605fe/lib/kitchen/instance.rb:273:in `perform_action'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-4df71d5605fe/lib/kitchen/instance.rb:260:in `setup_action'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-4df71d5605fe/lib/kitchen/instance.rb:246:in `block in transition_to'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-4df71d5605fe/lib/kitchen/instance.rb:245:in `each'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-4df71d5605fe/lib/kitchen/instance.rb:245:in `transition_to'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-4df71d5605fe/lib/kitchen/instance.rb:141:in `verify'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-4df71d5605fe/lib/kitchen/instance.rb:170:in `block in test'
D      /Users/tom/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/benchmark.rb:280:in `measure'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-4df71d5605fe/lib/kitchen/instance.rb:166:in `test'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-4df71d5605fe/lib/kitchen/command.rb:109:in `public_send'
D      /Users/tom/.rvm/gems/ruby-1.9.3-p429/bundler/gems/test-kitchen-4df71d5605fe/lib/kitchen/command.rb:109:in `block (2 levels) in run_action'
D      ----------------------
bundle exec kitchen test precise -l debug  13.08s user 5.59s system 22% cpu 1:22.41 total
```

**Comment by sneakybeaky** [comment]
Hi,

Just hit the same issue. What worked for me was to bootstrap the Chef omnibus install in the shell script :

    #!/usr/bin/env bash

    #Install chef - needed for busser install as part of server spec
    curl -L https://www.chef.io/chef/install.sh | sudo bash

    # more stuff here....

Means you don't need to use a vagrant box with chef pre-installed.

**Comment by flaccid** [comment]
I ran into this too and would be very keen on not requiring chef in the VM to do tests.
