### ISSUE TITLE
kitchen init throws cannot load win32/process & windows/handle on Windows 8.1 x64

### ISSUE THREAD

**Issue by chiefy** [test-kitchen/test-kitchen#385]
I am not well versed with Ruby stuff, but I was just trying to mess around with Test Kitchen on Windows 8.1 x64 w/ Ruby 2.0.0 and got the following exceptions while trying to run `kitchen init --driver-kitchen-vagrant`

```
PS C:\Users\cnajewicz\Documents\ApprendaLinuxCookbook> kitchen init --driver-kitchen-vagrant
C:/Ruby200-x64/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require': cannot load such file -- win32/process (LoadError)
        from C:/Ruby200-x64/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mixlib-shellout-1.3.0/lib/mixlib/shellout/windows.rb:21:in `<top (required)>'
        from C:/Ruby200-x64/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'
        from C:/Ruby200-x64/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mixlib-shellout-1.3.0/lib/mixlib/shellout.rb:33:in `<class:ShellOut>'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mixlib-shellout-1.3.0/lib/mixlib/shellout.rb:26:in `<module:Mixlib>'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mixlib-shellout-1.3.0/lib/mixlib/shellout.rb:24:in `<top (required)>'
        from C:/Ruby200-x64/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'
        from C:/Ruby200-x64/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/test-kitchen-1.2.1/lib/kitchen/shell_out.rb:19:in `<top (required)>'
        from C:/Ruby200-x64/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'
        from C:/Ruby200-x64/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/test-kitchen-1.2.1/lib/kitchen.rb:25:in `<top (required)>'
        from C:/Ruby200-x64/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'
        from C:/Ruby200-x64/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/test-kitchen-1.2.1/lib/kitchen/cli.rb:21:in `<top (required)>'
        from C:/Ruby200-x64/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'
        from C:/Ruby200-x64/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/test-kitchen-1.2.1/bin/kitchen:10:in `<top (required)>'
        from C:/Ruby200-x64/bin/kitchen:23:in `load'
        from C:/Ruby200-x64/bin/kitchen:23:in `<main>'
```

To fix I had to:`gem install win32-process windows-pr` and then things seemed to start working. Just leaving this here in case anyone else runs into it. Cheers.

**Comment by IrishGlugg** [comment]
Thanks for the quick fix!

**Comment by Ramesh7** [comment]
thanks, saved my time.

**Comment by jdmundrawala** [comment]
The issue here is that mixlib-shellout has a windows gem that only matches a 32-bit ruby. I highly suggest you use chefdk. If you are set on vendoring your own ruby, https://github.com/chef/mixlib-shellout/pull/92
