### ISSUE TITLE
During converge on Win 8.1 x64: Creation of file mapping failed with error: 998

### ISSUE THREAD

**Issue by chiefy** [test-kitchen/test-kitchen#448]
Windows 8.1 x64
Vagrant 1.6.2 x64
Test Kitchen 1.2.1
ruby 2.0.0p353 (2013-11-22) [x64-mingw32]

```
E, [2014-05-27T15:41:30.133871 #12524] ERROR -- default1-centos-64: ----------------------
I, [2014-05-27T15:47:54.526942 #12904]  INFO -- default1-centos-64: -----> Converging <default1-centos-64>...
I, [2014-05-27T15:47:54.530816 #12904]  INFO -- default1-centos-64: Preparing files for transfer
I, [2014-05-27T15:47:54.531793 #12904]  INFO -- default1-centos-64: Resolving cookbook dependencies with Berkshelf 3.1.2...
I, [2014-05-27T15:47:57.944508 #12904]  INFO -- default1-centos-64: Removing non-cookbook files before transfer
E, [2014-05-27T15:47:58.059873 #12904] ERROR -- default1-centos-64: Converge failed on instance <default1-centos-64>.
E, [2014-05-27T15:47:58.059873 #12904] ERROR -- default1-centos-64: ------Exception-------
E, [2014-05-27T15:47:58.059873 #12904] ERROR -- default1-centos-64: Class: Kitchen::ActionFailed
E, [2014-05-27T15:47:58.060849 #12904] ERROR -- default1-centos-64: Message: Creation of file mapping failed with error: 998
E, [2014-05-27T15:47:58.060849 #12904] ERROR -- default1-centos-64: ---Nested Exception---
E, [2014-05-27T15:47:58.060849 #12904] ERROR -- default1-centos-64: Class: Net::SSH::Exception
E, [2014-05-27T15:47:58.060849 #12904] ERROR -- default1-centos-64: Message: Creation of file mapping failed with error: 998
E, [2014-05-27T15:47:58.060849 #12904] ERROR -- default1-centos-64: ------Backtrace-------
E, [2014-05-27T15:47:58.060849 #12904] ERROR -- default1-centos-64: C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/test-kitchen-1.2.1/lib/kitchen/driver/ssh_base.rb:112:in `rescue in run_remote'
E, [2014-05-27T15:47:58.060849 #12904] ERROR -- default1-centos-64: C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/test-kitchen-1.2.1/lib/kitchen/driver/ssh_base.rb:108:in `run_remote'
E, [2014-05-27T15:47:58.060849 #12904] ERROR -- default1-centos-64: C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/test-kitchen-1.2.1/lib/kitchen/driver/ssh_base.rb:44:in `block in converge'
E, [2014-05-27T15:47:58.061813 #12904] ERROR -- default1-centos-64: C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/test-kitchen-1.2.1/lib/kitchen/ssh.rb:47:in `initialize'
E, [2014-05-27T15:47:58.061813 #12904] ERROR -- default1-centos-64: C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/test-kitchen-1.2.1/lib/kitchen/driver/ssh_base.rb:43:in `new'
E, [2014-05-27T15:47:58.061813 #12904] ERROR -- default1-centos-64: C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/test-kitchen-1.2.1/lib/kitchen/driver/ssh_base.rb:43:in `converge'
E, [2014-05-27T15:47:58.061813 #12904] ERROR -- default1-centos-64: C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/kitchen-vagrant-0.15.0/lib/kitchen/driver/vagrant.rb:75:in `converge'
E, [2014-05-27T15:47:58.061813 #12904] ERROR -- default1-centos-64: C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:273:in `public_send'
E, [2014-05-27T15:47:58.061813 #12904] ERROR -- default1-centos-64: C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:273:in `block in perform_action'
E, [2014-05-27T15:47:58.061813 #12904] ERROR -- default1-centos-64: C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:308:in `call'
E, [2014-05-27T15:47:58.061813 #12904] ERROR -- default1-centos-64: C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:308:in `synchronize_or_call'
E, [2014-05-27T15:47:58.061813 #12904] ERROR -- default1-centos-64: C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:283:in `block in action'
E, [2014-05-27T15:47:58.061813 #12904] ERROR -- default1-centos-64: C:/Ruby200-x64/lib/ruby/2.0.0/benchmark.rb:281:in `measure'
E, [2014-05-27T15:47:58.061813 #12904] ERROR -- default1-centos-64: C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:282:in `action'
E, [2014-05-27T15:47:58.061813 #12904] ERROR -- default1-centos-64: C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:273:in `perform_action'
E, [2014-05-27T15:47:58.061813 #12904] ERROR -- default1-centos-64: C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:256:in `converge_action'
E, [2014-05-27T15:47:58.061813 #12904] ERROR -- default1-centos-64: C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:246:in `block in transition_to'
E, [2014-05-27T15:47:58.061813 #12904] ERROR -- default1-centos-64: C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:245:in `each'
E, [2014-05-27T15:47:58.061813 #12904] ERROR -- default1-centos-64: C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:245:in `transition_to'
E, [2014-05-27T15:47:58.062791 #12904] ERROR -- default1-centos-64: C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:119:in `converge'
E, [2014-05-27T15:47:58.062791 #12904] ERROR -- default1-centos-64: C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/test-kitchen-1.2.1/lib/kitchen/command.rb:109:in `public_send'
E, [2014-05-27T15:47:58.062791 #12904] ERROR -- default1-centos-64: C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/test-kitchen-1.2.1/lib/kitchen/command.rb:109:in `block (2 levels) in run_action'
E, [2014-05-27T15:47:58.062791 #12904] ERROR -- default1-centos-64: ----------------------
```

Looks like some issue with Net::SSH & Windows? Anyone have a solution?

**Comment by sean-madhavan** [comment]
:+1: I exited pageant and it worked! You saved me tons of time!

**Comment by grisevg** [comment]
> :+1: I exited pageant and it worked! You saved me tons of time!

THANK YOU!
