### ISSUE TITLE
Test kitchen setup fails during busser serverspec plugin post install

### ISSUE THREAD

**Issue by MarkGibbons** [test-kitchen/test-kitchen#461]
Sorry if this is the wrong place to ask for help.  I can't tell where I should report this.  test-kitchen setup and verify just stopped working for me. I suspect it's because of the recent release of rspec 3.0 and 2.99.   Any suggestions?

Thanks,
   Mark

During kitchen setup I get this:

````
$ nord_cron git:(UIS-575) ✗ kitchen setup default-rhel-64
-----> Starting Kitchen (v1.2.2.dev)
-----> Setting up <default-rhel-64>...
Fetching: thor-0.19.0.gem (100%)
Fetching: busser-0.6.2.gem (100%)
       Successfully installed thor-0.19.0
       Successfully installed busser-0.6.2
       2 gems installed
-----> Setting up Busser
       Creating BUSSER_ROOT in /tmp/busser
       Creating busser binstub
       Plugin serverspec installed (version 0.2.6)
-----> Running postinstall for serverspec plugin
       /opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/dependency_installer.rb:153:in `gather_dependencies': Unable to resolve dependencies: rspec-expectations requires diff-lcs (< 2.0, >= 1.1.3) (Gem::DependencyError)
       	from /opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/dependency_installer.rb:267:in `install'
       	from /tmp/busser/gems/gems/busser-0.6.2/lib/busser/rubygems.rb:44:in `install_gem'
       	from /tmp/busser/gems/gems/busser-0.6.2/lib/busser/helpers.rb:57:in `install_gem'
       	from /tmp/busser/gems/gems/busser-serverspec-0.2.6/lib/busser/runner_plugin/serverspec.rb:27:in `block in <class:Serverspec>'
       	from /tmp/busser/gems/gems/thor-0.19.0/lib/thor/command.rb:27:in `run'
       	from /tmp/busser/gems/gems/thor-0.19.0/lib/thor/invocation.rb:126:in `invoke_command'
       	from /tmp/busser/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `block in invoke_all'
       	from /tmp/busser/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `each'
       	from /tmp/busser/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `map'
       	from /tmp/busser/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `invoke_all'
       	from /tmp/busser/gems/gems/thor-0.19.0/lib/thor/group.rb:232:in `dispatch'
       	from /tmp/busser/gems/gems/thor-0.19.0/lib/thor/base.rb:440:in `start'
       	from /tmp/busser/gems/gems/busser-0.6.2/lib/busser/runner_plugin.rb:36:in `block in postinstall'
       	from /tmp/busser/gems/gems/busser-0.6.2/lib/busser/command/plugin_install.rb:80:in `block in run_postinstall'
       	from /tmp/busser/gems/gems/busser-0.6.2/lib/busser/command/plugin_install.rb:100:in `drop_ssl_verify_peer'
       	from /tmp/busser/gems/gems/busser-0.6.2/lib/busser/command/plugin_install.rb:80:in `run_postinstall'
       	from /tmp/busser/gems/gems/busser-0.6.2/lib/busser/command/plugin_install.rb:57:in `install'
       	from /tmp/busser/gems/gems/busser-0.6.2/lib/busser/command/plugin_install.rb:43:in `block (2 levels) in install_all'
       	from /tmp/busser/gems/gems/busser-0.6.2/lib/busser/command/plugin_install.rb:43:in `each'
       	from /tmp/busser/gems/gems/busser-0.6.2/lib/busser/command/plugin_install.rb:43:in `block in install_all'
       	from /tmp/busser/gems/gems/busser-0.6.2/lib/busser/rubygems.rb:71:in `silence_gem_ui'
       	from /tmp/busser/gems/gems/busser-0.6.2/lib/busser/command/plugin_install.rb:42:in `install_all'
       	from /tmp/busser/gems/gems/thor-0.19.0/lib/thor/command.rb:27:in `run'
       	from /tmp/busser/gems/gems/thor-0.19.0/lib/thor/invocation.rb:126:in `invoke_command'
       	from /tmp/busser/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `block in invoke_all'
       	from /tmp/busser/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `each'
       	from /tmp/busser/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `map'
       	from /tmp/busser/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `invoke_all'
       	from /tmp/busser/gems/gems/thor-0.19.0/lib/thor/group.rb:232:in `dispatch'
       	from /tmp/busser/gems/gems/thor-0.19.0/lib/thor/invocation.rb:115:in `invoke'
       	from /tmp/busser/gems/gems/thor-0.19.0/lib/thor.rb:40:in `block in register'
       	from /tmp/busser/gems/gems/thor-0.19.0/lib/thor/command.rb:27:in `run'
       	from /tmp/busser/gems/gems/thor-0.19.0/lib/thor/invocation.rb:126:in `invoke_command'
       	from /tmp/busser/gems/gems/thor-0.19.0/lib/thor.rb:359:in `dispatch'
       	from /tmp/busser/gems/gems/thor-0.19.0/lib/thor/invocation.rb:115:in `invoke'
       	from /tmp/busser/gems/gems/thor-0.19.0/lib/thor.rb:235:in `block in subcommand'
       	from /tmp/busser/gems/gems/thor-0.19.0/lib/thor/command.rb:27:in `run'
       	from /tmp/busser/gems/gems/thor-0.19.0/lib/thor/invocation.rb:126:in `invoke_command'
       	from /tmp/busser/gems/gems/thor-0.19.0/lib/thor.rb:359:in `dispatch'
       	from /tmp/busser/gems/gems/thor-0.19.0/lib/thor/base.rb:440:in `start'
       	from /tmp/busser/gems/gems/busser-0.6.2/bin/busser:8:in `<top (required)>'
       	from /tmp/busser/gems/bin/busser:23:in `load'
       	from /tmp/busser/gems/bin/busser:23:in `<main>'
>>>>>> Setup failed on instance <default-rhel-64>.
>>>>>> Please see .kitchen/logs/default-rhel-64.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sh -c 'BUSSER_ROOT="/tmp/busser" GEM_HOME="/tmp/busser/gems" GEM_PATH="/tmp/busser/gems" GEM_CACHE="/tmp/busser/gems/cache" ; export BUSSER_ROOT GEM_HOME GEM_PATH GEM_CACHE; if ! sudo -E /opt/chef/embedded/bin/gem list busser -i >/dev/null; then sudo -E /opt/chef/embedded/bin/gem install busser --no-rdoc --no-ri; fi; gem_bindir=`/opt/chef/embedded/bin/ruby -rrubygems -e "puts Gem.bindir"`; sudo -E ${gem_bindir}/busser setup; sudo -E /tmp/busser/bin/busser plugin install busser-serverspec']
>>>>>> ----------------------
````

**Comment by MarkGibbons** [comment]
I use chef-dk and no longer have a problem.

Thanks,
  Mark
