### ISSUE TITLE
AWS is not a class (TypeError)

### ISSUE THREAD

**Issue by louisnayegon** [test-kitchen/test-kitchen#552]
```
/home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/fog-core-1.26.0/lib/fog/core/bin/aws.rb:1:in `<top (required)>': AWS is not a class (TypeError)
02-Dec-2014 15:45:21	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/fog-core-1.26.0/lib/fog/core/bin.rb:58:in `require'
02-Dec-2014 15:45:21	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/fog-core-1.26.0/lib/fog/core/bin.rb:58:in `<top (required)>'
02-Dec-2014 15:45:21	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/fog-core-1.26.0/lib/fog/core.rb:30:in `require'
02-Dec-2014 15:45:21	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/fog-core-1.26.0/lib/fog/core.rb:30:in `<top (required)>'
02-Dec-2014 15:45:21	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/fog-1.25.0/lib/fog.rb:7:in `require'
02-Dec-2014 15:45:21	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/fog-1.25.0/lib/fog.rb:7:in `<top (required)>'
02-Dec-2014 15:45:21	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/kitchen-ec2-0.8.0/lib/kitchen/driver/ec2.rb:21:in `require'
02-Dec-2014 15:45:21	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/kitchen-ec2-0.8.0/lib/kitchen/driver/ec2.rb:21:in `<top (required)>'
02-Dec-2014 15:45:21	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.2.1/lib/kitchen/driver.rb:40:in `require'
02-Dec-2014 15:45:21	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.2.1/lib/kitchen/driver.rb:40:in `for_plugin'
02-Dec-2014 15:45:21	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.2.1/lib/kitchen/config.rb:124:in `new_driver'
02-Dec-2014 15:45:21	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.2.1/lib/kitchen/config.rb:130:in `new_instance'
02-Dec-2014 15:45:21	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.2.1/lib/kitchen/config.rb:73:in `block in build_instances'
02-Dec-2014 15:45:21	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.2.1/lib/kitchen/config.rb:72:in `map'
02-Dec-2014 15:45:21	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.2.1/lib/kitchen/config.rb:72:in `with_index'
02-Dec-2014 15:45:21	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.2.1/lib/kitchen/config.rb:72:in `build_instances'
02-Dec-2014 15:45:21	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.2.1/lib/kitchen/config.rb:52:in `instances'
02-Dec-2014 15:45:21	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.2.1/lib/kitchen/command.rb:64:in `get_filtered_instances'
02-Dec-2014 15:45:21	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.2.1/lib/kitchen/command.rb:85:in `parse_subcommand'
02-Dec-2014 15:45:21	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.2.1/lib/kitchen/command/action.rb:37:in `block in call'
02-Dec-2014 15:45:21	        from /home/bamboo.agent/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/benchmark.rb:280:in `measure'
02-Dec-2014 15:45:21	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.2.1/lib/kitchen/command/action.rb:36:in `call'
02-Dec-2014 15:45:21	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.2.1/lib/kitchen/cli.rb:47:in `perform'
02-Dec-2014 15:45:21	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.2.1/lib/kitchen/cli.rb:118:in `block (2 levels) in <class:CLI>'
02-Dec-2014 15:45:21	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
02-Dec-2014 15:45:21	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
02-Dec-2014 15:45:21	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.2.1/lib/kitchen/cli.rb:233:in `invoke_task'
02-Dec-2014 15:45:21	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
02-Dec-2014 15:45:21	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
02-Dec-2014 15:45:21	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.2.1/bin/kitchen:13:in `block in <top (required)>'
02-Dec-2014 15:45:21	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.2.1/lib/kitchen/errors.rb:81:in `with_friendly_errors'
02-Dec-2014 15:45:21	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.2.1/bin/kitchen:13:in `<top (required)>'
02-Dec-2014 15:45:21	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/bin/kitchen:23:in `load'
02-Dec-2014 15:45:21	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/bin/kitchen:23:in `<main>'
02-Dec-2014 15:45:21	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/bin/ruby_executable_hooks:15:in `eval'
02-Dec-2014 15:45:21	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/bin/ruby_executable_hooks:15:in `<main>'
02-Dec-2014 15:45:21	Failing task since return code of [/bin/sh bamboo/converge.sh] was 1 while expected 0
02-Dec-2014 15:45:21	Finished task 'Test Kitchen Converge'
02-Dec-2014 15:45:21	Starting task 'Backup Results' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
02-Dec-2014 15:45:21	
Beginning to execute external process for build 'Copyright Hub - Identity Service Cookbook - test #79 (CT-ISC-JOB1-79)'
 ... running command line: 
/bin/sh bamboo/store_reports.sh
 ... in: /home/bamboo.agent/bamboo-agent-home/xml-data/build-dir/CT-ISC-JOB1/scm
 ... using extra environment variables: 
bamboo_AWS_DEFAULT_REGION=eu-west-1
bamboo_S3_FOLDER=ci
bamboo_S3_BUCKET=copyrighthub-artifacts
bamboo_AWS_VM_SIZE_TRANSFORMATION=c3.large
bamboo_AWS_VM_SIZE_ONBOARDING=c3.large
bamboo_AWS_VM_SIZE_ACCOUNTS=c3.large
bamboo_APIARY_API_KEY=************************************************
bamboo_PASSWORD_AWS_ACCESS_KEY_ID=********
bamboo_AWS_VM_SIZE_REPOSITORY=c3.large
bamboo_AWS_VM_SIZE_IDENTITY=c3.large
bamboo_REVISION=master
bamboo_PASSWORD_AWS_SECRET_ACCESS_KEY=********
bamboo_KITCHEN_YAML=kitchen_test.yml
02-Dec-2014 15:45:21	--------------------------------------------------------------------------------
02-Dec-2014 15:45:21	Checking if all required environmental variables are set...
02-Dec-2014 15:45:21	Env variable: bamboo_DO_NOT_TERMINATE doeasn't exist. This is OK.
02-Dec-2014 15:45:21	--------------------------------------------------------------------------------
02-Dec-2014 15:45:21	All system variables were successfully configured:
02-Dec-2014 15:45:21	AWS_ACCESS_KEY_ID=************************************************
02-Dec-2014 15:45:21	AWS_DEFAULT_REGION=eu-west-1
02-Dec-2014 15:45:21	AWS_SECRET_ACCESS_KEY=****************************************
02-Dec-2014 15:45:21	AWS_VM_SIZE_IDENTITY=c3.large
02-Dec-2014 15:45:21	bamboo_AWS_DEFAULT_REGION=eu-west-1
02-Dec-2014 15:45:21	bamboo_AWS_VM_SIZE_ACCOUNTS=c3.large
02-Dec-2014 15:45:21	bamboo_AWS_VM_SIZE_IDENTITY=c3.large
02-Dec-2014 15:45:21	bamboo_AWS_VM_SIZE_ONBOARDING=c3.large
02-Dec-2014 15:45:21	bamboo_AWS_VM_SIZE_REPOSITORY=c3.large
02-Dec-2014 15:45:21	bamboo_AWS_VM_SIZE_TRANSFORMATION=c3.large
02-Dec-2014 15:45:21	bamboo_KITCHEN_YAML=kitchen_test.yml
02-Dec-2014 15:45:21	bamboo_PASSWORD_AWS_ACCESS_KEY_ID=************************
02-Dec-2014 15:45:21	bamboo_PASSWORD_AWS_SECRET_ACCESS_KEY=****************
02-Dec-2014 15:45:21	bamboo_S3_BUCKET=copyrighthub-artifacts
02-Dec-2014 15:45:21	bamboo_S3_FOLDER=ci
02-Dec-2014 15:45:21	KITCHEN_YAML=kitchen_test.yml
02-Dec-2014 15:45:21	revision=master
02-Dec-2014 15:45:21	S3_BUCKET=copyrighthub-artifacts
02-Dec-2014 15:45:21	S3_FOLDER=ci
02-Dec-2014 15:45:21	--------------------------------------------------------------------------------
02-Dec-2014 15:45:23	[Tue 2014-12-02 15:45:23 +0000] [INFO]: SUT_HOSTNAME=
02-Dec-2014 15:45:23	[Tue 2014-12-02 15:45:23 +0000] [INFO]: mkdir -p reports/unit
02-Dec-2014 15:45:23	[Tue 2014-12-02 15:45:23 +0000] [INFO]: Fetching reports/unit from:
02-Dec-2014 15:45:23	[Tue 2014-12-02 15:45:23 +0000] [INFO]: rsync --progress -rave "ssh -i bamboo-key1.pem -o StrictHostKeyChecking=no" ubuntu@:/srv/-srv/current/tests/unit/reports reports/unit
02-Dec-2014 15:45:23	ssh: Could not resolve hostname : Name or service not known
02-Dec-2014 15:45:23	rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
02-Dec-2014 15:45:23	rsync error: error in rsync protocol data stream (code 12) at io.c(226) [Receiver=3.1.0]
02-Dec-2014 15:45:23	[Tue 2014-12-02 15:45:23 +0000] [INFO]: mkdir -p reports/behave
02-Dec-2014 15:45:23	[Tue 2014-12-02 15:45:23 +0000] [INFO]: Fetching reports/behave from:
02-Dec-2014 15:45:23	[Tue 2014-12-02 15:45:23 +0000] [INFO]: rsync --progress -rave "ssh -i bamboo-key1.pem -o StrictHostKeyChecking=no" ubuntu@:/srv/-srv/current/tests/behave/reports reports/behave
02-Dec-2014 15:45:23	ssh: Could not resolve hostname : Name or service not known
02-Dec-2014 15:45:23	rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
02-Dec-2014 15:45:23	rsync error: error in rsync protocol data stream (code 12) at io.c(226) [Receiver=3.1.0]
02-Dec-2014 15:45:23	[Tue 2014-12-02 15:45:23 +0000] [ERROR]: Couldn't fetch the reports from the: 
02-Dec-2014 15:45:23	Failing task since return code of [/bin/sh bamboo/store_reports.sh] was 1 while expected 0
02-Dec-2014 15:45:23	Finished task 'Backup Results'
02-Dec-2014 15:45:23	Skipping execution of task 'Publish Test Results' as it is disabled
02-Dec-2014 15:45:23	Starting task 'Test Kitchen Destroy' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
02-Dec-2014 15:45:23	
Beginning to execute external process for build 'Copyright Hub - Identity Service Cookbook - test #79 (CT-ISC-JOB1-79)'
 ... running command line: 
/bin/sh bamboo/destroy.sh
 ... in: /home/bamboo.agent/bamboo-agent-home/xml-data/build-dir/CT-ISC-JOB1/scm
 ... using extra environment variables: 
bamboo_AWS_DEFAULT_REGION=eu-west-1
bamboo_S3_FOLDER=ci
bamboo_S3_BUCKET=copyrighthub-artifacts
bamboo_AWS_VM_SIZE_TRANSFORMATION=c3.large
bamboo_AWS_VM_SIZE_ONBOARDING=c3.large
bamboo_AWS_VM_SIZE_ACCOUNTS=c3.large
bamboo_APIARY_API_KEY=************************
bamboo_PASSWORD_AWS_ACCESS_KEY_ID=********
bamboo_AWS_VM_SIZE_REPOSITORY=c3.large
bamboo_AWS_VM_SIZE_IDENTITY=c3.large
bamboo_REVISION=master
bamboo_PASSWORD_AWS_SECRET_ACCESS_KEY=********
bamboo_KITCHEN_YAML=kitchen_test.yml
02-Dec-2014 15:45:23	--------------------------------------------------------------------------------
02-Dec-2014 15:45:23	Checking if all required environmental variables are set...
02-Dec-2014 15:45:23	Env variable: bamboo_DO_NOT_TERMINATE doeasn't exist. This is OK.
02-Dec-2014 15:45:23	--------------------------------------------------------------------------------
02-Dec-2014 15:45:23	All system variables were successfully configured:
02-Dec-2014 15:45:23	AWS_ACCESS_KEY_ID=********************************
02-Dec-2014 15:45:23	AWS_DEFAULT_REGION=eu-west-1
02-Dec-2014 15:45:23	AWS_SECRET_ACCESS_KEY=********************************
02-Dec-2014 15:45:23	AWS_VM_SIZE_IDENTITY=c3.large
02-Dec-2014 15:45:23	bamboo_AWS_DEFAULT_REGION=eu-west-1
02-Dec-2014 15:45:23	bamboo_AWS_VM_SIZE_ACCOUNTS=c3.large
02-Dec-2014 15:45:23	bamboo_AWS_VM_SIZE_IDENTITY=c3.large
02-Dec-2014 15:45:23	bamboo_AWS_VM_SIZE_ONBOARDING=c3.large
02-Dec-2014 15:45:23	bamboo_AWS_VM_SIZE_REPOSITORY=c3.large
02-Dec-2014 15:45:23	bamboo_AWS_VM_SIZE_TRANSFORMATION=c3.large
02-Dec-2014 15:45:23	bamboo_KITCHEN_YAML=kitchen_test.yml
02-Dec-2014 15:45:23	bamboo_PASSWORD_AWS_ACCESS_KEY_ID=****************
02-Dec-2014 15:45:23	bamboo_PASSWORD_AWS_SECRET_ACCESS_KEY=************************
02-Dec-2014 15:45:23	bamboo_S3_BUCKET=copyrighthub-artifacts
02-Dec-2014 15:45:23	bamboo_S3_FOLDER=ci
02-Dec-2014 15:45:23	KITCHEN_YAML=kitchen_test.yml
02-Dec-2014 15:45:23	revision=master
02-Dec-2014 15:45:23	S3_BUCKET=copyrighthub-artifacts
02-Dec-2014 15:45:23	S3_FOLDER=ci
02-Dec-2014 15:45:23	--------------------------------------------------------------------------------
02-Dec-2014 15:45:24	-----> Starting Kitchen (v1.2.1)
02-Dec-2014 15:45:24	/home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/fog-core-1.26.0/lib/fog/core/bin/aws.rb:1:in `<top (required)>': AWS is not a class (TypeError)
02-Dec-2014 15:45:24	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/fog-core-1.26.0/lib/fog/core/bin.rb:58:in `require'
02-Dec-2014 15:45:24	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/fog-core-1.26.0/lib/fog/core/bin.rb:58:in `<top (required)>'
02-Dec-2014 15:45:24	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/fog-core-1.26.0/lib/fog/core.rb:30:in `require'
02-Dec-2014 15:45:24	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/fog-core-1.26.0/lib/fog/core.rb:30:in `<top (required)>'
02-Dec-2014 15:45:24	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/fog-1.25.0/lib/fog.rb:7:in `require'
02-Dec-2014 15:45:24	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/fog-1.25.0/lib/fog.rb:7:in `<top (required)>'
02-Dec-2014 15:45:24	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/kitchen-ec2-0.8.0/lib/kitchen/driver/ec2.rb:21:in `require'
02-Dec-2014 15:45:24	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/kitchen-ec2-0.8.0/lib/kitchen/driver/ec2.rb:21:in `<top (required)>'
02-Dec-2014 15:45:24	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.2.1/lib/kitchen/driver.rb:40:in `require'
02-Dec-2014 15:45:24	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.2.1/lib/kitchen/driver.rb:40:in `for_plugin'
02-Dec-2014 15:45:24	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.2.1/lib/kitchen/config.rb:124:in `new_driver'
02-Dec-2014 15:45:24	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.2.1/lib/kitchen/config.rb:130:in `new_instance'
02-Dec-2014 15:45:24	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.2.1/lib/kitchen/config.rb:73:in `block in build_instances'
02-Dec-2014 15:45:24	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.2.1/lib/kitchen/config.rb:72:in `map'
02-Dec-2014 15:45:24	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.2.1/lib/kitchen/config.rb:72:in `with_index'
02-Dec-2014 15:45:24	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.2.1/lib/kitchen/config.rb:72:in `build_instances'
02-Dec-2014 15:45:24	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.2.1/lib/kitchen/config.rb:52:in `instances'
02-Dec-2014 15:45:24	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.2.1/lib/kitchen/command.rb:64:in `get_filtered_instances'
02-Dec-2014 15:45:24	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.2.1/lib/kitchen/command.rb:85:in `parse_subcommand'
02-Dec-2014 15:45:24	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.2.1/lib/kitchen/command/action.rb:37:in `block in call'
02-Dec-2014 15:45:24	        from /home/bamboo.agent/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/benchmark.rb:280:in `measure'
02-Dec-2014 15:45:24	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.2.1/lib/kitchen/command/action.rb:36:in `call'
02-Dec-2014 15:45:24	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.2.1/lib/kitchen/cli.rb:47:in `perform'
02-Dec-2014 15:45:24	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.2.1/lib/kitchen/cli.rb:118:in `block (2 levels) in <class:CLI>'
02-Dec-2014 15:45:24	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
02-Dec-2014 15:45:24	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
02-Dec-2014 15:45:24	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.2.1/lib/kitchen/cli.rb:233:in `invoke_task'
02-Dec-2014 15:45:24	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
02-Dec-2014 15:45:24	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
02-Dec-2014 15:45:24	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.2.1/bin/kitchen:13:in `block in <top (required)>'
02-Dec-2014 15:45:24	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.2.1/lib/kitchen/errors.rb:81:in `with_friendly_errors'
02-Dec-2014 15:45:24	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.2.1/bin/kitchen:13:in `<top (required)>'
02-Dec-2014 15:45:24	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/bin/kitchen:23:in `load'
02-Dec-2014 15:45:24	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/bin/kitchen:23:in `<main>'
02-Dec-2014 15:45:24	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/bin/ruby_executable_hooks:15:in `eval'
02-Dec-2014 15:45:24	        from /home/bamboo.agent/.rvm/gems/ruby-1.9.3-p547/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by cheeseplus** [comment]
Given the age and this issue not being specific to kitchen-ec2 which had moved away from fog I'm closing.
