### ISSUE TITLE
kitchen verify fails on opscode centos-6.6 vagrant box

### ISSUE THREAD

**Issue by veetow** [test-kitchen/test-kitchen#664]
The `Installing Busser` step isn't creating the `/tmp/verifier` directory structure that's needed:

```
$ kitchen verify
-----> Starting Kitchen (v1.4.0.beta.2)
-----> Setting up <default-centos-66>...
       Finished setting up <default-centos-66> (0m0.00s).
-----> Verifying <default-centos-66>...
       Preparing files for transfer
-----> Installing Busser (busser)
Fetching: thor-0.19.0.gem (100%)
       ERROR:  While executing gem ... (Errno::EACCES)
           Permission denied - /tmp/verifier
       sh: line 23: /tmp/verifier/gems/bin/busser: No such file or directory
       Installing Busser plugins: busser-serverspec
       sudo: /tmp/verifier/bin/busser: command not found
>>>>>> Verify failed on instance <default-centos-66>.
>>>>>> Please see .kitchen/logs/default-centos-66.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sh -c '

BUSSER_ROOT="/tmp/verifier"; export BUSSER_ROOT
GEM_HOME="/tmp/verifier/gems"; export GEM_HOME
GEM_PATH="/tmp/verifier/gems"; export GEM_PATH
GEM_CACHE="/tmp/verifier/gems/cache"; export GEM_CACHE
ruby="/opt/chef/embedded/bin/ruby"
gem="/opt/chef/embedded/bin/gem"
version="busser"
gem_install_args="busser --no-rdoc --no-ri"
busser="sudo -E /tmp/verifier/bin/busser"
plugins="busser-serverspec"

$gem list busser -i 2>&1 >/dev/null
if test $? -ne 0; then
  echo "-----> Installing Busser ($version)"
  $gem install $gem_install_args
else
  echo "-----> Busser installation detected ($version)"
fi

if test ! -f "$BUSSER_ROOT/bin/busser"; then
  gem_bindir=`$ruby -rrubygems -e "puts Gem.bindir"`
  $gem_bindir/busser setup
fi

echo "       Installing Busser plugins: $plugins"
$busser plugin install $plugins
']
>>>>>> ----------------------
```

Here are the logs:

```
I, [2015-03-27T14:44:33.826444 #47186]  INFO -- default-centos-66: Finished converging <default-centos-66> (7m48.09s).
I, [2015-03-27T14:44:33.826542 #47186]  INFO -- default-centos-66: -----> Setting up <default-centos-66>...
I, [2015-03-27T14:44:33.833447 #47186]  INFO -- default-centos-66: Finished setting up <default-centos-66> (0m0.00s).
I, [2015-03-27T14:44:33.833531 #47186]  INFO -- default-centos-66: -----> Verifying <default-centos-66>...
I, [2015-03-27T14:44:33.834545 #47186]  INFO -- default-centos-66: Preparing files for transfer
I, [2015-03-27T14:44:33.963444 #47186]  INFO -- default-centos-66: -----> Installing Busser (busser)
I, [2015-03-27T14:44:48.662571 #47186]  INFO -- default-centos-66: Fetching: thor-0.19.0.gem
Fetching: thor-0.19.0.gem (  8%)
Fetching: thor-0.19.0.gem (  9%)
Fetching: thor-0.19.0.gem ( 17%)
Fetching: thor-0.19.0.gem ( 18%)
Fetching: thor-0.19.0.gem ( 26%)
Fetching: thor-0.19.0.gem ( 27%)
Fetching: thor-0.19.0.gem ( 35%)
Fetching: thor-0.19.0.gem ( 36%)
Fetching: thor-0.19.0.gem ( 43%)
Fetching: thor-0.19.0.gem ( 45%)
Fetching: thor-0.19.0.gem ( 52%)
Fetching: thor-0.19.0.gem ( 54%)
Fetching: thor-0.19.0.gem ( 61%)
Fetching: thor-0.19.0.gem ( 63%)
Fetching: thor-0.19.0.gem ( 70%)
Fetching: thor-0.19.0.gem ( 72%)
Fetching: thor-0.19.0.gem ( 78%)
Fetching: thor-0.19.0.gem ( 81%)
Fetching: thor-0.19.0.gem ( 87%)
Fetching: thor-0.19.0.gem ( 90%)
Fetching: thor-0.19.0.gem ( 96%)
Fetching: thor-0.19.0.gem ( 99%)
Fetching: thor-0.19.0.gem (100%)
Fetching: thor-0.19.0.gem (100%)
I, [2015-03-27T14:44:48.675858 #47186]  INFO -- default-centos-66: ERROR:  While executing gem ... (Errno::EACCES)
I, [2015-03-27T14:44:48.675913 #47186]  INFO -- default-centos-66:     Permission denied - /tmp/verifier
I, [2015-03-27T14:44:48.722640 #47186]  INFO -- default-centos-66: sh: line 23: /tmp/verifier/gems/bin/busser: No such file or directory
I, [2015-03-27T14:44:48.722713 #47186]  INFO -- default-centos-66: Installing Busser plugins: busser-serverspec
I, [2015-03-27T14:44:48.743162 #47186]  INFO -- default-centos-66: sudo: /tmp/verifier/bin/busser: command not found
E, [2015-03-27T14:44:48.743895 #47186] ERROR -- default-centos-66: Verify failed on instance <default-centos-66>.
E, [2015-03-27T14:44:48.743981 #47186] ERROR -- default-centos-66: ------Exception-------
E, [2015-03-27T14:44:48.743998 #47186] ERROR -- default-centos-66: Class: Kitchen::ActionFailed
E, [2015-03-27T14:44:48.744008 #47186] ERROR -- default-centos-66: Message: SSH exited (1) for command: [sh -c '

BUSSER_ROOT="/tmp/verifier"; export BUSSER_ROOT
GEM_HOME="/tmp/verifier/gems"; export GEM_HOME
GEM_PATH="/tmp/verifier/gems"; export GEM_PATH
GEM_CACHE="/tmp/verifier/gems/cache"; export GEM_CACHE
ruby="/opt/chef/embedded/bin/ruby"
gem="/opt/chef/embedded/bin/gem"
version="busser"
gem_install_args="busser --no-rdoc --no-ri"
busser="sudo -E /tmp/verifier/bin/busser"
plugins="busser-serverspec"

$gem list busser -i 2>&1 >/dev/null
if test $? -ne 0; then
  echo "-----> Installing Busser ($version)"
  $gem install $gem_install_args
else
  echo "-----> Busser installation detected ($version)"
fi

if test ! -f "$BUSSER_ROOT/bin/busser"; then
  gem_bindir=`$ruby -rrubygems -e "puts Gem.bindir"`
  $gem_bindir/busser setup
fi

echo "       Installing Busser plugins: $plugins"
$busser plugin install $plugins
']
E, [2015-03-27T14:44:48.744039 #47186] ERROR -- default-centos-66: ---Nested Exception---
E, [2015-03-27T14:44:48.744048 #47186] ERROR -- default-centos-66: Class: Kitchen::Transport::SshFailed
E, [2015-03-27T14:44:48.744057 #47186] ERROR -- default-centos-66: Message: SSH exited (1) for command: [sh -c '

BUSSER_ROOT="/tmp/verifier"; export BUSSER_ROOT
GEM_HOME="/tmp/verifier/gems"; export GEM_HOME
GEM_PATH="/tmp/verifier/gems"; export GEM_PATH
GEM_CACHE="/tmp/verifier/gems/cache"; export GEM_CACHE
ruby="/opt/chef/embedded/bin/ruby"
gem="/opt/chef/embedded/bin/gem"
version="busser"
gem_install_args="busser --no-rdoc --no-ri"
busser="sudo -E /tmp/verifier/bin/busser"
plugins="busser-serverspec"

$gem list busser -i 2>&1 >/dev/null
if test $? -ne 0; then
  echo "-----> Installing Busser ($version)"
  $gem install $gem_install_args
else
  echo "-----> Busser installation detected ($version)"
fi

if test ! -f "$BUSSER_ROOT/bin/busser"; then
  gem_bindir=`$ruby -rrubygems -e "puts Gem.bindir"`
  $gem_bindir/busser setup
fi

echo "       Installing Busser plugins: $plugins"
$busser plugin install $plugins
']
E, [2015-03-27T14:44:48.744069 #47186] ERROR -- default-centos-66: ------Backtrace-------
E, [2015-03-27T14:44:48.744078 #47186] ERROR -- default-centos-66: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/verifier/base.rb:75:in `rescue in call'
E, [2015-03-27T14:44:48.744086 #47186] ERROR -- default-centos-66: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/verifier/base.rb:78:in `call'
E, [2015-03-27T14:44:48.744106 #47186] ERROR -- default-centos-66: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:381:in `block in verify_action'
E, [2015-03-27T14:44:48.744117 #47186] ERROR -- default-centos-66: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:471:in `call'
E, [2015-03-27T14:44:48.744128 #47186] ERROR -- default-centos-66: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:471:in `synchronize_or_call'
E, [2015-03-27T14:44:48.744137 #47186] ERROR -- default-centos-66: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:436:in `block in action'
E, [2015-03-27T14:44:48.744146 #47186] ERROR -- default-centos-66: /opt/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
E, [2015-03-27T14:44:48.744154 #47186] ERROR -- default-centos-66: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:435:in `action'
E, [2015-03-27T14:44:48.744163 #47186] ERROR -- default-centos-66: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:377:in `verify_action'
E, [2015-03-27T14:44:48.744171 #47186] ERROR -- default-centos-66: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:324:in `block in transition_to'
E, [2015-03-27T14:44:48.744180 #47186] ERROR -- default-centos-66: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:323:in `each'
E, [2015-03-27T14:44:48.744189 #47186] ERROR -- default-centos-66: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:323:in `transition_to'
E, [2015-03-27T14:44:48.744212 #47186] ERROR -- default-centos-66: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:160:in `verify'
E, [2015-03-27T14:44:48.744221 #47186] ERROR -- default-centos-66: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/command.rb:176:in `public_send'
E, [2015-03-27T14:44:48.744230 #47186] ERROR -- default-centos-66: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
E, [2015-03-27T14:44:48.744238 #47186] ERROR -- default-centos-66: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
E, [2015-03-27T14:44:48.744249 #47186] ERROR -- default-centos-66: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
E, [2015-03-27T14:44:48.744258 #47186] ERROR -- default-centos-66: ----------------------
```

Here's my environment:

```
$ uname -a
Darwin XXXXXXXX 13.4.0 Darwin Kernel Version 13.4.0: Sun Aug 17 19:50:11 PDT 2014; root:xnu-2422.115.4~1/RELEASE_X86_64 x86_64
$ chef -v
Chef Development Kit Version: 0.3.6
$ kitchen -v
Test Kitchen version 1.4.0.beta.2
$ vagrant -v
Vagrant 1.7.2
$ gem list | grep -E 'kitchen|vagrant'
chef-provisioning-vagrant (0.8.1)
kitchen-vagrant (0.17.0.beta.4, 0.16.0, 0.15.0)
test-kitchen (1.4.0.beta.2, 1.3.1)
vagrant-berkshelf (4.0.2)
vagrant-omnibus (1.4.1)
vagrant-windows (1.6.0)
```

**Comment by lloydde** [comment]
@veetow did you confirm that you get the same symptom on the non-beta version, Test Kitchen version 1.3.1?

**Comment by veetow** [comment]
I did not have the same symptom this morning prior to upgrading to the beta version.

**Comment by lloydde** [comment]
@veetow did you delete the .kitchen folder and run 'kitchen init' after changing versions?

I'm brand new to test-kitchen, but haven't yet been able to reproduce the symptom you described. It's above my head, but I did notice this release has a significant change to interacting with Busser,  https://github.com/test-kitchen/test-kitchen/blob/master/CHANGELOG.md

~~~
-----> Creating <default-centos-66>...
       Bringing machine 'default' up with 'virtualbox' provider...
       ==> default: Importing base box 'opscode-centos-6.6'...
...
...
...
-----> Setting up <default-centos-66>...
$$$$$$ Running legacy setup for 'Vagrant' Driver
-----> Installing Busser (busser)
Fetching: thor-0.19.0.gem (100%)
       Successfully installed thor-0.19.0
Fetching: busser-0.7.0.gem (100%)
       Successfully installed busser-0.7.0
       2 gems installed
-----> Setting up Busser
       Creating BUSSER_ROOT in /tmp/verifier
       Creating busser binstub
       Installing Busser plugins: busser-bats
       Plugin bats installed (version 0.3.0)
-----> Running postinstall for bats plugin
       Installed Bats to /tmp/verifier/vendor/bats/bin/bats
       Finished setting up <default-centos-66> (0m15.21s).
-----> Verifying <default-centos-66>...
$$$$$$ Running legacy verify for 'Vagrant' Driver
       Preparing files for transfer
       Suite path directory /tmp/verifier/suites does not exist, skipping.
       Transferring files to <default-centos-66>
-----> Running bats test suite
 ✓ git binary is found in PATH
       
       1 test, 0 failures
       Finished verifying <default-centos-66> (0m2.08s).
-----> Kitchen is finished. (6m54.10s)
~~~

**Comment by veetow** [comment]
Yes, I did delete the .kitchen folder. :(

**Comment by veetow** [comment]
This was an issue with my environment, not with test-kitchen.  There was an errant recipe in the `run_list` that mistakenly set permissions on `/tmp` to `0755`.

**Comment by devilldog** [comment]
was it a recipe from supermarket ?

**Comment by veetow** [comment]
No, it was not a community cookbook.

**Comment by xmik** [comment]
If it helps anyone, I also ran into this: there was no `/tmp/verifier/bin/busser` after running `kitchen verify`. 

The reason was my environment: I had a `.gemrc` in $HOME of a linux user I provisioned with (it was root user, because I ran in Docker). I had there set:
```
gem:
- --bindir /usr/local/bin
```
and thus busser executable was in `/usr/local/bin`.
