### ISSUE TITLE
server.rb:283:in `block in start_background': undefined method `start' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by vinyar** [test-kitchen/test-kitchen#710]
Running test-kitchen with -c switch throws the error below.

```ruby
 kitchen create -c
-----> Starting Kitchen (v1.4.0)
-----> Creating <chef-server-be01-ubuntu-1204>...
-----> Creating <chef-server-fe01-ubuntu-1204>...
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-zero-4.2.1/lib/chef_zero/server.rb:283:in `block in start_background': undefined method `start' for nil:NilClass (NoMethodError)
```
 $ chef -v
Chef Development Kit Version: 0.5.1
chef-client version: 12.3.0
berks version: 3.2.3
kitchen version: 1.4.0

Please let me know if this is a new bug, I'll post additional logs/etc.

**Comment by tyler-ball** [comment]
@vinyar What driver are you using?  I was not able to reproduce this with a vagrant driver.  Also include what is in the .kitchen/ logs

**Comment by vinyar** [comment]
Using vsphere driver. I'll provide logs in a little bit, cant take down the boxes atm.

**Comment by vinyar** [comment]
nothing useful in the logs.
One thing I found is that it does not fail consistently. I'd say every other time.

```ruby
vagrant /chef-repo/cookbooks/chef_server_tiered/.kitchen/logs $ cat chef-server-analytics-ubuntu-1204.log
I, [2015-05-08T19:32:50.412557 #15952]  INFO -- chef-server-analytics-ubuntu-1204: -----> Creating <chef-server-analytics-ubuntu-1204>...
vagrant /chef-repo/cookbooks/chef_server_tiered/.kitchen/logs $ cat chef-server-be01-ubuntu-1204.log
I, [2015-05-08T19:32:50.411694 #15952]  INFO -- chef-server-be01-ubuntu-1204: -----> Creating <chef-server-be01-ubuntu-1204>...
vagrant /chef-repo/cookbooks/chef_server_tiered/.kitchen/logs $ cat chef-server-fe01-ubuntu-1204.log
I, [2015-05-08T19:32:50.409865 #15952]  INFO -- chef-server-fe01-ubuntu-1204: -----> Creating <chef-server-fe01-ubuntu-1204>...
vagrant /chef-repo/cookbooks/chef_server_tiered/.kitchen/logs $ cat kitchen.log
I, [2015-05-08T19:32:41.741695 #15952]  INFO -- Kitchen: -----> Starting Kitchen (v1.4.0)
I, [2015-05-08T19:32:50.409165 #15952]  INFO -- Kitchen: -----> Creating <chef-server-fe01-ubuntu-1204>...
I, [2015-05-08T19:32:50.409692 #15952]  INFO -- Kitchen: -----> Creating <chef-server-be01-ubuntu-1204>...
I, [2015-05-08T19:32:50.412119 #15952]  INFO -- Kitchen: -----> Creating <chef-server-analytics-ubuntu-1204>...
```

Debug mode:
```ruby
$ kitchen create -c -l debug
-----> Starting Kitchen (v1.4.0)
D      Berksfile found at /chef-repo/cookbooks/chef_server_tiered/Berksfile, loading Berkshelf
D      Berkshelf 3.2.3 previously loaded
D      Berksfile found at /chef-repo/cookbooks/chef_server_tiered/Berksfile, loading Berkshelf
D      Berkshelf 3.2.3 previously loaded
D      Berksfile found at /chef-repo/cookbooks/chef_server_tiered/Berksfile, loading Berkshelf
D      Berkshelf 3.2.3 previously loaded
-----> Creating <chef-server-be01-ubuntu-1204>...
-----> Creating <chef-server-fe01-ubuntu-1204>...
-----> Creating <chef-server-analytics-ubuntu-1204>...
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-zero-4.2.1/lib/chef_zero/server.rb:283:in `block in start_background': undefined method `start' for nil:NilClass (NoMethodError)
```

**Comment by vinyar** [comment]
seems this is related

vagrant /chef-repo/cookbooks/chef_server_tiered $ kitchen create -c -l debug
```ruby
-----> Starting Kitchen (v1.4.0)
D      Berksfile found at /chef-repo/cookbooks/chef_server_tiered/Berksfile, loading Berkshelf
D      Berkshelf 3.2.3 previously loaded
D      Berksfile found at /chef-repo/cookbooks/chef_server_tiered/Berksfile, loading Berkshelf
D      Berkshelf 3.2.3 previously loaded
D      Berksfile found at /chef-repo/cookbooks/chef_server_tiered/Berksfile, loading Berkshelf
D      Berkshelf 3.2.3 previously loaded
-----> Creating <chef-server-be01-ubuntu-1204>...
-----> Creating <chef-server-fe01-ubuntu-1204>...
-----> Creating <chef-server-analytics-ubuntu-1204>...
creating machine kitchen-4e5a20bb on vsphere://<vsphere_ip>/sdk?use_ssl=true&insecure=true
  use_linked_clone: true
  datacenter: "QA1"
  template_name: "UBUNTUDEVOPS1264"
  vm_folder: "DLAB"
  num_cpus: 2
  network_name: ["<vsphere_vlan>"]
  memory_mb: 4096
  resource_pool: "CLSTR02/DLAB"
  ssh: {:user=>"root", :paranoid=>false, :password=>"<ssh_pass>", :port=>22}
  convergence_options: nil
  customization_spec: {:domain=>"local", :ipsettings=>{:ip=>"<server_1>", :subnetMask=>"255.255.255.0", :gateway=>["<gateway_ip>"], :dnsServerList=>["<dns1_ip>", "<dns2_ip>"]}}
  tags: {"Name"=>"kitchen-4e5a20bb", "BootstrapId"=>"chefzero://localhost:8889/nodes/kitchen-4e5a20bb", "BootstrapHost"=>"chef-workstation", "BootstrapUser"=>"vagrant"}
  name: "kitchen-4e5a20bb"
establishing connection to <vsphere_ip>
creating machine kitchen-62403a99 on vsphere://<vsphere_ip>/sdk?use_ssl=true&insecure=true
  use_linked_clone: true
  datacenter: "QA1"
  template_name: "UBUNTUDEVOPS1264"
  vm_folder: "DLAB"
  num_cpus: 2
  network_name: ["<vsphere_vlan>"]
  memory_mb: 4096
  resource_pool: "CLSTR02/DLAB"
  ssh: {:user=>"root", :paranoid=>false, :password=>"<ssh_pass>", :port=>22}
  convergence_options: nil
  customization_spec: {:domain=>"local", :ipsettings=>{:ip=>"<server_3>", :subnetMask=>"255.255.255.0", :gateway=>["<gateway_ip>"], :dnsServerList=>["<dns1_ip>", "<dns2_ip>"]}}
  tags: {"Name"=>"kitchen-62403a99", "BootstrapId"=>"chefzero://localhost:8889/nodes/kitchen-62403a99", "BootstrapHost"=>"chef-workstation", "BootstrapUser"=>"vagrant"}
  name: "kitchen-62403a99"
establishing connection to <vsphere_ip>
customizing kitchen-4e5a20bb with static IP <server_1>
customizing kitchen-62403a99 with static IP <server_3>
network: <vsphere_vlan> is a Network}
changing template nic for <vsphere_vlan>
network: <vsphere_vlan> is a Network}
changing template nic for <vsphere_vlan>
machine kitchen-4e5a20bb created as 50064cfa-fd49-6941-839f-9e902de5fd8b on vsphere://<vsphere_ip>/sdk?use_ssl=true&insecure=true
machine kitchen-62403a99 created as 50069845-ba11-1083-f9cd-af0d2d4f25dd on vsphere://<vsphere_ip>/sdk?use_ssl=true&insecure=true
Power on VM [DLAB/kitchen-4e5a20bb]
waiting for kitchen-4e5a20bb (50064cfa-fd49-6941-839f-9e902de5fd8b on vsphere://<vsphere_ip>/sdk?use_ssl=true&insecure=true) to be ready ...
.Power on VM [DLAB/kitchen-62403a99]
waiting for kitchen-62403a99 (50069845-ba11-1083-f9cd-af0d2d4f25dd on vsphere://<vsphere_ip>/sdk?use_ssl=true&insecure=true) to be ready ...
..........kitchen-62403a99 is now ready
bash: warning: setlocale: LC_ALL: cannot change locale (en_US)
/root
waiting up to 90 seconds for customizations to complete and find <server_3>
IP addresses on kitchen-62403a99 are []
.IP addresses on kitchen-62403a99 are []
.IP addresses on kitchen-62403a99 are []
.IP addresses on kitchen-62403a99 are []
.IP addresses on kitchen-62403a99 are []
.IP addresses on kitchen-62403a99 are []
.IP addresses on kitchen-62403a99 are []
.IP addresses on kitchen-62403a99 are []
.IP addresses on kitchen-62403a99 are []
kitchen-4e5a20bb is now ready
bash: warning: setlocale: LC_ALL: cannot change locale (en_US)
/root
waiting up to 90 seconds for customizations to complete and find <server_1>
IP addresses on kitchen-4e5a20bb are []
IP addresses on kitchen-62403a99 are []
IP addresses on kitchen-4e5a20bb are []
IP addresses on kitchen-62403a99 are []
IP addresses on kitchen-4e5a20bb are []
IP addresses on kitchen-62403a99 are []
IP addresses on kitchen-4e5a20bb are []
IP address obtained: <server_3>
bash: warning: setlocale: LC_ALL: cannot change locale (en_US)
/root
IP addresses on kitchen-4e5a20bb are []
IP address obtained: <server_1>
bash: warning: setlocale: LC_ALL: cannot change locale (en_US)
/root
network: <vsphere_vlan> is a Network}
changing template nic for <vsphere_vlan>
bash: warning: setlocale: LC_ALL: cannot change locale (en_US)
network: <vsphere_vlan> is a Network}
changing template nic for <vsphere_vlan>
bash: warning: setlocale: LC_ALL: cannot change locale (en_US)
;; connection timed out; no servers could be reached
bash: warning: setlocale: LC_ALL: cannot change locale (en_US)
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US)
Generating locales...
  en_US.ISO-8859-1... /usr/sbin/locale-gen: line 177: warning: setlocale: LC_ALL: cannot change locale (en_US)
done
Generation complete.
	Ubuntu
12.04
 * Running /etc/init.d/networking restart is deprecated because it may not enable again some interfaces
 * Reconfiguring network interfaces...                                          ssh stop/waiting
ssh start/running, process 1818
                                                                         [ OK ]
;; connection timed out; no servers could be reached
bash: warning: setlocale: LC_ALL: cannot change locale (en_US)
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US)
Generating locales...
  en_US.ISO-8859-1... /usr/sbin/locale-gen: line 177: warning: setlocale: LC_ALL: cannot change locale (en_US)
done
Generation complete.
	Ubuntu
12.04
 * Running /etc/init.d/networking restart is deprecated because it may not enable again some interfaces
 * Reconfiguring network interfaces...                                          ssh stop/waiting
ssh start/running, process 2065
                                                                         [ OK ]
       Finished creating <chef-server-fe01-ubuntu-1204> (10m43.16s).
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #create action: [undefined method `listen' for nil:NilClass]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

Log file:

```ruby
I, [2015-05-08T19:38:25.131479 #16095]  INFO -- Kitchen: -----> Starting Kitchen (v1.4.0)
I, [2015-05-08T19:38:33.751524 #16095]  INFO -- Kitchen: -----> Creating <chef-server-be01-ubuntu-1204>...
I, [2015-05-08T19:38:33.752213 #16095]  INFO -- Kitchen: -----> Creating <chef-server-fe01-ubuntu-1204>...
I, [2015-05-08T19:38:33.756073 #16095]  INFO -- Kitchen: -----> Creating <chef-server-analytics-ubuntu-1204>...
D, [2015-05-08T19:49:16.926307 #16095] DEBUG -- Kitchen: ------Exception-------
D, [2015-05-08T19:49:16.926775 #16095] DEBUG -- Kitchen: Class: Kitchen::ActionFailed
D, [2015-05-08T19:49:16.927062 #16095] DEBUG -- Kitchen: Message: Failed to complete #create action: [undefined method `listen' for nil:NilClass]
D, [2015-05-08T19:49:16.927379 #16095] DEBUG -- Kitchen: ---Nested Exception---
D, [2015-05-08T19:49:16.927861 #16095] DEBUG -- Kitchen: Class: NoMethodError
D, [2015-05-08T19:49:16.928108 #16095] DEBUG -- Kitchen: Message: undefined method `listen' for nil:NilClass
D, [2015-05-08T19:49:16.928503 #16095] DEBUG -- Kitchen: ------Backtrace-------
D, [2015-05-08T19:49:16.929008 #16095] DEBUG -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-zero-4.2.1/lib/chef_zero/server.rb:264:in `block in start_background'
D, [2015-05-08T19:49:16.929220 #16095] DEBUG -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-zero-4.2.1/lib/chef_zero/server.rb:262:in `upto'
D, [2015-05-08T19:49:16.929603 #16095] DEBUG -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-zero-4.2.1/lib/chef_zero/server.rb:262:in `each'
D, [2015-05-08T19:49:16.929781 #16095] DEBUG -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-zero-4.2.1/lib/chef_zero/server.rb:262:in `start_background'
D, [2015-05-08T19:49:16.929997 #16095] DEBUG -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.3.0/lib/chef/local_mode.rb:69:in `setup_server_connectivity'
D, [2015-05-08T19:49:16.930205 #16095] DEBUG -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.3.0/lib/chef/local_mode.rb:37:in `with_server_connectivity'
D, [2015-05-08T19:49:16.930561 #16095] DEBUG -- Kitchen: /home/vagrant/.chefdk/gem/ruby/2.1.0/gems/cheffish-1.2/lib/cheffish.rb:65:in `honor_local_mode'
D, [2015-05-08T19:49:16.930750 #16095] DEBUG -- Kitchen: /home/vagrant/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-vsphere-0.4.2/lib/kitchen/driver/vsphere.rb:73:in `with_provisioning_driver'
D, [2015-05-08T19:49:16.930910 #16095] DEBUG -- Kitchen: /home/vagrant/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-vsphere-0.4.2/lib/kitchen/driver/vsphere.rb:32:in `create'
D, [2015-05-08T19:49:16.931288 #16095] DEBUG -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:424:in `public_send'
D, [2015-05-08T19:49:16.931490 #16095] DEBUG -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:424:in `block in perform_action'
D, [2015-05-08T19:49:16.932058 #16095] DEBUG -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:488:in `call'
D, [2015-05-08T19:49:16.932283 #16095] DEBUG -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:488:in `synchronize_or_call'
D, [2015-05-08T19:49:16.932527 #16095] DEBUG -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:453:in `block in action'
D, [2015-05-08T19:49:16.932820 #16095] DEBUG -- Kitchen: /opt/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
D, [2015-05-08T19:49:16.933125 #16095] DEBUG -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:452:in `action'
D, [2015-05-08T19:49:16.933578 #16095] DEBUG -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:424:in `perform_action'
D, [2015-05-08T19:49:16.933897 #16095] DEBUG -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:352:in `create_action'
D, [2015-05-08T19:49:16.934123 #16095] DEBUG -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:341:in `block in transition_to'
D, [2015-05-08T19:49:16.934492 #16095] DEBUG -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:340:in `each'
D, [2015-05-08T19:49:16.934747 #16095] DEBUG -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:340:in `transition_to'
D, [2015-05-08T19:49:16.935019 #16095] DEBUG -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:127:in `create'
D, [2015-05-08T19:49:16.935305 #16095] DEBUG -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/command.rb:176:in `public_send'
D, [2015-05-08T19:49:16.935512 #16095] DEBUG -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
D, [2015-05-08T19:49:16.935794 #16095] DEBUG -- Kitchen: ----------------------
```

**Comment by vinyar** [comment]
To add to the above comment. An interesting thing happens:
First node is created, other two reported as not created, however 3rd node is actually created.

Instance                           Driver   Provisioner  Verifier  Transport  Last Action
chef-server-fe01-ubuntu-1204       Vsphere  Environment  Busser    Ssh        Created
chef-server-be01-ubuntu-1204       Vsphere  Environment  Busser    Ssh        <Not Created>
chef-server-analytics-ubuntu-1204  Vsphere  Environment  Busser    Ssh        <Not Created>

**Comment by tyler-ball** [comment]
@vinyar I'm going to phone in @mwrock here - I have never seen a kitchen driver leverage chef-provisioning.  @mwrock have you tested the vsphere kitchen driver with concurrency (`-c` flag)?

My current guess is that test-kitchen spins up a bunch of threads to create the nodes, and then those threads spin up other threads to start chef-zero, and maybe something isn't waiting correctly.  But I'm not sure this is a Test Kitchen issue.

I would like to better understand what is going on before we declare that though.  I'm happy to see experiments using test-kitchen and provisioning!

**Comment by mwrock** [comment]
We don't usually use `-c` with our vsphere driver but use it often with docker. I just tried it now on a multi suite cookbook and see similar errors to @vinyar. It looks like a possible reentrancy issue with chef-zero. The exception occurs in `start_background` https://github.com/chef/chef-zero/blob/master/lib/chef_zero/server.rb#L246. I have see the undefined method exception happen in a couple spots bot are off of `@server` so my guess is that both threads are using the same `@server` and then one frees it which causes the other to fail.

We have recently open sourced our chef-provisioning-vsphere gem which includes the driver here:

https://github.com/CenturyLinkCloud/chef-provisioning-vsphere/blob/master/lib/kitchen/driver/vsphere.rb

**Comment by tyler-ball** [comment]
Okay, sitting in a room with @jkeiser and @fnichol we think we know whats going on.  First - `Cheffish.honor_local_mode` is _NOT_ thread safe, and it is such on purpose.  `Chef::Config` is global and `Chef::Config.chef_server_url` can only reference 1 Chef Server.  When Test Kitchen calls `Cheffish.honor_local_mode` it starts a chef-zero server and sets the `Chef::Config.chef_server_url` to point to this chef-zero instance.  With the current chef implementation there is no way to have the provisioned machines reference different `Chef::Config.chef_server_url`s.

When multiple threads (`kitchen -c`) call `Cheffish.honor_local_mode` it attempts to [create multiple servers](https://github.com/chef/chef/blob/12.3.0/lib/chef/local_mode.rb#L48) and update the global config.  So each thread _thinks_ it is referencing a different chef-zero server but they are really just stepping on each other's toes and all referencing the same server.  Then 1 thread [shuts down](https://github.com/chef/chef/blob/12.3.0/lib/chef/local_mode.rb#L41) the server and causes the nil error we are seeing.

We are going to make some updates to chef-zero to raise errors when users try to start multiple servers, but that change is orthagonal to the change I am going to propose.

We think that `chef-provisioning-vsphere` should start 1 chef-zero server before all the test kitchen instances try to create themselves (which calls chef-provisioning).  Then the instances won't be stepping on each other - they can all just reference the same chef-zero server.  I'll file a new issue in vsphere describing the updates that should occur there.

**Comment by fnichol** [comment]
Epic, nice writeup, @tyler-ball!
