### ISSUE TITLE
ssh breaks if vm restarts

### ISSUE THREAD

**Issue by ahelal** [test-kitchen/test-kitchen#769]
This is probably a very uncommon case. I am testing code for apt security updates. In some cases the vm might reboot to apply security patches. if that happens test kitchen breaks with
```
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: SSH command failed (connection closed by remote host)
D      ------Backtrace-------
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/test-kitchen-1.4.1/lib/kitchen/driver/ssh_base.rb:90:in `rescue in converge'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/test-kitchen-1.4.1/lib/kitchen/driver/ssh_base.rb:93:in `converge'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:540:in `legacy_ssh_base_converge'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:364:in `block in converge_action'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:488:in `call'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:488:in `synchronize_or_call'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:453:in `block in action'
D      /opt/atools/embedded/lib/ruby/1.9.1/benchmark.rb:280:in `measure'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:452:in `action'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:362:in `converge_action'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:341:in `block in transition_to'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:340:in `each'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:340:in `transition_to'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:160:in `verify'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:189:in `block in test'
D      /opt/atools/embedded/lib/ruby/1.9.1/benchmark.rb:280:in `measure'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:185:in `test'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/test-kitchen-1.4.1/lib/kitchen/command.rb:177:in `public_send'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/test-kitchen-1.4.1/lib/kitchen/command.rb:177:in `block (2 levels) in run_action'
D      ----------------------
```

**Comment by conorsch** [comment]
Yup, that's what I'm seeing. The Serverspec test suite requires a reboot before running, so kernel versions and patches are up to snuff. 

Is this really so uncommon a use case?

**Comment by cheeseplus** [comment]
Looks like this PR https://github.com/test-kitchen/test-kitchen/pull/564 will address this so closing this issue as it's already duped by a few others.
