### ISSUE TITLE
Uninitialized constant Kitchen::Transport::Ssh::Connection::Timeout

### ISSUE THREAD

**Issue by neillturner** [test-kitchen/test-kitchen#775]
when running 
 kitchen list 
using the driver ssh (ie the kitchen-ssh plugin)
i.e. .kitchen.yaml
---
driver:
  name: ssh
  ssh_timeout: 10
  ssh_retries: 5
  
gets errors 

 ------Exception-------
 Class: Kitchen::ClientError
 Message: Could not load the 'ssh' transport from the load path. Please ensure that your transport is installed as a gem or included in your Gemfile
 ---Nested Exception---
 Class: NameError
 Message: uninitialized constant Kitchen::Transport::Ssh::Connection::Timeout
 ------Backtrace-------
 C:/Puppet/sys/ruby/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.1/lib/kitchen/transport.rb:48:in `rescue in for_plugin'
 C:/Puppet/sys/ruby/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.1/lib/kitchen/transport.rb:40:in `for_plugin'
 C:/Puppet/sys/ruby/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.1/lib/kitchen/config.rb:303:in `new_transport'
 C:/Puppet/sys/ruby/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.1/lib/kitchen/config.rb:244:in `new_instance'
 C:/Puppet/sys/ruby/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.1/lib/kitchen/config.rb:135:in `block in build_instances'
 C:/Puppet/sys/ruby/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.1/lib/kitchen/config.rb:134:in `map'
 C:/Puppet/sys/ruby/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.1/lib/kitchen/config.rb:134:in `with_index'
 C:/Puppet/sys/ruby/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.1/lib/kitchen/config.rb:134:in `build_instances'

caused by code in kitchen/transport/ssh.rb 

        RESCUE_EXCEPTIONS_ON_ESTABLISH = [
          Errno::EACCES, Errno::EADDRINUSE, Errno::ECONNREFUSED,
          Errno::ECONNRESET, Errno::ENETUNREACH, Errno::EHOSTUNREACH,
          Net::SSH::Disconnect, Net::SSH::AuthenticationFailed, Timeout::Error
        ].freeze
       
        workaound by changing to: 
         RESCUE_EXCEPTIONS_ON_ESTABLISH = [
          Errno::EACCES, Errno::EADDRINUSE, Errno::ECONNREFUSED,
          Errno::ECONNRESET, Errno::ENETUNREACH, Errno::EHOSTUNREACH,
          Net::SSH::Disconnect, Net::SSH::AuthenticationFailed
        ].freeze

**Comment by neillturner** [comment]
Actually i traced this to a beta install of the net-ssh (2.10.0.beta2) when i installed net-ssh 2.9.2 all was ok. so closing. at least this will document it for others.
