### ISSUE TITLE
create_sandbox attempts to use cyclical path when /tmp does not have correct permissions

### ISSUE THREAD

**Issue by rhass** [test-kitchen/test-kitchen#779]
When /tmp has incorrect permissions, (eg: missing temp sticky bit in mode 0777 vs 1777) the mktmpdir call attempts to create tempdir which exists within the `kitchen_root` path resulting in a cyclical path when the during the "Prepairing cookbooks" phase.

This is an example of such issue:

```
-----> Starting Kitchen (v1.4.0)
D      [kitchen::driver::docker command] BEGIN (sudo -E docker >> /dev/null 2>&1)
D      [kitchen::driver::docker command] END (0m0.03s)
-----> Converging <default-ubuntu-1404>...
$$$$$$ Running legacy converge for 'Docker' Driver
       Preparing files for transfer
D      Creating local sandbox in /home/rhass/src/cookbooks/ratchet/default-ubuntu-1404-sandbox-20150714-13752-a7vopg
       Preparing dna.json
D      Creating dna.json from {:run_list=>["recipe[ratchet]"]}
       Preparing current project directory as a cookbook
D      Using metadata.rb from /home/rhass/src/cookbooks/ratchet/metadata.rb
D      Cleaning up local sandbox in /home/rhass/src/cookbooks/ratchet/default-ubuntu-1404-sandbox-20150714-13752-a7vopg
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [cannot copy directory /home/rhass/src/cookbooks/ratchet/default-ubuntu-1404-sandbox-20150714-13752-a7vopg to itself /home/rhass/src/cookbooks/ratchet/default-ubuntu-1404-sandbox-20150714-13752-a7vopg/cookbooks/ratchet/default-ubuntu-1404-sandbox-20150714-13752-a7vopg]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #converge action: [cannot copy directory /home/rhass/src/cookbooks/ratchet/default-ubuntu-1404-sandbox-20150714-13752-a7vopg to itself /home/rhass/src/cookbooks/ratchet/default-ubuntu-1404-sandbox-20150714-13752-a7vopg/cookbooks/ratchet/default-ubuntu-1404-sandbox-20150714-13752-a7vopg]
D      ---Nested Exception---
D      Class: ArgumentError
D      Message: cannot copy directory /home/rhass/src/cookbooks/ratchet/default-ubuntu-1404-sandbox-20150714-13752-a7vopg to itself /home/rhass/src/cookbooks/ratchet/default-ubuntu-1404-sandbox-20150714-13752-a7vopg/cookbooks/ratchet/default-ubuntu-1404-sandbox-20150714-13752-a7vopg
D      ------Backtrace-------
D      /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1372:in `copy'
D      /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:469:in `block in copy_entry'
D      /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1506:in `call'
D      /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1506:in `wrap_traverse'
D      /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:466:in `copy_entry'
D      /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:441:in `block in cp_r'
D      /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1579:in `block in fu_each_src_dest'
D      /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1588:in `block in fu_each_src_dest0'
D      /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1586:in `each'
D      /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1586:in `fu_each_src_dest0'
D      /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1577:in `fu_each_src_dest'
D      /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:440:in `cp_r'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/provisioner/chef/common_sandbox.rb:152:in `cp_this_cookbook'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/provisioner/chef/common_sandbox.rb:258:in `prepare_cookbooks'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/provisioner/chef/common_sandbox.rb:50:in `populate'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/provisioner/chef_base.rb:99:in `create_sandbox'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/provisioner/chef_solo.rb:44:in `create_sandbox'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/driver/ssh_base.rb:72:in `converge'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:540:in `legacy_ssh_base_converge'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:364:in `block in converge_action'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:488:in `call'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:488:in `synchronize_or_call'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:453:in `block in action'
D      /opt/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:452:in `action'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:362:in `converge_action'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:341:in `block in transition_to'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:340:in `each'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:340:in `transition_to'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:138:in `converge'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/command.rb:176:in `public_send'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
D      ----------------------
```

The expected behavior is:
1) For test kitchen to check to see if  `Dir.tmpdir == config[:kitchen_root]` and if so, throw a friendly error message indicating the system temp directory either has the wrong permissions
2) Check to ensure `ENV['TMPDIR'] != config[:kitchen_root]`, if it is throw a friendly error indicating the system TMPDIR environment variable cannot be within the cookbook path.

**Comment by cheeseplus** [comment]
+1
