### ISSUE TITLE
uninitialized constant Kitchen::Transport::Ssh::Connection::Timeout with net-ssh 2.10

### ISSUE THREAD

**Issue by brugidou** [test-kitchen/test-kitchen#800]
net-ssh 2.10.0 has been released today (see https://rubygems.org/gems/net-ssh/versions/2.10.0 )

Now I get this error with test-kitchen:

```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'ssh' transport from the load path. Please ensure that your transport is installed as a gem or included in your Gemfile if using Bundler.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

and the kitchen log:

```
E, [2015-08-02T14:41:22.813163 #54411] ERROR -- Kitchen: ------Exception-------
E, [2015-08-02T14:41:22.813280 #54411] ERROR -- Kitchen: Class: Kitchen::ClientError
E, [2015-08-02T14:41:22.813312 #54411] ERROR -- Kitchen: Message: Could not load the 'ssh' transport from the load path. Please ensure that your transport is installed as a gem or included in your Gemfile if using Bundler.
E, [2015-08-02T14:41:22.813340 #54411] ERROR -- Kitchen: ---Nested Exception---
E, [2015-08-02T14:41:22.813365 #54411] ERROR -- Kitchen: Class: NameError
E, [2015-08-02T14:41:22.813390 #54411] ERROR -- Kitchen: Message: uninitialized constant Kitchen::Transport::Ssh::Connection::Timeout
E, [2015-08-02T14:41:22.813415 #54411] ERROR -- Kitchen: ------Backtrace-------
E, [2015-08-02T14:41:22.813442 #54411] ERROR -- Kitchen: /home/jenkins/.gem/gems/test-kitchen-1.4.1/lib/kitchen/transport.rb:48:in `rescue in for_plugin'
E, [2015-08-02T14:41:22.813468 #54411] ERROR -- Kitchen: /home/jenkins/.gem/gems/test-kitchen-1.4.1/lib/kitchen/transport.rb:40:in `for_plugin'
E, [2015-08-02T14:41:22.813494 #54411] ERROR -- Kitchen: /home/jenkins/.gem/gems/test-kitchen-1.4.1/lib/kitchen/config.rb:303:in `new_transport'
E, [2015-08-02T14:41:22.813520 #54411] ERROR -- Kitchen: /home/jenkins/.gem/gems/test-kitchen-1.4.1/lib/kitchen/config.rb:244:in `new_instance'
E, [2015-08-02T14:41:22.813546 #54411] ERROR -- Kitchen: /home/jenkins/.gem/gems/test-kitchen-1.4.1/lib/kitchen/config.rb:135:in `block in build_instances'
...
```

I managed to trace the inner exeception to https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/transport/ssh.rb#L158

And the issue did not happen before (with net-ssh 2.9). Nothing in the changelog of net-ssh seem to mention changes on Timeout exceptions but I did not find much more information than this.

**Comment by Annih** [comment]
This is due to https://github.com/net-ssh/net-ssh/commit/58b379787b19b47e3b17f73ac05bda208772bb3c that "Eliminate Timeout completely from transport session" and removes the require to `timeout`
