### ISSUE TITLE
serverspec tests fail on windows

### ISSUE THREAD

**Issue by lcc2207** [test-kitchen/test-kitchen#823]
Anyone else seeing this on kitchen 1.4.2

-----> Starting Kitchen (v1.4.2)
-----> Verifying <default-windows2012r2>...
       Preparing files for transfer
-----> Busser installation detected (busser)
       Installing Busser plugins: busser-serverspec
       Plugin serverspec already installed
       Removing C:/Users/ADMINI~1/AppData/Local/Temp/verifier/suites/serverspec
       Transferring files to <default-windows2012r2>
-----> Running serverspec test suite

       File "c:/test/test.txt"
         should be file (FAILED - 1)

       C:/opscode/chef/embedded/bin/ruby.exe -IC:/Users/ADMINI~1/AppData/Local/Temp/verifier/suites/serverspec -I'C:/Users/ADMINI~1/AppData/Local/Temp/verifier/gems/gems/rspec-support-3.3.0/lib';'C:/Users/ADMINI~1/AppData/Local/Temp/verifier/gems/gems/rspec-core-3.3.2/lib' 'C:/Users/ADMINI~1/AppData/Local/Temp/verifier/gems/gems/rspec-core-3.3.2/exe/rspec' --pattern 'C:/Users/ADMINI~1/AppData/Local/Temp/verifier/suites/serverspec/**/*_spec.rb' --color --format documentation --default-path C:/Users/ADMINI~1/AppData/Local/Temp/verifier/suites/serverspec
$$$$$$ C:/Users/ADMINI~1/AppData/Local/Temp/verifier/gems/gems/specinfra-2.43.0/lib/specinfra/backend/exec.rb:73:in `read_nonblock': Bad file descriptor (Errno::EBADF)
$$$$$$ 	from C:/Users/ADMINI~1/AppData/Local/Temp/verifier/gems/gems/specinfra-2.43.0/lib/specinfra/backend/exec.rb:73:in `block (4 levels) in spawn_command'
$$$$$$ 	from C:/Users/ADMINI~1/AppData/Local/Temp/verifier/gems/gems/specinfra-2.43.0/lib/specinfra/backend/exec.rb:71:in `loop'
$$$$$$ 	from C:/Users/ADMINI~1/AppData/Local/Temp/verifier/gems/gems/specinfra-2.43.0/lib/specinfra/backend/exec.rb:71:in `block (3 levels) in spawn_command'
$$$$$$ 	from C:/Users/ADMINI~1/AppData/Local/Temp/verifier/gems/gems/specinfra-2.43.0/lib/specinfra/backend/exec.rb:70:in `each'
$$$$$$ 	from C:/Users/ADMINI~1/AppData/Local/Temp/verifier/gems/gems/specinfra-2.43.0/lib/specinfra/backend/exec.rb:70:in `block (2 levels) in spawn_command'
$$$$$$ 	from C:/Users/ADMINI~1/AppData/Local/Temp/verifier/gems/gems/specinfra-2.43.0/lib/specinfra/backend/exec.rb:67:in `loop'
$$$$$$ 	from C:/Users/ADMINI~1/AppData/Local/Temp/verifier/gems/gems/specinfra-2.43.0/lib/specinfra/backend/exec.rb:67:in `block in spawn_command'
$$$$$$ C:/opscode/chef/embedded/bin/ruby.exe -IC:/Users/ADMINI~1/AppData/Local/Temp/verifier/suites/serverspec -I'C:/Users/ADMINI~1/AppData/Local/Temp/verifier/gems/gems/rspec-support-3.3.0/lib';'C:/Users/ADMINI~1/AppData/Local/Temp/verifier/gems/gems/rspec-core-3.3.2/lib' 'C:/Users/ADMINI~1/AppData/Local/Temp/verifier/gems/gems/rspec-core-3.3.2/exe/rspec' --pattern 'C:/Users/ADMINI~1/AppData/Local/Temp/verifier/suites/serverspec/**/*_spec.rb' --color --format documentation --default-path C:/Users/ADMINI~1/AppData/Local/Temp/verifier/suites/serverspec failed
$$$$$$ !!!!!! Ruby Script [C:/Users/ADMINI~1/AppData/Local/Temp/verifier/gems/gems/busser-serverspec-0.5.7/lib/busser/runner_plugin/../serverspec/runner.rb C:/Users/ADMINI~1/AppData/Local/Temp/verifier/suites/serverspec] exit code was 1
>>>>>> Verify failed on instance <default-windows2012r2>.
>>>>>> Please see .kitchen/logs/default-windows2012r2.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: WinRM exited (1) for command: [
$env:BUSSER_ROOT = "$env:TEMP\verifier"
$env:GEM_HOME = "$env:TEMP\verifier\gems"
$env:GEM_PATH = "$env:TEMP\verifier\gems"
$env:GEM_CACHE = "$env:TEMP\verifier\gems\cache"

& $env:TEMP\verifier\bin\busser.bat test
]
>>>>>> ----------------------

**Comment by lcc2207** [comment]
I added the following to the spec_helper.rb

set :backend, :cmd
set :os, :family => 'windows'
