### ISSUE TITLE
chefdk install issues

### ISSUE THREAD

**Issue by patrick-wright** [test-kitchen/test-kitchen#830]
I'm running chefdk 0.7.0 and I'm following the chefdk install steps from: https://docs.chef.io/config_yml_kitchen.html#chef-chef-dk-title.
```
Chef Development Kit Version: 0.7.0
chef-client version: 12.4.1
berks version: 3.3.0
kitchen version: 1.4.2
```

Here's my config
```yaml
---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  chef_omnibus_install_options: -P chefdk
  chef_omnibus_root: /opt/chefdk

platforms:
  - name: ubuntu-14.04
  - name: centos-7.1

suites:
  - name: default
```

Verify stage fails
```
-----> Verifying <default-ubuntu-1404>...
       Preparing files for transfer
D      Creating local sandbox in /var/folders/pm/sr29vgdj6x5g894t4m4zcym80000gp/T/default-ubuntu-1404-sandbox-20150914-4477-zaox3m
D      [SSH] reusing existing connection vagrant@127.0.0.1<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>"2222", :compression=>true, :compression_level=>6, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :keys_only=>true, :keys=>["/Users/patrickwright/github/chef-acceptance-example/.kitchen/kitchen-vagrant/kitchen-chef-acceptance-example-default-ubuntu-1404/.vagrant/machines/default/virtualbox/private_key"], :auth_methods=>["publickey"], :user=>"vagrant"}>
D      [SSH] vagrant@127.0.0.1<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>"2222", :compression=>true, :compression_level=>6, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :keys_only=>true, :keys=>["/Users/patrickwright/github/chef-acceptance-example/.kitchen/kitchen-vagrant/kitchen-chef-acceptance-example-default-ubuntu-1404/.vagrant/machines/default/virtualbox/private_key"], :auth_methods=>["publickey"], :user=>"vagrant"}> (sh -c '

BUSSER_ROOT="/tmp/verifier"; export BUSSER_ROOT
GEM_HOME="/tmp/verifier/gems"; export GEM_HOME
GEM_PATH="/tmp/verifier/gems"; export GEM_PATH
GEM_CACHE="/tmp/verifier/gems/cache"; export GEM_CACHE
ruby="/opt/chef/embedded/bin/ruby"
gem="/opt/chef/embedded/bin/gem"
version="busser"
gem_install_args="busser --no-rdoc --no-ri"
busser="sudo -E /tmp/verifier/bin/busser"
plugins="busser-rspec busser-serverspec"

$gem list busser -i 2>&1 >/dev/null
if test $? -ne 0; then
  echo "-----> Installing Busser ($version)"
  $gem install $gem_install_args
else
  echo "-----> Busser installation detected ($version)"
fi

if test ! -f "$BUSSER_ROOT/bin/busser"; then
  gem_bindir=`$ruby -rrubygems -e "puts Gem.bindir"`
  $gem_bindir/busser setup
fi

echo "       Installing Busser plugins: $plugins"
$busser plugin install $plugins
')
       sh: 14: /opt/chef/embedded/bin/gem: not found
-----> Installing Busser (busser)
       sh: 17: /opt/chef/embedded/bin/gem: not found
       /opt/chef/embedded/bin/ruby: not found
       /busser: not found

       sudo: /tmp/verifier/bin/busser: command not found
D      Cleaning up local sandbox in /var/folders/pm/sr29vgdj6x5g894t4m4zcym80000gp/T/default-ubuntu-1404-sandbox-20150914-4477-zaox3m
>>>>>> Verify failed on instance <default-ubuntu-1404>.
>>>>>> Please see .kitchen/logs/default-ubuntu-1404.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sh -c '

BUSSER_ROOT="/tmp/verifier"; export BUSSER_ROOT
GEM_HOME="/tmp/verifier/gems"; export GEM_HOME
GEM_PATH="/tmp/verifier/gems"; export GEM_PATH
GEM_CACHE="/tmp/verifier/gems/cache"; export GEM_CACHE
ruby="/opt/chef/embedded/bin/ruby"
gem="/opt/chef/embedded/bin/gem"
version="busser"
gem_install_args="busser --no-rdoc --no-ri"
busser="sudo -E /tmp/verifier/bin/busser"
plugins="busser-rspec busser-serverspec"

$gem list busser -i 2>&1 >/dev/null
if test $? -ne 0; then
  echo "-----> Installing Busser ($version)"
  $gem install $gem_install_args
else
  echo "-----> Busser installation detected ($version)"
fi

if test ! -f "$BUSSER_ROOT/bin/busser"; then
  gem_bindir=`$ruby -rrubygems -e "puts Gem.bindir"`
  $gem_bindir/busser setup
fi

echo "       Installing Busser plugins: $plugins"
$busser plugin install $plugins
']
>>>>>> ----------------------
D      Verify failed on instance <default-ubuntu-1404>.
D      ------Exception-------
D      Class: Kitchen::InstanceFailure
D      Message: Verify failed on instance <default-ubuntu-1404>.  Please see .kitchen/logs/default-ubuntu-1404.log for more details
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: SSH exited (1) for command: [sh -c '

BUSSER_ROOT="/tmp/verifier"; export BUSSER_ROOT
GEM_HOME="/tmp/verifier/gems"; export GEM_HOME
GEM_PATH="/tmp/verifier/gems"; export GEM_PATH
GEM_CACHE="/tmp/verifier/gems/cache"; export GEM_CACHE
ruby="/opt/chef/embedded/bin/ruby"
gem="/opt/chef/embedded/bin/gem"
version="busser"
gem_install_args="busser --no-rdoc --no-ri"
busser="sudo -E /tmp/verifier/bin/busser"
plugins="busser-rspec busser-serverspec"

$gem list busser -i 2>&1 >/dev/null
if test $? -ne 0; then
  echo "-----> Installing Busser ($version)"
  $gem install $gem_install_args
else
  echo "-----> Busser installation detected ($version)"
fi

if test ! -f "$BUSSER_ROOT/bin/busser"; then
  gem_bindir=`$ruby -rrubygems -e "puts Gem.bindir"`
  $gem_bindir/busser setup
fi

echo "       Installing Busser plugins: $plugins"
$busser plugin install $plugins
']
D      ------Backtrace-------
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/verifier/base.rb:79:in `rescue in call'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/verifier/base.rb:82:in `call'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:398:in `block in verify_action'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:488:in `call'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:488:in `synchronize_or_call'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:453:in `block in action'
D      /opt/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:452:in `action'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:394:in `verify_action'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:341:in `block in transition_to'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:340:in `each'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:340:in `transition_to'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:160:in `verify'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:189:in `block in test'
D      /opt/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:185:in `test'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/command.rb:176:in `public_send'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
D      ----------------------
```

@tyler-ball

**Comment by tyler-ball** [comment]
Also pinging @fnichol

**Comment by patrick-wright** [comment]
I added the shell command to a script and modified it on the instance.  Here's how I got it to run:

```bash
BUSSER_ROOT="/tmp/verifier"; export BUSSER_ROOT
GEM_HOME="/tmp/verifier/gems"; export GEM_HOME
GEM_PATH="/tmp/verifier/gems"; export GEM_PATH
GEM_CACHE="/tmp/verifier/gems/cache"; export GEM_CACHE

# Had to change the root chefdk dir
ruby="/opt/chefdk/embedded/bin/ruby"
gem="/opt/chefdk/embedded/bin/gem"
###

version="busser"
gem_install_args="busser --no-rdoc --no-ri"
busser="sudo -E /tmp/verifier/bin/busser"
plugins="busser-rspec busser-serverspec"

# Added to get rid of the bin path warning
PATH="$PATH:/home/vagrant/.chefdk/gem/ruby/2.1.0/bin"; export PATH

$gem list busser -i 2>&1 >/dev/null
if test $? -ne 0; then
  echo "-----> Installing Busser ($version)"
  $gem install $gem_install_args
else
  echo "-----> Busser installation detected ($version)"
fi

if test ! -f "$BUSSER_ROOT/bin/busser"; then
  gem_bindir=`$ruby -rrubygems -e "puts Gem.bindir"`
  #$gem_bindir/busser setup
  sudo busser setup
fi

echo "       Installing Busser plugins: $plugins"
#$busser plugin install $plugins
sudo busser plugin install $plugins
```

I can't really tell if its actually working since I can't run the tests without running the busser stuff, but it runs :/

**Comment by tyler-ball** [comment]
@patrick-wright Did it install the `busser` gem to `~/.chefdk` or `/tmp`?

**Comment by patrick-wright** [comment]
Installed in `~/.chefdk`.  Do we need that to be installed in /tmp for specs to run?  If so, I can continue working on it to do that.

**Comment by fnichol** [comment]
Ah, now I think I get this: you'll need to override the `:ruby_bindir` in a verifier block to make this work. Currently biased is completely disconnected from Chef, omnibus packages, etc. *except* that we're stealing our Ruby runtime from an omnibus package. See if this helps:


```yaml
---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  chef_omnibus_install_options: -P
  chef_omnibus_root: /opt/chefdk

verifier:
  ruby_bindir: /opt/chefdk/embedded/bin
  
```

**Comment by scotthain** [comment]
For the record @fnichol - before the PR (833) - the `ruby_bindir` was actually not used in the verifier, it was hardcoded in... :(

**Comment by tyler-ball** [comment]
@fnichol do you want us to put out another PR to uses `ruby_bindir` instead of `chef_omnibus_root`?

**Comment by scotthain** [comment]
I feel like chef_omnibus_root is the correct thing to do, because then you can override ruby_bindir as well...

That being said, I think the part that is missing here is the automatic defaulting of chef_omnibus_root :(
