### ISSUE TITLE
SSL read error when attempting to download Ubuntu 12.04 box for simple converge

### ISSUE THREAD

**Issue by danapplegate** [test-kitchen/test-kitchen#834]
Hi,

I'm trying to just get up and running with Kitchen. I'm on Mac OSx 10.10.3. Here is my .kitchen.yml:

```
---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04

suites:
  - name: local
    run_list:
      - recipe[my_company-environments::local]
    attributes:
```

The runlist contains just an empty recipe.

Here is my logfile from the run:

```
I, [2015-09-18T18:49:01.968590 #6270]  INFO -- local-ubuntu-1204: -----> Creating <local-ubuntu-1204>...
I, [2015-09-18T18:49:03.141338 #6270]  INFO -- local-ubuntu-1204: Bringing machine 'default' up with 'virtualbox' provider...
I, [2015-09-18T18:49:03.300679 #6270]  INFO -- local-ubuntu-1204: ==> default: Box 'opscode-ubuntu-12.04' could not be found. Attempting to find and install...
I, [2015-09-18T18:49:03.300964 #6270]  INFO -- local-ubuntu-1204:     default: Box Provider: virtualbox
I, [2015-09-18T18:49:03.301088 #6270]  INFO -- local-ubuntu-1204:     default: Box Version: >= 0
I, [2015-09-18T18:49:03.652936 #6270]  INFO -- local-ubuntu-1204: ==> default: Box file was not detected as metadata. Adding it directly...
I, [2015-09-18T18:49:03.653429 #6270]  INFO -- local-ubuntu-1204: ==> default: Adding box 'opscode-ubuntu-12.04' (v0) for provider: virtualbox
I, [2015-09-18T18:49:03.658073 #6270]  INFO -- local-ubuntu-1204:     default: Downloading: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box
I, [2015-09-18T18:49:03.658329 #6270]  INFO -- local-ubuntu-1204: ==> default: Box download is resuming from prior download progress
I, [2015-09-18T18:49:05.659996 #6270]  INFO -- local-ubuntu-1204: 
[K    default: Progress: 0% (Rate: 0/s, Estimated time remaining: --:--:--)
[K    default: Progress: 2% (Rate: 4678k/s, Estimated time remaining: 0:00:12)
[KAn error occurred while downloading the remote file. The error
I, [2015-09-18T18:49:05.660054 #6270]  INFO -- local-ubuntu-1204: message, if any, is reproduced below. Please fix this error and try
I, [2015-09-18T18:49:05.660073 #6270]  INFO -- local-ubuntu-1204: again.
I, [2015-09-18T18:49:05.660086 #6270]  INFO -- local-ubuntu-1204: 
I, [2015-09-18T18:49:05.660104 #6270]  INFO -- local-ubuntu-1204: SSL read: error:00000000:lib(0):func(0):reason(0), errno 54
E, [2015-09-18T18:49:05.719853 #6270] ERROR -- local-ubuntu-1204: Create failed on instance <local-ubuntu-1204>.
E, [2015-09-18T18:49:05.720128 #6270] ERROR -- local-ubuntu-1204: ------Exception-------
E, [2015-09-18T18:49:05.720169 #6270] ERROR -- local-ubuntu-1204: Class: Kitchen::ShellOut::ShellCommandFailed
E, [2015-09-18T18:49:05.720190 #6270] ERROR -- local-ubuntu-1204: Message: Expected process to exit with [0], but received '1'
---- Begin output of vagrant up --no-provision --provider virtualbox ----
STDOUT: Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'opscode-ubuntu-12.04' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'opscode-ubuntu-12.04' (v0) for provider: virtualbox
    default: Downloading: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box
==> default: Box download is resuming from prior download progress

[K    default: Progress: 0% (Rate: 0/s, Estimated time remaining: --:--:--)
[K    default: Progress: 2% (Rate: 4678k/s, Estimated time remaining: 0:00:12)
[K
STDERR: An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

SSL read: error:00000000:lib(0):func(0):reason(0), errno 54
---- End output of vagrant up --no-provision --provider virtualbox ----
Ran vagrant up --no-provision --provider virtualbox returned 1
E, [2015-09-18T18:49:05.720218 #6270] ERROR -- local-ubuntu-1204: ---Nested Exception---
E, [2015-09-18T18:49:05.720235 #6270] ERROR -- local-ubuntu-1204: Class: Mixlib::ShellOut::ShellCommandFailed
E, [2015-09-18T18:49:05.720259 #6270] ERROR -- local-ubuntu-1204: Message: Expected process to exit with [0], but received '1'
---- Begin output of vagrant up --no-provision --provider virtualbox ----
STDOUT: Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'opscode-ubuntu-12.04' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'opscode-ubuntu-12.04' (v0) for provider: virtualbox
    default: Downloading: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box
==> default: Box download is resuming from prior download progress

[K    default: Progress: 0% (Rate: 0/s, Estimated time remaining: --:--:--)
[K    default: Progress: 2% (Rate: 4678k/s, Estimated time remaining: 0:00:12)
[K
STDERR: An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

SSL read: error:00000000:lib(0):func(0):reason(0), errno 54
---- End output of vagrant up --no-provision --provider virtualbox ----
Ran vagrant up --no-provision --provider virtualbox returned 1
E, [2015-09-18T18:49:05.720307 #6270] ERROR -- local-ubuntu-1204: ------Backtrace-------
E, [2015-09-18T18:49:05.720326 #6270] ERROR -- local-ubuntu-1204: /Users/applegatedt/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/shell_out.rb:73:in `rescue in run_command'
E, [2015-09-18T18:49:05.720341 #6270] ERROR -- local-ubuntu-1204: /Users/applegatedt/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/shell_out.rb:61:in `run_command'
E, [2015-09-18T18:49:05.720356 #6270] ERROR -- local-ubuntu-1204: /Users/applegatedt/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/kitchen-vagrant-0.19.0/lib/kitchen/driver/vagrant.rb:343:in `run_command'
E, [2015-09-18T18:49:05.720371 #6270] ERROR -- local-ubuntu-1204: /Users/applegatedt/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/kitchen-vagrant-0.19.0/lib/kitchen/driver/vagrant.rb:302:in `run'
E, [2015-09-18T18:49:05.720386 #6270] ERROR -- local-ubuntu-1204: /Users/applegatedt/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/kitchen-vagrant-0.19.0/lib/kitchen/driver/vagrant.rb:373:in `run_vagrant_up'
E, [2015-09-18T18:49:05.720402 #6270] ERROR -- local-ubuntu-1204: /Users/applegatedt/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/kitchen-vagrant-0.19.0/lib/kitchen/driver/vagrant.rb:88:in `create'
E, [2015-09-18T18:49:05.720416 #6270] ERROR -- local-ubuntu-1204: /Users/applegatedt/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:424:in `public_send'
E, [2015-09-18T18:49:05.720433 #6270] ERROR -- local-ubuntu-1204: /Users/applegatedt/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:424:in `block in perform_action'
E, [2015-09-18T18:49:05.720454 #6270] ERROR -- local-ubuntu-1204: /Users/applegatedt/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:485:in `call'
E, [2015-09-18T18:49:05.720468 #6270] ERROR -- local-ubuntu-1204: /Users/applegatedt/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:485:in `block in synchronize_or_call'
E, [2015-09-18T18:49:05.720482 #6270] ERROR -- local-ubuntu-1204: /Users/applegatedt/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:483:in `synchronize'
E, [2015-09-18T18:49:05.720507 #6270] ERROR -- local-ubuntu-1204: /Users/applegatedt/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:483:in `synchronize_or_call'
E, [2015-09-18T18:49:05.720521 #6270] ERROR -- local-ubuntu-1204: /Users/applegatedt/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:453:in `block in action'
E, [2015-09-18T18:49:05.720534 #6270] ERROR -- local-ubuntu-1204: /Users/applegatedt/.rbenv/versions/2.0.0-p481/lib/ruby/2.0.0/benchmark.rb:281:in `measure'
E, [2015-09-18T18:49:05.720549 #6270] ERROR -- local-ubuntu-1204: /Users/applegatedt/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:452:in `action'
E, [2015-09-18T18:49:05.720564 #6270] ERROR -- local-ubuntu-1204: /Users/applegatedt/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:424:in `perform_action'
E, [2015-09-18T18:49:05.720584 #6270] ERROR -- local-ubuntu-1204: /Users/applegatedt/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:352:in `create_action'
E, [2015-09-18T18:49:05.720599 #6270] ERROR -- local-ubuntu-1204: /Users/applegatedt/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:341:in `block in transition_to'
E, [2015-09-18T18:49:05.720611 #6270] ERROR -- local-ubuntu-1204: /Users/applegatedt/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:340:in `each'
E, [2015-09-18T18:49:05.720624 #6270] ERROR -- local-ubuntu-1204: /Users/applegatedt/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:340:in `transition_to'
E, [2015-09-18T18:49:05.720637 #6270] ERROR -- local-ubuntu-1204: /Users/applegatedt/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:138:in `converge'
E, [2015-09-18T18:49:05.720649 #6270] ERROR -- local-ubuntu-1204: /Users/applegatedt/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/command.rb:176:in `public_send'
E, [2015-09-18T18:49:05.720662 #6270] ERROR -- local-ubuntu-1204: /Users/applegatedt/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
E, [2015-09-18T18:49:05.720675 #6270] ERROR -- local-ubuntu-1204: ----------------------
```

**Comment by danapplegate** [comment]
Hmm, the issue seems to have resolved itself. Possibly connectivity issues with opscode-vm-bento.s3.amazonaws.com? I tried going to the URL directly while it was occurring, and I was able to download just fine...

**Comment by cheeseplus** [comment]
I was pushing a new bento release to S3 so it's possible you were caught by that.
