### ISSUE TITLE
Chef Omnibus Windows Issues (mixlib-install #22 related)

### ISSUE THREAD

**Issue by icberg7** [test-kitchen/test-kitchen#847]
I've recently been playing with kitchen-openstack with Windows (well, more or less trudging through), and I finally got the WinRM stuff baked out. Unfortunately, Chef fails to upgrade the installed version of Chef due to an uncaught exception.
I have this in my `.kitchen.yml`:
```
provisioner:
  name: chef_zero
  require_chef_omnibus:  12.4.3
```

When Chef attempts to bootstrap the node, I get this error:
```
& $env:systemdrive\opscode\chef\bin\chef-client.bat --local-mode --config $env:TEMP\kitchen\client.rb --log_level debug --force-formatter --no-color --json-attributes $env:TEMP\kitchen\dna.json --chef-zero-port 8889)
W, [2015-10-07T16:18:57.633551 #3557]  WARN -- default-win2k8: C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/mixlib-cli-1.2.2/lib/mixlib/cli.rb:154:in `parse_options': invalid option: --local-mode (OptionParser::InvalidOption)
    from C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.2/lib/chef/application.rb:77:in `configure_chef'
    from C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.2/lib/chef/application.rb:64:in `reconfigure'
    from C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.2/lib/chef/application/client.rb:194:in `reconfigure'
    from C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.2/lib/chef/application.rb:70:in `run'
    from C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.2/bin/chef-client:26:in `<top (required)>'
    from C:/opscode/chef/bin/chef-client:19:in `load'
    from C:/opscode/chef/bin/chef-client:19:in `<main>'

D, [2015-10-07T16:18:57.634790 #3557] DEBUG -- default-win2k8: Cleaning up local sandbox in /tmp/default-win2k8-sandbox-20151007-3557-c3pzfv
E, [2015-10-07T16:18:57.635263 #3557] ERROR -- default-win2k8: Converge failed on instance <default-win2k8>.
E, [2015-10-07T16:18:57.635339 #3557] ERROR -- default-win2k8: ------Exception-------
E, [2015-10-07T16:18:57.635357 #3557] ERROR -- default-win2k8: Class: Kitchen::ActionFailed
E, [2015-10-07T16:18:57.635369 #3557] ERROR -- default-win2k8: Message: WinRM exited (1) for command: [
$env:PATH = [System.Environment]::GetEnvironmentVariable("PATH","Machine")

& $env:systemdrive\opscode\chef\bin\chef-client.bat --local-mode --config $env:TEMP\kitchen\client.rb --log_level debug --force-formatter --no-color --json-attributes $env:TEMP\kitchen\dna.json --chef-zero-port 8889]
E, [2015-10-07T16:18:57.635388 #3557] ERROR -- default-win2k8: ---Nested Exception---
E, [2015-10-07T16:18:57.635400 #3557] ERROR -- default-win2k8: Class: Kitchen::Transport::WinrmFailed
E, [2015-10-07T16:18:57.635411 #3557] ERROR -- default-win2k8: Message: WinRM exited (1) for command: [
$env:PATH = [System.Environment]::GetEnvironmentVariable("PATH","Machine")

& $env:systemdrive\opscode\chef\bin\chef-client.bat --local-mode --config $env:TEMP\kitchen\client.rb --log_level debug --force-formatter --no-color --json-attributes $env:TEMP\kitchen\dna.json --chef-zero-port 8889]
E, [2015-10-07T16:18:57.635421 #3557] ERROR -- default-win2k8: ------Backtrace-------
E, [2015-10-07T16:18:57.635431 #3557] ERROR -- default-win2k8: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/provisioner/base.rb:74:in `rescue in call'
E, [2015-10-07T16:18:57.635441 #3557] ERROR -- default-win2k8: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/provisioner/base.rb:77:in `call'
E, [2015-10-07T16:18:57.635452 #3557] ERROR -- default-win2k8: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:366:in `block in converge_action'
E, [2015-10-07T16:18:57.635463 #3557] ERROR -- default-win2k8: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:488:in `call'
E, [2015-10-07T16:18:57.635473 #3557] ERROR -- default-win2k8: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:488:in `synchronize_or_call'
E, [2015-10-07T16:18:57.635484 #3557] ERROR -- default-win2k8: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:453:in `block in action'
E, [2015-10-07T16:18:57.635538 #3557] ERROR -- default-win2k8: /opt/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
E, [2015-10-07T16:18:57.635553 #3557] ERROR -- default-win2k8: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:452:in `action'
E, [2015-10-07T16:18:57.635564 #3557] ERROR -- default-win2k8: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:362:in `converge_action'
E, [2015-10-07T16:18:57.635574 #3557] ERROR -- default-win2k8: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:341:in `block in transition_to'
E, [2015-10-07T16:18:57.635584 #3557] ERROR -- default-win2k8: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:340:in `each'
E, [2015-10-07T16:18:57.635594 #3557] ERROR -- default-win2k8: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:340:in `transition_to'
E, [2015-10-07T16:18:57.635605 #3557] ERROR -- default-win2k8: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:138:in `converge'
E, [2015-10-07T16:18:57.635615 #3557] ERROR -- default-win2k8: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/command.rb:176:in `public_send'
E, [2015-10-07T16:18:57.635625 #3557] ERROR -- default-win2k8: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
E, [2015-10-07T16:18:57.635655 #3557] ERROR -- default-win2k8: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
E, [2015-10-07T16:18:57.635666 #3557] ERROR -- default-win2k8: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
E, [2015-10-07T16:18:57.635676 #3557] ERROR -- default-win2k8: ----------------------
```

It appears that the real issue is that this server has Chef 10.16.2 installed and the boostrap process failed to upgrade it to the desired 12.4.3:
```
-----> Chef Omnibus installation detected (12.4.3)
$$$$$$ Get-Content : Cannot find path 'C:\opscode\chef\version-manifest.txt' because i
$$$$$$ t does not exist.
$$$$$$ At line:12 char:36
$$$$$$ +   Try { $chef_version = Get-Content &lt;&lt;&lt;&lt;  $root\version-manifest.txt | select
$$$$$$ -object -1}
$$$$$$     + CategoryInfo          : ObjectNotFound: (C:\opscode\chef\version-manifes
$$$$$$    t.txt:String) [Get-Content], ItemNotFoundException
$$$$$$     + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetCo
$$$$$$    ntentCommand
$$$$$$ 
$$$$$$ You cannot call a method on a null-valued expression.
$$$$$$ At line:18 char:31
$$$$$$ +   if ($chef_version.StartsWith &lt;&lt;&lt;&lt; ($version)) { return $false }
$$$$$$     + CategoryInfo          : InvalidOperation: (StartsWith:String) [], Runtim
$$$$$$    eException
$$$$$$     + FullyQualifiedErrorId : InvokeMethodOnNull
```

Based on the code here, it appears to be looking at a `C:\opscode\chef\version-manifest.txt` file that doesn't exist:
```
$chef_metadata_url = "https://www.chef.io/chef/metadata?p=windows&m=x86_64&pv=2008r2&v=12.4.3"
$chef_omnibus_root = "$env:systemdrive\opscode\chef"
$msi = "$env:TEMP\chef-12.4.3.msi"
$pretty_version = "12.4.3"
$version = "12.4.3"
Function Check-UpdateChef($root, $version) {
  if (-Not (Test-Path $root)) { return $true }
  elseif ("$version" -eq "true") { return $false }
  elseif ("$version" -eq "latest") { return $true }
  Try { $chef_version = Get-Content $root\version-manifest.txt | select-object -1}
  Catch {
    Try { $chef_version = (& $root\bin\chef-solo.bat -v).split(" ", 2)[1] }
    Catch { $chef_version = "" }
  }
  if ($chef_version.StartsWith($version)) { return $false }
  else { return $true }
}
<snip>
if (Check-UpdateChef $chef_omnibus_root $version) {
  Write-Host "-----> Installing Chef Omnibus ($pretty_version)`n"
  Download-Chef "$chef_metadata_url" $msi
  Install-Chef $msi
} else {
  Write-Host "-----> Chef Omnibus installation detected ($pretty_version)`n"
}
```

```
PS C:\Windows\system32> $chef_omnibus_root
C:\opscode\chef
PS C:\Windows\system32> Test-Path $chef_omnibus_root
True
PS C:\Windows\system32> Test-Path $chef_omnibus_root\version-manifest.txt
False
```

I don't know when this `version-manifest.txt` file was introduced, but it would seem that there needs to be another condition or try/catch block to handle the scenario where it's missing.

**Comment by icberg7** [comment]
This appears to be broken on even newer versions. I attempted to converge a windows node with `require_chef_omnibus` originally set to `11.18.6`. After a converge failure, I changed `require_chef_omnibus` in the `platform` section to `12.4.3`. When running `chef converge`, it still did not attempt to upgrade the package:

```
-----> Chef Omnibus installation detected (12.4.3)
       Transferring files to <default-win2k8>
       Starting Chef Client, version 11.18.6
```

**Comment by mlcooper** [comment]
I'm running into a similar issue.  Here's my environment:
```
$ chef -v
Chef Development Kit Version: 0.9.0
chef-client version: 12.5.1
berks version: 4.0.1
kitchen version: 1.4.2
```
When I run test kitchen, the virtualbox image I'm using has 11.18.6 installed, but the Chef Omnibus installation is detecting 12.5.1:
```
-----> Chef Omnibus installation detected (12.5.1)
       Transferring files to <default-windows-2008-r2-chef1251>
       Starting Chef Client, version 11.18.6
```
I've changed numerous settings in the kitchen.yml file trying to figure this out, but the erroneous detection continues.

**Comment by mlcooper** [comment]
@icberg7 I found out that at a minimum you need to install `11.18.10` on a Windows node to get the version-manifest.txt file in place.  It will not be there for `11.18.6`.

**Comment by mwrock** [comment]
I thhink https://github.com/chef/mixlib-install/pull/21 will fix this given test-kitchen adjusts its dependencies when it is released.

**Comment by cheeseplus** [comment]
The root issue is here Chef related and test-kitchen isn't really involved in the bugs contained in the thread. Closing.
