### ISSUE TITLE
test-kitchen winrm w/proxies "The command line is too long."

### ISSUE THREAD

**Issue by stevehedrick** [test-kitchen/test-kitchen#854]
I'm having a problem using test-kitchen with a windows host thats behind a proxy with authentication.  Without the proxy I'm able to run a kitchen create, but my converge will fail (because of the proxy).  That's expected.  But when I add the proxy strings to the provider section of test-kitchen, everything fails with a command too long error.

```
$ kitchen converge Windows2
-----> Starting Kitchen (v1.4.2)
-----> Converging <default-Windows2>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 4.0.1...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
$$$$$$ The command line is too long.
>>>>>> Converge failed on instance <default-Windows2>.
```

I'm passing the proxies (both http and https) as 
```
provisioner:
  name: chef_zero
  http_proxy: http://uuuuuuuuuuu:pppppppp@myproxyserver
  https_proxy: https://uuuuuuuuuuu:pppppppp@myproxyserver
```
Those are the actual lengths of the strings being passed, just cleaned.  The same settings work on a linux host.  Both the https and http connections are being proxied from port 80, I left it out trying to shorten the command some (along with the rest of the domain) but no dice.

Here's the full error and the return code:
```
$ kitchen converge Windows2
-----> Starting Kitchen (v1.4.2)
-----> Converging <default-Windows2>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 4.0.1...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
$$$$$$ The command line is too long.
>>>>>> Converge failed on instance <default-Windows2>.
>>>>>> Please see .kitchen/logs/default-Windows2.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: WinRM exited (1) for command: [$env:http_proxy = "http://uuuuuuuuuuu:pppppppp@myproxyserver"
$env:HTTP_PROXY = "http://uuuuuuuuuuu:pppppppp@myproxyserver"
$env:https_proxy = "https://uuuuuuuuuuu:pppppppp@myproxyserver"
$env:HTTPS_PROXY = "https://uuuuuuuuuuu:pppppppp@myproxyserver"
$chef_metadata_url = "https://www.chef.io/chef/metadata?p=windows&m=x86_64&pv=2008r2&v=latest"
$chef_omnibus_root = "$env:systemdrive\opscode\chef"
$msi = "$env:TEMP\chef-true.msi"
$pretty_version = "install only if missing"
$version = "true"

Function Check-UpdateChef($root, $version) {
  if (-Not (Test-Path $root)) { return $true }
  elseif ("$version" -eq "true") { return $false }
  elseif ("$version" -eq "latest") { return $true }
  Try { $chef_version = Get-Content $root\version-manifest.txt | select-object -1}
  Catch {
    Try { $chef_version = (& $root\bin\chef-solo.bat -v).split(" ", 2)[1] }
    Catch { $chef_version = "" }
  }

  if ($chef_version.StartsWith($version)) { return $false }
  else { return $true }
}

Function Get-ChefMetadata($url) {
  Try { $response = ($c = Make-WebClient).DownloadString($url) }
  Finally { if ($c -ne $null) { $c.Dispose() } }

  $md = ConvertFrom-StringData $response.Replace("`t", "=")
  return @($md.url, $md.md5)
}

Function Get-MD5Sum($src) {
  Try {
    $c = New-Object -TypeName System.Security.Cryptography.MD5CryptoServiceProvider
    $bytes = $c.ComputeHash(($in = (Get-Item $src).OpenRead()))
    return ([System.BitConverter]::ToString($bytes)).Replace("-", "").ToLower()
  } Finally { if (($c -ne $null) -and ($c.GetType().GetMethod("Dispose") -ne $null)) { $c.Dispose() }; if ($in -ne $null) { $in.Dispose() } }
}

Function Download-Chef($md_url, $dst) {
  $url, $md5 = Get-ChefMetadata $md_url

  Try {
    Log "Downloading package from $url"
    ($c = Make-WebClient).DownloadFile($url, $dst)
    Log "Download complete."
  } Finally { if ($c -ne $null) { $c.Dispose() } }

  if (($dmd5 = Get-MD5Sum $dst) -eq $md5) { Log "Successfully verified $dst" }
  else { throw "MD5 for $dst $dmd5 does not match $md5" }
}

Function Install-Chef($msi) {
  Log "Installing Chef Omnibus package $msi"
  $p = Start-Process -FilePath "msiexec.exe" -ArgumentList "/qn /i $msi" -Passthru -Wait

  if ($p.ExitCode -ne 0) { throw "msiexec was not successful. Received exit code $($p.ExitCode)" }

  Remove-Item $msi -Force
  Log "Installation complete"
}

Function Log($m) { Write-Host "       $m`n" }

Function Make-WebClient {
  $proxy = New-Object -TypeName System.Net.WebProxy
  $proxy.Address = $env:http_proxy
  $client = New-Object -TypeName System.Net.WebClient
  $client.Proxy = $proxy
  return $client
}

Function Unresolve-Path($p) {
  if ($p -eq $null) { return $null }
  else { return $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($p) }
}

$chef_omnibus_root = Unresolve-Path $chef_omnibus_root
$msi = Unresolve-Path $msi

if (Check-UpdateChef $chef_omnibus_root $version) {
  Write-Host "-----> Installing Chef Omnibus ($pretty_version)`n"
  Download-Chef "$chef_metadata_url" $msi
  Install-Chef $msi
} else {
  Write-Host "-----> Chef Omnibus installation detected ($pretty_version)`n"
}
]
>>>>>> ----------------------
$ echo $?
10
$
```

Anybody have any ideas how to work around this?

**Comment by stevehedrick** [comment]
So as far as I can tell so far, this is an error coming back from WinRM.  Because of all the functions being passed along in the command after encoding the command length is passing 32k.  I'm getting this from WinRb/WinRM#41 and chef/mixlib-install#6.

Those two issues are referencing a limit of `3040` characters unencoded.  With my proxies added I'm at `3133` characters.  Removing the proxies yields `2881` characters.  That runs, but of course fails because I'm behind proxies.  Adding just one(https, the longer) of the two (http/https) proxies back, yields `3009` characters, which runs, but doesn't work again, because some requests are http and some are https.

Windows doesn't seem to support any method of updating the proxies in an already running powershell, without actually doing it in 'that' powershell.  And of course it would have to be done before the chef session starts so chef knows about it.  I'm currently trying to figure out if I can setup a second cookbook to run ahead of time, set them globally, and then reboot.  Then have the actual test-kitchen session run to test what I actually need to test.  

The other idea I'm planning to try is to install and configure ssh on the windows test node, then see if I can just do the connection that way and avoid winrm's brokenness all together.

The last idea I have to try is to hack test-kitchen some to remove the double setting of the environment variables, since windows is case insensitive anyway.  In theory that should work...

**Comment by mwrock** [comment]
Not sure where the 3040 limit is referenced itts actually 8k .For instance, when using the winrm-transport gem, test-kitcen is mindful of tyhis limit as it streams content to the test instance. see https://github.com/test-kitchen/winrm-transport/blob/master/lib/winrm/transport/file_transporter.rb#L116.

While its carful not to overstep this limit uploading files, this may ba a case where the limit is not checked. Could you run in debug mode to get a full stack trace of the error?

**Comment by stevehedrick** [comment]
Here's the debug output, my proxies are a little longer, as I've realized I had to pass along the domain information as well.  They're cleaned (along with the winrm login info) but they're the actual lengths.
```
$ kitchen converge Windows -l DEBUG
-----> Starting Kitchen (v1.4.2)
D      Berksfile found at /Users/shedrick/Documents/Code/chef/chef/cookbooks/hl-logstash/Berksfile, loading Berkshelf
D      Berkshelf 4.0.1 library loaded
D      Berksfile found at /Users/shedrick/Documents/Code/chef/chef/cookbooks/hl-logstash/Berksfile, loading Berkshelf
D      Berkshelf 4.0.1 previously loaded
D      Winrm Transport requested, loading WinRM::Transport gem (~> 1.0)
D      WinRM::Transport 1.0.2 library loaded
-----> Converging <default-Windows>...
       Preparing files for transfer
D      Creating local sandbox in /var/folders/l7/1nqrys1n0sq1qf6_3gn_b804cw6pz3/T/default-Windows-sandbox-20151023-77983-9u0mzl
       Preparing dna.json
D      Creating dna.json from {:run_list=>["recipe[hl-logstash::logstash]"]}
       Resolving cookbook dependencies with Berkshelf 4.0.1...
D      Using Berksfile from /Users/shedrick/Documents/Code/chef/chef/cookbooks/hl-logstash/Berksfile
       Removing non-cookbook files before transfer
       Preparing validation.pem
D      Using a dummy validation.pem
       Preparing client.rb
D      Creating client.rb from {:node_name=>"default-Windows", :checksum_path=>"\#{ENV['TEMP']}\\kitchen\\checksums", :file_cache_path=>"\#{ENV['TEMP']}\\kitchen\\cache", :file_backup_path=>"\#{ENV['TEMP']}\\kitchen\\backup", :cookbook_path=>["\#{ENV['TEMP']}\\kitchen\\cookbooks", "\#{ENV['TEMP']}\\kitchen\\site-cookbooks"], :data_bag_path=>"\#{ENV['TEMP']}\\kitchen\\data_bags", :environment_path=>"\#{ENV['TEMP']}\\kitchen\\environments", :node_path=>"\#{ENV['TEMP']}\\kitchen\\nodes", :role_path=>"\#{ENV['TEMP']}\\kitchen\\roles", :client_path=>"\#{ENV['TEMP']}\\kitchen\\clients", :user_path=>"\#{ENV['TEMP']}\\kitchen\\users", :validation_key=>"\#{ENV['TEMP']}\\kitchen\\validation.pem", :client_key=>"\#{ENV['TEMP']}\\kitchen\\client.pem", :chef_server_url=>"http://127.0.0.1:8889", :encrypted_data_bag_secret=>"\#{ENV['TEMP']}\\kitchen\\encrypted_data_bag_secret"}
D      [WinRM] plaintext::http://MLVTCDEV29:5985/wsman<{:disable_sspi=>true, :basic_auth_only=>true, :user=>"uuuuuuuuuuu", :pass=>"ppppppppppp"}> ($env:http_proxy = "http://ddddddddddddddd%5Cuuuuuuuuuuu:pppppppp@myproxyserver"
$env:HTTP_PROXY = "http://ddddddddddddddd%5Cuuuuuuuuuuu:pppppppp@myproxyserver"
$env:https_proxy = "https://ddddddddddddddd%5Cuuuuuuuuuuu:pppppppp@myproxyserver"
$env:HTTPS_PROXY = "https://ddddddddddddddd%5Cuuuuuuuuuuu:pppppppp@myproxyserver"
$chef_metadata_url = "https://www.chef.io/chef/metadata?p=windows&m=x86_64&pv=2008r2&v=latest"
$chef_omnibus_root = "$env:systemdrive\opscode\chef"
$msi = "$env:TEMP\chef-true.msi"
$pretty_version = "install only if missing"
$version = "true"

Function Check-UpdateChef($root, $version) {
  if (-Not (Test-Path $root)) { return $true }
  elseif ("$version" -eq "true") { return $false }
  elseif ("$version" -eq "latest") { return $true }
  Try { $chef_version = Get-Content $root\version-manifest.txt | select-object -1}
  Catch {
    Try { $chef_version = (& $root\bin\chef-solo.bat -v).split(" ", 2)[1] }
    Catch { $chef_version = "" }
  }

  if ($chef_version.StartsWith($version)) { return $false }
  else { return $true }
}

Function Get-ChefMetadata($url) {
  Try { $response = ($c = Make-WebClient).DownloadString($url) }
  Finally { if ($c -ne $null) { $c.Dispose() } }

  $md = ConvertFrom-StringData $response.Replace("`t", "=")
  return @($md.url, $md.md5)
}

Function Get-MD5Sum($src) {
  Try {
    $c = New-Object -TypeName System.Security.Cryptography.MD5CryptoServiceProvider
    $bytes = $c.ComputeHash(($in = (Get-Item $src).OpenRead()))
    return ([System.BitConverter]::ToString($bytes)).Replace("-", "").ToLower()
  } Finally { if (($c -ne $null) -and ($c.GetType().GetMethod("Dispose") -ne $null)) { $c.Dispose() }; if ($in -ne $null) { $in.Dispose() } }
}

Function Download-Chef($md_url, $dst) {
  $url, $md5 = Get-ChefMetadata $md_url

  Try {
    Log "Downloading package from $url"
    ($c = Make-WebClient).DownloadFile($url, $dst)
    Log "Download complete."
  } Finally { if ($c -ne $null) { $c.Dispose() } }

  if (($dmd5 = Get-MD5Sum $dst) -eq $md5) { Log "Successfully verified $dst" }
  else { throw "MD5 for $dst $dmd5 does not match $md5" }
}

Function Install-Chef($msi) {
  Log "Installing Chef Omnibus package $msi"
  $p = Start-Process -FilePath "msiexec.exe" -ArgumentList "/qn /i $msi" -Passthru -Wait

  if ($p.ExitCode -ne 0) { throw "msiexec was not successful. Received exit code $($p.ExitCode)" }

  Remove-Item $msi -Force
  Log "Installation complete"
}

Function Log($m) { Write-Host "       $m`n" }

Function Make-WebClient {
  $proxy = New-Object -TypeName System.Net.WebProxy
  $proxy.Address = $env:http_proxy
  $client = New-Object -TypeName System.Net.WebClient
  $client.Proxy = $proxy
  return $client
}

Function Unresolve-Path($p) {
  if ($p -eq $null) { return $null }
  else { return $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($p) }
}

$chef_omnibus_root = Unresolve-Path $chef_omnibus_root
$msi = Unresolve-Path $msi

if (Check-UpdateChef $chef_omnibus_root $version) {
  Write-Host "-----> Installing Chef Omnibus ($pretty_version)`n"
  Download-Chef "$chef_metadata_url" $msi
  Install-Chef $msi
} else {
  Write-Host "-----> Chef Omnibus installation detected ($pretty_version)`n"
}
)
D      [WinRM] opening remote shell on plaintext::http://MLVTCDEV29:5985/wsman<{:disable_sspi=>true, :basic_auth_only=>true, :user=>"uuuuuuuuuuu", :pass=>"ppppppppppp"}>
D      [WinRM] remote shell 4DCF9473-1600-48E9-A16A-0A147BF649F2 is open on plaintext::http://MLVTCDEV29:5985/wsman<{:disable_sspi=>true, :basic_auth_only=>true, :user=>"uuuuuuuuuuu", :pass=>"ppppppppppp"}>
$$$$$$ The command line is too long.
D      Cleaning up local sandbox in /var/folders/l7/1nqrys1n0sq1qf6_3gn_b804cw6pz3/T/default-Windows-sandbox-20151023-77983-9u0mzl
>>>>>> Converge failed on instance <default-Windows>.
>>>>>> Please see .kitchen/logs/default-Windows.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: WinRM exited (1) for command: [$env:http_proxy = "http://ddddddddddddddd%5Cuuuuuuuuuuu:pppppppp@myproxyserver"
$env:HTTP_PROXY = "http://ddddddddddddddd%5Cuuuuuuuuuuu:pppppppp@myproxyserver"
$env:https_proxy = "https://ddddddddddddddd%5Cuuuuuuuuuuu:pppppppp@myproxyserver"
$env:HTTPS_PROXY = "https://ddddddddddddddd%5Cuuuuuuuuuuu:pppppppp@myproxyserver"
$chef_metadata_url = "https://www.chef.io/chef/metadata?p=windows&m=x86_64&pv=2008r2&v=latest"
$chef_omnibus_root = "$env:systemdrive\opscode\chef"
$msi = "$env:TEMP\chef-true.msi"
$pretty_version = "install only if missing"
$version = "true"

Function Check-UpdateChef($root, $version) {
  if (-Not (Test-Path $root)) { return $true }
  elseif ("$version" -eq "true") { return $false }
  elseif ("$version" -eq "latest") { return $true }
  Try { $chef_version = Get-Content $root\version-manifest.txt | select-object -1}
  Catch {
    Try { $chef_version = (& $root\bin\chef-solo.bat -v).split(" ", 2)[1] }
    Catch { $chef_version = "" }
  }

  if ($chef_version.StartsWith($version)) { return $false }
  else { return $true }
}

Function Get-ChefMetadata($url) {
  Try { $response = ($c = Make-WebClient).DownloadString($url) }
  Finally { if ($c -ne $null) { $c.Dispose() } }

  $md = ConvertFrom-StringData $response.Replace("`t", "=")
  return @($md.url, $md.md5)
}

Function Get-MD5Sum($src) {
  Try {
    $c = New-Object -TypeName System.Security.Cryptography.MD5CryptoServiceProvider
    $bytes = $c.ComputeHash(($in = (Get-Item $src).OpenRead()))
    return ([System.BitConverter]::ToString($bytes)).Replace("-", "").ToLower()
  } Finally { if (($c -ne $null) -and ($c.GetType().GetMethod("Dispose") -ne $null)) { $c.Dispose() }; if ($in -ne $null) { $in.Dispose() } }
}

Function Download-Chef($md_url, $dst) {
  $url, $md5 = Get-ChefMetadata $md_url

  Try {
    Log "Downloading package from $url"
    ($c = Make-WebClient).DownloadFile($url, $dst)
    Log "Download complete."
  } Finally { if ($c -ne $null) { $c.Dispose() } }

  if (($dmd5 = Get-MD5Sum $dst) -eq $md5) { Log "Successfully verified $dst" }
  else { throw "MD5 for $dst $dmd5 does not match $md5" }
}

Function Install-Chef($msi) {
  Log "Installing Chef Omnibus package $msi"
  $p = Start-Process -FilePath "msiexec.exe" -ArgumentList "/qn /i $msi" -Passthru -Wait

  if ($p.ExitCode -ne 0) { throw "msiexec was not successful. Received exit code $($p.ExitCode)" }

  Remove-Item $msi -Force
  Log "Installation complete"
}

Function Log($m) { Write-Host "       $m`n" }

Function Make-WebClient {
  $proxy = New-Object -TypeName System.Net.WebProxy
  $proxy.Address = $env:http_proxy
  $client = New-Object -TypeName System.Net.WebClient
  $client.Proxy = $proxy
  return $client
}

Function Unresolve-Path($p) {
  if ($p -eq $null) { return $null }
  else { return $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($p) }
}

$chef_omnibus_root = Unresolve-Path $chef_omnibus_root
$msi = Unresolve-Path $msi

if (Check-UpdateChef $chef_omnibus_root $version) {
  Write-Host "-----> Installing Chef Omnibus ($pretty_version)`n"
  Download-Chef "$chef_metadata_url" $msi
  Install-Chef $msi
} else {
  Write-Host "-----> Chef Omnibus installation detected ($pretty_version)`n"
}
]
>>>>>> ----------------------
D      Converge failed on instance <default-Windows>.
D      ------Exception-------
D      Class: Kitchen::InstanceFailure
D      Message: Converge failed on instance <default-Windows>.  Please see .kitchen/logs/default-Windows.log for more details
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: WinRM exited (1) for command: [$env:http_proxy = "http://ddddddddddddddd%5Cuuuuuuuuuuu:pppppppp@myproxyserver"
$env:HTTP_PROXY = "http://ddddddddddddddd%5Cuuuuuuuuuuu:pppppppp@myproxyserver"
$env:https_proxy = "https://ddddddddddddddd%5Cuuuuuuuuuuu:pppppppp@myproxyserver"
$env:HTTPS_PROXY = "https://ddddddddddddddd%5Cuuuuuuuuuuu:pppppppp@myproxyserver"
$chef_metadata_url = "https://www.chef.io/chef/metadata?p=windows&m=x86_64&pv=2008r2&v=latest"
$chef_omnibus_root = "$env:systemdrive\opscode\chef"
$msi = "$env:TEMP\chef-true.msi"
$pretty_version = "install only if missing"
$version = "true"

Function Check-UpdateChef($root, $version) {
  if (-Not (Test-Path $root)) { return $true }
  elseif ("$version" -eq "true") { return $false }
  elseif ("$version" -eq "latest") { return $true }
  Try { $chef_version = Get-Content $root\version-manifest.txt | select-object -1}
  Catch {
    Try { $chef_version = (& $root\bin\chef-solo.bat -v).split(" ", 2)[1] }
    Catch { $chef_version = "" }
  }

  if ($chef_version.StartsWith($version)) { return $false }
  else { return $true }
}

Function Get-ChefMetadata($url) {
  Try { $response = ($c = Make-WebClient).DownloadString($url) }
  Finally { if ($c -ne $null) { $c.Dispose() } }

  $md = ConvertFrom-StringData $response.Replace("`t", "=")
  return @($md.url, $md.md5)
}

Function Get-MD5Sum($src) {
  Try {
    $c = New-Object -TypeName System.Security.Cryptography.MD5CryptoServiceProvider
    $bytes = $c.ComputeHash(($in = (Get-Item $src).OpenRead()))
    return ([System.BitConverter]::ToString($bytes)).Replace("-", "").ToLower()
  } Finally { if (($c -ne $null) -and ($c.GetType().GetMethod("Dispose") -ne $null)) { $c.Dispose() }; if ($in -ne $null) { $in.Dispose() } }
}

Function Download-Chef($md_url, $dst) {
  $url, $md5 = Get-ChefMetadata $md_url

  Try {
    Log "Downloading package from $url"
    ($c = Make-WebClient).DownloadFile($url, $dst)
    Log "Download complete."
  } Finally { if ($c -ne $null) { $c.Dispose() } }

  if (($dmd5 = Get-MD5Sum $dst) -eq $md5) { Log "Successfully verified $dst" }
  else { throw "MD5 for $dst $dmd5 does not match $md5" }
}

Function Install-Chef($msi) {
  Log "Installing Chef Omnibus package $msi"
  $p = Start-Process -FilePath "msiexec.exe" -ArgumentList "/qn /i $msi" -Passthru -Wait

  if ($p.ExitCode -ne 0) { throw "msiexec was not successful. Received exit code $($p.ExitCode)" }

  Remove-Item $msi -Force
  Log "Installation complete"
}

Function Log($m) { Write-Host "       $m`n" }

Function Make-WebClient {
  $proxy = New-Object -TypeName System.Net.WebProxy
  $proxy.Address = $env:http_proxy
  $client = New-Object -TypeName System.Net.WebClient
  $client.Proxy = $proxy
  return $client
}

Function Unresolve-Path($p) {
  if ($p -eq $null) { return $null }
  else { return $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($p) }
}

$chef_omnibus_root = Unresolve-Path $chef_omnibus_root
$msi = Unresolve-Path $msi

if (Check-UpdateChef $chef_omnibus_root $version) {
  Write-Host "-----> Installing Chef Omnibus ($pretty_version)`n"
  Download-Chef "$chef_metadata_url" $msi
  Install-Chef $msi
} else {
  Write-Host "-----> Chef Omnibus installation detected ($pretty_version)`n"
}
]
D      ------Backtrace-------
D      /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/provisioner/base.rb:74:in `rescue in call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/provisioner/base.rb:77:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:366:in `block in converge_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:488:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:488:in `synchronize_or_call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:453:in `block in action'
D      /opt/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
D      /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:452:in `action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:362:in `converge_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:341:in `block in transition_to'
D      /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:340:in `each'
D      /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:340:in `transition_to'
D      /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:138:in `converge'
D      /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/command.rb:176:in `public_send'
D      /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
D      ----------------------
D      [CommandExecutor] closing remote shell 4DCF9473-1600-48E9-A16A-0A147BF649F2 on plaintext::http://MLVTCDEV29:5985/wsman<{:disable_sspi=>true, :basic_auth_only=>true, :user=>"uuuuuuuuuuu", :pass=>"ppppppppppp"}>
D      [CommandExecutor] remote shell 4DCF9473-1600-48E9-A16A-0A147BF649F2 closed

```

**Comment by mwrock** [comment]
Here is what is going on. WinRM (actually cmd.exe) has an 8k command line limit. The command you pasted above that test-kitchen is sending over is almost *exactly* 4k. WinRM converts the UTF-8 command to UTF-16 and then base64 encodes it which doubles the byte count. So the fact that you are so close to the threshold explains why just a few characters causes this error.

It seems like one way to fix this would be for test-kitchen to save this script (or the vast bulk of it) on the box beforehand to take advantage of the file copy functionality which accounts for this limit.

**Comment by stevehedrick** [comment]
Looks like my proxies are too long even with the slightly shorter test-kitchen 1.4.1 support/chef_base_install_command.ps1 running.  Sadly it makes it through if I leave out the domain info with 1.4.1, but that doesn't really help since I can't authenticate to the proxy without it.  @mwrock thank you for helping to diagnose the problem.
