### ISSUE TITLE
SSH Transport with Windows doesn't appear to work

### ISSUE THREAD

**Issue by icberg7** [test-kitchen/test-kitchen#868]
It seems like WinRM is the preferred/recommended transport for Windows based hosts; however, there are a number of things that Microsoft explicitly disallows when using WinRM/Powershell over a remote connection, including windows update methods.
The list can be found here:
https://msdn.microsoft.com/en-us/library/windows/desktop/aa387288(v=vs.85).aspx

For regular chef runs, this isn't a problem, as a scheduled task runs chef-client locally and Windows is happy. Our server images have WinSSHD installed by default, and we already use ssh instead of WinRM to bootstrap nodes using the default cmd shell. However, I have not been able to get Test Kitchen working with Windows at all. Kitchen defaults to PowerShell for all Windows hosts, so it still tries to shove a powershell script in there and it fails miserably. I've reconfigured WinSSHD on a test host to use PowerShell as the default login shell, and test kitchen still fails immediately when trying to call the initial converge script. I see successful logins in WinSSHD, and I can confirm that logging in via ssh gets you a powershell shell. 

I've attached the log output below:

```
D, [2015-10-27T16:09:39.667425 #4063] DEBUG -- default-win2k8: Berksfile found at /home/icberg7/git/icberg7_patch/Berksfile, loading Berkshelf
D, [2015-10-27T16:09:39.667553 #4063] DEBUG -- default-win2k8: Berkshelf 3.2.4 previously loaded
I, [2015-10-27T16:09:39.669242 #4063]  INFO -- default-win2k8: -----> Converging <default-win2k8>...
I, [2015-10-27T16:09:39.669766 #4063]  INFO -- default-win2k8: Preparing files for transfer
D, [2015-10-27T16:09:39.669904 #4063] DEBUG -- default-win2k8: Creating local sandbox in /tmp/default-win2k8-sandbox-20151027-4063-15ivchi
I, [2015-10-27T16:09:39.670018 #4063]  INFO -- default-win2k8: Preparing dna.json
D, [2015-10-27T16:09:39.670176 #4063] DEBUG -- default-win2k8: Creating dna.json from {:run_list=>["recipe[minitest-handler]", "recipe[icberg7_patch::default]", "recipe[icberg7_patch::heartbleed_fix]", "recipe[icberg7_patch::shellshock_fix]", "recipe[icberg7_patch::glibc]", "recipe[icberg7_patch::windows_powershell]"]}
I, [2015-10-27T16:09:39.670448 #4063]  INFO -- default-win2k8: Resolving cookbook dependencies with Berkshelf 3.2.4...
D, [2015-10-27T16:09:39.670559 #4063] DEBUG -- default-win2k8: Using Berksfile from /home/icberg7/git/icberg7_patch/Berksfile
I, [2015-10-27T16:09:40.478838 #4063]  INFO -- default-win2k8: Removing non-cookbook files before transfer
I, [2015-10-27T16:09:40.485060 #4063]  INFO -- default-win2k8: Preparing data_bags
D, [2015-10-27T16:09:40.485282 #4063] DEBUG -- default-win2k8: Using data_bags from /home/icberg7/git/icberg7_patch/test/fixtures/data_bags
I, [2015-10-27T16:09:40.485671 #4063]  INFO -- default-win2k8: Preparing environments
D, [2015-10-27T16:09:40.485775 #4063] DEBUG -- default-win2k8: Using environments from /home/icberg7/git/icberg7_patch/test/fixtures/environments
I, [2015-10-27T16:09:40.486176 #4063]  INFO -- default-win2k8: Preparing validation.pem
D, [2015-10-27T16:09:40.486277 #4063] DEBUG -- default-win2k8: Using a dummy validation.pem
I, [2015-10-27T16:09:40.486565 #4063]  INFO -- default-win2k8: Preparing client.rb
D, [2015-10-27T16:09:40.486751 #4063] DEBUG -- default-win2k8: Creating client.rb from {:node_name=>"default-win2k8", :checksum_path=>"\#{ENV['TEMP']}\\kitchen\\checksums", :file_cache_path=>"\#{ENV['TEMP']}\\kitchen\\cache", :file_backup_path=>"\#{ENV['TEMP']}\\kitchen\\backup", :cookbook_path=>["\#{ENV['TEMP']}\\kitchen\\cookbooks", "\#{ENV['TEMP']}\\kitchen\\site-cookbooks"], :data_bag_path=>"\#{ENV['TEMP']}\\kitchen\\data_bags", :environment_path=>"\#{ENV['TEMP']}\\kitchen\\environments", :node_path=>"\#{ENV['TEMP']}\\kitchen\\nodes", :role_path=>"\#{ENV['TEMP']}\\kitchen\\roles", :client_path=>"\#{ENV['TEMP']}\\kitchen\\clients", :user_path=>"\#{ENV['TEMP']}\\kitchen\\users", :validation_key=>"\#{ENV['TEMP']}\\kitchen\\validation.pem", :client_key=>"\#{ENV['TEMP']}\\kitchen\\client.pem", :chef_server_url=>"http://127.0.0.1:8889", :encrypted_data_bag_secret=>"\#{ENV['TEMP']}\\kitchen\\encrypted_data_bag_secret"}
D, [2015-10-27T16:09:40.487534 #4063] DEBUG -- default-win2k8: [SSH] cloud-user@X.X.X.X<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>22, :compression=>true, :compression_level=>6, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :password=>"XXXXXXXXXXXXXXX"}> (
$chef_metadata_url = "https://www.chef.io/chef/metadata?p=windows&m=x86_64&pv=2008r2&v=12.5.1"
$chef_omnibus_root = "$env:systemdrive\opscode\chef"
$msi = "$env:TEMP\chef-12.5.1.msi"
$pretty_version = "12.5.1"
$version = "12.5.1"

Function Check-UpdateChef($root, $version) {
  if (-Not (Test-Path $root)) { return $true }
  elseif ("$version" -eq "true") { return $false }
  elseif ("$version" -eq "latest") { return $true }
  Try { $chef_version = Get-Content $root\version-manifest.txt | select-object -1}
  Catch {
    Try { $chef_version = (& $root\bin\chef-solo.bat -v).split(" ", 2)[1] }
    Catch { $chef_version = "" }
  }

  if ($chef_version.StartsWith($version)) { return $false }
  else { return $true }
}

Function Get-ChefMetadata($url) {
  Try { $response = ($c = Make-WebClient).DownloadString($url) }
  Finally { if ($c -ne $null) { $c.Dispose() } }

  $md = ConvertFrom-StringData $response.Replace("`t", "=")
  return @($md.url, $md.md5)
}

Function Get-MD5Sum($src) {
  Try {
    $c = New-Object -TypeName System.Security.Cryptography.MD5CryptoServiceProvider
    $bytes = $c.ComputeHash(($in = (Get-Item $src).OpenRead()))
    return ([System.BitConverter]::ToString($bytes)).Replace("-", "").ToLower()
  } Finally { if (($c -ne $null) -and ($c.GetType().GetMethod("Dispose") -ne $null)) { $c.Dispose() }; if ($in -ne $null) { $in.Dispose() } }
}

Function Download-Chef($md_url, $dst) {
  $url, $md5 = Get-ChefMetadata $md_url

  Try {
    Log "Downloading package from $url"
    ($c = Make-WebClient).DownloadFile($url, $dst)
    Log "Download complete."
  } Finally { if ($c -ne $null) { $c.Dispose() } }

  if (($dmd5 = Get-MD5Sum $dst) -eq $md5) { Log "Successfully verified $dst" }
  else { throw "MD5 for $dst $dmd5 does not match $md5" }
}

Function Install-Chef($msi) {
  Log "Installing Chef Omnibus package $msi"
  $p = Start-Process -FilePath "msiexec.exe" -ArgumentList "/qn /i $msi" -Passthru -Wait

  if ($p.ExitCode -ne 0) { throw "msiexec was not successful. Received exit code $($p.ExitCode)" }

  Remove-Item $msi -Force
  Log "Installation complete"
}

Function Log($m) { Write-Host "       $m`n" }

Function Make-WebClient {
  $proxy = New-Object -TypeName System.Net.WebProxy
  $proxy.Address = $env:http_proxy
  $client = New-Object -TypeName System.Net.WebClient
  $client.Proxy = $proxy
  return $client
}

Function Unresolve-Path($p) {
  if ($p -eq $null) { return $null }
  else { return $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($p) }
}

$chef_omnibus_root = Unresolve-Path $chef_omnibus_root
$msi = Unresolve-Path $msi

if (Check-UpdateChef $chef_omnibus_root $version) {
  Write-Host "-----> Installing Chef Omnibus ($pretty_version)`n"
  Download-Chef "$chef_metadata_url" $msi
  Install-Chef $msi
} else {
  Write-Host "-----> Chef Omnibus installation detected ($pretty_version)`n"
}
)
D, [2015-10-27T16:09:40.491281 #4063] DEBUG -- default-win2k8: [SSH] opening connection to cloud-user@X.X.X.X<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>22, :compression=>true, :compression_level=>6, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :password=>"XXXXXXXXXXXXXX"}>
D, [2015-10-27T16:09:41.871575 #4063] DEBUG -- default-win2k8: Cleaning up local sandbox in /tmp/default-win2k8-sandbox-20151027-4063-15ivchi
E, [2015-10-27T16:09:41.883736 #4063] ERROR -- default-win2k8: Converge failed on instance <default-win2k8>.
E, [2015-10-27T16:09:41.883881 #4063] ERROR -- default-win2k8: ------Exception-------
E, [2015-10-27T16:09:41.883906 #4063] ERROR -- default-win2k8: Class: Kitchen::ActionFailed
E, [2015-10-27T16:09:41.883936 #4063] ERROR -- default-win2k8: Message: SSH exited (1) for command: [
$chef_metadata_url = "https://www.chef.io/chef/metadata?p=windows&m=x86_64&pv=2008r2&v=12.5.1"
$chef_omnibus_root = "$env:systemdrive\opscode\chef"
$msi = "$env:TEMP\chef-12.5.1.msi"
$pretty_version = "12.5.1"
$version = "12.5.1"

Function Check-UpdateChef($root, $version) {
  if (-Not (Test-Path $root)) { return $true }
  elseif ("$version" -eq "true") { return $false }
  elseif ("$version" -eq "latest") { return $true }
  Try { $chef_version = Get-Content $root\version-manifest.txt | select-object -1}
  Catch {
    Try { $chef_version = (& $root\bin\chef-solo.bat -v).split(" ", 2)[1] }
    Catch { $chef_version = "" }
  }

  if ($chef_version.StartsWith($version)) { return $false }
  else { return $true }
}

Function Get-ChefMetadata($url) {
  Try { $response = ($c = Make-WebClient).DownloadString($url) }
  Finally { if ($c -ne $null) { $c.Dispose() } }

  $md = ConvertFrom-StringData $response.Replace("`t", "=")
  return @($md.url, $md.md5)
}

Function Get-MD5Sum($src) {
  Try {
    $c = New-Object -TypeName System.Security.Cryptography.MD5CryptoServiceProvider
    $bytes = $c.ComputeHash(($in = (Get-Item $src).OpenRead()))
    return ([System.BitConverter]::ToString($bytes)).Replace("-", "").ToLower()
  } Finally { if (($c -ne $null) -and ($c.GetType().GetMethod("Dispose") -ne $null)) { $c.Dispose() }; if ($in -ne $null) { $in.Dispose() } }
}

Function Download-Chef($md_url, $dst) {
  $url, $md5 = Get-ChefMetadata $md_url

  Try {
    Log "Downloading package from $url"
    ($c = Make-WebClient).DownloadFile($url, $dst)
    Log "Download complete."
  } Finally { if ($c -ne $null) { $c.Dispose() } }

  if (($dmd5 = Get-MD5Sum $dst) -eq $md5) { Log "Successfully verified $dst" }
  else { throw "MD5 for $dst $dmd5 does not match $md5" }
}

Function Install-Chef($msi) {
  Log "Installing Chef Omnibus package $msi"
  $p = Start-Process -FilePath "msiexec.exe" -ArgumentList "/qn /i $msi" -Passthru -Wait

  if ($p.ExitCode -ne 0) { throw "msiexec was not successful. Received exit code $($p.ExitCode)" }

  Remove-Item $msi -Force
  Log "Installation complete"
}

Function Log($m) { Write-Host "       $m`n" }

Function Make-WebClient {
  $proxy = New-Object -TypeName System.Net.WebProxy
  $proxy.Address = $env:http_proxy
  $client = New-Object -TypeName System.Net.WebClient
  $client.Proxy = $proxy
  return $client
}

Function Unresolve-Path($p) {
  if ($p -eq $null) { return $null }
  else { return $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($p) }
}

$chef_omnibus_root = Unresolve-Path $chef_omnibus_root
$msi = Unresolve-Path $msi

if (Check-UpdateChef $chef_omnibus_root $version) {
  Write-Host "-----> Installing Chef Omnibus ($pretty_version)`n"
  Download-Chef "$chef_metadata_url" $msi
  Install-Chef $msi
} else {
  Write-Host "-----> Chef Omnibus installation detected ($pretty_version)`n"
}
]
E, [2015-10-27T16:09:41.883961 #4063] ERROR -- default-win2k8: ---Nested Exception---
E, [2015-10-27T16:09:41.883976 #4063] ERROR -- default-win2k8: Class: Kitchen::Transport::SshFailed
E, [2015-10-27T16:09:41.883988 #4063] ERROR -- default-win2k8: Message: SSH exited (1) for command: [
$chef_metadata_url = "https://www.chef.io/chef/metadata?p=windows&m=x86_64&pv=2008r2&v=12.5.1"
$chef_omnibus_root = "$env:systemdrive\opscode\chef"
$msi = "$env:TEMP\chef-12.5.1.msi"
$pretty_version = "12.5.1"
$version = "12.5.1"

Function Check-UpdateChef($root, $version) {
  if (-Not (Test-Path $root)) { return $true }
  elseif ("$version" -eq "true") { return $false }
  elseif ("$version" -eq "latest") { return $true }
  Try { $chef_version = Get-Content $root\version-manifest.txt | select-object -1}
  Catch {
    Try { $chef_version = (& $root\bin\chef-solo.bat -v).split(" ", 2)[1] }
    Catch { $chef_version = "" }
  }

  if ($chef_version.StartsWith($version)) { return $false }
  else { return $true }
}

Function Get-ChefMetadata($url) {
  Try { $response = ($c = Make-WebClient).DownloadString($url) }
  Finally { if ($c -ne $null) { $c.Dispose() } }

  $md = ConvertFrom-StringData $response.Replace("`t", "=")
  return @($md.url, $md.md5)
}

Function Get-MD5Sum($src) {
  Try {
    $c = New-Object -TypeName System.Security.Cryptography.MD5CryptoServiceProvider
    $bytes = $c.ComputeHash(($in = (Get-Item $src).OpenRead()))
    return ([System.BitConverter]::ToString($bytes)).Replace("-", "").ToLower()
  } Finally { if (($c -ne $null) -and ($c.GetType().GetMethod("Dispose") -ne $null)) { $c.Dispose() }; if ($in -ne $null) { $in.Dispose() } }
}

Function Download-Chef($md_url, $dst) {
  $url, $md5 = Get-ChefMetadata $md_url

  Try {
    Log "Downloading package from $url"
    ($c = Make-WebClient).DownloadFile($url, $dst)
    Log "Download complete."
  } Finally { if ($c -ne $null) { $c.Dispose() } }

  if (($dmd5 = Get-MD5Sum $dst) -eq $md5) { Log "Successfully verified $dst" }
  else { throw "MD5 for $dst $dmd5 does not match $md5" }
}

Function Install-Chef($msi) {
  Log "Installing Chef Omnibus package $msi"
  $p = Start-Process -FilePath "msiexec.exe" -ArgumentList "/qn /i $msi" -Passthru -Wait

  if ($p.ExitCode -ne 0) { throw "msiexec was not successful. Received exit code $($p.ExitCode)" }

  Remove-Item $msi -Force
  Log "Installation complete"
}

Function Log($m) { Write-Host "       $m`n" }

Function Make-WebClient {
  $proxy = New-Object -TypeName System.Net.WebProxy
  $proxy.Address = $env:http_proxy
  $client = New-Object -TypeName System.Net.WebClient
  $client.Proxy = $proxy
  return $client
}

Function Unresolve-Path($p) {
  if ($p -eq $null) { return $null }
  else { return $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($p) }
}

$chef_omnibus_root = Unresolve-Path $chef_omnibus_root
$msi = Unresolve-Path $msi

if (Check-UpdateChef $chef_omnibus_root $version) {
  Write-Host "-----> Installing Chef Omnibus ($pretty_version)`n"
  Download-Chef "$chef_metadata_url" $msi
  Install-Chef $msi
} else {
  Write-Host "-----> Chef Omnibus installation detected ($pretty_version)`n"
}
]
E, [2015-10-27T16:09:41.884005 #4063] ERROR -- default-win2k8: ------Backtrace-------
E, [2015-10-27T16:09:41.884018 #4063] ERROR -- default-win2k8: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/provisioner/base.rb:74:in `rescue in call'
E, [2015-10-27T16:09:41.884032 #4063] ERROR -- default-win2k8: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/provisioner/base.rb:77:in `call'
E, [2015-10-27T16:09:41.884045 #4063] ERROR -- default-win2k8: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:366:in `block in converge_action'
E, [2015-10-27T16:09:41.884057 #4063] ERROR -- default-win2k8: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:488:in `call'
E, [2015-10-27T16:09:41.884082 #4063] ERROR -- default-win2k8: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:488:in `synchronize_or_call'
E, [2015-10-27T16:09:41.884095 #4063] ERROR -- default-win2k8: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:453:in `block in action'
E, [2015-10-27T16:09:41.884558 #4063] ERROR -- default-win2k8: /opt/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
E, [2015-10-27T16:09:41.884603 #4063] ERROR -- default-win2k8: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:452:in `action'
E, [2015-10-27T16:09:41.884635 #4063] ERROR -- default-win2k8: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:362:in `converge_action'
E, [2015-10-27T16:09:41.884670 #4063] ERROR -- default-win2k8: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:341:in `block in transition_to'
E, [2015-10-27T16:09:41.884705 #4063] ERROR -- default-win2k8: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:340:in `each'
E, [2015-10-27T16:09:41.884720 #4063] ERROR -- default-win2k8: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:340:in `transition_to'
E, [2015-10-27T16:09:41.884733 #4063] ERROR -- default-win2k8: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:138:in `converge'
E, [2015-10-27T16:09:41.884746 #4063] ERROR -- default-win2k8: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/command.rb:176:in `public_send'
E, [2015-10-27T16:09:41.884773 #4063] ERROR -- default-win2k8: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
E, [2015-10-27T16:09:41.884787 #4063] ERROR -- default-win2k8: ----------------------
```

This is using Chef DK 0.9.0 and Chef 12.5.1.

**Comment by hh** [comment]
https://github.com/WinRb/winrm-elevated should eventually be integrated into test-kitchen

openssh is now getting some official support from MS: http://blogs.msdn.com/b/powershell/archive/2015/06/03/looking-forward-microsoft-support-for-secure-shell-ssh.aspx

**Comment by cheeseplus** [comment]
This was entirely reworked when we changed how `transport` worked and this should work at present with custom transport settings but given the age of this I'm closing - if this is still a problem please open with current versions and we're happy to take a look.
