### ISSUE TITLE
Failing to parse .kitchen.yml with ChefDK 0.9.0 on Windows 7

### ISSUE THREAD

**Issue by predatorian3** [test-kitchen/test-kitchen#877]
I recently upgraded to ChefDK 0.9.0 on Windows 7, and I haven't been able to run Test Kitchen, or rather `kitchen test` since then. The following error output is what I receive. Let me know if this should go under ChefDK rather than this. 

I thought that maybe it was because it was a Windows formatted file, but after doing a dos2unix using Cygwin, I still receive these errors. 

```
C:\Users\user01\Desktop\csm_zabbix_install (master){hg}
λ kitchen test
-----> Starting Kitchen (v1.4.2)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::UserError
>>>>>> Message: Error parsing C:/Users/user01/Desktop/csm_zabbix_install/.kitchen.yml as YAML.
Please run `kitchen diagnose --no-instances --loader' to help debug your issue.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration


C:\Users\user01\Desktop\csm_zabbix_install (master){hg}
λ kitchen diagnose --all`
---
timestamp: 2015-11-09 19:39:20 UTC
kitchen_version: 1.4.2
instances:
  error:
    exception: |-
      #<Kitchen::UserError: Error parsing C:/Users/user01/Desktop/csm_zabbix_install/.kitchen.yml as YAML.
      Please run `kitchen diagnose --no-instances --loader' to help debug your issue.>
    message: |-
      Error parsing C:/Users/user01/Desktop/csm_zabbix_install/.kitchen.yml as YAML.
      Please run `kitchen diagnose --no-instances --loader' to help debug your issue.
    backtrace:
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/loader/yaml.rb:343:in `rescue in parse_yaml_string'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/loader/yaml.rb:332:in `parse_yaml_string'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/loader/yaml.rb:138:in `yaml'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/loader/yaml.rb:126:in `combined_hash'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/loader/yaml.rb:77:in `read'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/config.rb:145:in `data'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/config.rb:124:in `suites'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/config.rb:175:in `filter_instances'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/config.rb:134:in `build_instances'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/config.rb:110:in `instances'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/command.rb:115:in `filtered_instances'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/command.rb:145:in `parse_subcommand'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/command/diagnose.rb:56:in `load_instances'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/command/diagnose.rb:35:in `block in call'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/command/diagnose.rb:80:in `record_failure'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/command/diagnose.rb:35:in `call'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/cli.rb:56:in `perform'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/cli.rb:128:in `diagnose'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/cli.rb:308:in `invoke_task'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/bin/kitchen:13:in `block in <top (required)>'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/errors.rb:154:in `with_friendly_errors'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/bin/kitchen:13:in `<top (required)>'
    - C:/opscode/chefdk/bin/kitchen:16:in `load'
    - C:/opscode/chefdk/bin/kitchen:16:in `<main>'

C:\Users\user01\Desktop\csm_zabbix_install (master){hg}
λ kitchen diagnose --no-instances --loader
---
timestamp: 2015-11-09 19:39:39 UTC
kitchen_version: 1.4.2
loader:
  process_erb: true
  process_local: true
  process_global: true
  global_config:
  project_config:
    filename: C:/Users/user01/Desktop/csm_zabbix_install/.kitchen.yml
    raw_data:
      error:
        exception: |-
          #<Kitchen::UserError: Error parsing C:/Users/user01/Desktop/csm_zabbix_install/.kitchen.yml as YAML.
          Please run `kitchen diagnose --no-instances --loader' to help debug your issue.>
        message: |-
          Error parsing C:/Users/user01/Desktop/csm_zabbix_install/.kitchen.yml as YAML.
          Please run `kitchen diagnose --no-instances --loader' to help debug your issue.
        backtrace:
        - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/loader/yaml.rb:343:in `rescue in parse_yaml_string'
        - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/loader/yaml.rb:332:in `parse_yaml_string'
        - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/loader/yaml.rb:138:in `yaml'
        - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/loader/yaml.rb:237:in `diagnose_component'
        - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/loader/yaml.rb:89:in `diagnose'
        - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/diagnostic.rb:90:in `prepare_loader'
        - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/diagnostic.rb:53:in `read'
        - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/command/diagnose.rb:41:in `call'
        - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/cli.rb:56:in `perform'
        - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/cli.rb:128:in `diagnose'
        - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/cli.rb:308:in `invoke_task'
        - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/bin/kitchen:13:in `block in <top (required)>'
        - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/errors.rb:154:in `with_friendly_errors'
        - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/bin/kitchen:13:in `<top (required)>'
        - C:/opscode/chefdk/bin/kitchen:16:in `load'
        - C:/opscode/chefdk/bin/kitchen:16:in `<main>'
        raw_file: "---\ndriver:\n  name: vagrant\n\n## The forwarded_port port feature
          lets you connect to ports on the VM guest via\n## localhost on the host.\n##
          see also: https://docs.vagrantup.com/v2/networking/forwarded_ports.html\n\n#
          \ network:\n#    - [\"forwarded_port\", {guest: 80, host: 8080}]\n\nprovisioner:\n
          \ name: policyfile_zero\n\n## require_chef_omnibus specifies a specific
          chef version to install. You can\n## also set this to `true` to always use
          the latest version.\n## see also: https://docs.chef.io/config_yml_kitchen.html\n\n#
          \ require_chef_omnibus: 12.5.0\n\nplatforms:\n  - name: CentOS_6_Minimal\n
          \ driver_config:\n    box: CentOS_6_Minimal\n\nsuites:\n  - name: default\n
          \   run_list:\n      - recipe[csm_zabbix::default]\n    attributes: \n"
  local_config:
  combined_config:
    filename:
    raw_data:
      error:
        exception: |-
          #<Kitchen::UserError: Error parsing C:/Users/user01/Desktop/csm_zabbix_install/.kitchen.yml as YAML.
          Please run `kitchen diagnose --no-instances --loader' to help debug your issue.>
        message: |-
          Error parsing C:/Users/user01/Desktop/csm_zabbix_install/.kitchen.yml as YAML.
          Please run `kitchen diagnose --no-instances --loader' to help debug your issue.
        backtrace:
        - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/loader/yaml.rb:343:in `rescue in parse_yaml_string'
        - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/loader/yaml.rb:332:in `parse_yaml_string'
        - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/loader/yaml.rb:138:in `yaml'
        - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/loader/yaml.rb:126:in `combined_hash'
        - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/loader/yaml.rb:237:in `diagnose_component'
        - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/loader/yaml.rb:91:in `diagnose'
        - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/diagnostic.rb:90:in `prepare_loader'
        - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/diagnostic.rb:53:in `read'
        - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/command/diagnose.rb:41:in `call'
        - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/cli.rb:56:in `perform'
        - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/cli.rb:128:in `diagnose'
        - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/cli.rb:308:in `invoke_task'
        - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/bin/kitchen:13:in `block in <top (required)>'
        - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/errors.rb:154:in `with_friendly_errors'
        - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/bin/kitchen:13:in `<top (required)>'
        - C:/opscode/chefdk/bin/kitchen:16:in `load'
        - C:/opscode/chefdk/bin/kitchen:16:in `<main>'
instances: {}
```

**Comment by predatorian3** [comment]
It was a spacing issue in one line. I had to add 2 spaces.

**Comment by rohitsingh186** [comment]
Same spacing issue. Had 4 spaces instead of 2. Thanks for pointing out.
