### ISSUE TITLE
WinrRM "The device is not ready"

### ISSUE THREAD

**Issue by shoekstra** [test-kitchen/test-kitchen#891]
Hello,

I have run into an issue where a Windows VM does not finish it's provisioning step when being created as the Vagrant WinRM retry/max attempts seems to be exhausted before the VM is ready.  While I can run `kitchen create` a second time, the provisioning stage is skipped because the box is seen as already created thus customisations like IP address and hostname are not set. 

If I watch the VM in VirtualBox, I can see it is still booting when this "device not ready" error appears.  I have tried to increase the `retry_delay` and `max_retries` but am not sure if I am doing it correctly.

I have these lines in my `.kitchen.yml` file:

```
platforms:
  - name: windows2012r2
    driver:
      winrm:
        retry_delay: 5
        max_tries: 50
```

Unfortunately this did not make any difference.  Below is the debug output of an attempt to create a VM.  I've also been able to replicate this on my colleague's Mac, we're both using Chef-DK 0.10.0.

```
$ time kitchen create StandaloneRootCA-windows2012r2 -l debug
-----> Starting Kitchen (v1.4.2)
D      [Vagrant command] BEGIN (vagrant --version)
D      [Vagrant command] END (0m0.18s)
D      [Vagrant command] BEGIN (vagrant plugin list)
D      [Vagrant command] END (0m1.28s)
D      Berksfile found at /Users/shoekstra/cookbooks/sbp_certificate_services/Berksfile, loading Berkshelf
D      Berkshelf 4.0.1 library loaded
D      Winrm Transport requested, loading WinRM::Transport gem (~> 1.0)
D      WinRM::Transport 1.0.3 library loaded
-----> Creating <StandaloneRootCA-windows2012r2>...
D      <StandaloneRootCA-windows2012r2> is synchronizing on Kitchen::Driver::Vagrant#create
D      <StandaloneRootCA-windows2012r2> is messaging Kitchen::Driver::Vagrant#create
D      Creating Vagrantfile for <StandaloneRootCA-windows2012r2> (/Users/shoekstra/cookbooks/sbp_certificate_services/.kitchen/kitchen-vagrant/kitchen-sbp_certificate_services-StandaloneRootCA-windows2012r2/Vagrantfile)
D      ------------
D      Vagrant.configure("2") do |c|
D        c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
D        c.vm.box = "windows2012r2"
D        c.vm.box_url = "https://artifacts.schubergphilis.com/artifacts/vagrant/sbp_windows_2012_r2_20141211_1.box"
D        c.vm.hostname = "ROOTCA"
D        c.vm.guest = "windows"
D          c.winrm.retry_delay = 5
D          c.winrm.max_tries = 50
D        c.vm.network(:private_network, {:ip=>"192.168.33.11"})
D        c.vm.synced_folder ".", "/vagrant", disabled: true
D        c.vm.provider :virtualbox do |p|
D        end
D      end
D      ------------
D      [Vagrant command] BEGIN (vagrant up --provider virtualbox)
       Bringing machine 'default' up with 'virtualbox' provider...
       ==> default: Importing base box 'windows2012r2'...
==> default: Matching MAC address for NAT networking...
       ==> default: Setting the name of the VM: kitchen-sbp_certificate_services-StandaloneRootCA-windows2012r2_default_1449584770796_76862
       ==> default: Fixed port collision for 3389 => 3389. Now on port 2200.
       ==> default: Fixed port collision for 5985 => 55985. Now on port 2201.
       ==> default: Fixed port collision for 5986 => 55986. Now on port 2202.
       ==> default: Clearing any previously set network interfaces...
       ==> default: Preparing network interfaces based on configuration...
           default: Adapter 1: nat
           default: Adapter 2: hostonly
       ==> default: Forwarding ports...
           default: 3389 => 2200 (adapter 1)
           default: 5985 => 2201 (adapter 1)
           default: 5986 => 2202 (adapter 1)
       ==> default: Running 'pre-boot' VM customizations...
       ==> default: Booting VM...
       ==> default: Waiting for machine to boot. This may take a few minutes...    default: WinRM address: 127.0.0.1:2201
           default: WinRM username: vagrant
           default: WinRM transport: plaintext
       An error occurred executing a remote WinRM command.

       Shell: powershell
       Command: hostname
       if ($?) { exit 0 } else { if($LASTEXITCODE) { exit $LASTEXITCODE } else { exit 1 } }
       Message: [WSMAN ERROR CODE: 2147942421]: <f:WSManFault Code='2147942421' Machine='127.0.0.1' xmlns:f='http://schemas.microsoft.com/wbem/wsman/1/wsmanfault'><f:Message><f:ProviderFault path='%systemroot%\system32\winrscmd.dll' provider='Shell cmd plugin'>The device is not ready. </f:ProviderFault></f:Message></f:WSManFault>
D      [Vagrant command] END (1m31.02s)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #create action: [Expected process to exit with [0], but received '1'
---- Begin output of vagrant up --provider virtualbox ----
STDOUT: Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'windows2012r2'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: kitchen-sbp_certificate_services-StandaloneRootCA-windows2012r2_default_1449584770796_76862
==> default: Fixed port collision for 3389 => 3389. Now on port 2200.
==> default: Fixed port collision for 5985 => 55985. Now on port 2201.
==> default: Fixed port collision for 5986 => 55986. Now on port 2202.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 3389 => 2200 (adapter 1)
    default: 5985 => 2201 (adapter 1)
    default: 5986 => 2202 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: WinRM address: 127.0.0.1:2201
    default: WinRM username: vagrant
    default: WinRM transport: plaintext
STDERR: An error occurred executing a remote WinRM command.

Shell: powershell
Command: hostname
if ($?) { exit 0 } else { if($LASTEXITCODE) { exit $LASTEXITCODE } else { exit 1 } }
Message: [WSMAN ERROR CODE: 2147942421]: <f:WSManFault Code='2147942421' Machine='127.0.0.1' xmlns:f='http://schemas.microsoft.com/wbem/wsman/1/wsmanfault'><f:Message><f:ProviderFault path='%systemroot%\system32\winrscmd.dll' provider='Shell cmd plugin'>The device is not ready. </f:ProviderFault></f:Message></f:WSManFault>
---- End output of vagrant up --provider virtualbox ----
Ran vagrant up --provider virtualbox returned 1]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #create action: [Expected process to exit with [0], but received '1'
---- Begin output of vagrant up --provider virtualbox ----
STDOUT: Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'windows2012r2'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: kitchen-sbp_certificate_services-StandaloneRootCA-windows2012r2_default_1449584770796_76862
==> default: Fixed port collision for 3389 => 3389. Now on port 2200.
==> default: Fixed port collision for 5985 => 55985. Now on port 2201.
==> default: Fixed port collision for 5986 => 55986. Now on port 2202.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 3389 => 2200 (adapter 1)
    default: 5985 => 2201 (adapter 1)
    default: 5986 => 2202 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: WinRM address: 127.0.0.1:2201
    default: WinRM username: vagrant
    default: WinRM transport: plaintext
STDERR: An error occurred executing a remote WinRM command.

Shell: powershell
Command: hostname
if ($?) { exit 0 } else { if($LASTEXITCODE) { exit $LASTEXITCODE } else { exit 1 } }
Message: [WSMAN ERROR CODE: 2147942421]: <f:WSManFault Code='2147942421' Machine='127.0.0.1' xmlns:f='http://schemas.microsoft.com/wbem/wsman/1/wsmanfault'><f:Message><f:ProviderFault path='%systemroot%\system32\winrscmd.dll' provider='Shell cmd plugin'>The device is not ready. </f:ProviderFault></f:Message></f:WSManFault>
---- End output of vagrant up --provider virtualbox ----
Ran vagrant up --provider virtualbox returned 1]
D      ---Nested Exception---
D      Class: Kitchen::ShellOut::ShellCommandFailed
D      Message: Expected process to exit with [0], but received '1'
---- Begin output of vagrant up --provider virtualbox ----
STDOUT: Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'windows2012r2'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: kitchen-sbp_certificate_services-StandaloneRootCA-windows2012r2_default_1449584770796_76862
==> default: Fixed port collision for 3389 => 3389. Now on port 2200.
==> default: Fixed port collision for 5985 => 55985. Now on port 2201.
==> default: Fixed port collision for 5986 => 55986. Now on port 2202.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 3389 => 2200 (adapter 1)
    default: 5985 => 2201 (adapter 1)
    default: 5986 => 2202 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: WinRM address: 127.0.0.1:2201
    default: WinRM username: vagrant
    default: WinRM transport: plaintext
STDERR: An error occurred executing a remote WinRM command.

Shell: powershell
Command: hostname
if ($?) { exit 0 } else { if($LASTEXITCODE) { exit $LASTEXITCODE } else { exit 1 } }
Message: [WSMAN ERROR CODE: 2147942421]: <f:WSManFault Code='2147942421' Machine='127.0.0.1' xmlns:f='http://schemas.microsoft.com/wbem/wsman/1/wsmanfault'><f:Message><f:ProviderFault path='%systemroot%\system32\winrscmd.dll' provider='Shell cmd plugin'>The device is not ready. </f:ProviderFault></f:Message></f:WSManFault>
---- End output of vagrant up --provider virtualbox ----
Ran vagrant up --provider virtualbox returned 1
D      ------Backtrace-------
D      /Users/shoekstra/.chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/shell_out.rb:73:in `rescue in run_command'
D      /Users/shoekstra/.chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/shell_out.rb:61:in `run_command'
D      /Users/shoekstra/.chefdk/gem/ruby/2.1.0/bundler/gems/kitchen-vagrant-fc35d02576c0/lib/kitchen/driver/vagrant.rb:343:in `run_command'
D      /Users/shoekstra/.chefdk/gem/ruby/2.1.0/bundler/gems/kitchen-vagrant-fc35d02576c0/lib/kitchen/driver/vagrant.rb:302:in `run'
D      /Users/shoekstra/.chefdk/gem/ruby/2.1.0/bundler/gems/kitchen-vagrant-fc35d02576c0/lib/kitchen/driver/vagrant.rb:373:in `run_vagrant_up'
D      /Users/shoekstra/.chefdk/gem/ruby/2.1.0/bundler/gems/kitchen-vagrant-fc35d02576c0/lib/kitchen/driver/vagrant.rb:88:in `create'
D      /Users/shoekstra/.chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:424:in `public_send'
D      /Users/shoekstra/.chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:424:in `block in perform_action'
D      /Users/shoekstra/.chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:485:in `call'
D      /Users/shoekstra/.chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:485:in `block in synchronize_or_call'
D      /Users/shoekstra/.chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:483:in `synchronize'
D      /Users/shoekstra/.chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:483:in `synchronize_or_call'
D      /Users/shoekstra/.chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:453:in `block in action'
D      /opt/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
D      /Users/shoekstra/.chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:452:in `action'
D      /Users/shoekstra/.chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:424:in `perform_action'
D      /Users/shoekstra/.chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:352:in `create_action'
D      /Users/shoekstra/.chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:341:in `block in transition_to'
D      /Users/shoekstra/.chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:340:in `each'
D      /Users/shoekstra/.chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:340:in `transition_to'
D      /Users/shoekstra/.chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:127:in `create'
D      /Users/shoekstra/.chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/command.rb:176:in `public_send'
D      /Users/shoekstra/.chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
D      /Users/shoekstra/.chefdk/gem/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
D      /Users/shoekstra/.chefdk/gem/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
D      ----------------------
GLOBAL_VAGRANT_CACHIER_DISABLED=1 bundle exec kitchen create  -l debug  7.57s user 3.04s system 10% cpu 1:45.05 total
~/c/sbp_certificate_services ❯❯❯ time GLOBAL_VAGRANT_CACHIER_DISABLED=1 bundle exec kitchen create StandaloneRootCA-windows2012r2 -l debug                                  ⏎ develop ⬆ ⬇ ✱ ◼
-----> Starting Kitchen (v1.4.2)
D      [Vagrant command] BEGIN (vagrant --version)
D      [Vagrant command] END (0m0.29s)
D      [Vagrant command] BEGIN (vagrant plugin list)
D      [Vagrant command] END (0m1.54s)
D      Berksfile found at /Users/shoekstra/cookbooks/sbp_certificate_services/Berksfile, loading Berkshelf
/Users/shoekstra/.chefdk/gem/ruby/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/webagent-cookie.rb:458: warning: already initialized constant HTTPClient::CookieManager
/Users/shoekstra/.chefdk/gem/ruby/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/cookie.rb:8: warning: previous definition of CookieManager was here
D      Berkshelf 4.0.1 library loaded
D      Winrm Transport requested, loading WinRM::Transport gem (~> 1.0)
D      WinRM::Transport 1.0.3 library loaded
D      Berksfile found at /Users/shoekstra/cookbooks/sbp_certificate_services/Berksfile, loading Berkshelf
D      Berkshelf 4.0.1 previously loaded
D      Winrm Transport requested, loading WinRM::Transport gem (~> 1.0)
D      WinRM::Transport 1.0.3 previously loaded
D      Berksfile found at /Users/shoekstra/cookbooks/sbp_certificate_services/Berksfile, loading Berkshelf
D      Berkshelf 4.0.1 previously loaded
D      Winrm Transport requested, loading WinRM::Transport gem (~> 1.0)
D      WinRM::Transport 1.0.3 previously loaded
D      Berksfile found at /Users/shoekstra/cookbooks/sbp_certificate_services/Berksfile, loading Berkshelf
D      Berkshelf 4.0.1 previously loaded
D      Winrm Transport requested, loading WinRM::Transport gem (~> 1.0)
D      WinRM::Transport 1.0.3 previously loaded
-----> Creating <StandaloneRootCA-windows2012r2>...
D      <StandaloneRootCA-windows2012r2> is synchronizing on Kitchen::Driver::Vagrant#create
D      <StandaloneRootCA-windows2012r2> is messaging Kitchen::Driver::Vagrant#create
D      Creating Vagrantfile for <StandaloneRootCA-windows2012r2> (/Users/shoekstra/cookbooks/sbp_certificate_services/.kitchen/kitchen-vagrant/kitchen-sbp_certificate_services-StandaloneRootCA-windows2012r2/Vagrantfile)
D      ------------
D      Vagrant.configure("2") do |c|
D        c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
D        c.vm.box = "windows2012r2"
D        c.vm.box_url = "https://artifacts.schubergphilis.com/artifacts/vagrant/sbp_windows_2012_r2_20141211_1.box"
D        c.vm.hostname = "ROOTCA"
D        c.vm.guest = "windows"
D          c.winrm.retry_delay = 5
D          c.winrm.max_tries = 50
D        c.vm.network(:private_network, {:ip=>"192.168.33.11"})
D        c.vm.synced_folder ".", "/vagrant", disabled: true
D        c.vm.provider :virtualbox do |p|
D        end
D      end
D      ------------
D      [Vagrant command] BEGIN (vagrant up --provider virtualbox)
       Bringing machine 'default' up with 'virtualbox' provider...
       ==> default: VirtualBox VM is already running.
D      [Vagrant command] END (0m2.95s)
D      [Vagrant command] BEGIN (vagrant winrm-config)
D      [Vagrant command] END (0m2.79s)
D      [WinRM] opening remote shell on plaintext::http://127.0.0.1:2201/wsman<{:disable_sspi=>true, :basic_auth_only=>true, :user=>"vagrant", :pass=>"vagrant"}>
D      [WinRM] remote shell 12FCD436-CEF2-4C61-B926-ACC6A08DF608 is open on plaintext::http://127.0.0.1:2201/wsman<{:disable_sspi=>true, :basic_auth_only=>true, :user=>"vagrant", :pass=>"vagrant"}>
D      [WinRM] plaintext::http://127.0.0.1:2201/wsman<{:disable_sspi=>true, :basic_auth_only=>true, :user=>"vagrant", :pass=>"vagrant"}> (Write-Host '[WinRM] Established
')
       [WinRM] Established
       Vagrant instance <StandaloneRootCA-windows2012r2> created.
       Finished creating <StandaloneRootCA-windows2012r2> (0m8.91s).
-----> Kitchen is finished. (0m11.97s)
D      [CommandExecutor] closing remote shell 12FCD436-CEF2-4C61-B926-ACC6A08DF608 on plaintext::http://127.0.0.1:2201/wsman<{:disable_sspi=>true, :basic_auth_only=>true, :user=>"vagrant", :pass=>"vagrant"}>
D      [CommandExecutor] remote shell 12FCD436-CEF2-4C61-B926-ACC6A08DF608 closed
GLOBAL_VAGRANT_CACHIER_DISABLED=1 bundle exec kitchen create  -l debug  7.50s user 1.74s system 69% cpu 13.246 total
```

**Comment by mwrock** [comment]
I have seen this before. In my case I was building a vagrant box with packer and the box was sysprepped as the final stage of the packer build. On the first vagrant up I got this same error about device not ready.

Adjusting the timeouts or retries won't help because they control how long to wait for a successful connection. In this case, a winrm connection makes it through "successfully" but the machine is in a bad state.

I got around this byinstalling the virtualbox guest additions in my packer build. I believe that the "device not ready" is related to driver issues.

**Comment by shoekstra** [comment]
This happens pretty often on my laptop and can reproduce it on a colleague's when using multi-machine environments when the host is under more load and creating machines takes longer than usual (currently using a 3 Windows node kitchen setup and this happens about ~65% of the time).

So I guess the actual fix for this would be in vagrant's WinRM communicator and to perhaps retry if a a "device is not ready" message is received rather than trying to fiddle with timeouts?

**Comment by mwrock** [comment]
I think thats right @shoekstra

**Comment by shoekstra** [comment]
I'll close this one in that case - thanks for the feedback.
