### ISSUE TITLE
Unable to test Chef11 due to net-ssh 

### ISSUE THREAD

**Issue by CVTJNII** [test-kitchen/test-kitchen#914]
We still have Chef11 in our environment which I need to test for.  It looks like net-ssh has been upgraded and now requires Ruby 2.0, whereas Chef11 is still on 1.9.1.

```
-----> Verifying <default-ubuntu-1404-chef11>...              
       Preparing files for transfer
-----> Installing Busser (busser)
Fetching: thor-0.19.0.gem (100%)
Fetching: busser-0.7.1.gem (100%)
       Successfully installed thor-0.19.0
       Successfully installed busser-0.7.1
       2 gems installed
-----> Setting up Busser                                      
       Creating BUSSER_ROOT in /tmp/verifier                  
       Creating busser binstub                                
       Installing Busser plugins: busser-serverspec           
       Plugin serverspec installed (version 0.5.7)            
-----> Running postinstall for serverspec plugin              
       Suite path directory /tmp/verifier/suites does not exist, skipping.
       Transferring files to <default-ubuntu-1404-chef11>     
-----> Running serverspec test suite                          
-----> Installing Serverspec..                                
Fetching: rspec-support-3.4.1.gem (100%)                      
Fetching: rspec-core-3.4.1.gem (100%)                         
Fetching: diff-lcs-1.2.5.gem (100%)                           
Fetching: rspec-expectations-3.4.0.gem (100%)                 
Fetching: rspec-mocks-3.4.1.gem (100%)                        
Fetching: rspec-3.4.0.gem (100%)                              
Fetching: rspec-its-1.2.0.gem (100%)                          
Fetching: multi_json-1.11.2.gem (100%)                        
Fetching: net-ssh-3.0.2.gem (100%)                            
       /opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/installer.rb:388:in `ensure_required_ruby_version_met': net-ssh requires Ruby version >= 2.0. (Gem::InstallError)
        from /opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/installer.rb:156:in `install'
        from /opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/dependency_installer.rb:297:in `block in install'
        from /opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/dependency_installer.rb:270:in `each'
        from /opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/dependency_installer.rb:270:in `each_with_index'
        from /opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/dependency_installer.rb:270:in `install'
        from /tmp/verifier/gems/gems/busser-0.7.1/lib/busser/rubygems.rb:44:in `install_gem'
        from /tmp/verifier/gems/gems/busser-0.7.1/lib/busser/helpers.rb:57:in `install_gem'
        from /tmp/verifier/gems/gems/busser-serverspec-0.5.7/lib/busser/runner_plugin/serverspec.rb:60:in `install_serverspec'
        from /tmp/verifier/gems/gems/busser-serverspec-0.5.7/lib/busser/runner_plugin/serverspec.rb:33:in `test'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/command.rb:27:in `run'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `block in invoke_all'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `each'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `map'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `invoke_all'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/group.rb:232:in `dispatch'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:115:in `invoke'
        from /tmp/verifier/gems/gems/busser-0.7.1/lib/busser/command/test.rb:43:in `block in perform'
        from /tmp/verifier/gems/gems/busser-0.7.1/lib/busser/command/test.rb:35:in `each'
        from /tmp/verifier/gems/gems/busser-0.7.1/lib/busser/command/test.rb:35:in `perform'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/command.rb:27:in `run'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `block in invoke_all'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `each'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `map'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `invoke_all'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/group.rb:232:in `dispatch'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:115:in `invoke'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor.rb:40:in `block in register'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/command.rb:27:in `run'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor.rb:359:in `dispatch'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/base.rb:440:in `start'
        from /tmp/verifier/gems/gems/busser-0.7.1/bin/busser:8:in `<top (required)>'
        from /tmp/verifier/gems/bin/busser:23:in `load'       
        from /tmp/verifier/gems/bin/busser:23:in `<main>'     
```

Is Chef11 still supported?  Is it possible to pin these gems back down to make them behave?  Thanks!

**Comment by CVTJNII** [comment]
Working around this with the following [Gemfile](https://github.com/test-kitchen/busser-serverspec#-usage) in busser-serverspec:

```
source 'https://rubygems.org'

# https://github.com/test-kitchen/test-kitchen/issues/914                               
gem 'net-ssh', '<3'
```

I'm unclear on where this bug should be filed, or if it's simply a 'won't fix' for Chef 11.  Please advise, thanks.

**Comment by cheeseplus** [comment]
Given that Ruby 1.9 is EOL and Chef 11 over two years old this isn't likely something we're going to work around.
