### ISSUE TITLE
chef_omnibus_root is nil on images pre-baked with a chef client

### ISSUE THREAD

**Issue by aespinosa** [test-kitchen/test-kitchen#923]
On test-kitchen 1.5.0, the chef_client_path is set to /bin/chef-client if the chef_zero provisioner doesn't have to perform an omnibus install.

Here's my `kitchen diagnose` : https://gist.github.com/aespinosa/00d81f95d1a9e060c51d

**Comment by zl4bv** [comment]
Experiencing this error too.

Relevant section from the log:
```
D      Transfer complete
D      [WinRM] plaintext::http://ip-xxx-xxx-xxx-xxx.ap-southeast-2.compute.internal:5985/wsman<{:user=>"administrator", :pass=>"************", :disable_sspi=>true, :basic_auth_only=>true}> ($env:PATH = [System.Environment]::GetEnvironmentVariable("PATH","Machine")

& \bin\chef-solo.bat --config $env:TEMP\kitchen\solo.rb --log_level debug --force-formatter --no-color --json-attributes $env:TEMP\kitchen\dna.json)
$$$$$$ &amp; : The term '\bin\chef-solo.bat' is not recognized as the name of a cmdlet,
$$$$$$ function, script file, or operable program. Check the spelling of the name, or
$$$$$$ if a path was included, verify that the path is correct and try again.
$$$$$$ At line:9 char:3
$$$$$$ + &amp; \bin\chef-solo.bat --config $env:TEMP\kitchen\solo.rb --log_level debug
$$$$$$ --forc ...
$$$$$$ +   ~~~~~~~~~~~~~~~~~~
$$$$$$     + CategoryInfo          : ObjectNotFound: (\bin\chef-solo.bat:String) [],
$$$$$$    CommandNotFoundException
$$$$$$     + FullyQualifiedErrorId : CommandNotFoundException
D      Cleaning up local sandbox in /tmp/default-windows-2012r2-sandbox-20160128-10604-143gxar
-----> Destroying <default-windows-2012r2>...
```

**Comment by zl4bv** [comment]
Aside from when the user explicitly defines it in their config, `chef_omnibus_root` is only ever set for the Chef provisioners on [this line](https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/provisioner/chef_base.rb#L145), which does not get executed unless `require_chef_omnibus` is truthy.

Given mixlib-install [defines](https://github.com/chef/mixlib-install/blob/v0.7.1/lib/mixlib/install.rb#L82-L86) sensible defaults, would it make sense to use them by default in the chef provisioners even if `chef_omnibus_root` is falsey?

**Comment by xeron** [comment]
I see the same issue. We use AWS AMIs with pre-baked omnibus chef and `test-kitchen` > 1.4.2 doesn't work. Error:

```
       sudo: /bin/chef-solo: command not found
D      Cleaning up local sandbox in <SKIPPED>
>>>>>> Converge failed on instance <SKIPPED>
>>>>>> Please see .kitchen/logs/<SKIPPED>.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sh -c '

sudo -E /bin/chef-solo --config /tmp/kitchen/solo.rb --log_level debug --force-formatter --no-color --json-attributes /tmp/kitchen/dna.json
']

<SKIPPED>

sudo -E /bin/chef-solo --config /tmp/kitchen/solo.rb --log_level debug --force-formatter --no-color --json-attributes /tmp/kitchen/dna.json
']
D      ------Backtrace-------
D      /Users/ilarionov/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.6.0/lib/kitchen/driver/ssh_base.rb:85:in `rescue in converge'
D      /Users/ilarionov/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.6.0/lib/kitchen/driver/ssh_base.rb:88:in `converge'
D      /Users/ilarionov/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:565:in `legacy_ssh_base_converge'
D      /Users/ilarionov/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:371:in `block in converge_action'
D      /Users/ilarionov/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:513:in `synchronize_or_call'
D      /Users/ilarionov/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:478:in `block in action'
D      /Users/ilarionov/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
D      /Users/ilarionov/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:477:in `action'
D      /Users/ilarionov/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:369:in `converge_action'
D      /Users/ilarionov/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:348:in `block in transition_to'
D      /Users/ilarionov/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:347:in `each'
D      /Users/ilarionov/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:347:in `transition_to'
D      /Users/ilarionov/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:138:in `converge'
D      /Users/ilarionov/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.6.0/lib/kitchen/command.rb:176:in `public_send'
D      /Users/ilarionov/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.6.0/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
D      ----------------------
```

**Comment by xeron** [comment]
Workaround is to set this under `provisioner `:
```ruby
chef_omnibus_root: /opt/chef
```

**Comment by donwlewis** [comment]
Is there any update on this?  I just ran into this scenario myself, but really seems to only affect RHEL6.

**Comment by cheeseplus** [comment]
@donwlewis it's not a great update but one of the reasons this was never fixed was that for a bit folks were working on the  "New Provisioner Options" which moved everything to using the common `mixlib-install` path which is more widely used across Chef software. Unfortunately that effort never quite completed / took over from the older `require_omnibus` style so we've been left with slightly less than awesome versions of both.

The folks who were all working on this are either not at Chef or no longer part of the community but if someone (at this point not sure Chef has bandwidth or interest) wanted to finish out that work on the new system then this would fix the issue and dramatically clean up the codepaths (though probably requiring a major bump).

**Comment by donwlewis** [comment]
Thanks @tarcinil!
